### ISSUE TITLE
[FEATURE] Support Flutter 3.0

### ISSUE THREAD

**Issue by ciriousjoker** [jhomlala/betterplayer#1006]
**Is your feature request related to a problem? Please describe.**
We upgraded to Flutter 3.0, but now we get lots of warnings during compilation.

**Describe the solution you'd like**
No warnings should be thrown.

**Describe alternatives you've considered**
- Use old Flutter/Dart versions

**Additional context**

Example:

```dart
WidgetsBinding.instance!.addObserver(this);
```

now becomes (notice the missing `!`):

```dart
WidgetsBinding.instance.addObserver(this);
```

**Comment by jhomlala** [comment]
Fixed in latest release.
