### ISSUE TITLE
setTrackParameters not working in IOS

### ISSUE THREAD

**Issue by Anhthangtshn** [jhomlala/betterplayer#101]
I checked and found that this function does not work on IOS (link hls .m3u8). On an Android device, it still works fine
I have tested it on Iphone 6s+. IOS 14.1 

`[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-VN)
    • Flutter version 1.22.2 at /Users/thangdv/WorkSpace/flutter
    • Framework revision 84f3d28555 (8 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/thangdv/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5
`

**Comment by Anhthangtshn** [comment]
Oh, I just tested the Youtube app on my iPhone, I also didn't notice the change in quality. Or is it the mechanism of IOS?

**Comment by jhomlala** [comment]
Is there any error in console, or it's just doesn't change anything? On iOS we can change only preferred bitrate and preferred resolution, but if AVPlayer decides that your device can't play given track, then it will change it automatically to best option.

**Comment by Anhthangtshn** [comment]
There aren't any errors in the control panel, I think it's the mechanism of iOS. Thank you very much
