### ISSUE TITLE
Update package xml to 6.0.1+

### ISSUE THREAD

**Issue by appcapsergen** [jhomlala/betterplayer#1013]
**Is your feature request related to a problem? Please describe.**
I use another package called flutter_svg, which now depends on xml 6.0.1, which makes it incompatible with better_player, since it depends on xml 5.3.0.

**Describe the solution you'd like**
Upgrade xml dependency to version 6.0.1 or higher.

**Comment by jhomlala** [comment]
Fixed in latest release.
