### ISSUE TITLE
FullScreenAspectRatio doesn't work 

### ISSUE THREAD

**Issue by mouaadsk** [jhomlala/betterplayer#102]
Hi, I've tried to use the fullScreenAspectRatio parameter in the better player configuration but when the video player full screen the video size (Ratio) is getting distorted and the player extends the video to fit the whole screen.
P.S : the video aspect ratio is 1.777 (16/9) and my phone aspect ration is 2.1 

this is the code I used in my app
`class VidepPlayerScreen extends StatefulWidget {
  final VideoWidgetModel videoModel;
  const VidepPlayerScreen({
    Key key,
    @required this.videoModel,
  }) : super(key: key);
  @override
  _VidepPlayerScreenState createState() => _VidepPlayerScreenState();
}

class _VidepPlayerScreenState extends State<VidepPlayerScreen> {
  BetterPlayerController _betterPlayerController;
  BetterPlayerConfiguration _betterPlayerConfiguration;
  BetterPlayerDataSource _betterPlayerDataSource;
  ScreenSize screenSize;
  @override
  void initState() {
    super.initState();
    this._betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK,
        this.widget.videoModel.video.videoQuality.hdLink != null
            ? this.widget.videoModel.video.videoQuality.hdLink
            : this.widget.videoModel.video.videoQuality.sdLink,
        resolutions:
            this.widget.videoModel.video.videoQuality.getQualitiesMap());
    _betterPlayerConfiguration = BetterPlayerConfiguration(
      aspectRatio: this.widget.videoModel.video.videoResolution.aspectRatio,
      autoPlay: true,
      fullScreenAspectRatio: this.widget.videoModel.video.videoResolution.aspectRatio,
      errorBuilder: (context, errorMessage) {
        return Text(errorMessage);
      },
      controlsConfiguration: BetterPlayerControlsConfiguration(
        enableProgressText: true,
        enableSubtitles: false,
        enableFullscreen: true,
      ),
    );
    setState(() {
      _betterPlayerController = BetterPlayerController(
        _betterPlayerConfiguration,
        betterPlayerDataSource: _betterPlayerDataSource,
      );
    });
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    this.screenSize = ScreenSize(
        height: MediaQuery.of(context).size.height,
        width: MediaQuery.of(context).size.width);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            BetterPlayer(
              controller: this._betterPlayerController,
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}`
Thanks in advance for your help

**Comment by jhomlala** [comment]
@mouaadsk 
Please use format options, when you're inserting your code. Also consider adding all necessary classes to run your code.
What you're missing is fit. Just use fit: BoxFit.contain in your BetterPlayerConfiguration.

**Comment by patrickbz** [comment]
hi @jhomlala 
I'm currently using this workaround in better_player_with_controls.dart, wrapping the player in a Center -> AspectRatio and the video keeps the correct aspect ratio also in fullscreen:
          Center(
            child: AspectRatio(
				   aspectRatio: configuration.aspectRatio,
                   child: Transform.rotate(
							angle: rotation * pi / 180,
							child: _BetterPlayerVideoFitWidget(
							betterPlayerController,
							betterPlayerController.betterPlayerConfiguration.fit,
							),
						),
					),
		  ),

Hope this can help

Best regards

**Comment by mouaadsk** [comment]
I used the `fit: BoxFit.fitHeight` in the BetterPlayerConfiguration to prevent the player from stretching the video to fit the whole player screen.
