### ISSUE TITLE
[BUG] After upgrade to flutter 3.0.1 (Warning: Operand of null-aware operation '!' has type '   ' which excludes null.)

### ISSUE THREAD

**Issue by alsamee27** [jhomlala/betterplayer#1021]
**The Issue**

Please note that this package still depend on another package visibility_detector version 0.2.2 , and the package of visibility_detector version 0.2.2 has error with flutter 3.0.1.

**Describe the bug**
I upgrade my flutter sdk  (flutter 3.0.1) ,then I found the error with this package. 

**Example code*
 Rect _computeClipRect() {
    assert(RendererBinding.instance?.renderView != null);
    var clipRect = Offset.zero & RendererBinding.instance!.renderView.size;

**Expected behavior**

**Screenshots**
C:/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:127:50: Warning: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null.
- 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('/C:/flutter/packages/flutter/lib/src/rendering/binding.dart').
package:flutter/…/rendering/binding.dart:1
    var clipRect = Offset.zero & RendererBinding.instance!.renderView.size;
                                                 ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:170:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.

**Flutter doctor**
No Error.

**Better Player version**
- Version:0.0.82

**Comment by jhomlala** [comment]
Fixed in latest release.
