### ISSUE TITLE
Plugin project :import_js_library not found. Please update settings.gradle

### ISSUE THREAD

**Issue by ufylord** [jhomlala/betterplayer#106]
#### The issue: 
Plugin project :import_js_library not found. Please update settings.gradle

#### The steps
- create flutter project by `flutter create --org=com.company -a java project_name`,
- install better_player as below
   ```
   dependencies:
     flutter:
       sdk: flutter
     better_player: ^0.0.29+1
   ```
- run `flutter run`, then get the info from the terminal as below:
   ```
   Launching lib/main.dart on XXX(my android devide) in debug mode...
   Plugin project :import_js_library not found. Please update settings.gradle.
   Running Gradle task 'assembleDebug'... 
   ...
   ```
#### Details 
Using Flutter in China
   ```
   export PUB_HOSTED_URL=https://pub.flutter-io.cn
   export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
   ```
The project could be launched, installed but did not use flutter_player in project
(BTW, get the http issue about video_player when use better_player in project, but that is another issue)

#### Content of settings.gradle
   ```
   include ':app'

   def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
   def properties = new Properties()

   assert localPropertiesFile.exists()
   localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

   def flutterSdkPath = properties.getProperty("flutter.sdk")
   assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
   apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
   ```

#### Flutter version
   ```
   Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
   Framework • revision 84f3d28555 (13 days ago) • 2020-10-15 16:26:19 -0700
   Engine • revision b8752bbfff
   Tools • Dart 2.10.2
   ```

**Comment by jhomlala** [comment]
@ufylord It's because wakelock dependency lib: https://github.com/creativecreatorormaybenot/wakelock/issues/48
I've overrided invalid library, so it should be fixed in next version.

**Comment by creativecreatorormaybenot** [comment]
@jhomlala This fix has landed now :) You can remove the `dependency_overrides` and simply run `flutter pub upgrade`.
