### ISSUE TITLE
[BUG] Unhandled Exception: PlatformException Android

### ISSUE THREAD

**Issue by awnigharbia** [jhomlala/betterplayer#1077]
I got this exception when I start the player:

E/flutter ( 7339): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior., null, java.lang.NullPointerException: MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior.
E/flutter ( 7339): 	at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:174)
E/flutter ( 7339): 	at com.google.android.exoplayer2.source.ProgressiveMediaSource$Factory.setDrmSessionManagerProvider(ProgressiveMediaSource.java:186)
E/flutter ( 7339): 	at com.jhomlala.better_player.BetterPlayer.buildMediaSource(BetterPlayer.kt:430)
E/flutter ( 7339): 	at com.jhomlala.better_player.BetterPlayer.setDataSource(BetterPlayer.kt:196)
E/flutter ( 7339): 	at com.jhomlala.better_player.BetterPlayerPlugin.setDataSource(BetterPlayerPlugin.kt:277)
E/flutter ( 7339): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:151)
E/flutter ( 7339): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:138)
E/flutter ( 7339): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 7339): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 7339): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 7339): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7339): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 7339): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7339): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 7339): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 7339): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7339): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 7339): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947

**Better Player version**
- Version: 0.0.83

**Smartphone (please complete the following information):**
 - Device: Android

**Additional context**
I just installed vdocipher package from pub.dart then suddenly better player started to throw this exception. Anyone can help me what happen?

**Comment by djdivesh007** [comment]
#1059

**Comment by awnigharbia** [comment]
Ty @djdivesh007 . I got it solved.

**Comment by che-ri** [comment]
I'm having the same problem. How did you solve it?

**Comment by djdivesh007** [comment]
this is temporary fix untill PR is merged. update your `pubspec.yml` file with
```
  better_player:
    git:
      url: https://github.com/matthewrice345/betterplayer.git
      ref: Issue1057

**Comment by che-ri** [comment]
I still have an error

PlatformException (PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, , null))

**Comment by che-ri** [comment]
The error still occurs
In the function _setupDataSource

PlatformException (PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, , null))

**Comment by che-ri** [comment]
I solved it with this.

https://github.com/jhomlala/betterplayer/issues/970#issue-1197319669

**Comment by JonasJW** [comment]
Any updates to this issue? This is still very relevant and I hope this can be fixed soon.

@djdivesh007 your fork works well, have you thought of making a PR?

**Comment by satyapsr13** [comment]
https://github.com/jhomlala/betterplayer/issues/1077#issuecomment-1245275049

It works 😎😎![SoExcited~GIF (2)](https://user-images.githubusercontent.com/73766765/221405315-e3b81269-3b80-410a-8c69-0d7317d60629.gif)

**Comment by alfayej45** [comment]
use this in pubspec.yaml 

 better_player:
    git:
      url: https://github.com/matthewrice345/betterplayer.git
      ref: Issue1057

**Comment by kevinbowie** [comment]
tq so much, solution from @djdivesh007 is works!
