### ISSUE TITLE
m3u8 video link is not working in iOS[BUG]

### ISSUE THREAD

**Issue by arun990y** [jhomlala/betterplayer#1092]
**Describe the bug**
m3u8 video link is not working in iOS devices, for android it is working fine. In iOS video player screen goes blank.

**Expected behavior**
m3u8 link should work in both android and iOS.

Sample Code
BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        link,
      );
      _controller = BetterPlayerController(
        BetterPlayerConfiguration(
          startAt: Duration(seconds: currentActivity!.duration),
          allowedScreenSleep: false,
          autoPlay: true,
          showPlaceholderUntilPlay: false,
          handleLifecycle: true,
          autoDispose: true,
          aspectRatio: 16 / 9,
          controlsConfiguration: BetterPlayerControlsConfiguration(
            enableSubtitles: false,
            enableAudioTracks: false,
            enableMute: true,
            pauseIcon: Icons.pause_circle,
            playIcon: Icons.play_circle_fill,
            skipBackIcon: Icons.replay,
            skipForwardIcon: Icons.forward_10,
          ),
        ),
        betterPlayerDataSource: betterPlayerDataSource,
      );

**Better Player version**
- Version:0.0.83

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS16.0.2]

**Comment by orenagiv** [comment]
Hey @arun990y,
I've been working with better_player v0.0.83 and .m3u8 files with iOS and didn't encounter any issues.

Are you trying a specific .m3u8?
Can you share it here?
Did you try with the default BetterPlayerConfiguration() configuration?

**Comment by SamerCat** [comment]
samer for me

**Comment by tintran-dev** [comment]
> samer for me

We should set the input video format for the player to be able to recognize what standard the video belongs to.
EX:
```
.m3u8 is videoFormat: BetterPlayerVideoFormat.hls
.mpd is videoFormat: BetterPlayerVideoFormat.dash
other set null
```

**Comment by arun990y** [comment]
> Hey @arun990y, I've been working with better_player v0.0.83 and .m3u8 files with iOS and didn't encounter any issues.
> 
> Are you trying a specific .m3u8? Can you share it here? Did you try with the default BetterPlayerConfiguration() configuration?

**Comment by arun990y** [comment]
> > samer for me
> 
> @SamerCat We should set the input video format for the player to be able to recognize what standard the video belongs to. EX:
> 
> ```
> .m3u8 is videoFormat: BetterPlayerVideoFormat.hls
> .mpd is videoFormat: BetterPlayerVideoFormat.dash
> other set null
> ```

i have tried this

**Comment by SamerCat** [comment]
@arun990y  I tried ti set BetterPlayerVideoFormat but I still facing the error
it's like this https://github.com/jhomlala/betterplayer/pull/1085

**Comment by arun990y** [comment]
m3u8 link was not proper that's why it was not working in the iOS.

**Comment by SamerCat** [comment]
@arun990y where did you found that there was an issue on m3u8 links and it's resolved.
can I get the source of this information because I want to provide them to my company please.
