### ISSUE TITLE
[BUG] Subtitle with two underlines

### ISSUE THREAD

**Issue by silvinhofranca** [jhomlala/betterplayer#1106]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**
When I add subtitles in either SRT or Webvtt, these double lines (underlines) appear.

**Example code*
```
BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        'https://example-url.com/media/01/file.m3u8',
        videoFormat: BetterPlayerVideoFormat.hls,
        cacheConfiguration: const BetterPlayerCacheConfiguration(
          useCache: true,
          preCacheSize: 10 * 1024 * 1024,
          maxCacheSize: 10 * 1024 * 1024,
          maxCacheFileSize: 10 * 1024 * 1024,
        ),
        subtitles: [
          BetterPlayerSubtitlesSource(
              type: BetterPlayerSubtitlesSourceType.network,
              name: 'English',
              urls: [
                 'https://example-url.com/media/01/file.srt',
              ],),
        ]);
```

**Expected behavior**
That the subtitles were displayed normally.

**Screenshots**
![subtitle bug](https://user-images.githubusercontent.com/113481056/197356458-a928e086-866e-4189-aaec-def13bc1ac38.png)

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.3, on Microsoft Windows [versÆo 10.0.22621.674], locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Better Player version**
- Version: 0.0.83

**Smartphone (please complete the following information):**
 - Device: Samsung SM-G930F
 - OS: Android 8.1

**Additional context**

**Comment by macopi** [comment]
I found a workarround setting a DefaultTextStyle


**example:**
`DefaultTextStyle(
                  child: BetterPlayer(controller: _betterPlayerController),
                  style: const TextStyle(decoration: TextDecoration.none)),`

**Comment by tintran-dev** [comment]
> **History check** Please confirm that you've checked issues history and you didn't find anything which may solve your issue.
> 
> **Describe the bug** When I add subtitles in either SRT or Webvtt, these double lines (underlines) appear.
> 
> *_Example code_
> 
> ```
> BetterPlayerDataSource dataSource = BetterPlayerDataSource(
>         BetterPlayerDataSourceType.network,
>         'https://example-url.com/media/01/file.m3u8',
>         videoFormat: BetterPlayerVideoFormat.hls,
>         cacheConfiguration: const BetterPlayerCacheConfiguration(
>           useCache: true,
>           preCacheSize: 10 * 1024 * 1024,
>           maxCacheSize: 10 * 1024 * 1024,
>           maxCacheFileSize: 10 * 1024 * 1024,
>         ),
>         subtitles: [
>           BetterPlayerSubtitlesSource(
>               type: BetterPlayerSubtitlesSourceType.network,
>               name: 'English',
>               urls: [
>                  'https://example-url.com/media/01/file.srt',
>               ],),
>         ]);
> ```
> 
> **Expected behavior** That the subtitles were displayed normally.
> 
> **Screenshots** ![subtitle bug](https://user-images.githubusercontent.com/113481056/197356458-a928e086-866e-4189-aaec-def13bc1ac38.png)
> 
> **Flutter doctor**
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.3.3, on Microsoft Windows [versÆo 10.0.22621.674], locale pt-BR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Chrome - develop for the web
> [✗] Visual Studio - develop for Windows
>     ✗ Visual Studio not installed; this is necessary for Windows development.
>       Download at https://visualstudio.microsoft.com/downloads/.
>       Please install the "Desktop development with C++" workload, including all of its default components
> [✓] Android Studio (version 2021.3)
> [✓] VS Code (version 1.72.2)
> [✓] Connected device (4 available)
> [✓] HTTP Host Availability
> 
> ! Doctor found issues in 1 category.
> ```
> 
> **Better Player version**
> 
> * Version: 0.0.83
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Samsung SM-G930F
> * OS: Android 8.1
> 
> **Additional context** Add any other context about the problem here.

This is a case of using a material widget in a non-material parent wedget. to solve the problem you need to wrap a Material widget outside the player:
`Material(
       child: BetterPlayer(
              #add some your code
              .................
       ),
);`
