### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by hiteshgarg002** [jhomlala/betterplayer#112]
Hello,

I am trying to handle errors but seems like player has the following issues :

1) I have tried to use errorBuilder widget to show user a custom widget when there is any error but errorBuilder widget never shows up.

2) I have tried using BetterPlayerEventType.EXCEPTION inside eventListener but it is not being called when there is any error.

Please fix this!

**Comment by jhomlala** [comment]
@hiteshgarg002 Please share example code. Which error do you want to handle? Error builder will be used if native player (ExoPlayer/AVPlayer) reports that some video can't be played.

**Comment by hiteshgarg002** [comment]
@jhomlala For an example if the video is being played and in between if user disconnects the internet connection, an error is thrown "Source error" and is visible on the console but neither errorBuilder widget is shown nor BetterPlayerEventType.EXCEPTION is called. Please fix this.

**Comment by jhomlala** [comment]
@hiteshgarg002 Please upgrade Better Player to 0.0.31. You should be able to receive exception via event listener.

**Comment by hiteshgarg002** [comment]
> 
> 
> @hiteshgarg002 Please upgrade Better Player to 0.0.31. You should be able to receive exception via event listener.

Thanks, it works now.

**Comment by huxaiphaer** [comment]
Is there an example of printing on exception ? @hiteshgarg002
