### ISSUE TITLE
[BUG]issues even in the reusable video list of example app

### ISSUE THREAD

**Issue by RezaKhajvand** [jhomlala/betterplayer#1144]
when scrolling in the reusable video list page some of videos not load to play...and after more scrolling alll the videos wont load anymore....i use last version of better player.

https://user-images.githubusercontent.com/120022216/208943622-39c626d6-cf38-4862-9589-6a18bebfa33c.mp4

**Comment by Simon-Tezda** [comment]
where you able to fix this @RezaKhajvand ?
