### ISSUE TITLE
[BUG] Exceptions

### ISSUE THREAD

**Issue by thirtysixmm** [jhomlala/betterplayer#115]
I am not 100% sure which scenario I am getting this exception, I see the following stacktrace in the console.

```
/flutter (26722): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
E/flutter (26722): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active., stack trace: #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:1090:9)
E/flutter (26722): #1      State.context (package:flutter/src/widgets/framework.dart:1096:6)
E/flutter (26722): #2      BetterPlayerState._setup (package:better_player/src/core/better_player.dart:73:44)
E/flutter (26722): #3      BetterPlayerState.initState.<anonymous closure> (package:better_player/src/core/better_player.dart:67:7)
```

The video display is fine and I don't think this has an impact on the user experiance.

**Comment by jhomlala** [comment]
@thirtysixmm  Thanks for reporting issue. I think that you're trying to use Better Player in some screen/route which has been already disposed. If possible please share your code or some reproducible code. 

Also, next time please follow issue template if possible.

**Comment by bdlukaa** [comment]
I the problem can be fixed in the plugin, at the VideoPlayer State (https://github.com/jhomlala/betterplayer/blob/master/lib/src/video_player/video_player.dart). When you call `setState` at `_listener`, you should check if it's `mounted` before

**Comment by jhomlala** [comment]
@bdlukaa Stack trace from issue doesn't point to this code.

**Comment by jhomlala** [comment]
@thirtysixmm Can you retry it with newest Better Player version (0.0.33)?

**Comment by thirtysixmm** [comment]
I am not seeing this exceptions anymore in the new version. Thank you for fixing.

**Comment by thirtysixmm** [comment]
Dart Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
E/flutter (17223): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active., stack trace: #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:1090:9)
E/flutter (17223): #1      State.context (package:flutter/src/widgets/framework.dart:1096:6)
E/flutter (17223): #2      BetterPlayerState._setup (package:better_player/src/core/better_player.dart:73:44)
E/flutter (17223): #3      BetterPlayerState.initState.<anonymous closure> (package:better_player/src/core/better_player.dart:67:7)
E/flutter (17223): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
E/flutter (17223): #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (17223): #6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (17223): #7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (17223): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

Now the same issue is coming in the full screen page.

**Comment by jhomlala** [comment]
Please provide sample code.

**Comment by jhomlala** [comment]
@thirtysixmm Please try latest Better Player version. If there is any issue, please create new ticket using issue template.
