### ISSUE TITLE
Cant load remain of a network video that not completely cached, between app sessions

### ISSUE THREAD

**Issue by RezaKhajvand** [jhomlala/betterplayer#1152]
HI.
thanks for youre package @jhomlala
All my problems have been solved but i cant solve this one

when loading video first time from internet it is ok...precached and loaded very good.
but When you watch a video until the middle it precached only half of the video and when u want to play that in another page it is playing until the middle of video and not load anymore.

This is my betterplayerdatasources
`BetterPlayerDataSource.network(
    url,
    placeholder: const SizedBox(),
    bufferingConfiguration: const BetterPlayerBufferingConfiguration(
      minBufferMs: 1000,
      maxBufferMs: 1000,
      bufferForPlaybackMs: 1000,
      bufferForPlaybackAfterRebufferMs: 1000,
    ),
    cacheConfiguration: BetterPlayerCacheConfiguration(
      useCache: true,
      key: url,
      preCacheSize: 1 * 1024 * 1024,
      maxCacheFileSize: 20 * 1024 * 1024,
      maxCacheSize: 100 * 1024 * 1024,
    ),
  )`

and I used reusable controller for my app just like the source project.

https://user-images.githubusercontent.com/120022216/211195699-1da82a63-bce8-4f82-a0b1-d9b74cccc3e7.mp4

**Comment by SurajLad** [comment]
@RezaKhajvand Did you find any solution for your problem ? how you dealt with this ? can you share your view

**Comment by RezaKhajvand** [comment]
> @RezaKhajvand Did you find any solution for your problem ? how you dealt with this ? can you share your view

remove key from cache video
let the better player decide about it
