### ISSUE TITLE
Maximized video player does not change orientation with change in device orientation 

### ISSUE THREAD

**Issue by hashimraza** [jhomlala/betterplayer#117]
**Describe the bug:**
I tried these configs already but the problem I'm facing can be reproduced as follows:
1. use maximize button to put video player to full screen mode,
2. rotate device physically to landscape and back to portrait,
3. the screen stays in maximized mode (does not exit fullscreen mode automatically, have to click minimize button on the player to exit the mode)

**Expected behavior:**
the device when it is put in fullscreen mode using maximize button when physically rotated back to portrait, should exit the fullscreen mode automatically

**Better Player version:**
Version: 0.0.31

**Smartphone:**
Emulator(Pixel 3), Device(S10)

**Comment by jhomlala** [comment]
@hashimraza Please use issue template next time.
I believe you should look into these 2 configuration options from BetterPlayerConfiguration:
```dart
    /// Defines the set of allowed device orientations on entering fullscreen
    final List<DeviceOrientation> deviceOrientationsOnFullScreen;

    /// Defines the set of allowed device orientations after exiting fullscreen
    final List<DeviceOrientation> deviceOrientationsAfterFullScreen;
```
If you want to have only portrait mode after exiting full screen, you should pass portrait device orientation to the `deviceOrientationAfterFullScreen` parameter.

**Comment by hashimraza** [comment]
Hi, sorry about not using the template.
I tried these configs already but the problem is:
when maximize button is used, and device orientation is changed physically from landscape to portrait, the build method is not called as it does not

**Comment by hashimraza** [comment]
Hi, sorry about not using the template.

I tried these configs already but the problem I'm facing can be reproduced as follows:
1. use maximize button to put video player to full screen mode,
2. rotate device physically to landscape and back to portrait, 
3. the screen stays in maximized mode (does not exit fullscreen mode automatically, have to click minimize button on the player to exit the mode)

Expectation:
the device when it is put in fullscreen mode using maximize button when physically rotated back to portrait, should exit the fullscreen mode automatically

**Comment by jhomlala** [comment]
This seems to be custom behavior. But it's doable. Try this example:
```dart
import 'dart:async';

import 'package:better_player/better_player.dart';
import 'package:better_player_example/constants.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class NormalPlayerPage extends StatefulWidget {
  @override
  _NormalPlayerPageState createState() => _NormalPlayerPageState();
}

class _NormalPlayerPageState extends State<NormalPlayerPage>
    with WidgetsBindingObserver {
  BetterPlayerController _betterPlayerController;
  bool _lastPortraitState = true;

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);

    ///Orientation on page started
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
            aspectRatio: 16 / 9,
            fit: BoxFit.contain,
            ///Orientation on full screen but only for start
            deviceOrientationsOnFullScreen: [
          DeviceOrientation.landscapeLeft,
          DeviceOrientation.landscapeRight,
        ],
            ///Orientation after full screen dismissed
            deviceOrientationsAfterFullScreen: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
        ]);
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK, Constants.forBiggerBlazesUrl);
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(dataSource);
    _betterPlayerController.addEventsListener((event) {
      if (event.betterPlayerEventType ==
          BetterPlayerEventType.OPEN_FULLSCREEN) {

        ///Delay required to screen properly rotate to landscape. Then change
        ///orientation both portrait and landscape, so user can rotate to portrait.
        Future.delayed(Duration(milliseconds: 3000), () {
          SystemChrome.setPreferredOrientations([
            DeviceOrientation.portraitUp,
            DeviceOrientation.portraitDown,
            DeviceOrientation.landscapeLeft,
            DeviceOrientation.landscapeRight
          ]);
        });
      }
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Normal player"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Text(
              "Normal player with configuration managed by developer.",
              style: TextStyle(fontSize: 16),
            ),
          ),
          AspectRatio(
            aspectRatio: 16 / 9,
            child: BetterPlayer(controller: _betterPlayerController),
          )
        ],
      ),
    );
  }

  bool _isPortraitMode() {
    var windowSize = WidgetsBinding.instance.window.physicalSize;
    return windowSize.width < windowSize.height;
  }

  @override
  void didChangeMetrics() {
    var isPortraitMode = _isPortraitMode();

    ///Ignore if last mode was portrait
    if (_lastPortraitState == isPortraitMode) {
      return;
    }

    if (_lastPortraitState == false && isPortraitMode && _betterPlayerController.isFullScreen) {
      _betterPlayerController.toggleFullScreen();
    }
    _lastPortraitState = isPortraitMode;
  }
}

```

**Comment by jhomlala** [comment]
I believe this issue is solved. Please let me know, if this issue still happens, so I'll reopen it.

**Comment by SinoMiles** [comment]
@jhomlala   
when device orientation is locked. use this code Three seconds later. the BetterPlayer will return to   DeviceOrientation.portraitUp.do you have another way to solve this problem .thanks
```
        ///Delay required to screen properly rotate to landscape. Then change
        ///orientation both portrait and landscape, so user can rotate to portrait.
        Future.delayed(Duration(milliseconds: 3000), () {
          SystemChrome.setPreferredOrientations([
            DeviceOrientation.portraitUp,
            DeviceOrientation.portraitDown,
            DeviceOrientation.landscapeLeft,
            DeviceOrientation.landscapeRight
          ]);
        });
```

**Comment by JoseBarreto1** [comment]
> @jhomlala when device orientation is locked. use this code Three seconds later. the BetterPlayer will return to DeviceOrientation.portraitUp.do you have another way to solve this problem .thanks
> 
> ```
>         ///Delay required to screen properly rotate to landscape. Then change
>         ///orientation both portrait and landscape, so user can rotate to portrait.
>         Future.delayed(Duration(milliseconds: 3000), () {
>           SystemChrome.setPreferredOrientations([
>             DeviceOrientation.portraitUp,
>             DeviceOrientation.portraitDown,
>             DeviceOrientation.landscapeLeft,
>             DeviceOrientation.landscapeRight
>           ]);
>         });
> ```

I also have this problem

**Comment by hanescargot** [comment]
hi!

`
List<DeviceOrientation> deviceOrientationsOnFullScreen = [
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight
    ];
     
BetterPlayerConfiguration(
          deviceOrientationsOnFullScreen: deviceOrientationsOnFullScreen,
          deviceOrientationsAfterFullScreen: deviceOrientationsOnFullScreen,
        ),
        `
