### ISSUE TITLE
[BUG] Compatiblity with Flutter 1.20.3 vs BetterPlayer 0.0.31

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [jhomlala/betterplayer#118]
**Describe the bug**
I have BetterPlayer v0.0.25 and I would like to upgrade to v0.0.31 but it says it's incompatible

```
Because every version of flutter_test from sdk depends on meta 1.1.8 and better_player >=0.0.26 depends on meta ^1.2.3, flutter_test from sdk is incompatible with better_player >=0.0.26.
```

**To Reproduce**
1. Download Flutter 1.20.3
2. Open pubspec.yaml
3. Add `better_player: ^0.0.31`
4. Run `flutter packages pub get`

**Expected behavior**
it should be installed and working fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/18269514/98201786-289e6c00-1f39-11eb-9719-9f07df9f266b.png)

**Flutter doctor**
```
[✓] Flutter (Channel stable, 1.20.3, on Linux, locale en_GB.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Better Player version**
- Version: 0.0.31

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android Samsung_Note_9_API_29

**Additional context**

**Comment by jhomlala** [comment]
@AhmedNourJamalElDin Please upgrade to last stable Flutter version which is 1.22.3.

**Comment by AhmedNourJamalElDin** [comment]
It's not easy to do this at the moment as I have like many projects using 1.20.3.
If I can make a PR to fix this, please let me know what to do.

**Comment by jhomlala** [comment]
So just use lower Better Player version until you'll upgrade your Flutter version. Staying too long in one version may leads to similiar issues in the future.

Anyway you can try this. Add this configuration to pubspec.yaml:
```dart
dependency_overrides:
  wakelock: 0.2.1
  meta: 1.1.8
```

**Comment by AhmedNourJamalElDin** [comment]
hmm, ok.
Thanks a lot. I'm closing this and will upgrade flutter when possible.
