### ISSUE TITLE
[BUG] Compatiblity with BetterPlayer 0.0.31 with chewie

### ISSUE THREAD

**Issue by svoza10** [jhomlala/betterplayer#119]
**Describe the bug**
I have BetterPlayer v0.0.25 and I would like to upgrade to v0.0.31 but it says it's incompatible with other package.

**Expected behavior**
it should be installed and working fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/71311571/98223119-f64d3880-1f51-11eb-8277-e8bb158877b2.png)

**Flutter doctor**
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale cs-CZ)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code, 64-bit edition (version 1.50.0)
[√] Connected device (1 available)

**Better Player version**
- Version: 0.0.31

**Smartphone (please complete the following information):**
 - Device: Emulator and honor 8

**Comment by jhomlala** [comment]
You're using flutter_html which uses Chewie which uses outdated wakelock plugin. Better Player uses new wakelock plugin version, so pub get fails. What you can do is:
* remove any plugin which uses outdated Chewie
* or add this to your pubspec.yaml
```
dependency_overrides:
  wakelock: 0.2.1
```
This will override wakelock dependency in all plugins from your pubspec.yaml so it will uses latest wakelock version.

**Comment by jhomlala** [comment]
Chewie has received recently updates, so it can be closed.
