### ISSUE TITLE
[GITHUB] Marking releases with tags

### ISSUE THREAD

**Issue by orestesgaolin** [jhomlala/betterplayer#120]
**Is your feature request related to a problem? Please describe.**

As developer I would be happy to be able to compare source code between the versions of the plugin. Having tags or releases for each pub release would be extremely helpful.

**Describe the solution you'd like**

Marking pub release commits with git tags or GitHub Releases

**Describe alternatives you've considered**

Maybe branches per each release

**Additional context**

I have issue with better_player and I'm not sure if this is my fault or some change in the native code.

**Comment by jhomlala** [comment]
@orestesgaolin Thanks, will do that in next releases. I've just released 0.0.32 with Github Releases.
