### ISSUE TITLE
Ac3 decoding not possible

### ISSUE THREAD

**Issue by lechevo** [jhomlala/betterplayer#121]
I am having no sound for video with ac3 codec neither in emulator or real device.

Any chance we could get the ac3 decoding ?

**Comment by jhomlala** [comment]
@lechevo 
* On iOS AVPlayer doesn't support AC3.
* On Android ExoPlayer supports AC3 only with ffmpeg extension, which requires a lot of work to just use it. I belive at this moment with my current timeframes it won't be doable.
