### ISSUE TITLE
BetterPlayerListViewPlayer  auto play/pause doesn't work when the video is bigger

### ISSUE THREAD

**Issue by thirtysixmm** [jhomlala/betterplayer#125]
Steps to reproduce

**To Reproduce**
1. Create a vertical video.
2.  Add this video to a list view using BetterPlayerListViewPlayer 
3. Add a fixed header so that the video height will be bigger than the available height.
4. Scroll up/down

**Expected behavior**
The screen has only the video in display and hence it should auto play.
**Better Player version**
- Version: 0.0.33

**Comment by jhomlala** [comment]
Can you provide your sample video?

**Comment by jhomlala** [comment]
You should lower playFraction. Try playing with values below 0.5.
