### ISSUE TITLE
Is it possible to detect orientation of video and handle full screen appropriately?

### ISSUE THREAD

**Issue by bagintz** [jhomlala/betterplayer#127]
Rather than storing the meta data with the state of the image being loaded and configuring the settings in client code, can the package detect what the orientation and open Landscape videos fullscreen in Landscape and Portrait in Portrait?

Not sure how possible this is, but I have had a heck of a time working on the client side (due to different packages handling height, width and orientation detection differently (or not at all!)

Thanks!

**Comment by jhomlala** [comment]
At this moment it's not doable, because even if you change device orientation, then aspect ratio is static. Maybe there is a chance to introduce automatic aspect ratio picking, but I can't give you exact timeframes when it will be solved.

**Comment by jhomlala** [comment]
Please upgrade to Better Player 0.0.36 and use this parameter from BetterPlayerConfiguration:
```    ///Defines if player should auto detect full screen device orientation based
    ///on aspect ratio of the video. If aspect ratio of the video is < 1 then
    ///video will played in full screen in portrait mode. If aspect ratio is >= 1
    ///then video will be played horizontally. If this parameter is true, then
    ///[deviceOrientationsOnFullScreen] and [fullScreenAspectRatio] value will be
    /// ignored.
    final bool autoDetectFullscreenDeviceOrientation;```
