### ISSUE TITLE
[BUG] showControlsOnInitialize not working

### ISSUE THREAD

**Issue by syssam** [jhomlala/betterplayer#131]
showControlsOnInitialize set to false, however, it visible on the begin

**Comment by syssam** [comment]
What different bettween BetterPlayerConfiguration.showControlsOnInitialize and BetterPlayerControlsConfiguration.showControlsOnInitialize

**Comment by jhomlala** [comment]
Removed BetterPlayerConfiguration.showControlsOnInitalize since it does nothing. Use BetterPlayerControlsConfiguration.showControlsOnInitalize.
