### ISSUE TITLE
[Betterplayer video screen is black but sound is playing]

### ISSUE THREAD

**Issue by TuhinFortmindz** [jhomlala/betterplayer#1315]
**History check**
Yes

**Describe the bug**
Run it with flutter run in my IOS real device.  but the better player shows a black screen on IOS iPhone . Android can play the videos which IOS can't play the videos.

**Comment by mehmetmutluelmas** [comment]
I have that same problem.

**Comment by ahmaaz10** [comment]
Merhaba Mehmet,iPhone simulatorda video gözükmez ama gerçek cihazda gözükür

**Comment by TuhinFortmindz** [comment]
in simulator is not working guys, but in real device it seems work.

**Comment by ahmaaz10** [comment]
Actually you can try updating your ios simulator to ios 17.4 or above and it will work on simulator too!

**Comment by mehmetmutluelmas** [comment]
> Actually you can try updating your ios simulator to ios 17.4 or above and it will work on simulator too!

ios 17.5 kullanıyorum fakat gözükmüyor.
