### ISSUE TITLE
iOS does not show the first frame of remote videos [BUG]

### ISSUE THREAD

**Issue by MikeDaniel18** [jhomlala/betterplayer#132]
**Describe the bug**
When loading a remote video on iOS a black screen is shown rather than the first frame of the video. Similarly, when playback has finished the final frame is also not shown, instead, the same black screen is shown.

**To Reproduce**
- Load a remote video on iOS with a `BetterPlayer()`
- Remove controls
- Display (in a ListView)

**Expected behavior**
I would expect the first frame of the video to be shown in the video area instead of a black screen. On Android it works as intended.

**Better Player version**
- Version: ^0.0.33

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.1

**Comment by jhomlala** [comment]
This is default behavior of AVPlayer, used in iOS. There is a change to fix it by using AVAssetImageGenerator to generate temporary thumbnail. I can't give exact timeframes when it will be solved.

**Comment by MikeDaniel18** [comment]
@jhomlala hopefully that'll be implemented at some point, is there anywhere we can follow its progress? If we generate the thumbnail ourselves, what's the best way of displaying it?

**Comment by MiroLiebschner** [comment]
@MikeDaniel18 do you also have a black screen when you pause the video?

**Comment by MikeDaniel18** [comment]
@MiroLiebschner Yes I do. Whenever a video is not actively playing, it's black which is an inconvenience.

**Comment by MiroLiebschner** [comment]
@jhomlala  I would argue that this is an important feature as use cases related to learning are affected.

**Comment by jhomlala** [comment]
There was issue with pixel buffer in ios native code. It should be fixed in Better Player 0.0.35.
