### ISSUE TITLE
how to solve this problem im using custom  header headers: {key: value}

### ISSUE THREAD

**Issue by kadan-dev** [jhomlala/betterplayer#135]
if  i run in emulator its work but if i run on real device its not work

error 1................................................................... on real device its not work
Set data source: DataSource{sourceType: DataSourceType.network, uri: http://anyhost/upload/images/logoA03.m3u8, formatHint: null, asset: null, package: null, closedCaptionFile: null, headers: {Referer: http://anyhost.com/, User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36}, useCache: false, maxCacheSize: 0, maxCacheFileSize: 0}
E/ExoPlayerImplInternal( 3036): Source error.

error 2................................................................... if i bulid apk and not work on real device

Running Gradle task 'assembleRelease'...
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\better_player-0.0.33\android\src\main\java\com\jhomlala\better_player\BetterPlayerPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\better_player-0.0.33\android\src\main\java\com\jhomlala\better_player\BetterPlayerPlugin.java uses unchecked or unsafe operations.

**Comment by jhomlala** [comment]
Please create ticket based on issue template. From my perspective, there is an issue with your datasource url. When you're testing app with simulator, you've probably access to http://anyhost/upload/images/logoA03.m3u8 resource, but your real device don't have access to this resource.  Please try uploading your video to some external server.
