### ISSUE TITLE
Play audio only mode when app is in background

### ISSUE THREAD

**Issue by shashikantdurge** [jhomlala/betterplayer#136]
**Is your feature request related to a problem? Please describe.**
When a user clicks on the home button or navigates to another app, the video pauses. It should be configurable by the developers.

**Describe the solution you'd like**
Either play the video in PIP mode or play audio only in the background 

Check out https://pub.dev/packages/flutter_vlc_player

**Comment by jhomlala** [comment]
PiP mode is something that I plan to add, but there are no timeframes when it will be done.

**Comment by jhomlala** [comment]
Added player notifications in 0.0.38.
