### ISSUE TITLE
This line causes invalid radix error

### ISSUE THREAD

**Issue by CalmAndCoDe** [jhomlala/betterplayer#137]
Hi, i have used this player and i had an issue with parsing vtt subtitles and when i checked then i notice that
```
var index = int.parse(scanner[0]);
```
caused the subtitle parse fail and i couldn't find anywhere that uses the index argument, so i removed it and everything works fine now. 
Note: this code will only work if you use subtitle with srt format not vtt.
for using both srt and vtt you have to check if the first index of scanner[0] is a number according to srt time-encode so i used:
```
// handle srt parsing for multi line subtitle
if (int.tryParse(scanner[0]) != null) {
   scanner.removeAt(0);
}
```
https://github.com/jhomlala/betterplayer/blob/943798b633b6788d98e13222b6cb09fb71fb2342/lib/src/subtitles/better_player_subtitle.dart#L56

**Comment by jhomlala** [comment]
@CalmAndCoDe can you provide sample subititles which cause this error?

**Comment by jhomlala** [comment]
Please check Better Player 0.0.35. I've added there subtitles parsing fixes.

**Comment by jhomlala** [comment]
If problem still happens, please let me know here and I'll reopen this ticket.
