### ISSUE TITLE
[BUG] Event for HIDE_FULLSCREEN doesn't work with the android back button

### ISSUE THREAD

**Issue by rc8marcelo** [jhomlala/betterplayer#139]
**Describe the bug**
So I have a video that only plays in full screen (I toggle it whenever the user plays). Whenever you either swipe back or press the Android back button (the left point arrow or Android 10 gesture), the player goes out of full screen. I want to pause the player when this happens however when I set the event for `HIDE_FULLSCREEN`, the event is not fired if you go out of full screen without tapping the full screen icon or programmatically calling it when you press any other control with `exitFullScreen()`

**To Reproduce**
1. Play video (set it so that when the PLAY event is fired, `enterFullScreen()` is called and `pause()` is called when `HIDE_FULLSCREEN` event is fired)
2. Either tap the Android's back/up button or use gesture to go to previous screen
3. Verify that the video is still playing 

**Expected behavior**
I want the `HIDE_FULLSCREEN` event to fire when the back button in Android is tapped or the gesture for back is triggered

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version: 0.0.34

**Smartphone (please complete the following information):**
 - Device: Poco F2 Pro
 - OS: Android 10

**Additional context**

My code for listening to events:

```dart
_betterPlayerController.addEventsListener((event) async {
      if (event.betterPlayerEventType == BetterPlayerEventType.PROGRESS) {
        currentWatched = event.parameters["progress"] as Duration;
      } else if (event.betterPlayerEventType == BetterPlayerEventType.PLAY) {
        _betterPlayerController.toggleFullScreen();
      } else if (event.betterPlayerEventType == BetterPlayerEventType.PAUSE) {
        _betterPlayerController.exitFullScreen();
      } else if (event.betterPlayerEventType ==
          BetterPlayerEventType.HIDE_FULLSCREEN) {
        await _betterPlayerController.pause();
      }
    });
```

My controller's config:

```dart
final betterPlayerControlsConfiguration = BetterPlayerControlsConfiguration(
      showControls: true,
      enableSkips: false,
      enableFullscreen: false,
      enableOverflowMenu: false,
      iconsColor: complianceYellow,
      progressBarHandleColor: complianceYellow,
      progressBarPlayedColor: complianceYellow,
    );
    _betterPlayerConfiguration = BetterPlayerConfiguration(
      controlsConfiguration: betterPlayerControlsConfiguration,
      deviceOrientationsOnFullScreen: [
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight
      ],
      fit: BoxFit.fitHeight,
      autoPlay: false,
    );
```

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.35.

Also, please modify your code to sample presented below, to block infinite loop of events.
```
_betterPlayerController.addEventsListener((event) async {
      if (event.betterPlayerEventType == BetterPlayerEventType.PROGRESS) {
        currentWatched = event.parameters["progress"] as Duration;
      } else if (event.betterPlayerEventType == BetterPlayerEventType.PLAY) {
        _betterPlayerController.toggleFullScreen();
      } else if (event.betterPlayerEventType == BetterPlayerEventType.PAUSE) {
        _betterPlayerController.exitFullScreen();
      } else if (event.betterPlayerEventType ==
          BetterPlayerEventType.HIDE_FULLSCREEN) {
       if (betterPlayerController.isPlaying()){
        await _betterPlayerController.pause();
       }
      }
    });```

**Comment by rc8marcelo** [comment]
Thanks for the fast response!

**Comment by HenglyEver** [comment]
I can reproduce this in `0.0.61`. Clicking the back button on Android when the video player is in full screen doesn't fire `BetterPlayerEventType.hideFullscreen` event.
