### ISSUE TITLE
Expose the initialize method from the internal VideoPlayerController

### ISSUE THREAD

**Issue by jinyus** [jhomlala/betterplayer#140]
**Is your feature request related to a problem? Please describe.**
The VideoPlayerController has a method called "initalize" which loads the video when called and throws an exception if the video fails to load. I need this because I manage my video player state in a bloc and do all the setup there and pass the controller to the UI if it loaded successfully.

**Describe the solution you'd like**
I would really appreciate if you could expose this method on the BetterPlayerController. So when I call initalize on the controller, it loads the video.

**Comment by jhomlala** [comment]
Added INITALIZED event in Better Player 0.0.36. Use event listener to get this event.

**Comment by jinyus** [comment]
Hello, I think it's worth reopening this issue because I forgot to mention something important in my use case. I use the initialize method so I can get the aspect ratio of the video before building the player. Your proposed method of using the initialized event would require me to rebuild the widget and the video just to get the correct aspect ratio. Here is how I currently doing it with chewie:

```
final vController = VideoPlayerController.network(fileToBePlayed);

  // load the video file
  await vController.initialize();

  // check if aspect ratio is valid
  final noAspectRatio = vController.value.aspectRatio.isNaN;

// assign aspect ratio before building the player
  final aspectRatio = noAspectRatio ? 3 / 2 : vController.value.aspectRatio;
  final cController = ChewieController(
        videoPlayerController: vController,
        aspectRatio: aspectRatio,
        autoPlay: true,
        looping: true,
  );

  // build the player
```

With Better player, since the aspectRatio is set in the BetterPlayerConfiguration, I would have to:
1. build the player
2. listen for when it's initialize
3. get aspect ratio from video (controller.videoPlayerController.value.aspectRatio)
4. create a new configuration with new aspect ratio
5. build the player again and reload the video (ie: wasting bandwidth)

With Chewie, these are the steps:
1. Initialize the video and get the aspect ratio
2. build the player

I hope you see what I am trying to convey here.
