### ISSUE TITLE
Issue with "Video Failed to Load"

### ISSUE THREAD

**Issue by bagintz** [jhomlala/betterplayer#143]
I am getting an error when I go into full screen, play a video and then come back out:

E/ExoPlayerImplInternal(20776): Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [640, 1136, 29.930895], [-1, -1]), rendererSupport=YES
E/ExoPlayerImplInternal(20776):   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder, Format(1, null, null, video/avc, null, -1, null, [640, 1136, 29.930895], [-1, -1])
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:563)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1254)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:814)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:712)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
E/ExoPlayerImplInternal(20776):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(20776):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(20776):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(20776):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder, Format(1, null, null, video/avc, null, -1, null, [640, 1136, 29.930895], [-1, -1])
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:867)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)
E/ExoPlayerImplInternal(20776):       ... 9 more
E/ExoPlayerImplInternal(20776):   Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(20776):       at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(20776):       at android.media.MediaCodec.start(MediaCodec.java:2235)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:931)
E/ExoPlayerImplInternal(20776):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:860)
E/ExoPlayerImplInternal(20776):       ... 10 more

**Comment by jhomlala** [comment]
Please use issue template.

This issue is similar to https://github.com/jhomlala/betterplayer/issues/27
What's the device that you're using?

**Comment by bagintz** [comment]
Will do, this is on a Pixel 5

**Comment by jhomlala** [comment]
If you still have issue please create issue with bug template.

**Comment by bagintz** [comment]
Sorry, I misunderstood, I am still having the issue and will resubmit.  Thanks
