### ISSUE TITLE
Video Portrait from Full Screen(Landscape)

### ISSUE THREAD

**Issue by MhtSuthar** [jhomlala/betterplayer#144]
Hi, once again @jhomlala , 

Actually, all works perfect but some days ago I updated your latest version **0.34** from **0.31** you can see that if my video is playing on full screen and I am pressing the play, pause button then the video goes to portrait mode, 

again press the full-screen button and goes to landscape mode and press again pause and play then also goes to portrait screen.
Which is weird, in the 0.31 version is good but after that version, this issue is coming.
Plz, check.
Thank you for your replay.

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.35.
