### ISSUE TITLE
Support MKV embeded subtitles and track selection

### ISSUE THREAD

**Issue by CalmAndCoDe** [jhomlala/betterplayer#146]
**Is your feature request related to a problem? Please describe.**
hi, please add Mkv embedded subtitles and tracks selections support for this plugin.

**Comment by mr-mamali** [comment]
+1

**Comment by jhomlala** [comment]
MKV is not supported in iOS AVPlayer. Main goal of BetterPlayer is to have same features in both Android/iOS. Right now I won't implement it, since it's only possible on Android side.
