### ISSUE TITLE
[BUG] Error fluter build apk with SDK 30

### ISSUE THREAD

**Issue by piotrmarcinkowski99** [jhomlala/betterplayer#147]
When I run "flutter build apk --release --split-per-abi --no-shrink" I am getting the below error. I think that the problem is about SDK 30.

Running Gradle task 'assembleRelease'...        Note: /Users/**/Desktop/development/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.35/android/src/main/java/com/jhomlala/better_player/BetterPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/**/Desktop/development/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.35/android/src/main/java/com/jhomlala/better_player/BetterPlayerPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: Some input files use unchecked or unsafe operations.                                                         
Note: Recompile with -Xlint:unchecked for details.   

**Better Player version**
- Version: 0.0.35 / 0.0.34

**SDK version **
- Version: 30

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G73 darwin-x64, locale pl-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by jhomlala** [comment]
@piotrmarcinkowski99 This is only warning, but yep, I need to remove deprecated API.

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.43.
