### ISSUE TITLE
[BUG] On autoplay enable and app in background, the video keeps playing

### ISSUE THREAD

**Issue by harolCalzada** [jhomlala/betterplayer#149]
**Describe the bug**
On autoplay enable and video still initializing  and  put the app in background,a few seconds the video starts playing.
**To Reproduce**
1. enable autoplay
2. open the screen with autoplay enable
3. minimize the app quickly
4. wait a few seconds, the video should start to play

**Expected behavior**
the app should dispose the video if still no finish initialization at moment of minimize or change application

**Flutter doctor**
✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale es-PE)
    • Flutter version 1.22.4 at /Users/harolcalzada/development/flutter
    • Framework revision 1aafb3a8b9 (hace 9 d'ias), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/harolcalzada/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Users/harolcalzada/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Mi 9T (mobile) • 7358807d • android-arm64 • Android 10 (API 29)

• No issues found!

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale es-PE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

• No issues found!

**Better Player version**
- Version: 0.0.35

**Smartphone (please complete the following information):**
 - Device: Mi 9T 
 - OS: Android 10

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.36.
