### ISSUE TITLE
Seekbar not working smoothly

### ISSUE THREAD

**Issue by trademunch** [jhomlala/betterplayer#15]
When seeking the movie, Seekbar doesn't move smoothly and unable to seek ahead or backward

**Comment by jhomlala** [comment]
Can you explain "doesn't move smoothly"? Maybe it's because you have small screen, and you can't click on it correctly? Can you show some flutter lib (or android) where move is "smooth"?

**Comment by trademunch** [comment]
No, I have a bigger screen and when I try to hold and move the seekbar to some other position it doesn't get dragged properly.
It doesn't work in normal mode and full screen mode both.
There's a lag when moving the seekbar.

Check out the link where I have attached the screen recording video

https://drive.google.com/file/d/1AsNkxT0-cr2qLEzZarufgOXISa7rcirY/view?usp=drivesdk

**Comment by jhomlala** [comment]
Fixed in 0.0.7. Please reopen if error still happens.
