### ISSUE TITLE
How to have animation on going fullscreen?

### ISSUE THREAD

**Issue by janlektonen** [jhomlala/betterplayer#150]
I like you player alot. Nice with video cache 👍 

I have implemented Hero() in the widget used as "overlay" in Betterplayer and the overlay have nice animation. But when player goes fullscreen there is no animation, it just goes fullscreen immediately without any animation. Only the overlay have animation and it does not look so good.

How can I have animation on player going fullscreen?

NB. I do not use your routePageBuilder as it does not work with fullscreen on and off while playing, without disposing video as far as I could learn.

**Comment by jhomlala** [comment]
@janlektonen You should routePageBuilder to create desired animation. Can you give me steps to reproduce issue that you encountered?

**Comment by janlektonen** [comment]
Okay, thank you for your answer. I would just like to have animation on standard opening to fullscreen in your player without using routePageBuilder. Is that possible?

**Comment by jhomlala** [comment]
No it's not supported. But I believe that you can achieve your animation with routePageBuilder.
