### ISSUE TITLE
[BUG] iOS apps with iOS 14 widget and better_player will get rejected on ITMS-90853: Invalid font

### ISSUE THREAD

**Issue by erickok** [jhomlala/betterplayer#151]
This is effecively the same bug that chewie had: https://github.com/brianegan/chewie/issues/381

better_player is using iconic fonts for button icons: https://github.com/jhomlala/betterplayer/blob/master/pubspec.yaml#L15

If you add better_player now to an iOS app that also has an iOS 14 widget (extension) and submit this for (TestFlight) review, it will get rejected:

    ITMS-90853: Invalid font - There was an error validating the font at 'Runner.app/Frameworks/App.framework/flutter_assets/packages/open_iconic_flutter/assets/open-iconic.woff'. Font not supported by platform.

This is due to the dependency on open_iconic_flutter which embeds the open-iconic font in unsupported woff format.

I am not sure why adding an iOS widget triggers this static analysis at Apple's side, but it is somewhat widely reported that it does, similar to how it did in Flutter itself.

**Better Player version**
- Version: 0.0.35

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.36.
