### ISSUE TITLE
[BUG] iOS 12 Device doesn't display progress indicator circle sometimes

### ISSUE THREAD

**Issue by rc8marcelo** [jhomlala/betterplayer#152]
**Describe the bug**
When setting the `BetterPlayerDataSource` to `.FILE`, the progress indicator circle disappears making it impossible to seek around the video.

**To Reproduce**
1. Setup the `BetterPlayerController`
2. Set the data source to file and provide a valid path to the local video

**Expected behavior**
On iOS 12 Devices, the progress indicator should also be visible. (We've tried this on iOS 13 and it works as intended)

**Screenshots**
![image](https://user-images.githubusercontent.com/341493/100493265-55c4ef80-3170-11eb-87f6-195d0b0eeb26.png)

Video: https://drive.google.com/file/d/1IztzO81dMRK-xR8hvqHA_5Z-FdB71Syl/view?usp=sharing

**Flutter doctor**
![image](https://user-images.githubusercontent.com/341493/100493303-a9cfd400-3170-11eb-99b3-70ac1b3c3247.png)

**Better Player version**
- Version: 0.0.35

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: iOS 12

**Additional context**
This works properly in Android. For context in the video, we let users either view the video online or download it. I provided the code below to show how we switch between the 2 if that helps? 

How I update the controller:

```dart
  Future<void> _switchController({@required bool isLocallyAvailable}) async {
    final datasource =
        _determineVideoSource(isLocallyAvailable: isLocallyAvailable);
    _betterPlayerController =
        BetterPlayerController(_betterPlayerConfiguration);
    await _betterPlayerController.setupDataSource(datasource);
    _betterPlayerController.addEventsListener((event) async {
      //removed for brevity
    });
  }
```

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.36.
