### ISSUE TITLE
DRM

### ISSUE THREAD

**Issue by santhoshprogrammer94** [jhomlala/betterplayer#155]
Is support DRM content?

**Comment by jhomlala** [comment]
This is something I'm planning for the future, but right now there's no timeframes when it'll be done.

**Comment by jhomlala** [comment]
If anyone is interested in DRM:
I'm looking for sample iOS stream with FairPlay DRM (online) to test solutions. If you have one that works, please let me know.

**Comment by JohnGalt1717** [comment]
This should give you all of the variants you need for DRM:

https://ampdemo.azureedge.net/

**Comment by jhomlala** [comment]
@JohnGalt1717 Did it work for you with video_player/better_player?

**Comment by JohnGalt1717** [comment]
@jhomlala They don't work because you have to pass the keys and have the code on ios/android etc. that calls into the the stream for decryption. It's not as simple as http headers.

**Comment by jhomlala** [comment]
@JohnGalt1717 Azure Media Player demo offers Widevine DRM for Android and PlayReady for Windows, Xbox etc. There's nothing about FairPlay in this demo. I believe the mostly used DRM in IOS ecosystem is FairPlay.

**Comment by JohnGalt1717** [comment]
@jhomlala I think if you go here: https://amp.azure.net/libs/amp/latest/docs/samples.html and do a search you'll find the fairplay example (don't know what the other page doesn't have it) and you should be able to view source and take a look at what it does.

the iOS code will have to be expanded to be able to pass the right data and attach the fairplay pipeline to the video playback. The same is true for Widevine on Android/Web and Playready on windows.

When everything gets to the point where UWP support is fully available I'm happy to do a pull request and add the UWP video player as I've done this in the past on Windows with playready support.

**Comment by jhomlala** [comment]
Added first DRM support in 0.0.58. More DRM types may be added in the future. You can request support given DRM type with feature request. With feature request please provide example video with required data like license url, etc.

**Comment by JohnGalt1717** [comment]
@jhomlala Which platform did you add?
