### ISSUE TITLE
Lazy Load option for multiple videos in the same widget/list

### ISSUE THREAD

**Issue by bagintz** [jhomlala/betterplayer#157]
It would be nice to have a lazy load option.

Widgets/Lists with multiple (usually > 3) videos will end up crashing (it seems due to OOM errors).  One possible solution to this is to add Lazy Load option or some equivalent (maybe only load the first image of the video instead of the whole video until the player is interacted with?)

I am sure there are other ideas to solve this but I wanted to see if there was something existing that I am missing that will accomplish the same thing.

**Comment by jhomlala** [comment]
Here is how you can do it: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list

Feel free to answer in this issue, so I will re-open it.
