### ISSUE TITLE
[FEATURE] Changing controls on full screen

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#158]
In my case, I need to hide controls when the video is not played in fullscreen. Then, when changing into fullscreen mode (typically when calling `_betterPlayerController.enterFullScreen();`, I need to somehow be able to change the configuration to display the controls while fullscreen in on. Is there currently a way to do this? If not, perhaps you could give me some indictations as to how you would do it and I can write a PR.

After some testing, it seems to me the most flexible solution is to change `better_player_controller.dart`:   `final BetterPlayerConfiguration betterPlayerConfiguration;` becomes `BetterPlayerConfiguration betterPlayerConfiguration;`  That way we can easily do the following:
```
_betterPlayerController.betterPlayerConfiguration =
    _betterPlayerController.betterPlayerConfiguration.copyWith(
        controlsConfiguration:
            BetterPlayerControlsConfiguration(showControls: true));
_betterPlayerController.enterFullScreen();
```
Does anything speak against? It would be the developer's responsibility not to change parameters that should remain unchanged in the same instance of `BetterPlayerController`.

**Comment by jhomlala** [comment]
Changing betterPlayerConfiguration instance may lead to unexepcted state of Better Player. In 0.0.37 there's new method: setControlsEnabled, which will solve your issue.

https://github.com/jhomlala/betterplayer#enabledisable-controls-always-hidden-if-false

**Comment by themadmrj** [comment]
> Changing betterPlayerConfiguration instance may lead to unexepcted state of Better Player. In 0.0.37 there's new method: setControlsEnabled, which will solve your issue.
> 
> https://github.com/jhomlala/betterplayer#enabledisable-controls-always-hidden-if-false

Brillant thanks a lot!
