### ISSUE TITLE
Enhancement to make this best - IMA ads

### ISSUE THREAD

**Issue by trademunch** [jhomlala/betterplayer#16]
Can you add IMA ads to this plugin so that we can show skippable video ads before the player starts playing videos.

No other player has this feature and supporting ads could make this plugin stand apart and help many developers.

**Comment by jhomlala** [comment]
This plugin scope is to provide white label player for flutter. I think that IMA ads is scope for another plugin.

**Comment by trademunch** [comment]
Closing this issue.
