### ISSUE TITLE
when autoPlay how mute when initialize

### ISSUE THREAD

**Issue by Mohamed-Elsayed-Nadsoft** [jhomlala/betterplayer#160]

**Comment by rc8marcelo** [comment]
Without any sample code I think its hard to find out how you're using the controller and the widget but assuming you've setup your controller you just have to add an event listener like so:

```dart
_betterPlayerController.addEventsListener((event) async {
      if (event.betterPlayerEventType == BetterPlayerEventType.INITIALIZED) {
        _betterPlayerController.setVolume(0.0); 
      }
});
```

I don't think there's an actual `.mute()` function that you can call from what I've seen so I also don't know how this works with the mute button on the controls

**Comment by jhomlala** [comment]
I believe this issue has been solved with code above. If not, please reply and I'll open this issue.
