### ISSUE TITLE
Re: exposing the initialize method on the videoplayerController

### ISSUE THREAD

**Issue by jinyus** [jhomlala/betterplayer#161]
Hello, I think it's worth reopening this issue because I forgot to mention something important in my use case. I use the initialize method so I can get the aspect ratio of the video before building the player. Your proposed method of using the initialized event would require me to rebuild the widget and the video just to get the correct aspect ratio. Here is how I currently doing it with chewie:

```
final vController = VideoPlayerController.network(fileToBePlayed);

  // load the video file
  await vController.initialize();

  // check if aspect ratio is valid
  final noAspectRatio = vController.value.aspectRatio.isNaN;

// assign aspect ratio before building the player
  final aspectRatio = noAspectRatio ? 3 / 2 : vController.value.aspectRatio;
  final cController = ChewieController(
        videoPlayerController: vController,
        aspectRatio: aspectRatio,
        autoPlay: true,
        looping: true,
  );

  // build the player
```

With Better player, since the aspectRatio is set in the BetterPlayerConfiguration, I would have to:
1. build the player
2. listen for when it's initialize
3. get aspect ratio from video (controller.videoPlayerController.value.aspectRatio)
4. create a new configuration with new aspect ratio
5. build the player again and reload the video (ie: wasting bandwidth)

With Chewie, these are the steps:
1. Initialize the video and get the aspect ratio
2. build the player

I hope you see what I am trying to convey here.

**Comment by jhomlala** [comment]
In 0.0.37 there's new method: setOverriddenAspectRatio. This method allows you to override aspect ratio from static configuration.
https://github.com/jhomlala/betterplayer#set-overridden-aspect-ratio-if-passed-overriddenaspectratio-will-be-used-instead-of-aspectratio
