### ISSUE TITLE
[BUG] BetterPlayerController isPlaying() should not be async

### ISSUE THREAD

**Issue by hongfeiyang** [jhomlala/betterplayer#162]
**Describe the bug**
BetterPlayerController isPlaying() should not be async

**To Reproduce**
BetterPlayerController isPlaying() asks for videoPlayerController.value.isPlaying which is not a future, therefore it should not need to return a Future<bool>, it should return a bool directly just like the other properties like isBuffering()

**Comment by jhomlala** [comment]
Fixed in 0.0.37.
