### ISSUE TITLE
[BUG] Just a small UI overflow bug in example app

### ISSUE THREAD

**Issue by mploigt** [jhomlala/betterplayer#165]
**Describe the bug**
An overflow happens in the button row when running the example "video in list"

**To Reproduce**
Run example app
Open "Video in List"

**Expected behavior**
No overflow in button row

**Screenshots**
<img src="https://user-images.githubusercontent.com/433231/101465219-f5883780-393f-11eb-9314-5f0b6ce9f359.PNG" width="200"/>

**Better Player version**
- Version: 0.0.36

**Smartphone**
 - Device: iPhoneX
 - OS: iOS14.2

**Comment by jhomlala** [comment]
Fixed in 0.0.37 release.
