### ISSUE TITLE
[HELP] How do i iterate over a snapshot data to build data source for multiple qualities?

### ISSUE THREAD

**Issue by RGProjectX** [jhomlala/betterplayer#166]
Hello i tried multiple ways to figure out but can't seem to get it right. If possible can you guys drop some solutions with examples?
P.S : I'm using stream builder and my json is structured as followed
```
{
"response" : {
"items" : [{
"quality" : "720",
"url": link
},
{
"quality" : "1080",
"url": link
}]
}
}
```

**Comment by jhomlala** [comment]
@RGProjectX You didn't provide informations which can help me detect whenever this is Better Player issue or not. Form my perspective you're having problem with extracting data from your json. What you need to do is to parse your response to Map<String,String> where key is quality and url is value. Then if you have this map you can add it to your datasource in resolutions parameter.

How to parse json properly: https://medium.com/flutter-community/parsing-complex-json-in-flutter-747c46655f51 (check #4 section). 

Please use issue template next time.

**Comment by RGProjectX** [comment]
Yeah thanks to your suggestions i got past that while my resolutions parameter works fine I've faced a new sort of error that is when i pass my url as default url for datasource it works perfectly fine but when the same url is passed in the resolution parameters it returns this 
Error:
```
Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403, null, null)
```

Note : The same url works fine in browser and as the default url for the player but returns the above error if passed into the resolution parameter

URL : https://cdn14x.cloud9xx.com/user1342/7f55b8a85cb56bcd20d44fb3d798e693/EP.1.1080p.mp4?token=QVV5UnMG9HH_4KPL33iYSQ&expires=1607867680&id=146053

P.S : The link will probably expire by the time you check it so I'll reply with a new url as soon as i get your reply.

Thanks in advance :)

**Comment by jhomlala** [comment]
@RGProjectX  Try using headers parameter from BetterPlayerDataSource to authorize player. Url with query parameters in given case doesn't owrk.

**Comment by RGProjectX** [comment]
I've been passing headers already but it still doesn't seems to work

**Comment by jhomlala** [comment]
@RGProjectX did you test it on iOS?

**Comment by RGProjectX** [comment]
No i haven't tested on iOS.
Yeah other links works but the one with queries doesn't works while passed via resolution

**Comment by jhomlala** [comment]
Please create new issue with issue template and working link. Please provide link which won't expire in 1-2 days.
