### ISSUE TITLE
[BUG] iOS Devices don't rotate to landscape on full screen

### ISSUE THREAD

**Issue by rc8marcelo** [jhomlala/betterplayer#167]
**Describe the bug**

I found a bug applicable to iOS devices. Setting the options for `deviceOrientationsOnFullScreen` and `deviceOrientationsAfterFullScreen` so that it uses landscape on full screen and goes to portrait on exit works properly on Android but keeps iOS on portrait mode when entering fullscreen.

**To Reproduce**

1. Play a video
2. Verify that the video enters full screen
3. Verify the orientation of the video

**Expected behavior**

When the options for `deviceOrientationsOnFullScreen` and `deviceOrientationsAfterFullScreen` are provided, it should work regardless of platform. (iOS / Android)

**Flutter doctor**

![image](https://user-images.githubusercontent.com/341493/101725343-6a4ba500-3aeb-11eb-9c0d-214d183a1a2c.png)

**Better Player version**
- Version: 0.0.36

**Smartphone (please complete the following information):**

Device: iPhone 6 / iPhone 6S Plus / Poco F2 Pro (working correctly)
OS: iOS 12 / iOS 13 / Android 10

**Additional context**

I've also tried using `SystemChrome.setPreferredOrientations()` which was a piece of code I found in one of the closed issues but it didn't fix the problem and I also found that this code crashes iOS 12 devices for some reason.

**Code To Replicate**

Note: I use the player in a way that it always has to be in full screen so the controls also have the full screen toggle disabled. I simply tap on play to enter and pause to exit full screen mode.

```dart
      //config
      final betterPlayerControlsConfiguration = BetterPlayerControlsConfiguration(
      showControls: true,
      enableSkips: false,
      enableFullscreen: false,
      enableOverflowMenu: false,
      iconsColor: complianceYellow,
      progressBarHandleColor: complianceYellow,
      progressBarPlayedColor: complianceYellow,
    );

    _betterPlayerConfiguration = BetterPlayerConfiguration(
      controlsConfiguration: betterPlayerControlsConfiguration,
      fullScreenByDefault: true,
      fit: BoxFit.scaleDown,
      aspectRatio: 16 / 9,
      autoPlay: false,
      deviceOrientationsOnFullScreen: [
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight
      ],
      deviceOrientationsAfterFullScreen: [
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown
      ],
    );
      //listener
      _betterPlayerController.addEventsListener((event) async {
      if (event.betterPlayerEventType == BetterPlayerEventType.PROGRESS) {
        currentWatched = event.parameters["progress"] as Duration;
      } else if (event.betterPlayerEventType == BetterPlayerEventType.PLAY) {
        _betterPlayerController.enterFullScreen();
      } else if (event.betterPlayerEventType == BetterPlayerEventType.PAUSE) {
        _betterPlayerController.exitFullScreen();
      } else if (event.betterPlayerEventType ==
          BetterPlayerEventType.HIDE_FULLSCREEN) {
        if (await _betterPlayerController.isPlaying()) {
          await _betterPlayerController.pause();
        }
      }
```

**Comment by jhomlala** [comment]
Fixed in 0.0.37 release.
