### ISSUE TITLE
BetterPlayerControlsConfiguration icons too small

### ISSUE THREAD

**Issue by dvird** [jhomlala/betterplayer#173]
the icons size is between 12-16. its too small and unconfigurable.
Im speaking about about the play/pasue/forward/backward buttons

this is how its look like on chewie:
<img width="351" alt="Screen Shot 2020-12-13 at 23 08 30" src="https://user-images.githubusercontent.com/42498461/102024111-9d669080-3d98-11eb-938f-87f9c1d4da8a.png">

and this on better player.
<img width="290" alt="Screen Shot 2020-12-13 at 23 08 30" src="https://user-images.githubusercontent.com/42498461/102024150-dd2d7800-3d98-11eb-84eb-b1fd8b830bac.PNG">

**Comment by jhomlala** [comment]
@dvird Please use issue template next time. Fixed in 0.0.41.
