### ISSUE TITLE
How to dispose player 

### ISSUE THREAD

**Issue by Faizi-Apps** [jhomlala/betterplayer#178]
How to dispose video playing when navigate back 
it still playing video in background

**Comment by jhomlala** [comment]
Better Player will dispose automatically on screen dispose. Maybe your screen doesn't dispose? Please provide sample code and follow issue template. Please answer this topic if you still have issue.

**Comment by ventr1x** [comment]
Didn't even answer the question like in EVERY ticket with this issue.
I tested this player barely a minute and see it randomly playing while already moved away and disposed the screen.
Force dispose (or simple state change) most of the time throws "being used after dispose" exception, which is clearly caused internally.
