### ISSUE TITLE
VideoPlayerValue VideoPlayerController type doesn't expose for usage.

### ISSUE THREAD

**Issue by benzsuankularb** [jhomlala/betterplayer#179]
**Is your feature request related to a problem? Please describe.**

I creating a custom control and found that
`VideoPlayerValue` `VideoPlayerController` type doesn't expose out of the library,
So when I refer to this type and trying to import, The warning shown.

**Describe the solution you'd like**

Expose `VideoPlayerValue` `VideoPlayerController` in the `lib/better_player.dart`.

**Comment by jhomlala** [comment]
Fixed in 0.0.40. You can import VideoPlayerValue.
