### ISSUE TITLE
Controls do not disappear in IOS [BUG]

### ISSUE THREAD

**Issue by dprogrammer** [jhomlala/betterplayer#180]
The controls on the player do not disappear after the video starts

Livestream option enabled

BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK,
        "url/playlist.m3u8",
        liveStream: true,
        useHlsSubtitles: false,
      );
      _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(
          autoPlay: true,
          allowedScreenSleep: false,
          autoDetectFullscreenDeviceOrientation: true,          
          controlsConfiguration: BetterPlayerControlsConfiguration(
              enableOverflowMenu: false,
              enableSubtitles: false,
              enableQualities: false,
              enableSkips: false,
              controlBarColor: Colors.transparent,
              controlBarHeight: 25.0
          ),
          translations: [
            BetterPlayerTranslations(
              controlsLive: "",
            ),
          ],
        ),
        betterPlayerDataSource: betterPlayerDataSource,
      );

The disable command did not work

if (MediaQuery.of(context).orientation == Orientation.portrait) {
      _betterPlayerController.setControlsEnabled(true);
      print("Portrait");
    } else {
      _betterPlayerController.setControlsEnabled(false);
      print("Landscape");
    }

iPhone 5s
OS: 12.4.9

better_player 0.0.37

And Android does not display the controls. I press the screen, they appear and then disappear

**Comment by jhomlala** [comment]
@dprogrammer  Please use issue template next time and at least try to format your code.
setControlsEnabled method has been fixed in 0.0.41.
