### ISSUE TITLE
Move playback speed icon from overflow menu to control bar

### ISSUE THREAD

**Issue by bdoubleu86** [jhomlala/betterplayer#190]
I am wondering how it is possible to position the playback speed icon into the control bar next to the mute button.
I was playing around with customControls, but I cannot figure out how to do it.
Chewie has it implemented like that already. Since you are using chewie internally I think, would it make sense to update to the latest chewie version since it has some nice features as well?

**Comment by jhomlala** [comment]
Just use custom controls builder. Here is an example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/change_player_theme_page.dart
You can change speed with controller's setSpeed method.
