### ISSUE TITLE
[FEATURE] Fadeout placeholder when the video starts playing

### ISSUE THREAD

**Issue by naamapps** [jhomlala/betterplayer#191]
Right now the placeholder switches to the video without any fade and it's not really easy on the eyes. 
It would be great of you can add a fadeout to the placeholder when the video is initialized and starts playing. 
Thanks

**Comment by jhomlala** [comment]
Check this example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/fade_placeholder_page.dart

Feel free to answer in this issue, so I will re-open it.

**Comment by naamapps** [comment]
Thank you @jhomlala! Working great 👍
