### ISSUE TITLE
[BUG] video does not init in release app

### ISSUE THREAD

**Issue by SamuelPerezJimenez** [jhomlala/betterplayer#192]
**Describe the bug**
 In debug it works correctly, but when I go to release in android the video does not start.

flutter build apk

in flutter build apk  --debug work perfectly

**Flutter doctor**
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)      
[√] Connected device (1 available)

• No issues found!

**Better Player version**
- Version: better_player 0.0.42 

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - OS: Android 9

**Comment by jhomlala** [comment]
Please provide link to the video and reproducible code example.

**Comment by SamuelPerezJimenez** [comment]
i also tried with other links
link: https://ss4.domint.net:3018/luna_str/lunatv/playlist.m3u8

      betterPlayerDataSource = new BetterPlayerDataSource(
          BetterPlayerDataSourceType.network,
          "https://ss4.domint.net:3018/luna_str/lunatv/playlist.m3u8",
          useHlsSubtitles: false,
          useHlsTracks: false,
          liveStream: true);
      _betterPlayerController = BetterPlayerController(
          BetterPlayerConfiguration(
              autoPlay: true,
              looping: true,
              allowedScreenSleep: false,
              aspectRatio: 16 / 9,
              controlsConfiguration: BetterPlayerControlsConfiguration(
                  enableSkips: false, enableOverflowMenu: false),
          betterPlayerDataSource: betterPlayerDataSource);

return Center(
            child: Container(
              color: Color.fromRGBO(59, 62, 62, 0.1),
              child: AspectRatio(
                aspectRatio: 16 / 9,
                child: BetterPlayer(
                  controller: _betterPlayerController,
                ),
              ),
            ),
          );

**Comment by jhomlala** [comment]
I've created this sample app:

```dart
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  BetterPlayerDataSource betterPlayerDataSource;
  BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    betterPlayerDataSource = new BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "https://ss4.domint.net:3018/luna_str/lunatv/playlist.m3u8",
        useHlsSubtitles: false,
        useHlsTracks: false,
        liveStream: true);
    _betterPlayerController = BetterPlayerController(
      BetterPlayerConfiguration(
        autoPlay: true,
        looping: true,
        allowedScreenSleep: false,
        aspectRatio: 16 / 9,
        controlsConfiguration: BetterPlayerControlsConfiguration(
            enableSkips: false, enableOverflowMenu: false),
      ),
      betterPlayerDataSource: betterPlayerDataSource,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test"),
      ),
      body: AspectRatio(
        aspectRatio: 16 / 9,
        child: BetterPlayer(controller: _betterPlayerController),
      ),
    );
  }
}

```
Permission in AndroidManifest.xml:
```xml
    <uses-permission android:name="android.permission.INTERNET" />
```

Using Better Player 0.0.42. 

Run app with command:
```bash
flutter run --release
```
Video is playing correctly and I can see the content of the live stream. Please try this on your side. Just create simple project and run it. 

Maybe there is something wrong with your app configuration on release mode. Fow now, I can't see any issue with Better Player.

**Comment by SamuelPerezJimenez** [comment]
Yes, i run it and it works, thank you, was my fault my bad.

**Comment by jhomlala** [comment]
:+1:

Closed issue.
