### ISSUE TITLE
[BUG] [iOS] PlatformException(VideoError, Failed to load video: Cannot Open, null, null) 

### ISSUE THREAD

**Issue by naamapps** [jhomlala/betterplayer#197]
Hey,
I have been testing local video playing with better player.
On android everything works fine.
On iOS, sometimes (but frequently) better player throws an error:
`PlatformException(VideoError, Failed to load video: Cannot Open, null, null)`
The data source type is set to file, and I give it a valid video file path.
```
BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
    BetterPlayerDataSourceType.file,
    file.path,
);
await betterPlayerController.setupDataSource(betterPlayerDataSource);
```
I am implementing a media picker, almost every time I choose a video to show it to the user, it throws the error. After switching to other photos and switch back to the same video the second time (or third), it works fine and plays the video.

**Steps to reproduce the behavior**
Show a local video file on iOS with better player.
Try to switch between multiple video files.

**Expected behavior**
The video should play without a problem.

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Better Player version**
- Version: 0.0.43

**Smartphone**
 - Device: iPhone 8 Plus
 - OS:  iOS 14.0

**Comment by jhomlala** [comment]
@naamapps I've checked it on my side. I've setup screen with 2 buttons which loads file data source to Better Player. 1 video was pretty big (150 MB) and second was small (around 10MB). Both were working fine and videos were loaded correctly.

From my perspective, you're trying to show video from iOS device, without proper access to this video. To make sure that you have access to some video, you need to use application documents directory . Also before using given file, check if it exists.

**Comment by naamapps** [comment]
Thanks for the answer and sorry for the inconvenience.
I found out that the package I was using to build the media picker (https://pub.dev/packages/photo_manager) shows that I needed to call a function to get the file path instead of using the actual file to get the path.
Thanks again
