### ISSUE TITLE
Picture in Picture feature 

### ISSUE THREAD

**Issue by AliHoseinpoor** [jhomlala/betterplayer#199]
**Is your feature request related to a problem? 
Hi dear friend. Thanks for the good package. 
When a video is playing, when we leave the app, the image of that video is no longer visible

**Describe the solution you'd like**
If you can add the picture in picture feature to this package, it will be really great

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jhomlala** [comment]
Added in 0.0.45.

**Comment by SinoMiles** [comment]
> Added in 0.0.45.

how can i set pip size,very small!
![f22eb4a96f29d95e25b9fdd3b35c008](https://user-images.githubusercontent.com/9588025/122681643-f6bbea80-d227-11eb-95ca-831a65071f3e.jpg)

**Comment by VictorLekweuwa** [comment]
How do I set up picture in picture mode or turn it off?
