### ISSUE TITLE
[FEATURE] Max video duration

### ISSUE THREAD

**Issue by naamapps** [jhomlala/betterplayer#201]
Hello again, 
I think it would be nice if you can add a `maxDuration` property to the configuration.
That way we can limit the length of the video that is playing instead of showing the whole video. So when the video arrives to that duration it will cut back to the start if looping or just stop if not looping. 

I need this because in my app I trim the video server side but in client side when picking the media, the video is in full length. I want the user to know that the video will be trimmed automatically.

Thanks

**Comment by arbile26** [comment]
It's a very useful feature!
I need it because I don't play the entire video...
I hope that it will be added very soon.

**Comment by jhomlala** [comment]
Please use issue template.
In the 0.0.44 version there's new overrideDuration parameter in BetterPlayerDataSource. Here is an example:  https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/overriden_duration_page.dart
