### ISSUE TITLE
[BUG] iOS Device orientation don't change to landscape on full screen.

### ISSUE THREAD

**Issue by samo92** [jhomlala/betterplayer#202]
**Describe the bug**
Bug on iOS devices. Setting the options for deviceOrientationsOnFullScreen and deviceOrientationsAfterFullScreen so that it uses landscape on full screen and goes to portrait on exit works properly on Android but keeps iOS on portrait mode when entering fullscreen.

**To Reproduce**

1. Play a video
2. Verify that the video enters full screen
3. Verify the orientation of the video

**Expected behavior**
Device change orientation to landscape.

**Flutter doctor**
![image](https://user-images.githubusercontent.com/12944410/103840817-ea681a80-5057-11eb-8323-da19435385ce.png)

**Better Player version**
- Version: 0.0.43

**Smartphone (please complete the following information):**
 - Device: iPhone XS MAX 
 - OS: iOS 14

**Additional context**
My app only works in portrait mode

**Code**
![image](https://user-images.githubusercontent.com/12944410/103841694-c6a5d400-5059-11eb-87ce-5eb104089db8.png)

**Comment by jhomlala** [comment]
@samo92 You jest need to set orientation in info.plist: https://github.com/jhomlala/betterplayer#ios-only-add-into-infoplist-to-support-fullscreen-rotation
