### ISSUE TITLE
How to reach position value and current index in videoPlaylist?

### ISSUE THREAD

**Issue by venimeux** [jhomlala/betterplayer#203]
Hi,
 I want to show videos list values after the video. How can I reach current index and video position value?
Thanks

**Comment by jhomlala** [comment]
Please use issue template.
Please upgrade to 0.0.44. Here is an example how to access BetterPlayerController in playlist player: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/playlist_page.dart

**Comment by venimeux** [comment]
Thank you for answer. 
Can I start the video from a specific index? For example: 
There is a list of 5 videos and I want it to be played from the 2nd index.
