### ISSUE TITLE
[BUG] how to add Custom controller, center button on player?

### ISSUE THREAD

**Issue by ahmadhariss** [jhomlala/betterplayer#204]
I tried to add center button shows with controls and hide with controls but i wasnt able to achieve this.

Also, hiding forward/backward buttons is not applicable using latest version:    better_player: ^0.0.43

Help needed please.

**Comment by jhomlala** [comment]
Please use issue template. You can use custom controls builder. Here is an example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/change_player_theme_page.dart
