### ISSUE TITLE
[BUG]. Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException

### ISSUE THREAD

**Issue by huxaiphaer** [jhomlala/betterplayer#209]
**Describe the bug**
Some phones like Techno Spark 3 throw an exception on the video as below :

`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(0, null, null, video/avc, avc1.4D4028, -1, null, [320, 180, -1.0], [-1, -1]), null, null)`

**To Reproduce**
If you have an Infinix phone or Techno Spark 3 , the live stream doesn't work , it immediately shows **Video can't be played** error 

**Expected behavior**
The live stream link of the video should stream like other devices 

**Screenshots**
N/A

**Comment by huxaiphaer** [comment]
@jhomlala ,  is there any solution for this ? Thanks

**Comment by jhomlala** [comment]
Can you share livestream URL? I don't have that kind of devices, they are not available in my country. Can you create simple ExoPlayer Android native app with your livestream?

**Comment by huxaiphaer** [comment]
Maybe let me share the link [http://197.239.30.29/readymedia/stream/DREAMTV/5-hls/live-media.m3u8](here). For the native you mean I create a flutter app or android java /kotlin native ?

**Comment by huxaiphaer** [comment]
On some devices, the URL works well, but some it doesn't work like that device.

**Comment by huxaiphaer** [comment]
@jhomlala , any update on this one ?

**Comment by jhomlala** [comment]
This error is ExoPlayer one, which can't be handled. Basically there's no fix for that. This may happen randomly on any device. There are many Android powered devices and there can be problems like this with some of them.

**Comment by jhomlala** [comment]
I can't help you right now. If someone else will find solution, please respond in this issue and I'll reopen it.
