### ISSUE TITLE
VideoPlayerController was used after being disposed

### ISSUE THREAD

**Issue by leszekkrol** [jhomlala/betterplayer#21]
Hello, 

In the example attached to the library, I increased the number of films to 100 on the list.builder. after rewinding the first dozen or so films, an error is displayed.

"A VideoPlayerController was used after being disposed. One you have called dispose() on a VideoPlayerController, it can no longer be used"

can you fix this problem?

**Comment by leszekkrol** [comment]
This quick fix temporary hide this issue. The problem lies in the controller itself, which is initiated when rendering the widget, when it is removed from the memory, the videocontroller will not be restored


`class VideoContainerState extends State<VideoContainer> {
  Widget player;
  
  @override
  void initState() {
    player = BetterPlayerListVideoPlayer(
      BetterPlayerDataSource(BetterPlayerDataSourceType.NETWORK, "${widget.filename}"),
      configuration: BetterPlayerConfiguration(
        autoPlay: false,
        allowedScreenSleep: false,
        looping: false,
        showControlsOnInitialize: true,
        controlsConfiguration: BetterPlayerControlsConfiguration(
          progressBarPlayedColor: Color.fromRGBO(78, 88, 110, 1.0),
          progressBarHandleColor: Color.fromRGBO(78, 88, 110, 1.0),
        ),
        errorBuilder: (context, errorMessage) {
          return Center(
            child: Text(
              errorMessage,
              style: TextStyle(color: Colors.white),
            ),
          );
        },
      ),
      playFraction: 0.8,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return player;
  }
}`

**Comment by jhomlala** [comment]
Fixed, please check next release.

**Comment by leszekkrol** [comment]
@jhomlala I have checked the new release and do not think the problem will be fixed.

Still I got similar error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: A VideoPlayerController was used after being disposed.
E/flutter (27887): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
E/flutter (27887): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:106:9)
E/flutter (27887): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:112:6)
E/flutter (27887): #2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:179:12)
E/flutter (27887): #3      VideoPlayerController.dispose (package:better_player/src/video_player/video_player.dart:343:11)
E/flutter (27887): <asynchronous suspension>
E/flutter (27887): #4      BetterPlayerController.dispose (package:better_player/src/core/better_player_controller.dart:292:28)
E/flutter (27887): #5      BetterPlayerState.dispose (package:better_player/src/core/better_player.dart:51:23)
E/flutter (27887): #6      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4729:12)

**Comment by leszekkrol** [comment]
@jhomlala I noticed that the error appears when the movie is loading and the user happens by clicking skip button. if I load the entire movie and start playing it, the problem will no longer occur. Can you improve the first case?

**Comment by gabdsg** [comment]
On 0.0.9
A BetterPlayerController was used after being disposed.
Once you have called dispose() on a BetterPlayerController, it can no longer be used.
