### ISSUE TITLE
[BUG] Seekbar thumb can exceed its limits on iOS.

### ISSUE THREAD

**Issue by artsemionov** [jhomlala/betterplayer#211]
**Describe the bug**
When I drag seekbar thumb it goes over its limits on the left (even further the play button).

**To Reproduce**
Drag the thumb :)

**Better Player version**
- 0.0.44

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 14.2

**Comment by jhomlala** [comment]
Fixed in 0.0.45.
