### ISSUE TITLE
[FEATURE] skipsTimeInMilliseconds can be different for forward and backward skip.

### ISSUE THREAD

**Issue by subhash279** [jhomlala/betterplayer#213]
Hi, First of all, great work on the plugin!

**Is your feature request related to a problem? Please describe.**
skipsTimeInMilliseconds can be different for forward and backward skip as this is a valid use case in many apps.

**Describe the solution you'd like**
Have ForwardSkipsTimeInMilliseconds and backwardSkipsTimeInMilliseconds separately.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jhomlala** [comment]
Added in 0.0.45.
