### ISSUE TITLE
[BUG] BetterPlayerEventType.pause is not fired when paused through notification screen

### ISSUE THREAD

**Issue by subhash279** [jhomlala/betterplayer#214]
**Describe the bug**
Hi, again great work on the plugin and everything works as expected. 
When a user presses pause icon in the notification, I assume BetterPlayerEventType.pause should fire but it doesn't. Is this something that can be added. Everything else works great!!

**To Reproduce**
1. Pause a video from notification area.

**Expected behavior**
BetterPlayerEventType.pause should fire.

**Screenshots**
-

**Flutter doctor**
-

**Better Player version**
- Version: 0.0.44

**Smartphone (please complete the following information):**
 - Device: iOS

**Additional context**
-

**Comment by jhomlala** [comment]
Fixed in 0.0.45.

**Comment by dannyboyukliev** [comment]
This is still reproduced happens in 0.0.83.
