### ISSUE TITLE
[FEATURE] Null Safety

### ISSUE THREAD

**Issue by JohnGalt1717** [jhomlala/betterplayer#216]
Please add a null safety pre-release version that we can start using like most other packages are.

Thanks!

**Comment by jhomlala** [comment]
@JohnGalt1717 Please follow feature request template.
Null safety is important feature, but right now I don't have timeframes when it will be done. If you have spare time, feel free to create PR. I will appreciate it. Until null safety will be merged into Flutter stable channel, I don't see chance to implement it.

**Comment by maares** [comment]
@JohnGalt1717 I'm also migrating to null safety, although as you would expect not all packages will migrate, follow beta or master. 

As a posible work around that permits both's versions to play along but requires from you some additional annotations.

Just specify on the sdk some version before null safety which is 2.12.

```
environment:
  sdk: ">=2.11.0-0 <3.0.0"
```

You will need then to specify which version of dart on each file you created, say you created a widget Class of Text.

```
// @dart=2.12 if you already migrated this class to null safety
// @dart=2.11 if you did not migrated to null safety

class MyTextClass extends StatelessWidget { 

```


It's not the best approach but at least you still can use amazing libraries like this one!

**Comment by jhomlala** [comment]
Better Player will be updated to null safety when null safety will hit stable. Right now there's no chance to do that and main reason is amount of changes that being made. I don't have enough time to handle 2 versions (stable and beta) of Better Player.

Anyway Flutter team allows to create app with unsound null safety, so everything will work fine until BP will be upgraded to null safety.

**Comment by jhomlala** [comment]
Added in 0.0.62.
