### ISSUE TITLE
The pause method is called and wants to stop buffering

### ISSUE THREAD

**Issue by Chills719** [jhomlala/betterplayer#217]
When caching is enabled, the pause method is called and the video needs to be stopped to continue buffering，You can refer to the link below

https://blog.csdn.net/u012230055/article/details/77453277

**Comment by jhomlala** [comment]
@Chills719 Follow feature request template.
I don't understand chinese. Please share english version and describe correctly what you want to achieve.

**Comment by Chills719** [comment]
> @Chills719 Follow feature request template.
> I don't understand chinese. Please share english version and describe correctly what you want to achieve.


When the player uses the network data to load the video and calls the pause method, the video is still buffered. Now I want to pause the video and stop buffering at the same time. Is there any way to do that? I have read your source code, Android uses ExoPlayer, and I have found a solution, just like the link below. I hope you can modify this requirement to include Android and iOS

https://blog.csdn.net/u012230055/article/details/77453277

**Comment by Chills719** [comment]
> @Chills719 Follow feature request template.
> I don't understand chinese. Please share english version and describe correctly what you want to achieve.

![IMG_20210116_121138_068](https://user-images.githubusercontent.com/9108468/104852970-58ea8980-5930-11eb-9b0b-a383615758a2.jpg)
As indicated in this picture, I want to call pause method at the same time, also can stop the buffer, but the player does not provide a buffer method, is there a better solution?

**Comment by Chills719** [comment]
> @Chills719 Follow feature request template.
> I don't understand chinese. Please share english version and describe correctly what you want to achieve.

ànzài bǐjiào zhāojí
When the player loads the network data, it will buffer. When I call the pause method of the player, the player is still buffering. Now I want to realize that when I call the pause method, the network data can stop buffering at the same time. What do you have? Good advice? I am more anxious now

**Comment by jhomlala** [comment]
> > @Chills719 Follow feature request template.
> > I don't understand chinese. Please share english version and describe correctly what you want to achieve.
> 
> When the player loads the network data, it will buffer. When I call the pause method of the player, the player is still buffering. Now I want to realize that when I call the pause method, the network data can stop buffering at the same time. What do you have? Good advice? I am more anxious now，I have taken a screenshot above and described it

Better Player is open source software. I'm not obligated to fix all issues or add features requested. It's my good will to do it in my spare time, so you shouldn't create comments like this. This is bad behavior and I'm warning you. This won't be tolerated next time.

Anyway I've tried to research this topic and Android is working fine, but in iOS there's no way stop video buffering. iOS documentation is not showing how to do that, and I couldn't find any method that will do that. In BetterPlayer I'm following convention that if something can't be done in some platform then I won't implement this.

If you need only Android version, check brach feature/january_changes_7_with_load_control which can be used on Android. In BetterPlayerDataSource you can use parameter stopBufferinOnPause.

If anyone can find a way to handle iOS buffering, please let me know.
