### ISSUE TITLE
Seek value applies to all elements in the playlist

### ISSUE THREAD

**Issue by venimeux** [jhomlala/betterplayer#219]
Hi, 
Can we apply different seek value for each element?

**Comment by jhomlala** [comment]
@venimeux Use issue template.
I don't understand what do you mean "apply seek value for each element". Playlist widget displays one video at time, so I don't see any issue by using seek method on BetterPlayerController.

**Comment by venimeux** [comment]
If I give seek duration in playlist, every video start at same duration.  When initial video end, next video should start 00:00 position or where I left off before.

**Comment by jhomlala** [comment]
You can access betterPlayerController with global key and then seek each item individually. 
https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/playlist_page.dart#L86
