### ISSUE TITLE
Controller dispose not working [BUG]

### ISSUE THREAD

**Issue by venimeux** [jhomlala/betterplayer#220]
Controller does not dispose when navigate back.

- Version: ^0.0.44
Here is the logs:
E/flutter (31153): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'betterPlayerController' was called on null.
E/flutter (31153): Receiver: null
E/flutter (31153): Tried calling: betterPlayerController
E/flutter (31153): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (31153): #1      _VideoTestState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:base/plugins/course/video/video_page.dart:108:90)
E/flutter (31153): #2      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
E/flutter (31153): #3      _VideoTestState.build.<anonymous closure>.<anonymous closure> (package:base/plugins/course/video/video_page.dart:107:29)
E/flutter (31153): #4      BetterPlayerController._postEvent (package:better_player/src/core/better_player_controller.dart:418:22)
E/flutter (31153): #5      BetterPlayerController._onVideoPlayerChanged (package:better_player/src/core/better_player_controller.dart:462:9)
E/flutter (31153): <asynchronous suspension>
E/flutter (31153): #6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
E/flutter (31153): #7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292:5)
E/flutter (31153): #8      VideoPlayerController._updatePosition (package:better_player/src/video_player/video_player.dart:553:5)
E/flutter (31153): #9      VideoPlayerController._applyPlayPause.<anonymous closure> (package:better_player/src/video_player/video_player.dart:453:11)
E/flutter (31153): <asynchronous suspension>
E/flutter (31153): #10     VideoPlayerController._applyPlayPause.<anonymous closure> (package:better_player/src/video_player/video_player.dart)
E/flutter (31153): #11     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (31153): #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (31153): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (31153): #14     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1042:26)
E/flutter (31153): #15     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (31153): #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (31153): #17     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1026:26)
E/flutter (31153): #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (31153): #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (31153): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by jhomlala** [comment]
@venimeux Use issue template. There is something wrong with your code. You didn't provide enough details, so I can't help you. You should check if betterPlayerController in video_page.dart is properly initialized and used.

**Comment by jhomlala** [comment]
Closed. Feel free to respond with more details and I'll reopen it.
