### ISSUE TITLE
[BUG] [iOS] Big .mp4 files not playing correctly

### ISSUE THREAD

**Issue by alurei97** [jhomlala/betterplayer#224]
**Describe the bug**
When trying to reproduce big .mp4 videos on iOS doesn't load properly, smaller files work normally.
Everything works perfectly on Android.

The code is very similar to [placeholder example](https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/fade_placeholder_page.dart).

As I said, with a small video (280 MB) like this one works good:
```
BetterPlayerDataSource dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      Uri.encodeFull("https://www.documentarymania.org/video_flutter.php?title=Cirque du Soleil Journey of Man")
    );
```

But a bigger file such as this one (620 MB) doesn't:
```
BetterPlayerDataSource dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      Uri.encodeFull("https://www.documentarymania.org/video_flutter.php?title=Gravity")
    );
```

And it produces this error:
```
2021-01-12 20:48:20.477422+0100 3D Online Films[1875:206969] Update playing state

2021-01-12 20:48:22.863760+0100 3D Online Films[1875:206969] Update playing state

2021-01-12 20:48:22.878299+0100 3D Online Films[1875:206969] OnReadyToPlay

2021-01-12 20:48:23.357413+0100 3D Online Films[1875:208721] Task <A01AE462-0E9D-4D7C-9494-63D580A73447>.<10> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://www.documentarymania.org/video_flutter.php?title=Gravity, NSErrorFailingURLKey=https://www.documentarymania.org/video_flutter.php?title=Gravity, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <A01AE462-0E9D-4D7C-9494-63D580A73447>.<10>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A01AE462-0E9D-4D7C-9494-63D580A73447>.<10>, NSLocalizedDescription=cancelled} [-999]

2021-01-12 20:48:23.363356+0100 3D Online Films[1875:208552] Task <A01AE462-0E9D-4D7C-9494-63D580A73447>.<10> finished with error - code: -999

2021-01-12 20:48:23.784518+0100 3D Online Films[1875:208558] Task <0E2D183D-E934-481D-AC2C-6110F6BD2CA1>.<11> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://www.documentarymania.org/video_flutter.php?title=Gravity, NSErrorFailingURLKey=https://www.documentarymania.org/video_flutter.php?title=Gravity, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0E2D183D-E934-481D-AC2C-6110F6BD2CA1>.<11>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0E2D183D-E934-481D-AC2C-6110F6BD2CA1>.<11>, NSLocalizedDescription=cancelled} [-999]

2021-01-12 20:48:23.793225+0100 3D Online Films[1875:208558] Task <0E2D183D-E934-481D-AC2C-6110F6BD2CA1>.<11> finished with error - code: -999


and it repeats again and again...
```

I also tried using and commenting cache settings but it still doesn't work.

**Better Player version**
- Version: 0.0.44

**Smartphone:**
 - Device: iPhone 6
 - OS: iOS 12.4.9

**Comment by jhomlala** [comment]
Hi @alurei97,
I did some tests on my side and here are my thoughts:
On iOS 14.x everything looks fine and there's no 999 error.
On iOS 12.x I can reproduce this error on my side. I did some research and there are many cases that could trigger this error:
* Slow connection on both device and server
* Invalid HTTPS certificate on server
* Some issues with providing video from your backend.

Can you do some small test: try some large video (something more than 500 MB) on your device but not from your endpoint (https://www.documentarymania.org/video_flutter.php).

**Comment by alurei97** [comment]
I'm new to iOS and I couldn't manage to reproduce Gravity.mp4 from my device (I don't know how to access iPhone's movie folders from the app), but I have tried another .mp4 +500MB files that I found from random servers in Google search (I obviously don't have access to their config):
`http://144.217.180.154/SERVIDOR_2/10_Things_We_Should_Do_Before_We_Break_Up_2020_DVDCustom_HD_Latino.mp4`
`https://kfilmes.club/A.Era.do.Gelo.2.2006.720p.BRRip.x264-VTM_SL.mp4`
and I still get the same result and debug logs.

One thing I forget to add in the original message: any big video (Gravity or the ones I tried) goes from 0:00 to 0:02 while showing the loading spinner and those error logs, then goes back to to 0:00, it goes to 0:02 back to 0:00... in a infinite loop; I can click on the middle of the video, e.g. 45:00 and it starts loading properly, even I can go back to 0:00 after that and it just works fine. But it's not a proper behaviour for the final user.

Can it be a Flutter project bad configuration? I have read about `NSAppTransportSecurity` in `info.plist`and I have tried different configurations without any difference.

**Comment by alurei97** [comment]
> Is there any update?

No updates from me. 
Do you have the same problem? Maybe if you give additional info it could help the developer.

**Comment by jhomlala** [comment]
Please check with last release (0.0.48). This release should fix loading large videos.

**Comment by alurei97** [comment]
Still not working in my iPhone.

**Comment by jhomlala** [comment]
Can you check this issue with iOS 14.x?
Can you record video with your issue on your iPhone? When I was testing video on iOS 12.x the first load of video was pretty long, but once I've started video, it worked fine. Seems like AVPlayer is not good at playing large mp4, since it's downloading a lot of data on the beginning.

**Comment by alurei97** [comment]
- Looks like iOS 14 isn't available for iPhone 6, so I can't check it.
- [Video1](https://photos.app.goo.gl/qmTsaTZ3WfGhmj9J9) [Video2](http://photos.app.goo.gl/kuqHJAdpQdo7itX96) (Sorry for the shitty quality but it was the fastest way to record it) You can see how it doesn't load (even if I let it load longer) and it loads when I click in the middle of the video.
- 2 days ago the server was upgraded to 500 Mbps bandwith but it's still the same (Android and browser loads perfectly).

**Comment by jhomlala** [comment]
@alurei97 In latest version 0.0.50 I've introduced another fix for slow loading issue. Please check it and let me know.

**Comment by alurei97** [comment]
I just tried 0.0.50 and it's not fixed, same weird behavior...

**Comment by jhomlala** [comment]
Basically, I've tried all possible solutions. Seems like AVPlayer can't handle big videos properly. iOS ecosystem's lack of documentation is really strange for me. Right now I can't provide anything more in this issue.

**Comment by smartking260** [comment]
@alurei97 Hi,i think  if your video is in next page use pushReplecement ,your player will be work so good.

**Comment by alurei97** [comment]
> @alurei97 Hi,i think if your video is in next page use pushReplecement ,your player will be work so good.

What do you mean? Can you elaborate more? I just updated plugin to 0.0.57 and replaced all my `push` with `pushReplacement` and it's still not working...

**Comment by jhomlala** [comment]
@smartking260 I don't think so it will change anything.
