### ISSUE TITLE
[BUG] HTTP Headers are not sent through

### ISSUE THREAD

**Issue by SimantovYousoufov** [jhomlala/betterplayer#227]
**Describe the bug**
Setting up a BetterPlayerDataSource with type `BetterPlayerDataSourceType.network` does not send the headers passed in to its `headers` argument.

**To Reproduce**

Sample code:
```
class VideoPlayer extends State<ExerciseView> {
  final MyModel _myModel;
  BetterPlayerController _betterPlayerController;
  BetterPlayerConfiguration _config = BetterPlayerConfiguration(autoPlay: true, looping: true);


  VideoPlayer(this._myModel);

  @override
  void initState() {
    super.initState();

    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        _myModel.assets.first.processedUrl,
        headers: {
          'Cookie': "Some header value",
        }
    );

    _betterPlayerController = BetterPlayerController(_config, betterPlayerDataSource: betterPlayerDataSource);
  }

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
      aspectRatio: 16 / 9,
      child: BetterPlayer(
        controller: _betterPlayerController,
      ),
    );
  }
}
```

**Expected behavior**
Expected the player to send through the `Cookie` header (or any arbitrary header) but it does not send any headers, even arbitrary ones. Verified via a requestbin:

```
{
  "method": "GET",
  "path": "/",
  "query": { },
  "headers": {
    "x-forwarded-for": "....",
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": ".....",
    "x-amzn-trace-id": "Root=1-5fff6bc9-748f72e97616c1f032999b4f",
    "accept": "*/*",
    "x-playback-session-id": "89D52953-3E11-4C5F-9A15-26A3BFC726C8",
    "range": "bytes=0-1",
    "user-agent": "AppleCoreMedia/1.0.0.18C66 (iPhone; U; CPU OS 14_3 like Mac OS X; en_us)",
    "accept-language": "en-us",
    "accept-encoding": "identity"
  }
}
```

**Better Player version**
- Version: 0.0.45

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Any device but testing on iPhone 12 Pro, Iphone 12 Pro Simulator, Pixel 3 Simulator
 - OS: iOS 14.3

**Additional context**
Sending [signed cookies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html) or auth headers is a pretty common way to protect content. Would love to help get this resolved as quickly as we can.

**Comment by jhomlala** [comment]
Should be fixed in 0.0.46. If not please answer in this topic and I'll reopen it.

**Comment by SimantovYousoufov** [comment]
Wow, thanks for the quick response @jhomlala! I tested 0.0.46 and it works like a charm with the exception of one issue:

0. Be on iOS
1. Use an HLS or DASH Stream (works fine with a single request stream such as progressive download MP4)
2. Have cache configuration `useCache: true`
3. Receive `flutter: Caught error: PlatformException(VideoError, Failed to load video: The network connection was lost., null, null)`

Single file streams working with cache enabled makes me think that this is another but related issue where KTVHTTPCache possibly doesn't handle the subsequent requests AVPlayer player makes for the stream segments. I dug around a bit through their docs and don't see an immediately obvious fix. Any ideas what we could do here? I'd be glad to help here if I can.

**Comment by bounty1342** [comment]
@jhomlala First, thank you for closing the issue on #311 so quickly. 

Just so you know, activating the cache on the same video, trigger an infinite load and the error :
```
flutter: ----------------------------------------------------
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(VideoError, Failed to load video: The network connection was lost., null, null)
flutter:
flutter: ----------------------------------------------------
```

For the time being, I have removed the cache, but as the video will loop, will certainly be great to reactivate it at one point.
