### ISSUE TITLE
[BUG] Exception at setDataSource on iOS

### ISSUE THREAD

**Issue by artsemionov** [jhomlala/betterplayer#228]
**Describe the bug**
Was working in 0.0.44.

Exception when trying to call setDataSource:
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <FLTBetterPlayer 0x283d777b0> for the key path "status" from <AVPlayerItem 0x280d6adf0> because it is not registered as an observer.'
terminating with uncaught exception of type NSException

**To Reproduce**
_player.controller.setupDataSource(
            BetterPlayerDataSource(
              BetterPlayerDataSourceType.network,
              "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            ),

**Better Player version**
- 0.045

**Comment by jhomlala** [comment]
Should be fixed in 0.0.46. If not please answer in this topic and I'll reopen it.
