### ISSUE TITLE
Customized Controls

### ISSUE THREAD

**Issue by ali9653** [jhomlala/betterplayer#229]
Is it possible to add support for customized controls. Something like this 
![Screenshot_20210115-013900](https://user-images.githubusercontent.com/52851947/104643702-c9946a80-56d2-11eb-9812-225da2656ad6.jpg)

This was achieved using Flick Video player but it does not support auto rotation.

**Comment by jhomlala** [comment]
For questions, use discussion. Also please check examples before creating new ticket. 

Check this example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/change_player_theme_page.dart
