### ISSUE TITLE
Controls not getting handled

### ISSUE THREAD

**Issue by imJithin777** [jhomlala/betterplayer#231]
How to handle the visibility of controls of the player. 
When a video is played, controls are shown and a second after it disappears and when we touch it the controls appear for a second and disapppears at the same time. Is there any solution to make the controls visible for all the time or a solution for increasing the time of controls appearance after player is touched.

**Comment by jhomlala** [comment]
Right now it's only doable with custom controls: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/change_player_theme_page.dart

**Comment by jhomlala** [comment]
Fixed in 0.0.47 (check this new method https://github.com/jhomlala/betterplayer#set-controls-always-visible).
