### ISSUE TITLE
[FEATURE] keep audio playing in the background while phone is locked [ like Spotify ]

### ISSUE THREAD

**Issue by maximevo** [jhomlala/betterplayer#235]
**Is your feature request related to a problem? Please describe.**
The users of our app would like to be keep listening to the video, even when their phone is locked.

**Describe the solution you'd like**
Just like Spotify, when the phone is locked, the audio of the video keeps playing.
From the locked screen, the user can press play/pause, go to next video, go to previous video.

**Additional context**
Spotify screenshot attached
![IMG_0013](https://user-images.githubusercontent.com/19479683/104897054-3714f500-5978-11eb-8191-cb61b04720ce.png)

**Comment by maximevo** [comment]
Sorry, hadn't realized that remote controls notification (and picture in picture) did exactly that ! Amazing !

**Comment by m1n093** [comment]
> Sorry, hadn't realized that remote controls notification (and picture in picture) did exactly that ! Amazing !

Its not working on iOS, the controls notification is showing but disappear when app in background or locked. On android it work perfect.
