### ISSUE TITLE
[BUG] continuous notification sounds when notification bar is added

### ISSUE THREAD

**Issue by hsnbsst** [jhomlala/betterplayer#236]
**Describe the bug**
continuous notification sounds when notification bar is added, I wonder if the notification sound is not turned off while watching the broadcast

**Flutter doctor**
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale tr-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.52.1)
[✓] Connected device (4 available)

• No issues found!

**Better Player version**
- Version: 0.0.46

**Smartphone (please complete the following information):**
 - android 30 emülatör

**Comment by jhomlala** [comment]
Please provide more details and example code.

**Comment by marcusforsberg** [comment]
I also get this issue using the notification player from the /example folder. My phone is set to vibrate for notifications, and any time I play the video or interact with it (play, pause or jump), the notification is updated and a vibration is triggered.

I believe you can read more about this here: https://github.com/google/ExoPlayer/issues/5890
The NotificationChannel needs to be set to `NotificationManager.IMPORTANCE_LOW`, I beleive 😊

**Comment by hsnbsst** [comment]
The problem is :. I activate notifications => I open Video => notification appears in a row = after you are constantly watching video. Notification sound continues to play 2 seconds period interval

I know a little English
