### ISSUE TITLE
[BUG] autoDispose = true interferes with explicit disposal

### ISSUE THREAD

**Issue by ajzome** [jhomlala/betterplayer#239]
**Describe the bug**
There is an issue with how the BetterPlayerConfiguration.autoDispose works. If you set this flag to false under the expectation that you can explicitly manage the BetterPlayerController, then it is no longer possible to dispose the BetterPlayerController. This is because BetterPlayerController.dispose() early exits if the autoDispose is false.

**To Reproduce**
1. var config = BetterPlayerConfiguration(autoDispose: false)
2. var controller = BetterPlayerController(configuration);
3. controller.dispose()

**Expected behavior**
I expect BetterPlayerController.dispose() to clean up the controller when explicitly called but not if called via BetterPlayer.dispose()

**Screenshots**
-

**Flutter doctor**
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.746], locale en-AU)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

NOTE: plugins are installed, bug with flutter doctor's detection with Android Studio setup.

**Better Player version**
- Version: 0.0.46

**Smartphone (please complete the following information):**
 - Device: Nokia 4.2
 - OS: Android 10

**Additional context**
A workaround exists by setting autoDispose to true (or default) and instead providing an empty BetterPlayerPlaylistConfiguration to the controller but this workaround has limited value (and is obviously not intuitive)

**Comment by jhomlala** [comment]
In 0.0.48 release I've added forceDispose parameter to dispose method in BetterPlayerController.
