### ISSUE TITLE
error when load video from youtube or stream

### ISSUE THREAD

**Issue by duckieu1989** [jhomlala/betterplayer#24]
W/_player_exampl(15920): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 29416 free bytes and 28KB until OOM, target footprint 16777216, growth limit 16777216" (VmSize 4154940 kB)
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 23(32KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 282us total 7.781ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 25(32KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 629us total 6.495ms
I/_player_exampl(15920): WaitForGcToComplete blocked Background on HeapTrim for 8.078ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 8.165ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 6.581ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 6.245ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 26(32KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 359us total 5.477ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 8.800ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 14.202ms
I/_player_exampl(15920): Starting a blocking GC Alloc
E/LoadTask(15920): OutOfMemory error loading stream
E/LoadTask(15920): java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 29416 free bytes and 28KB until OOM, target footprint 16777216, growth limit 16777216
E/LoadTask(15920): 	at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
E/LoadTask(15920): 	at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:633)
E/LoadTask(15920): 	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
E/LoadTask(15920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:533)
E/LoadTask(15920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:187)
E/LoadTask(15920): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
E/LoadTask(15920): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/LoadTask(15920): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/LoadTask(15920): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/LoadTask(15920): 	at java.lang.Thread.run(Thread.java:919)
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 9.634ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 2213(84KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 307us total 48.926ms
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 41.803ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 1149(58KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 4.468ms total 13.971ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 14.374ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 1096(47KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 3.945ms total 11.773ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 72.879ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 1489(68KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 291us total 19.786ms
I/_player_exampl(15920): WaitForGcToComplete blocked Background on HeapTrim for 10.466ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 9.429ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Alloc young concurrent copying GC freed 1801(62KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 273us total 39.859ms
I/_player_exampl(15920): WaitForGcToComplete blocked Background on HeapTrim for 19.028ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 11.429ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Alloc young concurrent copying GC freed 923(47KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 813us total 11.146ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 31.949ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Alloc young concurrent copying GC freed 114(9808B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 636us total 9.270ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 31(1760B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 626us total 8.605ms
I/_player_exampl(15920): Forcing collection of SoftReferences for 64KB allocation
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 1121(44KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 1.059ms total 11.437ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 11(272B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 270us total 8.084ms
I/_player_exampl(15920): Forcing collection of SoftReferences for 64KB allocation
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 10(304B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 769us total 5.125ms
W/_player_exampl(15920): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 29400 free bytes and 28KB until OOM, target footprint 16777216, growth limit 16777216" (VmSize 4162012 kB)
I/_player_exampl(15920): WaitForGcToComplete blocked Background on HeapTrim for 37.413ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 4(80B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 2.357ms total 17.695ms
I/_player_exampl(15920): WaitForGcToComplete blocked Background on HeapTrim for 17.543ms
I/_player_exampl(15920): Forcing collection of SoftReferences for 64KB allocation
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 8.524ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 5(136B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 286us total 6.576ms
W/_player_exampl(15920): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 29328 free bytes and 28KB until OOM, target footprint 16777216, growth limit 16777216" (VmSize 4162012 kB)
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Alloc young concurrent copying GC freed 22(24KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 283us total 6.364ms
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 21.195ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 8.882ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 9.189ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 14.534ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): WaitForGcToComplete blocked Alloc on HeapTrim for 5.617ms
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Waiting for a blocking GC Alloc
I/_player_exampl(15920): Starting a blocking GC Alloc
I/chatty  (15920): uid=10134(com.jhomlala.better_player_example) Loader:Extracto identical 1 line
I/_player_exampl(15920): Starting a blocking GC Alloc
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB
I/_player_exampl(15920): Alloc concurrent copying GC freed 33(32KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 281us total 12.459ms
I/_player_exampl(15920): WaitForGcToComplete blocked Background on HeapTrim for 9.573ms
E/LoadTask(15920): OutOfMemory error loading stream
E/LoadTask(15920): java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 29328 free bytes and 28KB until OOM, target footprint 16777216, growth limit 16777216
E/LoadTask(15920): 	at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
E/LoadTask(15920): 	at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:633)
E/LoadTask(15920): 	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
E/LoadTask(15920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:533)
E/LoadTask(15920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:187)
E/LoadTask(15920): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
E/LoadTask(15920): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/LoadTask(15920): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/LoadTask(15920): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/LoadTask(15920): 	at java.lang.Thread.run(Thread.java:919)
I/_player_exampl(15920): Clamp target GC heap from 21MB to 16MB

**Comment by jhomlala** [comment]
Seems like you're out of memory. Can you provide url video(s) that you've tested?

**Comment by duckieu1989** [comment]
okie give link example:
https://r3---sn-5ualdnle.googlevideo.com/videoplayback?expire=1590399890&ei=Mj_LXt-BIsvfj-8PmLe8sAo&ip=198.37.116.29&id=o-ADkseg4YCnx5Wi_uihCVgZXShLreWiC3oH5ruAc8ybVV&itag=18&source=youtube&requiressl=yes&mh=L7&mm=31%2C26&mn=sn-5ualdnle%2Csn-p5qs7nek&ms=au%2Conr&mv=u&mvi=2&pl=24&vprv=1&mime=video%2Fmp4&gir=yes&clen=346035406&ratebypass=yes&dur=4985.068&lmt=1590355017197554&mt=1590377808&fvip=3&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgB-Q_k52lSM5C05zCYW7b6-GRZkYfxzU0u_OoWSqro7gCIG-VLaDlYsFDHVtEm60G_MCbp7G3br3pKqlSUwcI9gdh&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRAIgDPRLqkUzdyGHuehIRhGC4NhZEf44XAxlSSfY8UcitBkCIG6hu9mKmE4KyI2iixzdfsgbq491RUJ4sOSMpY3tSvsp

**Comment by jhomlala** [comment]
Can't access this video. Can you provide link again?

**Comment by jhomlala** [comment]
No response from author, closing issue. Please reopen if you encounter this issue again.
