### ISSUE TITLE
[BUG] Can not play on iOS 14.2

### ISSUE THREAD

**Issue by anhlevfx** [jhomlala/betterplayer#243]
**Describe the bug**
Player only show controller GUI and black screen

**To Reproduce**
1. Init player inside InitState()

`BetterPlayerController _betterPlayerController;`
`@override`
`initState() {`
`BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(BetterPlayerDataSourceType.network, <url .mp4 or .m3u8 video>');`
` _betterPlayerController = BetterPlayerController(BetterPlayerConfiguration(), betterPlayerDataSource: betterPlayerDataSource);`
      `}`

2. Show in build

` BetterPlayer(`
                  `controller: _betterPlayerController,`
`                ),`

3. Play well on Android, but only black screen on iPhone and iPad.

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

**Better Player version**
- Version: 0.0.47

**Smartphone (please complete the following information):**
 - Device: iPhone 11, iPad Pro 12.9
 - OS: iOS 14.2

**Additional context**
Use video player combine chewie will have same result.

**Comment by jhomlala** [comment]
Are you trying to play video in simulator? Right now simulators don't support playing videos (you should see black screen).

**Comment by anhlevfx** [comment]
I tested on real devices. I think problem is about our server streaming or source video, this issues should be closed. 
I found an error PlatformException(VideoError, Failed to load video: Operation Stopped, null, null). But when I use another link on internet, it works.

**Comment by vanfresh** [comment]
I experienced the same problem.  My videos are behind Cloudflare, and the same video works on Android, but not on iOS.  It throws an error.  I think it was saying the connection was lost.   It also works with other videos on the internet, just not from my server :(.  Is it possible to implement a retry operation for iOS AVPlayer?

**Comment by jhomlala** [comment]
@vanfresh Please create new issue with reproducible example. Thanks.
Issue closed.

**Comment by anhlevfx** [comment]
@vanfresh In my case, I found the exception throw because "AVErrorServerIncorrectlyConfigured". In Apple's document "This might mean that the server does not support byte range requests". So, just config your server stream and iOS can play video normally.

**Comment by vanfresh** [comment]
@anhlevfx How did you find the exception?  I just got `PlatformException(VideoError, Failed to load video: Cannot Open, null, null)`.  I can't see the underlying error on iOS.

**Comment by vanfresh** [comment]
I figured it out.  For anyone that encounter this error, you need to provide these headers from the server: 

1. Content-Type
2. Accept-Ranges
3. Content-Range (must include total file length)
