### ISSUE TITLE
[FEATURE] Progress Indicator on load

### ISSUE THREAD

**Issue by helloalbin** [jhomlala/betterplayer#246]
Is it possible to add a progress indicator to indicate that the video is loading. Currently, in my application, it takes couple of seconds to load the video and the widget is empty until its loaded. I feel a progress bar will be a great addition.

**Comment by jhomlala** [comment]
Please follow issue template. You're probably can't see loading indicator because it's black as default. Simply do this:
```dart
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      controlsConfiguration:
          BetterPlayerControlsConfiguration(loadingColor: Colors.green),
      fit: BoxFit.contain,
    );
```

**Comment by helloalbin** [comment]
Thank you.
