### ISSUE TITLE
[BUG] Player in fullscreen is stuck (black screen) if underlying widget is removed

### ISSUE THREAD

**Issue by billy1380** [jhomlala/betterplayer#248]
**Describe the bug**
If the underlying widget tree is rebuilt and the player is removed while in full screen mode, the video goes black, the user can no longer dismiss the video or exit fullscreen mode.

**To Reproduce**
1/ Enter full screen mode.
2/ Set a timer to rebuild the widget tree with a different video
3/ Error occurs

**Better Player version**
- Version: 0.0.46

**Comment by jhomlala** [comment]
@billy1380 Please provide example code.

**Comment by jhomlala** [comment]
Should be fixed in Better Player 0.0.49.

**Comment by billy1380** [comment]
@jhomlala apologies for not being able to respond with a code sample, thanks for the update.
