### ISSUE TITLE
[BUG] BetterPlayerEventType.finished not broadcasted

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#249]
**Describe the bug**
**BetterPlayerEventType.finished** is not being broadcasted if the milliseconds since last broadcast **< 500**

`if (now - _lastPositionSelection > 500) {`

**To Reproduce**

`_playerController.addEventsListener((event) async {
        if (event.betterPlayerEventType == BetterPlayerEventType.finished) { } 
}`

**Expected behavior**
BetterPlayerEventType.finished should be broadcasted at the end of the video regardless of milliseconds

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Better Player version**
^0.0.48

**Comment by Jazzykhan** [comment]
same here

**Comment by Jazzykhan** [comment]
Sometimes it works and sometimes it doesnt. same code same device.

**Comment by jhomlala** [comment]
Fixed in 0.0.50.

**Comment by roshan1960701** [comment]
I have been facing the same isssue

**Comment by roshan1960701** [comment]
Finished is not getting called How can I checked whether the playlist is finished or not?
