### ISSUE TITLE
how to catch event?

### ISSUE THREAD

**Issue by mumulala-id** [jhomlala/betterplayer#25]
```
 eventListener: (event) {
                          if (event.betterPlayerEventType ==
                              'BetterPlayerEventType.OPEN_FULLSCREEN') {}
                          if (event.betterPlayerEventType ==
                              BetterPlayerEventType.OPEN_FULLSCREEN){}
                           
                        },
```
both of them give some errors

 info: Equality operator `==` invocation with references of unrelated types. 
error: Undefined name 'BetterPlayerEventType'.

**Comment by jhomlala** [comment]
You're comparing enum with string. This is how you should do it:

    _betterPlayerController.addEventsListener((event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.OPEN_FULLSCREEN){
        print("Open fullscreen triggered!");
      }
    });

**Comment by mumulala-id** [comment]
yes, but i still got error: Undefined name 'BetterPlayerEventType'.. I can't see BetterPlayerEventType enums in the documentations.

**Comment by jhomlala** [comment]
Check 0.0.9 release. You should be able to import BetterPlayerEventType
