### ISSUE TITLE
[BUG] Doesn't play url media without extension? 

### ISSUE THREAD

**Issue by lavara123** [jhomlala/betterplayer#250]
**Describe the bug**
URL without video file extension can't play in better . URL = [https://d6b09034.tekurarere.tk/mq/NNUVmAXzjPHmdFAxvlmOAXjNYAmNAgjVmZJiRmX_lp](https://d6b09034.tekurarere.tk/mq/NNUVmAXzjPHmdFAxvlmOAXjNYAmNAgjVmZJiRmX_lp) 

URL return m3u8 file but "better player" don't play it

**To Reproduce**
```
@override
void initState(){
    super.initState();
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "https://d6b09034.tekurarere.tk/mq/NNUVmAXzjPHmdFAxvlmOAXjNYAmNAgjVmZJiRmX_lp",
        headers: {"User-Agent:":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0", "Content-Type:":"application/vnd.apple.mpegurl"}
        );
    _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(),
        betterPlayerDataSource: betterPlayerDataSource);
  }
```

**Expected behavior**
play a video from a url without file extension

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.168, on Linux, locale tr_TR.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

**Better Player version**
^0.0.48

**Screnshots**
can be played url (vlc, js video player bla bla )
![Ekran görüntüsü_2021-01-27_14-16-25](https://user-images.githubusercontent.com/12005386/105983902-4d663380-6091-11eb-9046-bbb23d0a2e6d.png)

**Additional context**
fixed for video_player ios:
[https://github.com/flutter/plugins/pull/1794](https://github.com/flutter/plugins/pull/1794)

ExoPlayer MimeType document
[https://exoplayer.dev/troubleshooting.html#](https://exoplayer.dev/troubleshooting.html#why-do-some-streams-fail-with-unrecognizedinputformatexception)

**Comment by lavara123** [comment]
Url works well in other test locations (vlc, video play javascript demo)

**Comment by jhomlala** [comment]
Thanks for reporting. I'll try fix it next release.

**Comment by jhomlala** [comment]
Fixed in 0.0.49. Please use videoFormat in BetterPlayerDataSource.

**Comment by lavara123** [comment]
> 0.0.49'da düzeltildi. Lütfen BetterPlayerDataSource'ta videoFormat kullanın.

thank you so much, it works for me :+1: :)

```BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "https://d6b09034.tekurarere.tk/mi/NNUVmAXzjPHmdFAxvlmOAXjNYAmNAgjVmZJiRmX_lp",
        videoFormat: BetterPlayerVideoFormat.hls,
        headers: {
          "User-Agent:":
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0",
          "Content-Type:": "application/vnd.apple.mpegurl"
        });
```

**Comment by brightchip** [comment]
How use BetterPlayerVideoFormat.mp4 ?? When the mp4 has no file extension

**Comment by lavara123** [comment]
> How use BetterPlayerVideoFormat.mp4 ?? When the mp4 has no file extension

No need for extension or definition for mp4, it works directly
