### ISSUE TITLE
[FEATURE] Retry network datasource

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#252]
**Is your feature request related to a problem? Please describe.**
Sometimes requesting videos through the network will fail.  

**Describe the solution you'd like**
It would be great if there was a way to retry fetching the video. 

**Describe alternatives you've considered**
Right now, it seems using FlutterCacheManager to download the file locally first is more stable than using the network datasource.  The major downside is that the whole file needs to be downloaded first.

**Comment by jhomlala** [comment]
Fixed in 0.0.49. Error widget will have now retry button. You can control this button with BetterPlayerControlsConfiguration.
