### ISSUE TITLE
[BUG] Once I get 'Video Can't Be Played' error, the video doesn't play anymore, even when internet is back

### ISSUE THREAD

**Issue by maximevo** [jhomlala/betterplayer#256]
**Describe the bug**
When I try to navigate or watch through an unloaded portion of the video, I get a screen that shows an ! icon with a message "Video can't be played" on Android. 
Then, if I restore internet, the video player is stuck on the error screen. The video doesn't start playing again, even when internet is back. 

**To Reproduce**
1. Setup BetterPlayer to use a .network datasource
2. Upon loading a part of the video, turn off your wi-fi
3. Either watch until the part where it isn't stream or navigate/seek to it with the progress indicator circle
4. You will reach a black screen with a message "Video can't be played" 
5. Then, even when internet is back, the video player stays stuck on the error screen "Video can't be played", rather than streaming the video. 

**Expected behavior**
I would expect an error widget to appear, while internet is down, but once internet is back up, then I would expect the video to automatically keep playing.

![image](https://user-images.githubusercontent.com/19479683/106293920-d6769980-624e-11eb-8de4-1cf5f49523a4.png)

**Why is this a problem ?**
Sometimes, our users lose internet for a few seconds (on the subway for instance). They get the error screen "Video can't be played". But then, even when their internet is restored, they keep seeing the error screen, rather than seeing the video ...

**Comment by jhomlala** [comment]
Fixed in 0.0.49. Error widget will have now retry button. You can control this button with BetterPlayerControlsConfiguration.

**Comment by maximevo** [comment]
Amazing, thank you ! We're having a look at the modification :) will let you know how it goes !

**Comment by maximevo** [comment]
Hey @jhomlala, it looks like you have made the modification on iOS (which is great !)

Re-opening because my request was for Android :)

**Comment by jhomlala** [comment]
Android version works same - there's retry button when error is displayed.
