### ISSUE TITLE
[FEATURE] Change Language Audio from m3u8 ?

### ISSUE THREAD

**Issue by lavara123** [jhomlala/betterplayer#258]
**Is your feature request related to a problem? Please describe.**
better_player needs a possibility to change audio tracks in video, like elector in Exoplayer do.

**maybe the solution needed:**
this link can help: [https://github.com/flutter/flutter/issues/59437](https://github.com/flutter/flutter/issues/59437)

**Describe alternatives you've considered**
![Screenshot_20210130-165553450 (1)](https://s12.directupload.net/images/210130/skta3vqm.jpg)

**test m3u8 file**
[http://cdn.theoplayer.com/video/elephants-dream/playlist.m3u8](http://cdn.theoplayer.com/video/elephants-dream/playlist.m3u8)

**Comment by jhomlala** [comment]
How about iOS AvPlayer. Is this doable? Can you provide informations about AvPlayer?

**Comment by lavara123** [comment]
> How about iOS AvPlayer. Is this doable? Can you provide informations about AvPlayer?

I have no information about the AvPlayer and IOS

Maybe:

**Comment by jhomlala** [comment]
Main goal is to support both Android & iOS with same functionality. If there's no option in AvPlayer to do it, then it won't be implemented. Please try to do some research and let me know here if you find anything helpful.

**Comment by balvinderz** [comment]
this can be implemented in ios too  @jhomlala . https://github.com/flutter/flutter/issues/59437 my fork works on android,ios and web.

**Comment by lavara123** [comment]
> Main goal is to support both Android & iOS with same functionality. If there's no option in AvPlayer to do it, then it won't be implemented. Please try to do some research and let me know here if you find anything helpful.

Hey avplayer auto

**Comment by jhomlala** [comment]
Will look into this in spare time.

**Comment by jhomlala** [comment]
Added support for HLS audio tracks in 0.0.50.

**Comment by lavara123** [comment]
> Added support for HLS audio tracks in 0.0.50.

thanks so much, but there is a problem: [https://github.com/jhomlala/betterplayer/issues/275](https://github.com/jhomlala/betterplayer/issues/275)
