### ISSUE TITLE
[BUG] Before the video has initialised a block box appears in its place. 

### ISSUE THREAD

**Issue by ajzome** [jhomlala/betterplayer#262]
**Describe the bug**
We have noticed that during the initial setup of the BetterPlayer a black box will appear in its place. This seems to only be an issue when using a BetterPlayerDataSourceType.network datasource.

I traced the issue to:
lib/src/core/better_player_with_controls.dart:99 
```
return Center(
      child: Container(
        width: double.infinity,
        color: Colors.black, // <-- this line
        child: AspectRatio(
          aspectRatio: aspectRatio,
          child: _buildPlayerWithControls(betterPlayerController, context),
        ),
      ),
```

The container is being set to Colors.black however in our case Colors.transparent would be preferred.

**To Reproduce**
1. Create a BetterPlayerDataSource using a network resource (providing headers?)
2. Create a BetterPlayerController using the datasource
3. Create a BetterPlayer ideally in a nonblack container (for visibility)
4. Notice black box before first frame appears in player.

**Expected behavior**
Either no black box or a configurable box colour.

**Screenshots**
![device-2021-02-03-140500](https://user-images.githubusercontent.com/56942564/106692700-13fd6d00-6629-11eb-810f-6a5f02aef08b.png)

**Flutter doctor**
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.746], locale en-AU)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

* Android Studio is a bug. Works fine and actually 4.1.2.

**Better Player version**
- Version: 0.0.49

**Smartphone (please complete the following information):**
 - Device: Nokia 4.2  (also noticed on iOS devices)
 - OS: android 

**Additional context**
I doubt it is relevant, however we do use headers with our datasource and turn on caching.

**Comment by jhomlala** [comment]
Basically it's not a bug, but in 0.0.50 added support for changing color of background.
