### ISSUE TITLE
Video Streaming with bytes array

### ISSUE THREAD

**Issue by sriramsk1999** [jhomlala/betterplayer#264]
Hello, thanks for the work on this project.

I'm building a game streaming application and I need to display video on the frontend with Flutter. The data is received as a sequence of images (byte arrays) and I would like to display this as a video.

I had a look at #89 and `BetterPlayerDataSource.memory` but I could not find any examples and so I'm not sure how to proceed. Is it possible to display video frame by frame as it is received, or can it only be used by loading an entire file into memory and then providing it as input? Thanks in advance for your help.

**Comment by jhomlala** [comment]
From my perspective it won't work unless you'll stream of data will be formatted in one of formats accepted in AvPlayer or ExoPlayer (for example HLS).

**Comment by sriramsk1999** [comment]
Thanks for the quick response. So from what I understand, I can dynamically create a video from the incoming images, and I can pass that file as it is being created to `BetterPlayerDataSource`, does that sound right? I'm new to video streaming so any guidance would be highly appreciated

**Comment by jhomlala** [comment]
Yes exactly.  But if you want to create video in user device, it may be hard. Rendering video with ffmpeg is memory consuming and it's not good idea to do that on mobile device. In my opinion it's better to render videos server side or just show images without video player.
