### ISSUE TITLE
[FEATURE] Do you plan to add support for MacOS?

### ISSUE THREAD

**Issue by subhash279** [jhomlala/betterplayer#266]
Hi,
Great work on the plugin!

**Is your feature request related to a problem? Please describe.**
Do you plan to add support for flutter apps built for MacOS. I think it uses the same AVPlayer.

**Describe the solution you'd like**
-Same as iOS

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jhomlala** [comment]
Won't do. Check answer here: https://github.com/jhomlala/betterplayer/issues/261
