### ISSUE TITLE
[BUG] Open and close repeatedly

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#267]
**Describe the bug**
When you open and close the player repeatedly, it will crash the app on iOS.  

Use case scenario is when scrolling through multiple videos and you click a few videos in succession. 

**To Reproduce**
1. Push a route to the player and press back before it finished loading the network datasource
2. Now immediately push the same route again 
3. Do this a few times, making sure to exit before the video is loaded
4. At that point it will crash 

There are no crash logs on TestFlight.  

Only crashes on iOS physical device.  Tested on Android physical device and simulator with no problem.  Cannot test on iOS simulator before it say it can't run metal.  

**Expected behavior**
When a users scrolls videos, they will open and close video players rapidly (think YouTube).  It should not crash the app.

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Better Player version**
- Version: ^0.0.49

**Smartphone (please complete the following information):**
 - iPhone 7 
 - iOS 14.4

**Comment by vanfresh** [comment]
There was a crash log.  Here's the relevant part. 

Incident Identifier: (removed)
Hardware Model:      iPhone9,1
Process:             Runner [889]
Path:                /private/var/containers/Bundle/Application/(removed)/Runner.app/Runner
Identifier:          (removed)
Version:             124 (0.0.12)
AppStoreTools:       12D4d
AppVariant:          1:iPhone9,1:14
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           (removed) [619]


Date/Time:           2021-02-05 03:27:43.5422 +0800
Launch Time:         2021-02-05 03:27:16.2588 +0800
OS Version:          iPhone OS 14.4 (18D52)
Release Type:        User
Baseband Version:    8.40.01
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000d32cd521c
VM Region Info: 0xd32cd521c is not in any region.  Bytes after previous region: 45412602397  Bytes before following region: 10958843364
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO              280000000-2a0000000 [512.0M] rw-/rwx SM=PRV  
--->  GAP OF 0xd20000000 BYTES
      commpage (reserved)      fc0000000-1000000000 [  1.0G] ---/--- SM=NUL  ...(unallocated)

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [889]
Triggered by Thread:  0

**Comment by jhomlala** [comment]
@vanfresh Please provide reproducible code.

**Comment by vanfresh** [comment]
@jhomlala Please find the repository demonstrating the crash here: [https://github.com/vanfresh/better_crash_example](better_crash_example)

I have also included a video in the repo that shows what happens when you open and close repeatedly.  In this case, it freezes and throw a memory error on xcode.

**Comment by vanfresh** [comment]
@jhomlala I tried the solution provided in [https://github.com/jhomlala/betterplayer/issues/254](https://github.com/jhomlala/betterplayer/issues/254) (branch: playlist).  It crashes much less frequently.  

I would prefer to keep my code as is. I still need access to the `BetterPlayerController` that is private in the `BetterPlayerListVideoPlayerController`.

**Comment by jhomlala** [comment]
I couldn't  reproduce it on my side. Anyway I've find possible solution for this issue. Please try 0.0.52 release.

**Comment by vanfresh** [comment]
Problem is fixed.  Will open if I encounter it again.  Thank you @jhomlala
