### ISSUE TITLE
Samsung S6 - Exoplayer2 error

### ISSUE THREAD

**Issue by leszekkrol** [jhomlala/betterplayer#27]
Hello, 

Sometimes I got this issue on my Samsung S6 device. Is it possible to improve somehow? if this error occurs, he receives the message "Video can't be played". The video file is not damaged, because e.g. restarting the application easily launches this video file. I also noticed that the problem appears when I run several movies one by one.

I/OMXClient(27887): MuxOMX ctor
I/ACodec  (27887): [OMX.Exynos.avc.dec] Now Loaded
D/SurfaceUtils(27887): set up nativeWindow 0x7438ad0e10 for 1080x1920, color 0x105, rotation 0, usage 0x2900
I/ACodec  (27887): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 9, minUndequeuedBuffers : 5
I/ACodec  (27887):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (27887):  [] Now kWhatShutdownCompleted event : 8438
I/MediaCodec(27887): Codec shutdown complete
W/MediaCodecRenderer(27887): Failed to initialize decoder: OMX.Exynos.avc.dec
W/MediaCodecRenderer(27887): android.media.MediaCodec$CodecException: Error 0xffffec77
W/MediaCodecRenderer(27887): 	at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(27887): 	at android.media.MediaCodec.configure(MediaCodec.java:1882)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(27887): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(27887): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/MediaCodecRenderer(27887): 	at android.os.Looper.loop(Looper.java:154)
W/MediaCodecRenderer(27887): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(27887): Playback error.
E/ExoPlayerImplInternal(27887): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [1080, 1920, -1.0], [-1, -1])
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(27887): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(27887): 	at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal(27887): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(27887): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [1080, 1920, -1.0], [-1, -1])
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(27887): 	... 9 more
E/ExoPlayerImplInternal(27887): Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
E/ExoPlayerImplInternal(27887): 	at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(27887): 	at android.media.MediaCodec.configure(MediaCodec.java:1882)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
E/ExoPlayerImplInternal(27887): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(27887): 	... 10 more
D/SurfaceUtils(27887): set up nativeWindow 0x743b2e0e10 for 1080x1920, color 0x105, rotation

**Comment by leszekkrol** [comment]
@jhomlala Any update?

**Comment by adamdupuis** [comment]
I'm also having this issue with the video_player plugin when trying to show many videos in a ListView, similar to an Instagram feed. I was hoping better_player could fix this, but after seeing this issue I am not hopeful. Anyone have a solution?

**Comment by jhomlala** [comment]
This seems to be issue with exoplayer which can't be solved easily. Let's leave this issue here, maybe this will be solved by authors of exoplayer in future.

**Comment by jinyus** [comment]
@leszekkrol @adamdupuis Samsung limits the number of mediaencoder instances that you can run at the same time to save battery...so it's better to have a few (say 3) global instances and use those to play the videos. Since only 1 video will be on the screen at a time. You could have 1 instance playing the current video, 1 for the previous and 1 loading the next video.

**Comment by vikasgupta4190** [comment]
Convert video into MP4 format with low resolution :
Bitrate : 2580 KBPS
Frame Rate : 30fps/Second 
Resolution :  1280 * 720 

Or you can use Any video converter software.

**Comment by huxaiphaer** [comment]
What if it's a stream like `.m3u8` @vikasgupta4190  ?

**Comment by jhomlala** [comment]
There's no point to keep this issue open. This issue won't be solved in any future and may happend. If you think that your device should play some video then open new issue ticket.

**Comment by kiloki-official** [comment]
@jinyus  how do you control media encoder instances in flutter?
