### ISSUE TITLE
Screen sleep while watching video

### ISSUE THREAD

**Issue by Faizi-Apps** [jhomlala/betterplayer#272]
Helo, thanks for this amazing package
i have a problem when im playing video screen auto sleep after some time 
i also added this line `allowedScreenSleep: false,`
but not working. Is anything im missing ?
Thanks for your help

**Comment by jhomlala** [comment]
@Faizi-Apps  Please start using issue template. 

```  
/// Defines if the player will sleep in fullscreen or not
final bool allowedScreenSleep;
```

AllowedScreenSleep parameter is used only with Wakelock plugin in full screen mode. In normal mode you need to handle it by yourself. Just use Wakelock plugin in your code.

**Comment by Faizi-Apps** [comment]
ok
