### ISSUE TITLE
[BUG] Change Language Audio problem ?

### ISSUE THREAD

**Issue by lavara123** [jhomlala/betterplayer#275]
**Describe the bug**
audio does not change.

**To Reproduce**
```dart
class _MyHomePageState extends State<MyHomePage> {
  BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      allowedScreenSleep: false,
      controlsConfiguration: BetterPlayerControlsConfiguration.cupertino(),
      aspectRatio: 16 / 9,
      fit: BoxFit.contain,
    );

    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "https://s44.rapidrame.com/hls/zojdnskdwuknuemgnzavurelqhgh2wtxjaxlydcbf,ztjrfws7stobovjs2xq,rtjrfws7stka47gz2xq,.urlset/master.m3u8",
        headers: {
          "Referer:":
              "https://sinefy.com/api/rapidrame/e553e8c0da8dc3487be9304397707ae8",
          "User-Agent:":
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0",
          "Content-Type:": "application/vnd.apple.mpegurl"
        });

    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(betterPlayerDataSource);

    super.initState();
  }
```

**Expected behavior**
should change the audio file correctly.

that m3u8 file:
```
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Türkçe",LANGUAGE="tr",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="https://s44.rapidrame.com/hls/zojdnskdwuknuemgnzavurelqhgh2wtxjaxlydcbfztjrfws7stobovjs2xq/index-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="English",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://s44.rapidrame.com/hls/zojdnskdwuknuemgnzavurelqhgh2wtxjaxlydcbfztjrfws7stobovjs2xq/index-a2.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=961426,RESOLUTION=1148x480,FRAME-RATE=23.974,CODECS="avc1.640020,mp4a.40.2",AUDIO="audio0"
https://s44.rapidrame.com/hls/zojdnskdwuknuemgnzavurelqhgh2wtxjaxlydcbfztjrfws7stobovjs2xq/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2654335,RESOLUTION=1920x800,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2",AUDIO="audio0"
https://s44.rapidrame.com/hls/zojdnskdwuknuemgnzavurelqhgh2wtxjaxlydcbfrtjrfws7stka47gz2xq/index-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=64848,RESOLUTION=1148x480,CODECS="avc1.640020",URI="https://s44.rapidrame.com/hls/zojdnskdwuknuemgnzavurelqhgh2wtxjaxlydcbfztjrfws7stobovjs2xq/iframes-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=124505,RESOLUTION=1920x800,CODECS="avc1.640028",URI="https://s44.rapidrame.com/hls/zojdnskdwuknuemgnzavurelqhgh2wtxjaxlydcbfrtjrfws7stka47gz2xq/iframes-v1-a1.m3u8"
```

**Screenshots**
audio filenames come but do not change:
![Screenshot_2021-02-06-23-00-09](https://user-images.githubusercontent.com/12005386/107128490-07417900-68b6-11eb-81a0-99f88b83ec61.png)

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale tr_TR.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Connected device (1 available)

**Better Player version**
- Version: ^0.0.51

**Additional context**
test links are connected with referer.

If the link doesn't work, I'll change it

**Comment by jhomlala** [comment]
@lavara123 There's something wrong with this stream. Check it here: https://castr.io/hlsplayer/
I've tried to change audio to English but I'm still hearing Turkish language. Please check your data source again.

**Comment by lavara123** [comment]
> @lavara123 There's something wrong with this stream. Check it here: https://castr.io/hlsplayer/
> I've tried to change audio to English but I'm still hearing Turkish language. Please check your data source again.


Work fine here? 
https://demo.theoplayer.com/test-your-stream-with-statistics?hsLang=en-us

**Comment by jhomlala** [comment]
There's an issue in ExoPlayer https://github.com/google/ExoPlayer/issues/6101. Anyway I've done some workaround and it's should work. Check 0.0.52 release.

**Comment by lavara123** [comment]
> There's an issue in ExoPlayer [google/ExoPlayer#6101](https://github.com/google/ExoPlayer/issues/6101). Anyway I've done some workaround and it's should work. Check 0.0.52 release.

Thanks work for me
