### ISSUE TITLE
[BUG] type 'HlsMediaPlaylist' is not a subtype of type 'HlsMasterPlaylist' in type cast

### ISSUE THREAD

**Issue by hsnbsst** [jhomlala/betterplayer#278]
**Describe the bug**
When I try to watch m3u8 link, an error occurs like this

**Expected behavior**
`type 'HlsMediaPlaylist' is not a subtype of type 'HlsMasterPlaylist' in type cast`

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale tr-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.52.1)
[✓] Connected device (3 available)

• No issues found!

**Better Player version**
- Version: 0.0.51

**Smartphone (please complete the following information):**
 - Device: iphone 7 plus
 - OS: os 14.5
**Additional context**

**Comment by jhomlala** [comment]
Please provide link to HLS video.

**Comment by hsnbsst** [comment]
https://mn-nl.mncdn.com/blutv_showtv/smil:show_sd.smil/chunklist_b2064000.m3u8

When I open this link, it gives such an error

**Comment by jhomlala** [comment]
Should be fixed in 0.0.52.
