### ISSUE TITLE
How to stop playing when the ListView is on background

### ISSUE THREAD

**Issue by wann2** [jhomlala/betterplayer#28]
BetterPlayer is very good!

I'd like to know how to stop playing when the ListView is on background,
for example, I push a new Navigator.push() on the ListView page, but some video still playing and its sound still playing.
Is there any way to stop playing it in that case?

**Comment by leszekkrol** [comment]
@jhomlala  Any update?

**Comment by jhomlala** [comment]
@wann2 Can you provide some example? I've tested it on my device with example app. I've used 
```
Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => EmptyPage()),
            );
```
in Video list and videos seems to be stopped after navigating to new page. It will be great if you could provide reproducable code.

**Comment by jhomlala** [comment]
Okay so you've run video from General tab and then navigated to another page. The video plays in background. It doesn't know that you've moved to next page. What you need to do is:
* pause video on navigation
or
* use visibility detector to automatically play/pause video on navigation
Here is example:

```
Widget _buildDefaultVideo() {
    return FutureBuilder<BetterPlayerController>(
      future: _setupDefaultVideoData(),
      builder: (context, snapshot) {
        var controller = snapshot.data;

        if (!snapshot.hasData) {
          return Center(child: CircularProgressIndicator());
        } else {
          return AspectRatio(
            aspectRatio: 16 / 9,
            child: VisibilityDetector(
              key: Key(snapshot.data.hashCode.toString()),
              onVisibilityChanged: (VisibilityInfo info) {
                if (info.visibleFraction == 0){
                  controller.pause();
                }
              },
              child: BetterPlayer(
                controller: controller
              ),
            ),
          );
        }
      },
    );
  }```

 List player uses this visibility detector to play/pause videos on scroll.
