### ISSUE TITLE
[FEATURE] Add ability to control which video to play in playlist in code

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#280]
**Is your feature request related to a problem? Please describe.**
Imagine a video playlist, when users select a video, it plays the video down the playlist.  But most of the time, users likes to skip +/- n videos to watch the ones they like.  

I want to be able to control this jump in code so users don't need to press multiple skips to jump n videos.   They can simply select a video anywhere in a ListView and BetterPlayer will load that video. 

**Describe the solution you'd like**
I would prefer to simply pass an index to  `BetterPlayerListVideoPlayerController` and it will load that nth video.   This way, I can also add my own custom gestures as well to skip videos. 

**Describe alternatives you've considered**
Right now, I need to re-initialize BetterPlayer to do this.

**Comment by JosephIbe** [comment]
This is a much needed feature. Expecting it soon. Cheers

**Comment by vanfresh** [comment]
Please also add the **current index** playing in ` BetterPlayerListVideoPlayerController`.  I am looking to add my own gestures for skipping to the previous or next video.

**Comment by jhomlala** [comment]
Playlist widget has been refactored in 0.0.54. Check playlist example to see how to handle playlist player.

**Comment by vanfresh** [comment]
Thank you.
