### ISSUE TITLE
Player causes app to crash on iOS

### ISSUE THREAD

**Issue by billy1380** [jhomlala/betterplayer#284]
**Describe the bug**
Application crashes with EXC_BAD_ACCESS (KVO_IS_RETAINING_ALL_OBSERVERS_OF_THIS_OBJECT_IF_IT_CRASHES_AN_OBSERVER_WAS_OVERRELEASED_OR_SMASHED)

**To Reproduce**
On iOS quickly create and recreate a BetterPlayer instances. I will try to recreate the issue with a short code sample and see if I can manage it.

**Flutter doctor**
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H512 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.0)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

**Better Player version**
- Version: 0.0.51

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plus
 - OS: e.g. iOS13

**Additional context**
Bellow are some grabs from xcode showing what methods are being called when the crash occurs.

![image](https://user-images.githubusercontent.com/1329727/107381234-8d440680-6ae6-11eb-9575-4c20efaf3168.png)

![image](https://user-images.githubusercontent.com/1329727/107381366-a9e03e80-6ae6-11eb-9c38-0778c6645e1e.png)

![image](https://user-images.githubusercontent.com/1329727/107381425-bb294b00-6ae6-11eb-901e-22dfae94447a.png)

The issue does not occur in android... I can skip as fast as I like through videos and there are no issues.

I am not using a playlist to manage the videos.

**Comment by billy1380** [comment]
```
void main() {
  runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  Home({Key key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  BetterPlayerController _controller;

  @override
  Widget build(BuildContext context) {
    _controller?.dispose(
      forceDispose: true,
    );

    BetterPlayerDataSource source = BetterPlayerDataSource.network(
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      notificationConfiguration: BetterPlayerNotificationConfiguration(
        showNotification: false,
      ),
      cacheConfiguration: BetterPlayerCacheConfiguration(
        useCache: true,
      ),
    );

    _controller = BetterPlayerController(
      BetterPlayerConfiguration(
        aspectRatio: 16 / 9,
        fit: BoxFit.cover,
        controlsConfiguration: BetterPlayerControlsConfiguration(
          showControls: false,
          loadingWidget: Container(),
        ),
      ),
      betterPlayerDataSource: source,
      betterPlayerPlaylistConfiguration: BetterPlayerPlaylistConfiguration(),
    );

    return Scaffold(
      appBar: AppBar(
        title: Text("Player Test"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() {}),
        child: Icon(Icons.refresh),
      ),
      body: Column(
        children: [
          BetterPlayer(
            controller: _controller,
          )
        ],
      ),
    );
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }
}
```

**Comment by billy1380** [comment]
I know this is not the advised way to use the player... but I have good reasons for doing this.

Pressing refresh on the floating action button will show the library trying to call the notifier on the controller even after it is disposed. If the notifier is removed the library still tries to call a notifier and causes a method call on null object (even thought the notifier is not required).

If you mash the refresh button... it will kill the app on iOS.

Please let me know if I can help in any way.

**Comment by isanimu** [comment]
@billy1380  You should not call dispose on the build method.
```dart
@override
Widget build(BuildContext context) {
  _controller?.dispose(
      forceDispose: true,
  );
}
```

In fact you should just let flutter handle the lifecycle. Let the controller be disposed when your widget is disposed
```dart
@override
void dispose() {
  _controller?.dispose();
  super.dispose();
}
```

**Comment by billy1380** [comment]
I need to keep the controller because of screen rotation and also there is a line in the code that stops the controller being disposed if `betterPlayerPlaylistConfiguration` is not null. Not sure if that is a bug, but I am using it to ensure that the controller is not disposed:

in `lib/src/core/better_player.dart`

``` dart
if (widget.controller.betterPlayerPlaylistConfiguration == null) {
    widget.controller.dispose();
}
super.dispose();
```

Just like with tabs etc in flutter I would like to be able to manage the controller e.g. when you need dynamic tabs you disposed the existing controller and create it... the dispose function then disposes of the final controller.

**Comment by isanimu** [comment]
> I need to keep the controller because of screen rotation and also there is a line in the code that stops the controller being disposed if `betterPlayerPlaylistConfiguration` is not null. Not sure if that is a bug, but I am using it to ensure that the controller is not disposed:

Then you shouldn't dispose it manually other than inside widget's dispose method.

> Just like with tabs etc in flutter I would like to be able to manage the controller e.g. when you need dynamic tabs you disposed the existing controller and create it... the dispose function then disposes of the final controller.

No, you shouldn't dispose it manually. Just by creating a new controller is enough. For example,
```
controller = TabController();
```
When you assign a new value, the 'old' value  will not be used anymore and will automatically get garbage collected. You just need to call dispose inside the widget's dispose method.

**Comment by isanimu** [comment]
This also happen the same when you're trying to use collection's clear method. When you're trying to mutate (add/remove) and clear the collection at the same time you'll get concurrent exception. The same when you're trying to dispose and use it at the same time. When you're disposing it manually the 'old' widget might still be using it. You'll get controller already disposed exception. That's why assigning a new value is more than enough rather than dispose it. Let's Flutter manage the lifecycle automatically.

**Comment by billy1380** [comment]
In the better player controller example, how would you change the network source without changing the controller?

**Comment by isanimu** [comment]
> In the better player controller example, how would you change the network source without changing the controller?

Just assign the controller a new value, you don't have to dispose it.

**Comment by isanimu** [comment]
Just like I mentioned before,

>When you call setState inside your widget, it will not recreate your widget but only recreate your state. But when your parent widget calls setState, it will recreate your widget but might or might not recreate your state. That's why your old widget might still be using your controller.

That's why you shouldn't dispose it manually. Just assign a new value to your controller. Just call controller?.dispose inside the widget's dispose method and lets flutter manage it automatically.

**Comment by billy1380** [comment]
Let me see if I can get that working through an orientation change. Will have an update shortly.

**Comment by isanimu** [comment]
```dart
List<String> urls = [...]
int currentIndex = 0;
BetterPlayerController controller;

void selectVideo(int index) {
  setState((){
    // update your index in here
  });
}

Widget build(BuildContext context) {
  controller = BetterPlayerController( ... ); // assign you new url in here
}
```

**Comment by billy1380** [comment]
@vanfresh thank you very much... will upgrade and try again.

**Comment by jhomlala** [comment]
There are few issues in your code:
* Please don't create BetterPlayerController in build method. Build method is executed each time your widget tree rebuilds. You should init BetterPlayerController in initState method.
* To change video in runtime you can simply call setDataSource method on controller. No need to recreate controller each time.
* You shouldn't dispose controller by yourself. Controller will automatically dispose once BetterPlayer instance will be removed from widget tree.

**Comment by billy1380** [comment]
> There are few issues in your code:
> 
> * Please don't create BetterPlayerController in build method. Build method is executed each time your widget tree rebuilds. You should init BetterPlayerController in initState method.
> * To change video in runtime you can simply call setDataSource method on controller. No need to recreate controller each time.
> * You shouldn't dispose controller by yourself. Controller will automatically dispose once BetterPlayer instance will be removed from widget tree.

Thanks so much for the reply, much appreciated:
- In my main project in is within a bloc so that is not an issue... it is only an issue in the sample code.
- That is great... I will do that instead... it makes more sense, I just did not know that I could do that: thank you.
- I understand, do you have any comments as to why the controller is not disposed if a betterPlayerPlaylistConfiguration is used?

**Comment by jhomlala** [comment]
Playlist feature of Better Player requires rebuilds of widget tree. When widget tree is rebuild, controller disposes automatically. There was need to prevent this and that's why playlist need to be disposed automatically. Better Player has changed during iterations and Better Playlist is some kind outdated.  Playlist feature will be revisted in near future, but can't give exact timeframes.

**Comment by billy1380** [comment]
Nice one... Thanks for the explanation. Keep up the great work. ❤️
