### ISSUE TITLE
[BUG] Multiple videos fail to load on app start due to cache instance conflict

### ISSUE THREAD

**Issue by ashishbeck** [jhomlala/betterplayer#285]
**Describe the bug**
When the package is initialized for the first time, it causes some of the players to fail to load video and throw an exception. The likely root of the cause is the cache feature as seen in the log.

I/ExoPlayerImpl(24376): Init 12a053e [ExoPlayerLib/2.12.2] [a50, SM-A505F, samsung, 29]
E/ExoPlayerImplInternal(24376): Playback error
E/ExoPlayerImplInternal(24376):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
E/ExoPlayerImplInternal(24376):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(24376):       at android.os.Looper.loop(Looper.java:237)
E/ExoPlayerImplInternal(24376):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(24376):   Caused by: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.myapp/cache/video
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:249)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:229)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:175)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:139)
E/ExoPlayerImplInternal(24376):       at com.jhomlala.better_player.CacheDataSourceFactory.createDataSource(CacheDataSourceFactory.java:41)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.ProgressiveMediaSource.createPeriod(ProgressiveMediaSource.java:281)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:120)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:209)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:37)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.CompositeMediaSource.lambda$prepareChildSource$0$CompositeMediaSource(CompositeMediaSource.java:113)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.-$$Lambda$CompositeMediaSource$XIMxMigUUqAS2WvqSyL5xh9sCFo.onSourceInfoRefreshed(Unknown Source:4)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:84)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.ProgressiveMediaSource.notifySourceInfoRefreshed(ProgressiveMediaSource.java:356)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.ProgressiveMediaSource.prepareSourceInternal(ProgressiveMediaSource.java:271)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:197)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:118)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:126)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.MediaSourceList.createPeriod(MediaSourceList.java:310)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.MediaPeriodHolder.createMediaPeriod(MediaPeriodHolder.java:422)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:105)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriodHolder(MediaPeriodQueue.java:170)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1750)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1737)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:858)
E/ExoPlayerImplInternal(24376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(24376):       ... 3 more

If I create a custom controller builder and listen for the exception event and use the retryDataSource() method on the controller, the videos load perfectly on first try but then some of them fail to loop even with looping enabled with this message in the log-
D/AudioTrack(15043): stop(2863): called with 533504 frames delivered
I/MediaCodec(15043): setCodecState state : 0

**To Reproduce**
I encounter this bug whenever I launch my app for the first time or kill it and restart.
1. Create a list of videos (3 is enough) which are loaded through network with cache support enabled
2. Launch the app for the first time
3. Wait for the video to loop

**Expected behavior**
The videos should be loaded normally and looped through as it does on subsequent reloading of the pages after the first start

**Flutter doctor**
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.19041.746], locale en-US)
    • Flutter version 1.26.0-17.3.pre at C:\Flutter
    • Framework revision 4b50ca7f7f (5 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Ashish\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\Ashish\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • SM A505F (mobile) • 192.168.1.6:5555 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 84.0.522.58

• No issues found!

**Better Player version**
- Version: 0.0.52

**Smartphone (please complete the following information):**
 - Device: Galaxy A50
 - OS: android-arm64  • Android 10 (API 29)

**Comment by jhomlala** [comment]
Please format your code next time with markdown.

Fixed in 0.0.53.
