### ISSUE TITLE
[BUG] When selecting HLS track it won't select the correct track.

### ISSUE THREAD

**Issue by isanimu** [jhomlala/betterplayer#287]
**Describe the bug**
When selecting HLS track, it won't select the correct track.

**To Reproduce**
As seen in the recorded video.

https://user-images.githubusercontent.com/11643300/107469476-5c260d80-6b9c-11eb-89d9-ae542cfe56f1.mp4

**Better Player version**
- Version: 0.0.52

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7
 - OS: Android 10

**Comment by jhomlala** [comment]
Fixed in 0.0.53.
