### ISSUE TITLE
How can I dispose BetterPlayer when the page is changed?

### ISSUE THREAD

**Issue by wann2** [jhomlala/betterplayer#29]
How can I dispose BetterPlayer when the page is changed?
I have encountered the below error whenever I change the page that uses BetterPlayer into the other page and then return to the previous page.

![KakaoTalk_Photo_2020-05-29-03-56-43](https://user-images.githubusercontent.com/8732515/83181854-7039f400-a160-11ea-94d5-9724a3e58f30.jpeg)

**Comment by wann2** [comment]
The below error message, When I return back to the ListView page

E/flutter ( 3817): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: A BetterPlayerController was used after being disposed.
E/flutter ( 3817): Once you have called dispose() on a BetterPlayerController, it can no longer be used.
E/flutter ( 3817): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:106:9)
E/flutter ( 3817): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:112:6)
E/flutter ( 3817): #2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:142:12)
E/flutter ( 3817): #3      BetterPlayerState._setup (package:better_player/src/core/better_player.dart:45:23)
E/flutter ( 3817): #4      BetterPlayerState.initState (package:better_player/src/core/better_player.dart:41:5)

**Comment by jhomlala** [comment]
Please provide code example.

**Comment by denniswhchung** [comment]
I met the same problem. Invited @jhomlala to my project. The list page is /lib/pages/vLog/vlog_list.dart
After I entered to /lib/pages/vLog/new_vlog_preview.dart, left comment and return back to vlog_list.dart
The error reported by @wann2 will be thrown

**Comment by sleepingkit** [comment]
I find the solution is that **don't call** the method `BetterPlayerController.dispose()`, since the controller will automatically disposed by itself, so no need to call it again in your project.

**Comment by jhomlala** [comment]
Fixed in release 0.0.14.
