### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by JosephIbe** [jhomlala/betterplayer#290]
I find it difficult to understand how one of the best flutter video player libraries doesn't have a video duration.

The user should be able to see the full duration of the video, such as - how much they have watched and what's left. This will greatly enhance the experience.

A good example is found in this library, which comparatively offers less features apart from it's neater design. [https://pub.dev/packages/yoyo_player](https://pub.dev/packages/yoyo_player)

**Comment by mohamed-Etman** [comment]
You can do that using enableProgressText in controlsConfiguration

`BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      fit: BoxFit.fill,
      autoDispose: true,
      aspectRatio: 16 / 9,
      autoDetectFullscreenDeviceOrientation: true,
      autoPlay: true,
      allowedScreenSleep: false,
      controlsConfiguration:
          BetterPlayerControlsConfiguration(enableProgressText: true),
    );`

**Comment by jhomlala** [comment]
I believe this issue is already solved.

**Comment by JosephIbe** [comment]
Thanks 👍
