### ISSUE TITLE
Preview seekbar like youtube

### ISSUE THREAD

**Issue by keshavbhusal1** [jhomlala/betterplayer#291]
Hi i would like to implement a preview seekbar like youtube.Can anyone tell me how to go about it.

![e8jwal](https://user-images.githubusercontent.com/25548829/107608157-3d3e7e80-6c63-11eb-9b68-8026decdfb98.jpeg)

**Comment by jhomlala** [comment]
@keshavbhusal1 Please use issue template. For questions you can use Discussions tab.

Yes, it's possible to do that. First you need to set custom player theme: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/change_player_theme_page.dart
Then you need to implement your custom theme. Here's an example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/custom_controls/custom_controls_widget.dart
Here's an example how you can create progress bar: https://github.com/jhomlala/betterplayer/blob/master/lib/src/controls/better_player_material_progress_bar.dart

I believe this should be enough to create youtube like progress bar.

**Comment by lavara123** [comment]
@keshavbhusal1 Could you make an example about it?
