### ISSUE TITLE
[BUG] control bar disappears as soon as it appears on android

### ISSUE THREAD

**Issue by nicejhkim** [jhomlala/betterplayer#292]
**Describe the bug**
A control bar disappears immediately when shown by tapping the screen on android device (including emulators). Should be shown for 3 seconds.
No problem on iOS.

**To Reproduce**
1. Start a player. (anything include examples in the repository)
2. Play a video by tapping a play button
3. When the video starts, the control bar disappears after 3 seconds.
4. When you tap the screen, a control bar appears.
5. It disappears as soon as it appears.

**Expected behavior**
A control bar should last for 3 seconds.

**Screenshots**

https://user-images.githubusercontent.com/13111251/107654321-e6b65c00-6cc5-11eb-869d-c254bc514fcf.mp4

**Flutter doctor**
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.0)
[✓] Connected device (3 available)

**Better Player version**
- Version: 0.0.52

**Smartphone (please complete the following information):**
 - Device: Pixel 4, 
 - OS: Android 11

**Additional context**

**Comment by jhomlala** [comment]
Seems like you're running example app on flutter beta. Can you run it on flutter stable version?

**Comment by nicejhkim** [comment]
@jhomlala Hi,
My bad. It works properly on flutter stable channel. 
onHover() was called before onTap() on flutter beta.
Thank you!
