### ISSUE TITLE
[BUG][IOS ONLY]

### ISSUE THREAD

**Issue by Ibrokhim98** [jhomlala/betterplayer#294]
**Describe the bug**
App is crashing when trying to seek forward in player in iOS devices.

**To Reproduce**
1. Go to videoplayer
2. Seek to unbufferred place 
3. See error

**Expected behavior**
Player should work without crashing the app when seeking in video

**Better Player version**
- Version: latest

**Smartphone (please complete the following information):**
 - Device: [e.g.Any iPhone]
 - OS: [e.g. iOS14+]

**Comment by jhomlala** [comment]
@Ibrokhim98 I've testes latest version with both simulator and physical device and didn't get any issue. You didn't provide all informations: what's your iOS version, what's the data source, what's the error. Please provide more details.

**Comment by Ibrokhim98** [comment]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(0x1a56bd9d8 0x1b9a26b54 0x1a55c98f4 0x1051664ec 0x1051662dc 0x1051668e8 0x1a694b6c4 0x1a694daf8 0x1a694aef0 0x1acbf32e0 0x107323ce4 0x107325528 0x107333994 0x1a563d5e0 0x1a5637a88 0x1a5636ba0 0x1bc374598 0x1a7f263d8 0x1a7f2b958 0x104eabb78 0x1a5315568)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
terminating with uncaught exception of type NSException

I am getting this error message and app is crashing.
Here is video link
https://www.dropbox.com/s/s1kwvndjqvgmd0y/RPReplay_Final1613205557.MP4?dl=0

**Comment by jhomlala** [comment]
Fixed in 0.0.54.
