### ISSUE TITLE
Programmatically Control Volume, Play, Pause Video.

### ISSUE THREAD

**Issue by narayanvyas** [jhomlala/betterplayer#30]
How we can control a particular video programmatically in BetterPlayerListVideoPlayer. For example, I want to set the volume of each video to 0 by default when initialized.

**Comment by leszekkrol** [comment]
@jhomlala  Any update?

**Comment by jhomlala** [comment]
Added video player list controller in BetterPlayer 0.0.10. See example here: https://github.com/jhomlala/betterplayer/blob/master/example/lib/video_list/video_list_widget.dart
