### ISSUE TITLE
[BUG] Video from Assets not playing - File not found

### ISSUE THREAD

**Issue by jgjurrius** [jhomlala/betterplayer#302]
I am struggling to get a video played from the assets folder. It keeps on saying that the file does not exist. So it seems as if the path to the file is not correct. I tried creating a release build as well and gives the same problem. When I try to play a video from a URL (external from the internet) everything works fine: 

E/ExoPlayerImplInternal(25863): Playback error
E/ExoPlayerImplInternal(25863):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(25863):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(25863):       at android.os.Looper.loop(Looper.java:246)
E/ExoPlayerImplInternal(25863):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(25863):   Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/user/0/za.co.lighuiswelkom/app_flutter/oorwin.mp4: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:97)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(25863):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(25863):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(25863):       at java.lang.Thread.run(Thread.java:923)
E/ExoPlayerImplInternal(25863):   Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/user/0/za.co.lighuiswelkom/app_flutter/oorwin.mp4: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:166)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:89)
E/ExoPlayerImplInternal(25863):       ... 7 more
E/ExoPlayerImplInternal(25863):   Caused by: java.io.FileNotFoundException: /data/user/0/za.co.lighuiswelkom/app_flutter/oorwin.mp4: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(25863):       at libcore.io.IoBridge.open(IoBridge.java:492)
E/ExoPlayerImplInternal(25863):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
E/ExoPlayerImplInternal(25863):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
E/ExoPlayerImplInternal(25863):       at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:155)
E/ExoPlayerImplInternal(25863):       ... 8 more
E/ExoPlayerImplInternal(25863):   Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(25863):       at libcore.io.Linux.open(Native Method)
E/ExoPlayerImplInternal(25863):       at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
E/ExoPlayerImplInternal(25863):       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
E/ExoPlayerImplInternal(25863):       at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
E/ExoPlayerImplInternal(25863):       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8275)
E/ExoPlayerImplInternal(25863):       at libcore.io.IoBridge.open(IoBridge.java:478)
E/ExoPlayerImplInternal(25863):       ... 11 more

**This is my coding (taken from the example on GitHub):**

**Steps to reproduce the behavior**:

I have the file "oorwin.mp4" in my assets folder and have the file listed in the pubspec.yaml file as "- assets/oorwin.mp4"

`import 'package:better_player/better_player.dart';

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

class TestVideo extends StatefulWidget {
  @override
  _TestVideState createState() => _TestVideState();
}

class _TestVideState extends State<TestVideo> {
  String fileTestVideoUrl = "oorwin.mp4";

  static Future<String> getFileUrl(String fileName) async {
    final directory = await getApplicationDocumentsDirectory();
    return "${directory.path}/$fileName";
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test Video Player'),
        centerTitle: true,
        backgroundColor: StaticApplication.baseColor,
      ),
      body: Column(
        children: [
          Container(
            child: AspectRatio(
              aspectRatio: 16 / 9,
              child: FutureBuilder<String>(
                future: getFileUrl(fileTestVideoUrl),
                builder:
                    (BuildContext context, AsyncSnapshot<String> snapshot) {
                  if (snapshot.data != null) {
                    return BetterPlayer.file(snapshot.data);
                  } else {
                    return const SizedBox();
                  }
                },
              ),
            ),
          ),
        ],
      ),
    );
  }
}`

**Expected behavior**
Play a video file from the assets folder / on the device

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on macOS 11.2.1 20D74, locale en-ZA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

- Version: 0.0.55

 - Device: Samsung Galaxy S20
 - OS: Android 11

**Comment by jhomlala** [comment]
@jgjurrius Please use code formatting. It's hard to read.
There's no bug in Better Player, you're passing source which doesn't exists. You're trying to play file from asset by using file data source. Right now Better Player doesn't support playing asset data source.  Anyway there's simply way to handle this scenario. Simply just save your asset to your applications directory and then use it as file source. Here's how you can do it: 

https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/welcome_page.dart#L196

Once asset is saved into file, you can simply use it as file data source.

**Comment by jgjurrius** [comment]
AH, I missed that part. Thank you very much for the comment.
