### ISSUE TITLE
[FEATURE]Timer display

### ISSUE THREAD

**Issue by hiroki-niinuma** [jhomlala/betterplayer#304]
I would like to display the timer like chewie, but I can't find a way to do that as far as I called the documentation. Could you please add it as a feature?

As an alternative,I added a Text widget to the overlay of BetterPlayerConfiguration(with progress event), but it was in a position where setState did not reach, so the text was not updated.
(Stack widget has been updated of course, but it is hidden when in full screen mode.)

It would be great if you could implement either, or both if you like.

Sorry,Thanks.

chewie
![image](https://user-images.githubusercontent.com/16321909/107961455-49bb3200-6fe9-11eb-91a4-b37105e2e233.png)

betterplayer
![image](https://user-images.githubusercontent.com/16321909/107961299-0eb8fe80-6fe9-11eb-8862-bc72803e56e9.png)

overlay Text widget (not updated)
![image](https://user-images.githubusercontent.com/16321909/107961788-b5050400-6fe9-11eb-9f4c-28c73d0c6379.png)

**Comment by jhomlala** [comment]
@hiroki-niinuma Just use enableProgressText im BetterPlayerControlsConfiguration: https://github.com/jhomlala/betterplayer#betterplayercontrolsconfiguration

**Comment by hiroki-niinuma** [comment]
thanks!
