### ISSUE TITLE
[BUG] Memory DataSource fails on some iOS devices.

### ISSUE THREAD

**Issue by ajzome** [jhomlala/betterplayer#305]
**Describe the bug**
On some devices playing from memory results in a black screen. I traced the issue to the _createFile function. Specifically this can generate paths with invalid characters (e.g. time may contain a space) or wrong extension (some devices won't play a .temp file). 

**To Reproduce**
1. Load a video asset bundled with the app (i.e. an asset)
2. Create a BetterPlayerDataSource.memory from the bytes of the asset
3. Create and play a BetterPlayer with the datasource

**Expected behavior**
Playback from a BetterPlayerDataSource.memory to work on all devices.

**Better Player version**
- Version: 0.0.52

**Smartphone (please complete the following information):**
 - Device: iPad Pro (4th gen)
 - OS: iOS 14.3

**Additional context**
We load a video for playback from assets. We are able to work around the issue by doing a cache ourselves and then use a BetterPlayerDataSource.file but passing a BetterPlayerDataSource.memory would allow for cleaner code.

**Comment by jhomlala** [comment]
Fixed in 0.0.56.
