### ISSUE TITLE
[BUG] - Player controls hide fast (No time enough to tap options)

### ISSUE THREAD

**Issue by chmiguel** [jhomlala/betterplayer#306]
**Describe the bug**

When you tap on the video, the controls appear and disappear so fast that They don't give enough chance to tap on their buttons (Fullscreen, more options button). This started to happen when I updated to new versions. I previously had the 0.0.36 version and it was ok, the controls didn't have this problem. Can you please check? Thank you for any help you can give me.

**To Reproduce**
1. Use the following configuration: ```void setChannel(Channel channel) {
    _dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      channel.streamUrl,
      liveStream: true,
    );
    _controller = BetterPlayerController(
      BetterPlayerConfiguration(
        autoPlay: true,
        autoDispose: false,
        controlsConfiguration: BetterPlayerControlsConfiguration(
          showControlsOnInitialize: false,
          enableSkips: false,
        ),
      ),
      betterPlayerDataSource: _dataSource,
    );
  }```
2. You can use this live stream https://content.uplynk.com/channel/ff809e6d9ec34109abfb333f0d4444b5.m3u8
3. Click on the video and the controls should appear and disappear fast. Sometimes the first time you tap They appear and give you enough time to tap their options, but the next taps they start behaving as described above

**Expected behavior**
The controls should give enough time to tap their options 

**Flutter doctor**
[✓] Flutter (Channel master, 1.25.0-5.0.pre.69, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

**Better Player version**
- Version: 0.0.55

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 9S
 - OS: MIUI 12.0.3, Android 10 QKQ1.191215.002 

**Additional context**

**Comment by chmiguel** [comment]
@surveshoeb I've switched to the stable channel and upgrade flutter and this issue went away
```flutter channel stable```
```flutter upgrade```

**Comment by slowisfast168** [comment]
could you reopen it? 

I had the same problem on the latest flutter channel stable.
flutter --version
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (25 hours ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by jhomlala** [comment]
Fixed in latest release.
