### ISSUE TITLE
[BUG] control bar does not disappear when playing live stream on ios

### ISSUE THREAD

**Issue by nicejhkim** [jhomlala/betterplayer#310]
**Describe the bug**
When datasource is a live stream, control bar is stuck on the video screen.
Works properly on android.

isVideoFinished() always returns true  because videoPlayerValue.duration is 0 on iOS when plays live stream.

**To Reproduce**

use live stream url on any example.

ex) 
BetterPlayer.network('https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8')

**Expected behavior**
the control bar should disappear after 3 seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/13111251/108477631-d100f200-72d6-11eb-839e-73fa719d0a2d.png)

**Flutter doctor**
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale ko-KR)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

**Better Player version**
- Version: 0.0.55

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: 13.6.1

**Additional context**

**Comment by jhomlala** [comment]
Fixed in version 0.0.56. Also please use `liveStream: true` parameter in data source.
