### ISSUE TITLE
Pre-fetch/cache/buffer/load multiple videos for seamless playback

### ISSUE THREAD

**Issue by jtkeyva** [jhomlala/betterplayer#316]
Thank you for developing a better player! This seems like a universally useful high value feature request...surprised it hasn't been requested.

It's frustrating to have a black/blank screen and to have to wait a second for each video to load when you have a list of videos playing back to back such as a story view.

The reusable player example shows quite a lag between players and doesn't always seem to initialize and play properly either.

A solution would be to continuously look ahead in the list, say 3-5 videos and begin pre-fetch/cache/buffer/load them so that when the video ends it **instantly plays back the next video**. Or you can quickly and seamlessly skip videos with no wait time until the next video plays. It should also work when going back a video too.

Perhaps your playlist feature could have an unlimited video list/playback capability? Then it could be used as a story mode player as well.

I was going to load up 5-10 players in a hidden widget but i understand theres a limit to how many simultaneous players can be loaded at once, and this method feels pretty dirty.

I've considered lazy loading but still would need to prefetch the next video in the background.

Ideally this would work with an unlimited list of videos, be fully seamless and do all the heavy lifting like magic.

**Comment by jhomlala** [comment]
@jtkeyva Thanks for using Better Player.

Right now there's no way to prefetch video until it actually added into player. Anyway you can try to play with these settings to do something similar to prefetch.

1. Test different number of reusable controllers:
```dart
 ReusableVideoListController() {
    for (int index = 0; index < 5; index++) {
      _betterPlayerControllerRegistry.add(
        BetterPlayerController(
          BetterPlayerConfiguration(handleLifecycle: false, autoDispose: false),
        ),
      );
    }
  }
```
The number of 3 controllers was chosen without any special way, it was just working fine during tests. You can try add more controllers here.

2. Lower visibility fraction:
```dart
 VisibilityDetector(
            key: Key(hashCode.toString() + DateTime.now().toString()),
            onVisibilityChanged: (info) {
              if (!_afterBuild) {
                return;
              }
              if (info.visibleFraction >= 0.5) {
                _setupController();
              } else {
                _freeController();
              }
            },
```
To start Better Player loading video earlier, you can lower visibility fraction to 0.5 or even less - it depends on how's your list view item build.

3. Use cache. Basically it won't help loading new items, but when someone scrolls back to old items, they will load much faster.
```dart
 controller.setupDataSource(
        BetterPlayerDataSource.network(
          videoListData.videoUrl,
          cacheConfiguration: BetterPlayerCacheConfiguration(useCache: true),
        ),
      );
```
I believe these techniques may help you create pre-fetch behaviour (or at least give the best effect that it's possible).

**Comment by jtkeyva** [comment]
@jhomlala thank you for the quick response! I'm testing out right now. It's loading quicker, however still some issues.

- Reusable video isn't consistent. Sometimes the player shows, sometimes it doesn't
- Playlist: There is an unavoidable "flash" when going back and forth from next to previous video. I've tried making background transparent and you can then see the canvas background. So seems advancing is not seamless. Is that fixable?
- Caching is helping for going back and forth :) but there's still a "flash" in between videos.

Maybe playlist isn't the solution here, as I'm going to be adding some text overlays etc for each video anyhow. I'm gonna try perhaps a carousel slider or something to see if I can find a seamless solution.

Thanks for the awesome plugin, the UI stuff is really slick!

**Comment by jtkeyva** [comment]
For the record, I got it working with [Flutter Cache Manager](https://pub.dev/packages/flutter_cache_manager)  and [Story_view](https://pub.dev/packages/story_view) rather than trying to use a playlist. I think the slight "flash" may be unavoidable as it seems to do that with the standard Video package.

**Comment by jhomlala** [comment]
In latest release I've upgraded reusable video player example. There's still some room for improvment. You may try it if you want. Hope it will solve some of your issues. Please let me know once you've tested it.

**Comment by jtkeyva** [comment]
@jhomlala hey great job! feels very nice. i really like the control with visibleFraction. i'm tweaking it but it's pretty seamless! this is really cool man, thanks.

i noticed double tap on the video pauses it which is a nice touch (punny!). where can i change that/override it? i also tried wrapping in gesture detector but no luck.
