### ISSUE TITLE
[BUG] Resuming app when video was paused due to visibility plays invisible video

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#317]
**Describe the bug**

The video plays in the background when the screen is not visible.

**To Reproduce**
1. Play a video
2. Navigate to another screen without pausing the video (which triggers `onPlayerVisibilityChanged` and pauses the video)
3. Background the app
4. Return to the app on that same screen
5. Video resumes and plays while the initial screen is not visible

**Expected behavior**
The video should not resume if the screen is not visible.

<details>
  <summary>**Flutter doctor**</summary>
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.804], locale fr-FR)
    • Flutter version 1.22.5 at E:\Flutter
    • Framework revision 7891006299 (2 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MrJ\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

</details>

**Better Player version**
- 0.0.56

**Additional context**
My solution was to simply keep track of the visibility state with `_isVisible ` (I can write a quick PR if you want):  

`better_player_controller.dart`

  ```
bool _isVisible = true;

  void onPlayerVisibilityChanged(double visibilityFraction) async {
    if (_disposed) {
      return;
    }
    _postEvent(
        BetterPlayerEvent(BetterPlayerEventType.changedPlayerVisibility));

    if (!(_betterPlayerDataSource
                ?.notificationConfiguration?.showNotification ==
            true) &&
        betterPlayerConfiguration.handleLifecycle) {
      if (betterPlayerConfiguration.playerVisibilityChangedBehavior != null) {
        betterPlayerConfiguration
            .playerVisibilityChangedBehavior(visibilityFraction);
      } else {
        if (visibilityFraction == 0) {
          _isVisible = false;
          _wasPlayingBeforePause ??= isPlaying();
          pause();
        } else {
          _isVisible = true;
          if (_wasPlayingBeforePause == true && !isPlaying()) {
            play();
          }
        }
      }
    }
  }


  void setAppLifecycleState(AppLifecycleState appLifecycleState) {
    if (!_betterPlayerDataSource.notificationConfiguration.showNotification &&
        betterPlayerConfiguration.handleLifecycle) {
      _appLifecycleState = appLifecycleState;
      if (appLifecycleState == AppLifecycleState.resumed) {
        if (_wasPlayingBeforePause == true && _isVisible == true) {
          play();
        }
      }
      if (appLifecycleState == AppLifecycleState.paused) {
        _wasPlayingBeforePause ??= isPlaying();
        pause();
      }
    }
  }


```

**Comment by jhomlala** [comment]
Thanks, fixed in 0.0.57.
