### ISSUE TITLE
[FEATURE] Automatic quality can be selected again after quality is selected

### ISSUE THREAD

**Issue by lavara123** [jhomlala/betterplayer#318]
**Is your feature request related to a problem? Please describe.**
repeat after selecting quality, not automatically select quality

**Describe the solution you'd like**
this is better_player quality select menu:
![Screenshot_20210221-142232507 (1)](https://user-images.githubusercontent.com/12005386/108624017-12f67900-743a-11eb-9077-ebdaa8ab9999.jpg)

may have auto option like this:
![Screenshot_20210221-143414562 (1)](https://user-images.githubusercontent.com/12005386/108624030-286ba300-743a-11eb-8bde-b59853c43df3.jpg)

**Comment by jhomlala** [comment]
Added in 0.0.57.

**Comment by felixgabler** [comment]
Unfortunately, I do not see the "Auto" option. Using `better_player` version `0.0.81` and when I use DASH, I just see the different quality options (all unselected, so I assume we start with "Auto") but can't go back to "Auto" once I select one of the qualities.
