### ISSUE TITLE
betterplayer live stream .m3u8 not working on ios

### ISSUE THREAD

**Issue by mnl92** [jhomlala/betterplayer#32]
My code is identical like betterplayer example code, I only did the following:
1- Put `liveStream: true`.
2- Change the given URL to a live online .m3u8 stream.

My code:

    Future<BetterPlayerController> _setupDefaultVideoData() async {
      var dataSource = BetterPlayerDataSource(
          BetterPlayerDataSourceType.NETWORK,
          "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8",
          liveStream: true);
      _betterPlayerController = BetterPlayerController(
          BetterPlayerConfiguration(
            autoPlay: true,
            controlsConfiguration:
            BetterPlayerControlsConfiguration(
                enableProgressText: true),
          ),
          betterPlayerDataSource: dataSource);
      return _betterPlayerController;
    }

**Note:** I used the same code for android and the app was working, even I uploaded it to play store and it is working fine, But when I tried the IOS version the video on demand (VOD) was also working **BUT** I faced the following error only with the live stream 

════════ Exception caught by gesture ══════════════════════════════

The following NoSuchMethodError was thrown while handling a gesture:
The getter '_duration' was called on null.
Receiver: null
Tried calling: _duration

When the exception was thrown, this was the stack: 

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Duration.>= (dart:core/duration.dart:175:63)
#2      _BetterPlayerCupertinoControlsState._playPause (package:better_player/src/controls/better_player_cupertino_controls.dart:532:45)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#22cb7
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(22.0, 309.5)
  finalLocalPosition: Offset(9.0, 25.6)
  button: 1
  sent tap down
══════════════════════════════════════════════════════

My flutter doctor -v was:

Macs-MacBook-Pro:betterplayer-master mac$ flutter doctor -v

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)

    • Flutter version 1.17.1 at /Users/mac/development/flutter

    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700

    • Engine revision 6bc433c6b6

    • Dart version 2.8.2

 

 

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)

    • Android SDK at /Users/mac/Library/Android/sdk

    • Platform android-29, build-tools 29.0.3

    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java

    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

    • All Android licenses accepted.

 

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    • Xcode 11.5, Build version 11E608c

    • CocoaPods version 1.9.1

 

[✓] Android Studio (version 3.6)

    • Android Studio at /Applications/Android Studio.app/Contents

    • Flutter plugin version 45.1.1

    • Dart plugin version 192.8052

    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

 

[✓] Connected device (1 available)

    • iPhone SE (2nd generation) • 2D3BE9D0-C5DF-44A6-90EE-818D8D1383D9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

 

• No issues found!

Macs-MacBook-Pro:betterplayer-master mac$

**Comment by jhomlala** [comment]
Should be fixed in 0.12.0.

**Comment by kapilsharma-gts** [comment]
Play m3u8 file using chewie: ^1.4.0. 
[Go to package](https://pub.dev/packages/chewie)

chewie package supports both Android and iOS platforms. This package provides a video player widget based on ExoPlayer.
