### ISSUE TITLE
Bottom sheet Background color can be changed

### ISSUE THREAD

**Issue by AliHoseinpoor** [jhomlala/betterplayer#321]
**Is your feature request related to a problem? 
None

**Describe the solution you'd like**
The background color of the bottom sheet is white. It'd be nice if we could change color.As a rule, the color of the bottom sheet menu text should be changed.

**Describe alternatives you've considered**
None

**Additional context**
![IMG_20210222_004243](https://user-images.githubusercontent.com/41499466/108639015-82568200-74a7-11eb-8763-6f0a3984b0ec.jpg)

**Comment by jhomlala** [comment]
Added support for background color of bottom sheet in 0.0.58. Check BetterPlayerControlsConfiguration -> overflowModalColor.
