### ISSUE TITLE
Pip mode in fullscreen not working well 

### ISSUE THREAD

**Issue by AliHoseinpoor** [jhomlala/betterplayer#322]
**Describe the bug**
When I'm not in fullscreen mode and I play the video normally, pip mode works properly. But when I enter fullscreen mode and activate pip mode, the video is not displayed properly in pip mode. For a better understanding, I've made a short film that I'll put in the end.

**To Reproduce**
1. Play the video 
2. Go to Fullscreen mode
3. Click on pip icon
4. You can see the bug now.

**Expected behavior**
It is expected that pip mode will work properly in fullscreen mode. 

**Screenshots**

https://user-images.githubusercontent.com/41499466/108639303-11b06500-74a9-11eb-9f5f-28fc4880041a.mp4

**Flutter doctor**
Every thing ok

**Better Player version**
- 0.0.57

**Smartphone (please complete the following information):**
 - Device : huawie mate 10 lite
 - OS: android 8

**Additional context**
None

**Comment by jhomlala** [comment]
PiP shouldn't be enabled in full screen mode. In 0.0.58 I've disabled it.
