### ISSUE TITLE
[FEATURE] This way it gets cheaper

### ISSUE THREAD

**Issue by lavara123** [jhomlala/betterplayer#324]
**Is your feature request related to a problem? Please describe.**
Audio, quality and subtitle options would be more like the picture
![Screenshot_20210222-131430964 (1)_1](https://user-images.githubusercontent.com/12005386/108694880-ae5a1d80-7510-11eb-87e7-6c1737fdb531.jpg)

**Comment by jhomlala** [comment]
Won't do. This custom theme can be recreated with custom theme feature of Better Player. Here's an example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/change_player_theme_page.dart

**Comment by lavara123** [comment]
> Won't do. This custom theme can be recreated with custom theme feature of Better Player. Here's an example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/change_player_theme_page.dart

Is there a small example of how I can bring quality and subtitle options to those icons?
