### ISSUE TITLE
[BUG] Hide skip button in IOS

### ISSUE THREAD

**Issue by m4iu3m** [jhomlala/betterplayer#325]
In file better_player_cupertino_controls.dart
I guess it should be like this:

if (_controlsConfiguration.enablePlayPause) -----> _controlsConfiguration.enableSkips
  _buildSkipBack(iconColor, barHeight)
else
  const SizedBox(),
if (_controlsConfiguration.enablePlayPause)
  _buildPlayPause(_controller, iconColor, barHeight)
else
  const SizedBox(),
if (_controlsConfiguration.enablePlayPause) ---------> _controlsConfiguration.enableSkips
  _buildSkipForward(iconColor, barHeight)
else

Do not know if that is true

**Comment by jhomlala** [comment]
You didn't fill your issue with template, but anyway I've fixed it in 0.0.58.
