### ISSUE TITLE
[BUG] Notification Bar Seekbar (Progressbar)

### ISSUE THREAD

**Issue by thecaptrex** [jhomlala/betterplayer#326]
**Describe the bug**
the seekbar (progress bar) at the notification bar is still visible eventho i made sure `enableProgressBar = false`

**To Reproduce**
1. turn on the notification configuration `showNotification: true`
2. turn off progress bar `enableProgressBar = false`
2. Play any video (in my case it was an hls video)
3. open notificiation bar 
4. See the seekbar (progress bar is stil visible and functioning)

**Expected behavior**
with the`enableProgressBar = false` i was expecting that ALL the progress bar would be disabled (or invisible) but it turned out that the progress bar is only disabled in the player and still visible in the notification bar

**Flutter doctor**
`[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-ID)
    • Flutter version 1.22.6 at /Users/Arkademi/Developer/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Arkademi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29)
      (emulator)

• No issues found!`

**Better Player version**
- Version: 0.0.55

**Smartphone (please complete the following information):**
 - Device: emulator Nexus 5, physical Samsung S8
 - OS: emulator is Android 10 & physical is Android 9

**Additional context**
also with the notification configuration is on `showNotification: true`, the player is still playing in the background even tho i already close the app. i'll open another issue for this specific problem

**Comment by jhomlala** [comment]
`enableProgressBar` applies only to controls visible in app, not in notification. I will add documentation for that.

`also with the notification configuration is on showNotification: true, the player is still playing in the background even tho i already close the app. i'll open another issue for this specific problem` - can you create new issue with exact steps or reproducible code?
