### ISSUE TITLE
[FEATURE] set speed to higher than 2x

### ISSUE THREAD

**Issue by HiroyukTamura** [jhomlala/betterplayer#328]
**Is your feature request related to a problem? Please describe.**
Firstly, really thank you for this awesome plugin.
I want to set video speed to faster than 2x, but BetterPlayer restricts it to 2x or less.

**Describe the solution you'd like**
loosen limitation.

**Additional context**
on dart, speed is limited as `speed < 0 || speed > 2`.
https://github.com/jhomlala/betterplayer/blob/726f095f7e46642d5df2d338966554749c8ce3b5/lib/src/core/better_player_controller.dart#L528-L530
on iOS native, speed is limited as `speed < 0 || speed > 2` , too.
https://github.com/jhomlala/betterplayer/blob/958a2b412bbb10df7ed2405fe657ca9309820d04/ios/Classes/FLTBetterPlayerPlugin.m#L585-L588
but on Android native, there is no speed limitation.
https://github.com/jhomlala/betterplayer/blob/958a2b412bbb10df7ed2405fe657ca9309820d04/android/src/main/java/com/jhomlala/better_player/BetterPlayer.java#L549-L553

I'm sorry if I may be mistaken, but the assertion seems duplicated(or lacked).

**Comment by jhomlala** [comment]
Won't do. Reason why I won't do that is simple - I want to have same behavior in both Android/iOS. 

Anyway you can do it with current API (it may be blocked in the future, but right feel free to use it):
```dart
 _betterPlayerController.videoPlayerController.setSpeed(3.0);
```
