### ISSUE TITLE
[FEATURE] support to extract subtitles and audio tracks from containers like mkv

### ISSUE THREAD

**Issue by sreealeti** [jhomlala/betterplayer#329]
**Is your feature request related to a problem? Please describe.**
mkv containers which are also bundled with multiple audio tracks and subtitles which are not in hls format may needs either transcoding to hls for the tracks available. 

**Describe the solution you'd like**
extend the track and subtitle extractions to other containers like mkv or mp4.

**Describe alternatives you've considered**

**Additional context**
expoplayer currently support audio tracks for mkv containers.

**Comment by jhomlala** [comment]
MKV - won't be supported (iOS won't play MKV).
MP4 - can you provide sample file with tracks/subtitles? Do you know how to extract them with ExoPlayer/AVPlayer?

**Comment by sreealeti** [comment]
this is a sample with tracks.
https://forum.cyberlink.com/forum/posts/downloadAttach/20726.page

getCurrentTrackGroups should provide track list i believe
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getCurrentTrackGroups()

**Comment by jhomlala** [comment]
How about AVPlayer? Is that doable?

**Comment by sreealeti** [comment]
i do not have AVPlayer info . for exoplayer it was introduced part of https://github.com/google/ExoPlayer/issues/514.

**Comment by jhomlala** [comment]
I've did some research and I couldn't find a way to demux (extract) subtitles encoded in mp4 in iOS's AVPlayer. Maybe it's possible, but right now I can't find how to do it.

I won't implement feature only for Android, that's why I won't do that feature.

Feel free to answer in this issue if you have some examples from both Android and iOS which shows how to extract subtitles in mp4.

**Comment by sreealeti** [comment]
i do see vlc player is playing the files in their example package, so i am sure their is a way its doin git in android and iphones.
