### ISSUE TITLE
[BUG] Changing screen while video is initializing plays invisible video

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#331]
Describe the bug

The video plays in the background when the screen is not visible. Linked to #317 I suppose.

To Reproduce

Load a video with autoplay = true on a slow internet connection.
Navigate to another screen before the player is initialized
As soon as the player has finished initializing, the video will play in the background

**Flutter doctor**
Better Player version

0.0.57
Additional context
The following change should do the trick:

better_player_controller.dart

```
///Start video playback. Play will be triggered only if current lifecycle state
///is resumed.
Future<void> play() async {
  if (_appLifecycleState == AppLifecycleState.resumed && _isPlayerVisible) {
    await videoPlayerController.play();
    _hasCurrentDataSourceStarted = true;
    _wasPlayingBeforePause = null;
    _postEvent(BetterPlayerEvent(BetterPlayerEventType.play));
  }
}

```

**Comment by jhomlala** [comment]
Should be fixed in 0.0.59.
