### ISSUE TITLE
[BUG] Video still playing in the background with notification configuration is true

### ISSUE THREAD

**Issue by thecaptrex** [jhomlala/betterplayer#334]
**Describe the bug**
idk know if it's a bug or an actual feature but when notification configuration is on `showNotification: true`, video will still playing even tho it's no longer visible.  i already made sure that `handleLifecycle: true` but ther video is still playing even tho the app is on the background.

**To Reproduce**
1. turn on notification configuration `showNotification: true`
2. handleLifecycle is on  `handleLifecycle: true`
3. play any video (in my case it was an hls video)
4. whle video is still playing minimize the app
4. and hear the video is playing in the background

**Expected behavior**
when `handleLifecycle: true` i expect that when i minimize the app the video is paused and when i reopen the app again the video would resume playing. but it wasn't like that because i turned on `showNotification: true`.

**Screenshots**

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-ID)
    • Flutter version 1.22.6 at /Users/--/Developer/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
    • Android SDK at /Users/--/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86 • Android 10 (API 29) (emulator)
    • my iPhone (mobile)           •
      dfbd5c9c65f0f5a8555b1dc6bae9af1f6873946e • ios         • iOS 14.4
• No issues found!

**Better Player version**
- Version:  0.0.55

**Smartphone (please complete the following information):**
 - Device: emulator Nexus 5, physical Samsung S8
 - OS: emulator is Android 10 & physical is Android 9

**Additional context**
and there's one more issue regarding the notification. when video is still playing (in the background or foreground) and i force close the app, the notification bar won't go away.

**Comment by jhomlala** [comment]
Notifcation mode is used to play video in background/foreground. Everything seems to be fine based on your description.
`handleLifecycle` will be ignored when notification is used.

Re additional context: You should read the manual. https://github.com/jhomlala/betterplayer#setup-player-notification

```
Important note for android: You need to add special service in android native code. Service will simply destroy all remaining notifications. This service need to be used to handle situation when app is killed without proper player destroying. Check BetterPlayerService in example project to see how to add this service to your app. https://github.com/jhomlala/betterplayer/blob/feature/player_notifications/example/android/app/src/main/kotlin/com/jhomlala/better_player_example/BetterPlayerService.kt
```

For me there's nothing to fix. If you don't agree let me know. Right now I'm closing this issue.
