### ISSUE TITLE
[BUG] Aspect Ratio incorrect for user recorded videos in iOS

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#335]
**Describe the bug**
I am experiencing this issue [https://github.com/flutter/flutter/issues/66413](https://github.com/flutter/flutter/issues/66413) when using **user recorded videos** with BetterPlayer.  

When you load better player, it shows the the correct aspect ratio for the placeholder image, but when you press play, the aspect ratio is either reversed or uses default aspect ratio (i.e the video is squished.)

**To Reproduce**
1. Record video with [camera plugin](https://pub.dev/packages/camera) using the **front** camera in **portrait** mode
2. Replay video using the saved video path with Better Player
3. Aspect Ratio on iOS is wrong when video is playing.  Instead of 9:16, it shows 16:9 (I think this is the better player's default aspect ratio) when video is played.
 
**Expected behavior**
User recorded videos should display the correct aspect ratio in iOS

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Better Player version**
- Version: 0.0.57

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 14.0

**Comment by vanfresh** [comment]
It seems like `aspectRatio` in `BetterPlayerConfiguration` is not being abide by in iOS, so it defaults back to fallback to fitting within the space allowed.

**Comment by vanfresh** [comment]
The issues seems to be **user recorded videos** only.  If I compress the video before using better player, the aspect ratio displays correctly.   This is an iOS only bug and the metadata isn't changed during compression.

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.59.
