### ISSUE TITLE
[BUG] navigtion to page immediately crasges the app

### ISSUE THREAD

**Issue by shayant98** [jhomlala/betterplayer#336]
**Describe the bug**
navigating to the screen with better player immediately crashes the app and return the following error
E/flutter (14357): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoSuchMethodError: No virtual method setAudioAttributes(Lcom/google/android/exoplayer2/audio/AudioAttributes;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/~~Gr4Bvx2myRqujX4-fum2vA==/com.radiotrishul.tbn-Py1gzmfsf7s0O_l83_Hw_A==/base.apk)

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/27793497/109112010-b1bff580-7718-11eb-8505-afa82580d14c.png)

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/shayantsital/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shayantsital/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Users/shayantsital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.2

[!] Android Studio (version 4.1)
    • Android Studio at /Users/shayantsital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/shayantsital/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • SM G988B (mobile) • R5CN30SCWCV • android-arm64 • Android 11 (API 30)

**Better Player version**
- Version: 0.0.58

**Smartphone (please complete the following information):**
 - Device: [Samsung s20 ultra 5g]
 - OS: [Android 11]

**Additional context**

**Comment by jhomlala** [comment]
Seems like you have build app with ExoPlayer 2.13.x which has removed this method. I've upgraded ExoPlayer to 2.13.1 in Better Player 0.0.59.
