### ISSUE TITLE
[BUG] HLS subtitles not working

### ISSUE THREAD

**Issue by FlutterSu** [jhomlala/betterplayer#337]
**Describe the bug**
HLS subtitles not working.

**To Reproduce**
1. Run better_player example
2. Click on 'HLS subtitles'
3. Click play
4. Select subtitles
5. See subtitles not showing

**Expected behavior**
See subtitles.

**Screenshots**
<img width=150 src=https://user-images.githubusercontent.com/46503636/109121224-0cc50d00-7758-11eb-93e8-a3c27e9cfc48.jpg><img width=150
 src=https://user-images.githubusercontent.com/46503636/109121230-0d5da380-7758-11eb-959f-3bfe9e1951c8.jpg><img width=180
 src=https://user-images.githubusercontent.com/46503636/109121695-a1c80600-7758-11eb-91cb-9a635d79185c.jpg>

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.0.1 20B29 darwin-x64, locale ru-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)
    ! Device 10.181.0.130:5555 is offline.
    ! Device 10.181.167.240:5555 is not authorized.
      You might need to check your device for an authorization dialog.
    ! Device 10.181.170.89:5555 is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 3 categories.
```

**Better Player version**
- Version: 0.0.57 and 0.0.58

**Smartphone:**
 - iPhone SE - iOS 14.4
 - Honor 10, COL-L29 - Android 10

**Comment by jhomlala** [comment]
Fixed in 0.0.59.
