### ISSUE TITLE
Playing a video in iOS stops the audio, allow mix with others on iOS

### ISSUE THREAD

**Issue by billy1380** [jhomlala/betterplayer#339]
Playing a video in iOS stops the audio.

It would be great to have a way to support mixWithOthers similar to video player (https://github.com/flutter/flutter/issues/69757)

**Comment by jhomlala** [comment]
It would be nice if you will follow issue template. Added setMixWithOthers method in 0.0.60.

**Comment by billy1380** [comment]
> It would be nice if you will follow issue template. Anyway, I've added setMixWithOthers method in 0.0.60.

I did follow the template! I just removed the headings... anyway, they have been re-added... it is too pedantic for my taste... but if you prefer leaving the titles in then so be it.

Thanks for the fix.
