### ISSUE TITLE
[BUG] The method 'pause' was called on null.

### ISSUE THREAD

**Issue by naamapps** [jhomlala/betterplayer#342]
**Describe the bug**
When calling the dispose method on the better Player Controller (without initializing the BetterPlayerDataSource) it throws this error because there is no source.  
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'pause' was called on null.
E/flutter (20375): Receiver: null
E/flutter (20375): Tried calling: pause()
E/flutter (20375): #0      BetterPlayerController.pause (package:better_player/src/core/better_player_controller.dart:514)
E/flutter (20375): #1      BetterPlayerController.dispose (package:better_player/src/core/better_player_controller.dart:981)
```

**To Reproduce**
1. Init the better player controller without BetterPlayerDataSource.
2. Dispose the better player controller.
3. See error

**Expected behavior**
The controller disposes without throwing an error.

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale
    en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Better Player version**
- Version: 0.0.59

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy note20 ultra]
 - OS: [e.g. Android 11]

**Comment by jhomlala** [comment]
Fixed in 0.0.60.
