### ISSUE TITLE
[BUG] HLS SUBTITLES NOT WORKING

### ISSUE THREAD

**Issue by nsurghy** [jhomlala/betterplayer#343]
I need to make it work:
the audio tracks selector and embedded subtitles of a hls url.

With none of the properties of this player it works. I wonder if this player supports multiple audio tracks and hls subs, because I tried to use it and the subtitiles are not working (they don't even appear on the video). Everything else works well. Vscode gives me the following error: 

I/flutter (10485): Failed to parse subtitle line: [0
I/flutter (10485): Failed to parse subtitle line: [1
...
I/flutter (10485): Failed to parse subtitle line: [26
I/flutter (10485): Parsed total subtitles: 0

I used the example in this Git sample, at the section called 'HLS subtitles', which has one video and audio track and subtitles:

https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

Regards

**Comment by nsurghy** [comment]
Hi, there is some other console error but it's the same bug. It seems to have detected some subs in spanish but then it gives error (the subs wasn't displayed any time). Here's the console output error:


I/flutter ( 5950): Failed to parse subtitle line: [08:05:12.109 --> 08:05:14.201, ¿ Qué vas a hacer
I/flutter ( 5950): Failed to parse subtitle line: [WEBVTT, X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.000]
I/flutter ( 5950): Failed to parse subtitle line: [08:05:18.162 --> 08:05:21.162, No, no se la vamos a pasar así
I/flutter ( 5950): Parsed total subtitles: 1

**Comment by jhomlala** [comment]
@nsurghy Please use issue template next time. HLS subtitles bug was fixed yesterday. Please check latest version 0.0.59.

**Comment by jhomlala** [comment]
If there's still some problem, just respond in this issue.
