### ISSUE TITLE
[BUG] openFullscreen then setState() or markNeedsBuild() called when widget tree was locked / Tried to build dirty widget in the wrong build scope

### ISSUE THREAD

**Issue by thegrxp** [jhomlala/betterplayer#344]
**Describe the bug**
Sometimes when going fullscreen the following exception occurs

> ======== Exception caught by foundation library ====================================================
setState() or markNeedsBuild() called when widget tree was locked.
> ======== Exception caught by scheduler library =====================================================
setState() called after dispose(): _BetterPlayerSubtitlesDrawerState#77f27(lifecycle state: defunct, not mounted)
> ======== Exception caught by scheduler library =====================================================
setState() called after dispose(): _BetterPlayerSubtitlesDrawerState#77f27(lifecycle state: defunct, not mounted)
> ======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#b631a](state: OverlayState#67000(entries: [OverlayEntry#6dde8(opaque: true; maintainState: false), OverlayEntry#bb3fa(opaque: false; maintainState: true)])):
A VideoPlayerController was used after being disposed.
> Once you have called dispose() on a VideoPlayerController, it can no longer be used.
The relevant error-causing widget was: 
  MaterialApp file:///Users/admin/development/nevercamp/flutter-app/lib/main.dart:127:14
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:178:12)
#3      _VideoPlayerState.deactivate (package:better_player/src/video_player/video_player.dart:629:23)
#4      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:4847:12)
> ======== Exception caught by scheduler library =====================================================
Tried to build dirty widget in the wrong build scope.
> ======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Tried to build dirty widget in the wrong build scope.
> A widget which was marked as dirty and is still active was scheduled to be built, but the current build scope unexpectedly does not contain that widget.
> Sometimes this is detected when an element is removed from the widget tree, but the element somehow did not get marked as inactive. In that case, it might be caused by an ancestor element failing to implement visitChildren correctly, thus preventing some or all of its descendants from being correctly deactivated.
The root of the build scope was: [root]
  renderObject: RenderView#30bc2
> The offending element (which does not appear to be a descendant of the root of the build scope) was: BetterPlayerCupertinoControls
  dirty
  dependencies: [BetterPlayerControllerProvider, MediaQuery]
  state: _BetterPlayerCupertinoControlsState#f25f7
When the exception was thrown, this was the stack: 
#0      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2703:13)
#1      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2728:10)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)

**Better Player version**
- Version: 0.0.59

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS: 14

**Additional context**
```
 @override
  void initState() {
    super.initState();
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      autoPlay: true,
      autoDispose: true,
      looping: true,
      aspectRatio: widget.ratio,
      controlsConfiguration:
          BetterPlayerControlsConfiguration(enableFullscreen: true),
    );
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      widget.videoUrl,
    );
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration,
        betterPlayerDataSource: betterPlayerDataSource);
    _betterPlayerController.addEventsListener((event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.openFullscreen) {
        Future.delayed(Duration(milliseconds: 500), () {
          SystemChrome.setPreferredOrientations(_landscapeOrientation);
        });
      }

      if (event.betterPlayerEventType == BetterPlayerEventType.hideFullscreen) {
        Future.delayed(Duration(milliseconds: 500), () {
          SystemChrome.setPreferredOrientations(_portraitOrientation);
        });
      }
    });
  }
```

Thank you for this amazing lib :)

**Comment by jhomlala** [comment]
Seems like your BP configuration is fine. Can you give more details about this issue? Are you able to reproduce this issue each time? Are you using this widget in list view or in other view which is getting deactivated when you have started full screen?

**Comment by thegrxp** [comment]
> Seems like your BP configuration is fine. Can you give more details about this issue? Are you able to reproduce this issue each time? Are you using this widget in list view or in other view which is getting deactivated/disposed when you have started full screen?

Indeed it happens only when the widget is in a ListView. It happens randomly at least one time out of ten.  Thank you for your help

**Comment by jhomlala** [comment]
Check reusable video list to see how to work with lists: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list

You may also try video list example: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/video_list

**Comment by thegrxp** [comment]
Oh I missed that part in the doc sorry. I can’t try it before monday I’ll let you know. Thanks a lot

**Comment by thegrxp** [comment]
This is working well, thank you!
