### ISSUE TITLE
[BUG] Video not stopped when popping the active screen as last screen

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#348]
**Describe the bug**

The video keeps playing if popping the active screen quits the app.

**Steps to reproduce the behavior:**

1. Load a video in a single screen app, with the active screen being the only NavigationRoute in memory.
2. Make sure the video is playing.
3. Pop the active screen (press the back button on Android), which should quit the app since there is not previous Route to pop. Note: do NOT press "home", which works as expected.
4. Now you are outside of the app with the video still playing.

<details>
  <summary>**Flutter doctor**</summary>
  
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale fr-FR)
    • Flutter version 1.22.6 at E:\Flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MrJ\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
</details>

**Better Player version**

0.0.59

**Additional context**

Some logging showed the following:

- `betterPlayerController.setAppLifecycleState()` is trigger normally. When you pop the last screen, you can see the following lines in a row:
```
AppLifecycleState.inactive
AppLifecycleState.paused
AppLifecycleState.detached
```
-`await _videoPlayerPlatform.pause(_textureId);` in `videoPlayer._applyPlayPause()` is also called succesfully.
Therefore I suppose the problem lies in the method `_videoPlayerPlatform`?

**Comment by jhomlala** [comment]
Yes, you're right, issue was on native code side. I've fixed it in 0.0.60.
