### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by smartking260** [jhomlala/betterplayer#349]
how can I add close icon to betterPlayer notification ?
actually i want to customise better player notification .
can you help me?
yhanks

**Comment by jhomlala** [comment]
@smartking260 You're keep ignoring my requests to use discussions tab for questions or issue template for bug. I asking last time - please use these communicating options correctly. 

Right now you can only use options from BetterPlayerNotificationConfiguration class. There's no option for close icon in notification. I have no plans to add more options for notifications. Anyway you can always fork BP and customize it.
See this method on Android: https://github.com/jhomlala/betterplayer/blob/master/android/src/main/java/com/jhomlala/better_player/BetterPlayer.java#L202 and iOS: https://github.com/jhomlala/betterplayer/blob/master/ios/Classes/FLTBetterPlayerPlugin.m#L909

You should modify these methods to get what you need.
