### ISSUE TITLE
[FEATURE] Dynamically set placeholder

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#350]
**Is your feature request related to a problem? Please describe.**
When you set a new datasource and before the video plays, the placeholder cannot be updated set to match the video (i.e. video thumbnail)

**Describe the solution you'd like**
I would like to be able to update the placeholder when the video changes

**Describe alternatives you've considered**
I could place a image underneath the player

**Comment by jhomlala** [comment]
Added in 0.0.60. Try placeholder in data source.
