### ISSUE TITLE
notification dose'nt show on lockscreen

### ISSUE THREAD

**Issue by smartking260** [jhomlala/betterplayer#351]
**Describe the bug**
Hi,actually notification dosn't show notification on lock screen after screen is off, if stop it before that then notification will be showing on lockscreen but we cant clear notification on lockscreen,
how can I add close botton on better player notification?
thanks.

**Comment by jhomlala** [comment]
@smartking260 this is last warning. Please read this comment: https://github.com/jhomlala/betterplayer/issues/349#issuecomment-787127011
