### ISSUE TITLE
Video playing stuck landscape mode  app orientation is disable when you try to play on disable orientation only portrait  mode app is closed unable to play fullscreen mode while  i want my app is only on portrait they go landscape when video is playing

### ISSUE THREAD

**Issue by joshua750** [jhomlala/betterplayer#353]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jhomlala** [comment]
@joshua750 Please follow issue template. I don't understand why did you put description of your issue into title...
