### ISSUE TITLE
Documentation typo and unclear

### ISSUE THREAD

**Issue by petoknm** [jhomlala/betterplayer#358]
I am trying to understand how `autoDispose` works because I have a memory leak in my application and the documentation is not very clear.

https://github.com/jhomlala/betterplayer/blame/master/README.md#L826

What exactly does `Your event listener will ne auto-disposed on dispose time` mean? And in what situations should it be false?

**Comment by jhomlala** [comment]
@petoknm Please use discussions tab next time to ask questions.
I agree that this may be not clear. I will change description in next version.

`autoDispose` parameter will prevent BetterPlayerController from disposing when BetterPlayer disposes. So when you have BetterPlayer in your tree with attached BetterPlayerController and your BetterPlayer widget will be not anymore used in widget tree then dispose method is called inside BetterPlayer. BetterPlayer's dispose method has betterPlayerController.dispose() call which dispose BetterPlayerController.
