### ISSUE TITLE
[FEATURE] Clear cache or option timeout for cache automatic

### ISSUE THREAD

**Issue by qhu91it** [jhomlala/betterplayer#360]
**Is your feature request related to a problem? Please describe.**
I looking for a feature to clear cache or option set timeout to delete cache automatic

**Describe the solution you'd like**
Something like this, automatically delete this cache after 7 days

```
BetterPlayerCacheConfiguration(
    useCache: true,
    timeout: Duration(days: 7),
)
```

or function to clear all cache

`BetterPlayer.clearAllCache()`

**Describe alternatives you've considered**

**Additional context**

**Comment by jhomlala** [comment]
Seems good addition, but right now this have low priority for me. There are more important issues that need to be resolved. I may back to this task later. I can't give you exact timeframes when it will be done. Feel free to create PR if you want to speed up this feature.

**Comment by schisms** [comment]
Where is the cache itself stored on iOS/Android? I can't seem to find it in appdir, but maybe I didn't look hard enough.

With a static file path, integrating this within your app should be easy.

**Comment by jhomlala** [comment]
Added clearCache method in 0.0.63. Check BetterPlayerController for that method.
