### ISSUE TITLE
[BUG] Unhandled Exception on VideoError

### ISSUE THREAD

**Issue by schisms** [jhomlala/betterplayer#362]
**History check**
Closest thing I could find: https://github.com/jhomlala/betterplayer/issues/40

**Describe the bug**
Unhandled exception if device has poor internet connection or unstable connection.

`[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The network connection was lost., null, null)
`

Error arises at  better_player_controller.dart under "await videoPlayerController?.setNetworkDataSource" line 362. 

BetterPlayerEventType.exception event listener is called, but because the event is not handled, the entire app crashes. The only workaround I have found is by reloading the entire app within the event handler. Strangely, if you simply kill the connection entirely while the video is playing, the error is handled properly and the entire app does not crash. 

**To Reproduce**
Example project with network data source. I am using url 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' from constants

I'm testing on a very slow connection (<256kbps.) 

**Flutter doctor**
[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on macOS 11.2.2 20D80 darwin-arm,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
[✓] Connected device (1 available)
**Better Player version**
- Version: 0.0.61

**Smartphone (please complete the following information):**
-iPhone 12 Pro Max Simulator
-iOS 14.4

**Comment by jhomlala** [comment]
You're not using stable channel. I'm not working on this channel so probably that's the issue. Try running your code on stable flutter and let me know.

**Comment by schisms** [comment]
Looks like you may be right. On stable, the exception is thrown where I set the data source in my code itself, but it doesn't crash the entire application like above (I think  unhandled exceptions on ui_dart_state.cc crash entire app, somebody please correct me because I have been using flutter for less than a month.)

The "problem" is that the stable branch is not stable on m1 Macs. But that's not your problem, your plugin is great.

Closing this.
