### ISSUE TITLE
Video can not show after call setupDataSource

### ISSUE THREAD

**Issue by Invincible1996** [jhomlala/betterplayer#363]
**Describe the bug**
Video can not show after call setupDataSource.

**To Reproduce**
1. first start app play video has problem
2. Click on  set data
3. video cannot show

**Example code*
```
class VideoPlayer extends StatefulWidget {
  @override
  _VideoPlayerState createState() => _VideoPlayerState();
}

class _VideoPlayerState extends State<VideoPlayer> {
  BetterPlayerController _betterPlayerController;
  BetterPlayerDataSource betterPlayerDataSource;
  List dataSourceList = List<BetterPlayerDataSource>();
  List<VideoModel> videoList = [];

  int _currentIndex = 0;

  @override
  initState() {
    super.initState();
    Future.delayed(Duration.zero, () async {
      betterPlayerDataSource = BetterPlayerDataSource(BetterPlayerDataSourceType.network,
          'http://cdn.theoplayer.com/video/elephants-dream/playlist.m3u8');
      _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(
          autoPlay: true,
          controlsConfiguration: BetterPlayerControlsConfiguration(
            enableMute: false,
            enablePlaybackSpeed: false,
            enableProgressText: true,
            enableSkips: false,
          ),
        ),
        betterPlayerDataSource: betterPlayerDataSource,
      );
      _betterPlayerController.seekTo(Duration(seconds: 14));
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
      child: Column(
        children: [
         _betterPlayerController !=null
              ? AspectRatio(
                  aspectRatio: 16 / 9,
                  child: BetterPlayer(
                    controller: _betterPlayerController,
                  ),
                )
              : CircularProgressIndicator(),
          RaisedButton(onPressed: (){
            _betterPlayerController.setupDataSource(
                BetterPlayerDataSource(
                  BetterPlayerDataSourceType.network,
                  'http://cdn.theoplayer.com/video/elephants-dream/playlist.m3u8',
                ));
          },child: Text('set data'),)
        ],
      ),
    ));
  }
```

**Expected behavior**
Viedo can play normal.

**Better Player version**
- Version: 0.0.61

**Comment by iShi0n** [comment]
I have the same problem, the player continues with the black screen after changing the quality, but the audio keeps playing.

I am not using HLS.

In version 0.0.50 it worked normally

**Comment by nicejhkim** [comment]
I have the same issue too, it happens from version 0.0.60.

**Comment by jhomlala** [comment]
Fixed in 0.0.62.

**Comment by saviourdog** [comment]
here is my code,Looking forward to your reply

`class VideoBox extends StatefulWidget {
  const VideoBox();
  @override
  _VideoBoxState createState() => _VideoBoxState();
}

class _VideoBoxState extends State<VideoBox> {
  BetterPlayerController videoCon;
  File tmpVideo;
  var i = 0;

  @override
  void initState() {
    super.initState();
    pickVideo();
  }

  @override
  void dispose() {
    // tmpVideo?.delete();
    videoCon?.dispose();
    super.dispose();
  }

  pickVideo() async {
    FilePickerResult result = await FilePicker.platform.pickFiles(
        // allowMultiple: true,
        type: FileType.any
        // allowCompression: true,
        );
    if (result != null) {
      var file = result.files.first;
      print(file.name);
      print(file.bytes);
      print(file.size);
      print(file.extension);
      print(file.path);
      if (file.size > 104857600) {
        showToast('请不要上传大于100M的文件!');
      }
      showLoading();
      var path = file.path;
      if (Platform.isIOS) {
        final doc = await getApplicationDocumentsDirectory();
        var dir = Directory(doc.path + '/tmp');
        if (!dir.existsSync()) {
          dir.createSync();
        }
        tmpVideo = await File(file.path).copy(
            dir.path + '/tmpVideo' + (i++).toString() + getSuffix(file.path));
        FilePicker.platform.clearTemporaryFiles();
        path = tmpVideo.path;
      }
      if (videoCon == null) {
        videoCon = bpCon(path);
      } else {
        await videoCon.setupDataSource(BetterPlayerDataSource(
          BetterPlayerDataSourceType.file,
          path,
        ));
      }
      setState(() {});
      print('video.path   $path   ');
      hideLoading();
      // routeTo('upload_material', args: result.paths);
      // result.paths.forEach((a) {
      //   upload(a);
      // });
    } else {
      showToast('无文件~');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.end,
      children: [
        AspectRatio(
            aspectRatio: 1.8,
            child: Stack(
              children: [
                videoCon != null
                    ? BetterPlayer(
                        controller: videoCon,
                      )
                    : Container(
                        color: Colors.black,
                      ),
                Positioned(
                    left: 20,
                    bottom: 15,
                    child: MyButton('选择视频', pickVideo,
                        color: Colors.red,
                        style: TextStyle(fontSize: 10, color: Colors.white),
                        padding:
                            EdgeInsets.symmetric(horizontal: 12, vertical: 3)))
              ],
            )),
      ],
    );
  }
}
`



`bpCon(String url, {cache}) => BetterPlayerController(
    BetterPlayerConfiguration(
      placeholder: Center(
        child: loading,
      ),
      showPlaceholderUntilPlay: false,
      looping: true,
      fit: BoxFit.cover,
      controlsConfiguration: BetterPlayerControlsConfiguration(
        showControlsOnInitialize: false,
        customControlsBuilder: (con) => Stack(
          children: [
            Positioned(right: 10, bottom: 10, child: PlayBtn(con)),
          ],
        ),
        playerTheme: BetterPlayerTheme.custom,
      ),
    ),
    betterPlayerDataSource: url.startsWith('http')
        ? BetterPlayerDataSource(BetterPlayerDataSourceType.network, url,
            cacheConfiguration: BetterPlayerCacheConfiguration(useCache: cache??true))
        : BetterPlayerDataSource(
            BetterPlayerDataSourceType.file,
            url,
          ));`

**Comment by jhomlala** [comment]
@saviourdog Just create new issue and fill issue template. Any screenshots/video will be appreciated.
