### ISSUE TITLE
Video Area Gestures

### ISSUE THREAD

**Issue by jtkeyva** [jhomlala/betterplayer#364]
**Is your feature request related to a problem? Please describe.**
I'd like to run a function when the video is tapped, held, swiped and but GesterDetector or Inkwell don't "override". If I double tap the video it pauses it.
**Describe the solution you'd like**
A way to control what happens when video is interacted with
**Describe alternatives you've considered**
Wrapping in gesturedetector or inkwell...but no luck
**Additional context**

**Comment by jhomlala** [comment]
Please at least try formatting your request. It's unreadable. Right now I have no plans to expose any GestureDetector. But you may achieve your requested feature by using custom theme on player. Here is an example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/custom_controls/custom_controls_widget.dart

**Comment by jtkeyva** [comment]
Will do. Thank you for the info, I'll give it a try :)
