### ISSUE TITLE
Issue With Setting Custom Aspect Ratio

### ISSUE THREAD

**Issue by JosephIbe** [jhomlala/betterplayer#365]
**Describe the bug**
I am trying to scale the video player to work seamlessly according to a height I specify (with media query) and the full device width, without much luck.

**Example code*
`return Scaffold(
  body: AspectRatio(
    aspectRatio: 4.5/3,
    // aspectRatio: width / height * 0.35,
    child: BetterPlayer(
      key: _playerKey,
      controller: _controller,
    ),
  )
);`

I have skipped the initialization part of MQ like `width = MediaQuery.of(context).size.width;
    height = MediaQuery.of(context).size.height;` for brevity.

**Expected behavior**
I expected that the player will resize on smaller devices to take up the full width and 35% of the height but unfortunately I ran into this error:
`The method '/' was called on null.
Receiver: null
Tried calling: /(null)` 

This happens when I'm trying to calculate the new device aspect ration using `MQ.width/MQ.height`

**Flutter doctor**
Flutter doctor found no issues.

**Better Player version**
- Version: 0.0.52

**Smartphone (please complete the following information):**
 - Device: Samsung, Tecno, Infinix
 - OS: Android OS

**Additional context**
Is there a way to get the player size from the device dimensions? This would be great and better than using static or conjectured dimens.

**Comment by jhomlala** [comment]
Please provide complete reproducible example code. Also check latest version 0.0.61.

**Comment by JosephIbe** [comment]
Hello, thanks for your timely response. Unfortunately I am viewing from a mobile device now. Have attached the link to the SO question I asked. It contains the full code sample.

https://stackoverflow.com/questions/66437546/flutter-responsive-aspect-ratio-with-mediaquery/66437923?noredirect=1#comment117454020_66437923

Please bear with me. Thanks 👍

**Comment by JosephIbe** [comment]
Will upgrade to the newest version once I'm back to my workstation

**Comment by jhomlala** [comment]
This is not Better Player issue. You're trying to access width and height in initState but you're filling it in build method.  Please check stateful widget lifecycle. You should use some future that inits better player controller once you have access context and then updates UI.
