### ISSUE TITLE
[BUG] Follow-up #354

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#368]
0.0.61 fixed #354, thank you. However, when I exit fullscreen, I get the following error:

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A BetterPlayerController was used after being disposed.

Once you have called dispose() on a BetterPlayerController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:178:12)
#3      _BetterPlayerWithControlsState.dispose (package:better_player/src/core/better_player_with_controls.dart:60:23)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
**My Widget above**
In my Widget, I tried removing _controller.dispose(); so autoDispose is set to true, but it didn't help. Then I tried replacing serviceLocator<NavigationService>().pop(); with this:

WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
  serviceLocator<NavigationService>().pop();
});
But the error still arrises about 40% of the time. Any idea how to fix it?

**Comment by jhomlala** [comment]
Please re test with 0.0.62.

**Comment by themadmrj** [comment]
> Please re test with 0.0.62.

There are still a lot a packages that my project depends on which did not migrate to null safety yet. Therefore it'll sadly take some time before I can try the 0.0.62 update :(

**Comment by jhomlala** [comment]
If you'll encounter any issue connected with issue #354, feel free to answer in this topic and I'll reopen it.

**Comment by ventr1x** [comment]
This issues happens 100% of the time when disposing the player while it is still in full screen or e.g. trying to change screens right after exit full screen event.

autoDispose causes this internally same as any manual dispose with or without force.

This has nothing to do with #354 , this is the same error on exit, not on auto start/ENTER fullscreen.

Without looking into the code this simply looks like amateur internal state management. Either an ongoing, not disposed, animation is causing this other calculations, like orientation change AFTER (auto) dispose.
Nothing any user can do but setting a random timer around any action.
Horribly unstable to use right now!

**Comment by omidraha** [comment]
I have the same issue,
The `Fullscreen` mode rebuild all parents.
I don't have any issue when using `chewie`.


```
setState() or markNeedsBuild() called when widget tree was locked.

Unhandled Exception: Bad state: Cannot add new events after calling close

VideoPlayerController was used after being disposed
```

**Comment by jhomlala** [comment]
> @jhomlala
> This issues happens 100% of the time when disposing the player while it is still in full screen or e.g. trying to change screens right after exit full screen event.
> 
> autoDispose causes this internally same as any manual dispose with or without force.
> 
> This has nothing to do with #354 , this is the same error on exit, not on auto start/ENTER fullscreen.
> 
> Without looking into the code this simply looks like amateur internal state management. Either an ongoing, not disposed, animation is causing this or other calculations, like orientation change AFTER (auto) dispose.
> Nothing any user can do but setting a random timer around any action (about 500ms mitigates this issue 95% of the time, still not feasible for any production use).
> 
> There are other major issues with full screen I've seen after barely 10 minutes of the most basic testing.
> Example: If you have two videos on screen, Start one in full screen, Exit the full screen, Start the 2nd video => the first video will go back into full screen and play even though not being touched or triggered.
> 
> Horribly unstable to use right now!

Thank you for your opinion. This plugin is open source - you can always help with your PR! Seems like you are expert and have already reviewed state management of Better Player and other stuff, so you may help with solving these issues. This will be appreciated.
Anyway I'll check it in on my side in my spare time.

**Comment by jhomlala** [comment]
> I have the same issue,
> The `Fullscreen` mode rebuild all parents.
> And also raise many `state` errors.
> I don't have any issue when using `chewie`.
> 
> ```
> setState() or markNeedsBuild() called when widget tree was locked.
> 
> Unhandled Exception: Bad state: Cannot add new events after calling close
> 
> VideoPlayerController was used after being disposed
> ```

Can you create issue for that problem? Please fill issue template and I'll look into it.

**Comment by themadmrj** [comment]
@ventr1x while I agree on the fact that state management still needs some work, this package is still the most complete flutter video playing library out there. Instead of just wildly criticizing and indirectly claiming you're the boss, you could also act like it and play the same game the whole world is playing: Flutter is based on open source development so don't be lazy, fill out the template to report a bug and submit a PR?

**Comment by ventr1x** [comment]
I stumpled across at least 3 major (for my current app) bugs last night.
I will look into it, but demanding sample apps is a big time sink when a plugin itself does not offer a running modifiable example.

If I have the time I will help, especially when I see that PR are actually actively managed. Most repos ignore them for months.

I can also offer financial help if that motivates and can help out. While I still think that should be googles job.

**Comment by jhomlala** [comment]
@ventr1x The biggest motivation for me is good filled issue ticket with screenshots or video. I don't need any financial help. If you encounter 3 major bugs, then simply report it here in this repo. You don't even need to use google.

**Comment by MinseokKang003** [comment]
@omidraha In my case , it was the ScreenUtil causing the issue. I wrapped the entire app with ScreenUtilInit, and every orientation change, including fullscreen mode caused the entire widget tree to get rebuilt. But I'm not sure why you didn't have any issues when using chewie.
