### ISSUE TITLE
[BUG] better_player >=0.0.62 version solving failed.

### ISSUE THREAD

**Issue by peterbyCom** [jhomlala/betterplayer#374]
Hello sir. The following problems occurred after the upgrade

Dart version : 3.20.1

Running "flutter pub get" in study...
The current Dart SDK version is 2.12.0-29.10.beta.

Because study depends on better_player >=0.0.62 which requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because study depends on better_player >=0.0.62 which requires SDK version >=2.12.0 <3.0.0, version solving failed.)
Exited (1)

**Comment by jhomlala** [comment]
You should use stable flutter.

**Comment by peterbyCom** [comment]
flutter channel stable
flutter upgrade
flutter pub get

I tried to switch from dev channel to stable. After doing so, it still doesn't work.
