### ISSUE TITLE
[BUG]better_player and cached_network_image plugins are not compatible

### ISSUE THREAD

**Issue by peterbyCom** [jhomlala/betterplayer#375]
There seems to be a problem between the two.

[study] flutter pub get
Running "flutter pub get" in study...                           
Because better_player >=0.0.62 depends on path_provider ^2.0.1 and flutter_cache_manager >=2.0.0-beta <3.0.0-nullsafety.0 depends on path_provider ^1.6.18, better_player >=0.0.62 is incompatible with flutter_cache_manager >=2.0.0-beta <3.0.0-nullsafety.0.

And because cached_network_image 2.5.0 depends on flutter_cache_manager ^2.1.0 and no versions of cached_network_image match >2.5.0 <3.0.0, better_player >=0.0.62 is incompatible with cached_network_image ^2.5.0.

So, because study depends on both cached_network_image ^2.5.0 and better_player ^0.0.62, version solving failed.
pub get failed (1; So, because study depends on both cached_network_image ^2.5.0 and better_player ^0.0.62, version solving failed.)
exit code 1

**Comment by peterbyCom** [comment]
[study] flutter pub get
Running "flutter pub get" in study...                           
Because no versions of cached_network_image match >2.5.0 <3.0.0 and cached_network_image 2.5.0 depends on flutter_cache_manager ^2.1.0, cached_network_image ^2.5.0 requires flutter_cache_manager ^2.1.0.

And because flutter_cache_manager >=2.0.0-beta <3.0.0-nullsafety.0 depends on path_provider ^1.6.18, cached_network_image ^2.5.0 requires path_provider ^1.6.18.

So, because study depends on both cached_network_image ^2.5.0 and path_provider ^2.0.1, version solving failed.
pub get failed (1; So, because study depends on both cached_network_image ^2.5.0 and path_provider ^2.0.1, version solving failed.)
exit code 1


It seems that the version of flutter_cache_manager is not compatible. Is there any solution?

**Comment by peterbyCom** [comment]
https://github.com/jhomlala/betterplayer/issues/363

Because of this problem, I upgraded to 0.0.62, which subsequently caused the above compatibility problem.

**Comment by ohm1998** [comment]
Same issue I am having. Any work around?

**Comment by ohm1998** [comment]
@jhomlala the dependency override worked for me. Thank you!
