### ISSUE TITLE
[FEATURE] Fullscreen Stack for Custom Video Overlays

### ISSUE THREAD

**Issue by t-kietzmann** [jhomlala/betterplayer#379]
**Is your feature request related to a problem? Please describe.**

I'm working with custom video overlays (like YouTube etc.) for showing information during the video. This works fine when the player is not in fullscreen with a simple Stack-Widget. If the player is in full screen mode, this solution doesn't work

**Describe the solution you'd like**
I would be happy when this would also work in full screen mode.

**Comment by jhomlala** [comment]
You need to use routePageBuilder from BetterPlayerConfiguration to setup custom widgets over Better Player in fullscreen mode.

**Comment by jhomlala** [comment]
I believe this issue is solved now. Closed due to no answer.
