### ISSUE TITLE
[FEATURE] Provide access to cached video file from network once the entire file has been cached

### ISSUE THREAD

**Issue by ashishbeck** [jhomlala/betterplayer#380]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Once the caching has been done, the controller will have a method that can be used to access the cached file. If the caching is incomplete, return null (or progress).

**Describe alternatives you've considered**
The BetterPlayerController does not currently have any method to access the cached file.

**Comment by schisms** [comment]
I would like to have something like this. In fact, I'm having a lot of trouble finding the actual cache file itself, at least on iOS Simulator (iPhone 12 Pro Max, iOS 14.4.) I even deleted the app, reinstalled it, went to the app directory, got the folder size of the appdir in Finder, loaded the video and played it though, then checked the folder size of the apps directory. No change. I know it's caching on Android as it will play offline.

**Comment by jhomlala** [comment]
This solution won't work Android. Exoplayer saves file in chunks in different format than original video: https://github.com/google/ExoPlayer/issues/7417#issuecomment-640472954

Android path for cache is: /data/user/0/com.jhomlala.better_player_example/cache/betterPlayerCache
iOS path for cache is: /Users/jhomlala/Library/Developer/CoreSimulator/Devices/76410080-04F6-48B3-BCE1-54B819BA01DB/data/Containers/Data/Application/C683CECA-03B9-4389-912C-416F30EFF185/Documents/KTVHTTPCache/868b58acff54b7b284ced6a5d449a250/868b58acff54b7b284ced6a5d449a250.mp4
