### ISSUE TITLE
[BUG] Throwing an error the data source has not been initialized

### ISSUE THREAD

**Issue by naamapps** [jhomlala/betterplayer#382]
**History check**
Checked

**Describe the bug**
After you fixed #342 in version 0.60, in the latest update (0.62) you added an exception - "data source has not been initialized" when pausing.
So when disposing, it throws an error (even when it's surrounded with try-catch).
```
E/flutter ( 2952): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: The data source has not been initialized
E/flutter ( 2952): #0      BetterPlayerController.pause (package:better_player/src/core/better_player_controller.dart:537:7)
E/flutter ( 2952): #1      BetterPlayerController.dispose (package:better_player/src/core/better_player_controller.dart:1069:7)
```

**To Reproduce**
1. Init the better player controller without BetterPlayerDataSource.
2. Dispose the better player controller.
3. See error

**Expected behavior**
The controller disposes without throwing an error.

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2 20D64 darwin-x64, locale
    en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.2)
[✓] Connected device (2 available)

• No issues found!

**Better Player version**
- Version: 0.0.62

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy note20 ultra]
 - OS: [e.g. Android 11]

**Comment by jhomlala** [comment]
Fixed in 0.0.63.
