### ISSUE TITLE
Hi can you please help me create a page like tik tok or instagram reels or feed page?

### ISSUE THREAD

**Issue by marc-walton** [jhomlala/betterplayer#386]
i have two pages under a tabbar with two tabs for videos and live streaming. Im not able to understand the controllers or device orientation as I'm getting an error stating **''The name 'DeviceOrientation' isn't a type so it can't be used as a type argument''.**
not just that ,a portrait video is being shrunk to fit the player.
An example code for creating feed type page or tiktok kind will be helpful.
Sorry i don't understand the example codes and also I can't find an example for listvideoplayer.
Please help I'm still learning to code.
I've also started a discussion.If you feel thsi shouldn't be here

**Comment by jhomlala** [comment]
There are many clones of Tik Tok for example: https://github.com/salvadordeveloper/TikTok-Flutter. Simply replace video_player with Better Player.

Examples presented here https://github.com/jhomlala/betterplayer/tree/master/example/lib are the best way to understand features of Better Player. Device Orientation simply determines which orientations are supported in app (for example you can configure portrait only app). Check Device Orientation description here: https://api.flutter.dev/flutter/services/DeviceOrientation-class.html
