### ISSUE TITLE
[BUG] Default video controls dissapear right after user taps on the screen

### ISSUE THREAD

**Issue by zilvinas-t** [jhomlala/betterplayer#388]
**History check**
Tried to update the version, but the error still occurs.

**Describe the bug**
When user taps on the screen the video controls should appear and stay there until user taps on the screen again. The issue is that when user taps on the screen the video controls appear for like 0.1 second and dissapears again. It's impossible to interact with the controls (pause, mute, open quality, subtitle etc.). It didn't occur in the past, I don't get what happened. Thanks in advance :)

**To Reproduce**
1. Launch the video
2. Tap on the screen
3. The controls dissapears right after the tap

**Expected behavior**
Controlls should stay for a while or until user taps on the screen again.

**Better Player version**
- Version: 0.0.61

**Smartphone (please complete the following information):**
 - Device: Multiple devices

**Comment by jhomlala** [comment]
@zilvinas-t Version 0.0.62 has fix for this issue.
