### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Michael24884** [jhomlala/betterplayer#390]
**History check**
I sure did

**Describe the bug**
Using custom player theme the controls do not auto fade out. I don't know if this is intentional or not. For other themes it works properly.

**To Reproduce**
1. Set playerTheme to: PlayerTheme.custom
2. Add a controlsHideTime to controls configuration 

**Expected behavior**
Expected the custom controls to fade away using the controlsHideTimer function

**Better Player version**
- Version: 0.0.62

**Smartphone (please complete the following information):**
 - Device: Both Platforms

**Comment by jhomlala** [comment]
@Michael24884 This is intentional. Custom theme is theme which is managed by developer itself. controlsHideTimer and other parameters from controls configuration are used for material and cupertino themes.
