### ISSUE TITLE
[BUG] Doesn't play this url ?

### ISSUE THREAD

**Issue by lavara123** [jhomlala/betterplayer#391]
**Describe the bug**
does not play this urls
Example video URL return function::
```dart
import 'dart:convert';
import 'dart:io';

void getUrls() async {
  try {
    var url = 'https://jetfilmizle.live/96-saat-turkce-dublaj-izle.html/2';
    var headers = {
      'Referer': 'https://jetfilmizle.live/',
      'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0'
    };
    var _httpClient = HttpClient();
    final request = await _httpClient.getUrl(Uri.parse(url));
    headers.forEach((name, value) => request.headers.add(name, value));

    final response = await request.close();
    var data = '';
    await response.transform(const Utf8Decoder()).listen((contents) {
      data += contents.toString();
    }).asFuture<String>();

    headers = {
      'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0',
      'Accept': 'application/json, text/javascript, */*; q=0.01',
      'Accept-Language': 'tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3',
      'Connection': 'keep-alive',
      'Referer': 'https://jetfilmizle.live/',
      'X-Requested-With': 'XMLHttpRequest'
    };

    final req = await _httpClient.getUrl(Uri.parse(RegExp(
      r"iframe src='(.*?)'",
    ).firstMatch(data).group(1)));
    headers.forEach((name, value) => req.headers.add(name, value));

    final res = await req.close();
    data = '';
    await res.transform(const Utf8Decoder()).listen((contents) {
      data += contents.toString();
    }).asFuture<String>();

    var match = RegExp(
      r'"file":"([^"]+)"',
    ).allMatches(data);
    for (var item in match) {
      print(item.group(1).replaceAll('\\', '') + '\n');
    }
  } catch (exception) {
    print('Failed: $exception');
    return null;
  }
}
```

**To Reproduce**
```dart
BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "https://s058.jetfilmvid.com/videoplayback?NDVBZHIxYkNxSkFGMEhFMFJYREFiT3hVZEVkQUFvNmUrR3p5eGc1L1VaeDNZNnpNb1FSSjd1OVpzRjJuUUd1cTo6V%2FCwHKDB7r2mwVEc7Bq4FQ%3D%3D",
);
```

**URL Video Type:**
```
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 04:02:08.02, start: 0.000000, bitrate: 1130 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 995 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 131 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```
You can test the url is working here
https://demo.theoplayer.com/test-your-stream-with-statistics
( If the link does not work in the test player, let me change it. )

**Better Player version**
- ^0.0.62

**Comment by jhomlala** [comment]
This link doesn't work @lavara123.

**Comment by lavara123** [comment]
> This link doesn't work @lavara123.

i update the url, https://s038.jetfilmvid.com/videoplayback?K2ZIdkZ6NEFaV0NwUjJ0dlNiY1p2NWVlY25XVWtoVk9icFJPQzZwS2cxSEQ1aEs3dE1uYXlUVW80WUhwT2JYUjo6r%2BTqrxkaUUtrUromydVAKw%3D%3D

**Comment by jhomlala** [comment]
Still doesn't work. ExoPlayer returns 403 error, Theo player doesn't play this URL.

**Comment by lavara123** [comment]
> Still doesn't work. ExoPlayer returns 403 error, Theo player doesn't play this URL.

i update url:
https://s053.jetfilmvid.com/videoplayback?Ukw1VWdOdWlyOFRRdURzYm81cGw2QTJUdjhGZGtiTnljUU5pSlpDV05mYitFek1nbWRia3gwWDVXcWFSYjB1Tjo6klBtiDEW4U1XGEL7QSJpSA%3D%3D

**Comment by lavara123** [comment]
> Same problem again @lavara123. Can you prepare link which wont expire quickly?

I added a function that returns a URL
https://github.com/jhomlala/betterplayer/issues/391#issue-836798576

**Comment by jhomlala** [comment]
@lavara123 This code isn't null safety. Please provide code which compiles with latest stable flutter version.

**Comment by lavara123** [comment]
> @lavara123 This code isn't null safety. Please provide code which compiles with latest stable flutter version.

Compile with C ++ without any problems?
`dart test.dart`

**Comment by lavara123** [comment]
> @lavara123 This code isn't null safety. Please provide code which compiles with latest stable flutter version.

i edited. 
in that:
![1](https://user-images.githubusercontent.com/12005386/115151576-01f26e80-a05d-11eb-8220-91fab784306d.png)
![2](https://user-images.githubusercontent.com/12005386/115151581-0585f580-a05d-11eb-9946-0afe79598bd3.png)
![Ekran görüntüsü_2021-04-18_18-43-58](https://user-images.githubusercontent.com/12005386/115151583-0880e600-a05d-11eb-9d65-54bb5c98cfa0.png)

**Comment by lavara123** [comment]
@jhomlala have you tried ?

**Comment by jhomlala** [comment]
@lavara123 Please keep using _normal_ sources for videos in your app. This seems like data scrapped video from not your owned site. 

ExoPlayer is working fine but this data source is custom one which is served with some PHP code. To access your video you need to pass this header:

```dart
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "https://s004.jetfilmvid.com/videoplayback?allkcjhlRVpZaFhKUDVobkVrbnR2elJFWUJMWjhwdkZkNVZuMzgvVzNrVUxwaGZ3NGZSNnMxZm5vQXU3THpDYTo6B%2BqRfKnPsrT6mtKCZFRgGg%3D%3D",
        headers: {"range": "bytes=0-"}));
```

I don't know why this data source requires that header.

**Comment by lavara123** [comment]
> @lavara123 Please keep using _normal_ sources for videos in your app. This seems like data scrapped video from not your owned site.
> 
> ExoPlayer is working fine but this data source is custom one which is served with some PHP code. To access your video you need to pass this header:
> 
> ```dart
>     _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
>     _betterPlayerController.setupDataSource(BetterPlayerDataSource(
>         BetterPlayerDataSourceType.network,
>         "https://s004.jetfilmvid.com/videoplayback?allkcjhlRVpZaFhKUDVobkVrbnR2elJFWUJMWjhwdkZkNVZuMzgvVzNrVUxwaGZ3NGZSNnMxZm5vQXU3THpDYTo6B%2BqRfKnPsrT6mtKCZFRgGg%3D%3D",
>         headers: {
>           "range": "bytes=0-",
>         }));
> ```
> 
> I don't know why this data source requires that header.
> 
> I don't accept using videos which you don't have rights to.
To test the site. 

Thanks I will try this 👍
