### ISSUE TITLE
How do I pass a dynamic header with every ts pieces

### ISSUE THREAD

**Issue by chenyifan88** [jhomlala/betterplayer#392]
How do I pass a dynamic header with every ts pieces，oh my god！！

**Comment by jhomlala** [comment]
Can you please fill issue ticket properly? Follow issue template.

**Comment by chenyifan88** [comment]
To defend video stoler, the m3u8 and every ts files request need add a custom header.
for example:
when I play a video(hls), the httprequest of ts file, i want put "refer" and "x-jsl-api-auth" two key in headers, and the value is calculated on realtime.

**Comment by jhomlala** [comment]
You keep ignoring my request for using template. With BetterPlayer you can only pass headers once you're requesting video to run. To secure your videos you should look into DRM's like Widevine etc.
