### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ankittiwarielsner** [jhomlala/betterplayer#394]
Its not working in  ios real device, showing **module better_player not found**
![Screenshot 2021-03-22 at 4 18 08 PM](https://user-images.githubusercontent.com/69836949/111978785-553ed300-8b2a-11eb-93b4-9cd482b5fe6f.png)

**Comment by jhomlala** [comment]
Please follow issue template next time. This is not better_player rather than problem with pods: https://github.com/flutter/flutter/issues/53573 You should remove podfile and try to run app again.
