### ISSUE TITLE
[BUG - REGRESSION] fit: BoxFit.cover makes widget overlap parent size

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#395]
**History check**
Confirmed.

**Describe the bug**
New bug since v0.0.62. Was working fine in v0.0.61.
I need to use `BoxFit.cover` to fit my video in a specific container size. However since v0.0.62 using `BoxFit.cover` makes the video bigger than the parent size. The video size is fine when I remove `BoxFit.cover`, but then the video is distorted.

**To Reproduce**
Play a video with `BoxFit.cover`.
I use a container size of w400*h300. The test videos all have phone resolution (height > width), typically 1920*1080.

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Screenshots**
[
![Untitled](https://user-images.githubusercontent.com/11475495/112216489-d927b680-8c21-11eb-9141-9ce5f34e2a6a.png)
](url)

**Flutter doctor**
[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.19041.867], locale fr-FR)
    • Flutter version 2.1.0-12.1.pre at E:\Flutter
    • Framework revision 8264cb3e8a (13 days ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MrJ\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 (mobile)            • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!

**Better Player version**
- Version: v0.0.63

**Smartphone (please complete the following information):**
 - Device: android studio emulator (api 30)

**Comment by jhomlala** [comment]
Seems like you're on dev channel. Can you check it on stable?

**Comment by themadmrj** [comment]
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale fr-FR)
    • Flutter version 2.0.3 at E:\Flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MrJ\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 (mobile)            • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!



Sadly same problem :(

**Comment by themadmrj** [comment]
Fix sent as PR.

**Comment by jhomlala** [comment]
Fix for this will be released with next version.

**Comment by jhomlala** [comment]
Fixed in 0.0.64.
