### ISSUE TITLE
[FEATURE] Preload videos

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#396]
**Is your feature request related to a problem? Please describe.**
My project needs video preloading, so that it plays immediately from the portion of the video that was cached previously. As I have already implemented this in the past, I propose to write a PR for this feature on Android (I don't know how on iOS).
Since the library already uses ExoPlayer caching, I can just add a simple method like `preCache(DataSource, {preCacheSize})` and write the precache natively.

**Describe the solution you'd like**
I'll submit a PR. It would be awesome if someone could do the same for iOS.

**Comment by jhomlala** [comment]
Requested changes in PR.

**Comment by jhomlala** [comment]
Added in 0.0.64. Thanks @themadmrj.
