### ISSUE TITLE
[BUG] Can't install 

### ISSUE THREAD

**Issue by CharuwanNoi** [jhomlala/betterplayer#399]
better_player: ^0.0.63 not working in Flutter 2.0.3

```Running "flutter pub get" in socialproject...                      
Because shared_preferences_windows <0.0.3-nullsafety depends on path_provider_windows ^0.0.2 and shared_preferences_windows >=0.0.3-nullsafety <2.0.0 depends on shared_preferences_platform_interface ^2.0.0-nullsafety, shared_preferences_windows <2.0.0 requires path_provider_windows ^0.0.2 or shared_preferences_platform_interface ^2.0.0-nullsafety.

And because shared_preferences 0.5.12+4 depends on shared_preferences_platform_interface ^1.0.0, if shared_preferences_windows <2.0.0 and shared_preferences 0.5.12+4 then path_provider_windows ^0.0.2.

And because shared_preferences 0.5.12+4 depends on shared_preferences_windows ^0.0.1 and no versions of shared_preferences match >0.5.12+4 <0.6.0, shared_preferences ^0.5.12+4 requires path_provider_windows ^0.0.2.

And because better_player >=0.0.62 depends on path_provider ^2.0.1 which depends on path_provider_windows ^2.0.0, shared_preferences ^0.5.12+4 is incompatible with better_player >=0.0.62.

So, because socialproject depends on both shared_preferences ^0.5.12+4 and better_player ^0.0.62, version solving failed.
pub get failed (1; So, because socialproject depends on both shared_preferences ^0.5.12+4 and better_player ^0.0.62, version solving failed.)
exit code 1
```

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-TH)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)
    ! Error: Charuwan’s iPhone is busy: Copying cache files from device. Xcode will continue when Charuwan’s iPhone is finished. (code -10)

! Doctor found issues in 1 category.

**Better Player version**
- Version: ^0.0.63

**Comment by jhomlala** [comment]
What's your `shared_preferences` version  in pubspec.yaml?

**Comment by CharuwanNoi** [comment]
@jhomlala  shared_preferences: ^0.5.12+4

**Comment by CharuwanNoi** [comment]
@jhomlala I change shared_preferences version to current(shared_preferences: ^2.0.5) then better_player: ^0.0.63 it' work. thank you

**Comment by dc480506** [comment]
@jhomlala what is the minimum major version of shared_preferences required for this because when I tried to use current version of  shared_preferences, my whole application is breaking. Please tell me the minimum major version required for shared_preferences
