### ISSUE TITLE
When there is no internet or internet connection fluctuates - app crashes

### ISSUE THREAD

**Issue by ssbaval** [jhomlala/betterplayer#40]
Hi - on the surface this is a great plugin but has major flaws with respect to handling offline mode - The plugin doesnt fully support when the device is offline or transitions between on-offline-on etc : 

**Issue 1**

Add the plugin and open a screen which auto plays the video. Assuming that the device is online, the video plays. Now quickly turn your device to offline. After a while (depends on how much is buffered) - you will see the circular progress bar. Now close the view and then go back in. the app will crash.

This is on iOS.

**Issue 2**

When there is no internet and we try and load betterPlayer - we see a message : 

'Video Cannot be Played'

After a while we get a crash : 

```
PlatformException(VideoError, Failed to load video: The Internet connection appears to be offline., null)
flutter: Error caught by Crashlytics plugin <recordError>:
flutter: RangeError (index): Invalid value: Only valid value is 0: 1

```

It makes no difference if we define an ErrorBuilder - nothing is shown with code in our ErrorBuilder.

We tried this on iOS.

**Comment by leszekkrol** [comment]
I got the same error, please fix this

**Comment by jhomlala** [comment]
Can you provide sample code? It can be as simple as possible.
Also please check again with latest release.

**Comment by jhomlala** [comment]
No response from the author. Closing issue. Please re-open new issue if problem still occurs.
