### ISSUE TITLE
 Alloc concurrent copying GC freed 53(5KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 799us total 68.546ms

### ISSUE THREAD

**Issue by getpu** [jhomlala/betterplayer#402]
Waiting for a blocking GC Alloc
E/AndroidRuntime( 5169): FATAL EXCEPTION: Loader:ProgressiveMediaPeriod
E/AndroidRuntime( 5169): Process: com.example.job, PID: 5169
E/AndroidRuntime( 5169): java.lang.OutOfMemoryError: Failed to allocate a 5768 byte allocation with 448 free bytes and 448B until OOM, max allowed footprint 402653184, growth limit 402653184
E/AndroidRuntime( 5169): 	at java.util.Arrays.copyOf(Arrays.java:3260)
E/AndroidRuntime( 5169): 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
E/AndroidRuntime( 5169): 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:605)
E/AndroidRuntime( 5169): 	at java.lang.StringBuffer.append(StringBuffer.java:367)
E/AndroidRuntime( 5169): 	at java.io.StringWriter.write(StringWriter.java:94)
E/AndroidRuntime( 5169): 	at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:380)
E/AndroidRuntime( 5169): 	at com.android.internal.util.FastPrintWriter.flush(FastPrintWriter.java:410)
E/AndroidRuntime( 5169): 	at android.util.Log.getStackTraceString(Log.java:374)
E/AndroidRuntime( 5169): 	at com.google.android.exoplayer2.util.Log.getThrowableString(Log.java:168)
E/AndroidRuntime( 5169): 	at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java:174)
E/AndroidRuntime( 5169): 	at com.google.android.exoplayer2.util.Log.e(Log.java:138)
E/AndroidRuntime( 5169): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:442)
E/AndroidRuntime( 5169): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime( 5169): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime( 5169): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 5169): 	at java.lang.Thread.run(Thread.java:784)

in example videoListPage, I only changed setupData。

for (int index = 0; index < 50; index++) {
      var randomVideoUrl = _videos[_random.nextInt(_videos.length)];
      dataList.add(VideoListData("Video $index", randomVideoUrl));
}

how to use repair...

**Comment by jhomlala** [comment]
Please use issue template next time. Anyway you want to play 50 videos in one screen. Please read your logs carefully - you run out of memory which is normal. I think no device can run 50 videos.

**Comment by getpu** [comment]
> Please use issue template next time. Anyway you want to play 50 videos in one screen. Please read your logs carefully - you run out of memory which is normal. I think no device can run 50 videos.

**Comment by getpu** [comment]
under your guidance, This issue has been solved perfectly. This project very nice, You are very nice, Thank you very much.

**Comment by dvird** [comment]
@getpu can you elaborate what you did?
