### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Arafa2020** [jhomlala/betterplayer#407]
subtitles vtt not work good 
there is problem in subtitles
Show at wrong timing
Or not show
This is a test file
Can you help with this problem
example: https://filebin.net/pdpv9j3vh6bce8sa/90726c9dfd157f5a70f590bcbe7272b2.vtt?t=w3tx5e71

**Comment by jhomlala** [comment]
@Arafa2020 Please follow issue template. Your file is not direct url to VTT. This url leads to hosting page. You need to provide url to file which will return subtitles directly. Here's an example: https://www.iandevlin.com/html5test/webvtt/upc-video-subtitles-en.vtt
