### ISSUE TITLE
[BUG] On click of Notification, app should open

### ISSUE THREAD

**Issue by shashikantdurge** [jhomlala/betterplayer#413]
**History check**
Didn't find any issue raised on this

**Describe the bug**
A player with notification configured and lifeCycle set to false (Background play).
Clicking on the Notification does nothing in Android. 

**To Reproduce**
1. Go to BetterPlayer Example
2. Click on Notifications player page
3. Click on Android Home button
4. Click on the Notification

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**
On click of notification, It should open the respective app.

**Better Player version**
- Version: 0.0.61

**Smartphone (please complete the following information):**
 - Device: One plus 3
 - OS: Android 9

**Comment by jhomlala** [comment]
https://github.com/jhomlala/betterplayer/pull/420

**Comment by jhomlala** [comment]
Fixed in 0.0.65.

**Comment by hosajadi** [comment]
how can I use this feature?
what is your mean about **activityName**?
my problem is that can't open app from the background by clicking on the notification

**Comment by jhomlala** [comment]
You need to pass name of your activity from Android directory of your app. Better Player will look up for that activity when user clicks on notification and open that activity.

**Comment by renatolealdev** [comment]
Greetings Devs. I also couldn't open the App by pressing on notifications. I mentioned MainActivity as directed, but was unsuccessful. Any guidance?

**Comment by renatolealdev** [comment]
@jhomlala Can you give an example of this Android directory activity? MainActivity didn't work for me.
