### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gadgetsteach** [jhomlala/betterplayer#418]
**History check**
pip not working please solve in android or reply with complete source code 

thanking you..

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jhomlala** [comment]
Please fill issue correctly. Check example app to see how PiP works.
