### ISSUE TITLE
Package name is easy to have conflict

### ISSUE THREAD

**Issue by denniswhchung** [jhomlala/betterplayer#43]
The package com.jhomlala.better_player.VideoPlayerPlugin will conflict with another plugin such as video_trimmer.
As there is a plugin VideoPlayer (io.flutter.plugins.videoplayer.VideoPlayerPlugin) use the same name VideoPlayerPlugin.

I suggest to rename it to prevent conflict probability .

**Comment by jhomlala** [comment]
Fixed in 0.0.13.
