### ISSUE TITLE
subtitle is not showing

### ISSUE THREAD

**Issue by nonameclub** [jhomlala/betterplayer#436]
var dataSource = BetterPlayerDataSource(
            BetterPlayerDataSourceType.network,
            "$url",
            useHlsSubtitles: true,
            hlsTrackNames: ["Low quality", "Not so low quality", "Medium quality"],
            subtitles: [
              BetterPlayerSubtitlesSource(
                type: BetterPlayerSubtitlesSourceType.network,
                name: "EN",
                urls: [
                  "https://dl.dropboxusercontent.com/s/71nzjo2ux3evxqk/example_subtitles.srt"
                ],
              ),
              BetterPlayerSubtitlesSource(
                type: BetterPlayerSubtitlesSourceType.network,
                name: "DE",
                urls: [
                  "https://dl.dropboxusercontent.com/s/71nzjo2ux3evxqk/example_subtitles.srt"
                ],
              ),
            ],
          );

**Comment by jhomlala** [comment]
I've checked and subtitles are working fine on my side. You need to pick EN/DE subtitles from overflow menu. Remember that you're using subtitles which are in first 10 secs.

**Comment by jhomlala** [comment]
No response from author - closing issue.
