### ISSUE TITLE
Stretched Video

### ISSUE THREAD

**Issue by denniswhchung** [jhomlala/betterplayer#44]
When I try to play a 16:9 video with 1:1 aspect ratio in better play, the video is stretched.
Is there any configuration can handle the stretching problem?
Just like the following example: https://fijkplayer.befovy.com/docs/en/fijkfit.html#gsc.tab=0

By the way, better player is really good!

**Comment by jhomlala** [comment]
@denniswhchung 
Did you set aspect ratio both in controller and widget? Check this example:

```import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

class ExamplePage extends StatefulWidget {
  @override
  _ExamplePageState createState() => _ExamplePageState();
}

class _ExamplePageState extends State<ExamplePage> {
  BetterPlayerController _betterPlayerController;

  Future<BetterPlayerController> _setupDefaultVideoData() async {
    var dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.NETWORK,
      "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8",
      liveStream: true,
      subtitles: BetterPlayerSubtitlesSource(
        type: BetterPlayerSubtitlesSourceType.NETWORK,
        url:
            "https://dl.dropboxusercontent.com/s/71nzjo2ux3evxqk/example_subtitles.srt",
      ),
    );
    _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(
          aspectRatio: 1,
          controlsConfiguration:
              BetterPlayerControlsConfiguration(enableProgressText: true),
        ),
        betterPlayerDataSource: dataSource);
    return _betterPlayerController;
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<BetterPlayerController>(
      future: _setupDefaultVideoData(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          return Center(child: CircularProgressIndicator());
        } else {
          return AspectRatio(
            aspectRatio: 1,
            child: BetterPlayer(
              controller: snapshot.data,
            ),
          );
        }
      },
    );
  }
}
```

Thanks for your appreciation!

**Comment by shiyiya** [comment]
use `FittedBox`

```dart
AspectRatio(
          aspectRatio: betterPlayerController.aspectRatio,
          child:  FittedBox(child: Videoplayer(),fit: BoxFit.cover)
 )
```

**Comment by denniswhchung** [comment]
I have already put aspect ratio 1:1 twice. The player is displayed as 1:1, but the 16:9 video is still stretched.
Here is my code.  Thanks.

AspectRatio(
                        aspectRatio: 1,
                        // Use the VideoPlayer widget to display the video.
                        child: _buildVideo(),
),

_playerController = BetterPlayerListVideoPlayerController();

_betterPlayerConfiguration = BetterPlayerConfiguration(
      autoPlay: false,
      aspectRatio: 1,
);

Widget _buildVideo() {
    return BetterPlayerListVideoPlayer(
      widget.post.customPostFileList[_listIndex].dataSource,
      configuration: _betterPlayerConfiguration,
      key: Key("VLogGridVideo" + _listIndex.toString()),
      playFraction: 0.8,
      betterPlayerListVideoPlayerController: _playerController,
    );
),

**Comment by vipinnegi90** [comment]
@denniswhchung Just remove aspectRatio argument from BetterPlayerConfiguration and remove AspectRatio widget, use BetterPlayer widget directly, I believe it takes aspect ratio from video source. I did same and video came fine for me. However, I didn't have enough videos to test for different aspect ratios. You can try and let us know.

**Comment by jhomlala** [comment]
Please check new release 0.0.15. There is a new `fit` option in configuration. This may solve your issue.
