### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by seesatya45** [jhomlala/betterplayer#441]
I am unable to work with pip mode in-app when I am enabling pip mode it throws me out of App. Kindly check it.

**Comment by jhomlala** [comment]
@seesatya45 Please fill the issue ticket. How can I help you if you didn't provide any details?

**Comment by jhomlala** [comment]
No response from author - closing issue.

**Comment by seesatya45** [comment]
Kindly send me an example of a PIP Mode in the better player, so I can
implement it in my app. Thank you!
