### ISSUE TITLE
[BUG] Orientation Problem

### ISSUE THREAD

**Issue by EjazAmir** [jhomlala/betterplayer#444]
Hi, i'm using this package, my app is set to portrait up mode only. but i want to go my better player in full screen mode (landscape). if i allow my landscape orientation in info.plist file and it works good but it also allows my app to go in landscape mode. i only want my player to go landscape mode and rest app in portrait mode only.

**Comment by jhomlala** [comment]
@EjazAmir This is not bug. Please use github correctly. You should ask questions in discussion tab. Issues are for reporting bugs or feature requests.

If your app is portrait only but you want to have horizontal orientation in video fullscreen then you need to use these parameters in BetterPlayerConfigration:

```dart
    /// Defines the set of allowed device orientations on entering fullscreen
    final List<DeviceOrientation> deviceOrientationsOnFullScreen;

    /// Defines the set of allowed device orientations after exiting fullscreen
    final List<DeviceOrientation> deviceOrientationsAfterFullScreen;
```

In `deviceOrientationsOnFullScreen` you should use only horizontal orienations and in `deviceOrientationsAfterFullScreen` you should use onky portrait orientations.
