### ISSUE TITLE
[FEATURE] Audio-only HLS

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#445]
**Is your feature request related to a problem? Please describe.**
Android will throw an error if you are trying to play audio-only HLS.  My application allows both audio and video clips so I would prefer to use BetterPlayer for both.

**Describe the solution you'd like**
1) I would like to specific if a source is audio-only in the `BetterPlayerDataSource` class. 
2) (Optional) If a source is audio-only, then the placeholder widget will not disappear. 

ExoPlayer already supports audio-only HLS.  [Stackoverflow](https://stackoverflow.com/questions/66687353/exoplayer-cant-play-only-audio-for-hls).  AVPlayer also supports. 

**Describe alternatives you've considered**
I could use another plugin like [just_audio](https://pub.dev/packages/just_audio) but I much prefer to use BetterPlayer! 

**Additional context**
`E/ExoPlayerImplInternal( 6651): Playback error
E/ExoPlayerImplInternal( 6651):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 6651):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal( 6651):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 6651):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 6651):       at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by vanfresh** [comment]
Issue was on my end

**Comment by cngeru** [comment]
@vanfresh How did you solve it
