### ISSUE TITLE
how can I invoke retry method?

### ISSUE THREAD

**Issue by SinoMiles** [jhomlala/betterplayer#446]
when Im try to speed video progress.some video will show "can't be played". then click retry button .It will come back to normal.so I wanna use code to invoke retry method.how can i do this?

maybe like following code
```
   controller.speedListening(x){
        retry();
}
 
```

**Comment by jhomlala** [comment]
@SinoMiles Please use github corretly. This is question and you should ask this in discussion tab.

You should call this method to retry your data source:
```dart
_betterPlayerController.retryDataSource();
```
