### ISSUE TITLE
[FEATURE] Dynamic headers

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#451]
**Is your feature request related to a problem? Please describe.**
I am using JWT for authentication.  The authentication token may expire before the datasource is played.  For example, in a playlist.

**Describe the solution you'd like**
In addition to defining headers when you declare `BetterPlayerDataSource.network(headers: headers)`, I want to be able to supply additional headers for said datasource the moment it plays to make sure the authentication token is up-to-date.

Perhaps allow me to pass a function when declaring `BetterPlayerPlaylistConfiguration`

**Describe alternatives you've considered**
Right now my authentication token is set longer than it needs to be.

**Additional context**
None

**Comment by jhomlala** [comment]
@vanfresh i suppose the easiest way will be:
1. Save position of currently played video
2. Authenticate with JWT
3. Pass new data source with new JWT token
4. Set position of the video

Did you tried something like that?

**Comment by vanfresh** [comment]
> Pass new data source with new JWT token

I wasn't aware that I can set a new playlist `betterPlayerDataSourceList` in `BetterPlayerPlaylist`.  If so, that is possible.

**Comment by jhomlala** [comment]
I didn't see that you're having problems with playlist. I will add new method in BetterPlayerPlaylistController to setup new data source without rebuilding playlist widget. This will be added in next version.

**Comment by jhomlala** [comment]
Released in 0.0.66.
