### ISSUE TITLE
[FEATURE] Is there way to change notification icon button ?

### ISSUE THREAD

**Issue by Rifqi31** [jhomlala/betterplayer#457]
**Is your feature request related to a problem? Please describe.**
Your package is very perfect  from PIP to notifications, but I think maybe need some tweak like change icon button from notification.

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jhomlala** [comment]
@Rifqi31 Which one icon exactly do you want to change? Can you attach some screenshot?

**Comment by Rifqi31** [comment]
![Screenshot_20210430-075532](https://user-images.githubusercontent.com/10386042/116636151-d0e23a00-a98a-11eb-9e4e-dbb117c16c26.jpg)

Seek button actually

**Comment by jhomlala** [comment]
@Rifqi31 Can you be more specific? Do you mean button near "SA V2"?

**Comment by jhomlala** [comment]
No answer from author - closed.

**Comment by hosajadi** [comment]
for me, I want to change the pause button, can I do that?

**Comment by Rifqi31** [comment]
@jhomlala I want change seek button left and right, sorry for late reply because connection problem

**Comment by hosajadi** [comment]
@Rifqi31 
I found solution for changing notification Icons
simply override this icons in drawable directory, for example: I want change pause Icon   so create .png file in this folder with name **exo_notification_pause**
for you, you can create .png file with name **exo_notification_fastforward**

**Comment by jhomlala** [comment]
Here are list of drawables which can be changed: https://github.com/google/ExoPlayer/blob/afd11de/library/ui/src/main/res/values/drawables.xml#L9

**Comment by Rifqi31** [comment]
Thank @hosajadi and @jhomlala  for the information is very helping me
