### ISSUE TITLE
[BUG] Issue causing black bars on all videos and weird aspect ratio

### ISSUE THREAD

**Issue by zadahmed** [jhomlala/betterplayer#458]
Error That Occurs

The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 46 pos 10: '<optimized out>'

The relevant error-causing widget was: 
  BetterPlayer file:///Users/zahidahmed/AndroidStudioProjects/veos/lib/screens/videoplaybetterhls.dart:196:22
When the exception was thrown, this was the stack: 
#2      _rrectIsValid (dart:ui/painting.dart:46:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:4159:12)
#4      _ProgressBarPainter.paint (package:better_player/src/controls/better_player_cupertino_progress_bar.dart:189:12)
#5      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:564:13)
#6      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
...

![Image from iOS](https://user-images.githubusercontent.com/24897782/116810480-e64a9600-ab3b-11eb-9639-b0b6202bec72.png)
My video player keeps having inconsistent issues with having weird aspect ratios and black bars on both sides on my videos from time to time. Can someone help if there is a fix for this? Attached a image of what the image looks like.

**Comment by jhomlala** [comment]
@zadahmed Can you fill issue ticket properly? You didn't provide any useful details. Please attach videos/screenshots.

**Comment by zadahmed** [comment]
This is mainly the error that occurs in Flutter - RRect argument contained a NaN value

**Comment by jhomlala** [comment]
Seems like you're missconfigured your aspect ratio and fit in BetterPlayerConfiguration. You should check these settings in order to make video fit your screen.

**Comment by zadahmed** [comment]
The aspect ratio and fit works fine and is based on settings . The issue doesn’t persist initially when the video starts playing. The issue seems to persist only when someone pops the navigation and returns back to the page.

**Comment by jhomlala** [comment]
Can you provide minimal reproducible example?

**Comment by jhomlala** [comment]
@zadahmed This is last call - please provide minimal reproducible code.

**Comment by jhomlala** [comment]
Closed. I'll reopen this ticket if you will provide minimal reproducible code in this issue. Please answer in this issue if you want to continue.
