### ISSUE TITLE
Tap player widget to play/pause

### ISSUE THREAD

**Issue by batthis** [jhomlala/betterplayer#459]
When I wrap the player with inkwell and use ontap to play/pause based on isPlaying(), it requires a double tap for the ontap to react. 

```
child: InkWell(
    onTap: () => videoPlayerController.isPlaying() ? videoPlayerController.pause(): videoPlayerController.play(),
    child: BetterPlayer(controller: videoPlayerController)
),
```

Is this an issue with another listener taking the first tap? 
If so is there a better way to create this behavior? 

Note: Forced to use release 0.0.61 due to compatibility to esys_flutter_share.

Thx.

**Comment by jhomlala** [comment]
So you're wrapping BetterPlayer widget with InkWell. BetterPlayer uses GestureDetector underhood to detect clicks. Probably that's the reason why clicks won't work correctly. If you want to have custom click behavior, you should consider using custom theme. Check example here: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/custom_controls/custom_controls_widget.dart
