### ISSUE TITLE
[BUG] HLS Cache fails for iOS

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#461]
**History check**
Yes, I have checked

**Describe the bug**
BetterPlayer throws an exception when playing HLS datasource with Cache configuration for **iOS** (14.5) only.

>  Non-fatal Exception: FlutterError
PlatformException(VideoError, Failed to load video: The network connection was lost., null, null). Error thrown null.

There is no stack track other than this line.  When cache config is turned off for iOS, everything works fine. 

Everything works as expected on Android.

**To Reproduce**
1. Set up `BetterPlayerDataSource.network` with cache configuration and HLS datasource
2. Play video on real Android and iOS Device
3. iOS Playback throws exception

**Example code**
```
BetterPlayerDataSource.network(
    videoUrl.toString(),
    headers: headers,
    cacheConfiguration: BetterPlayerCacheConfiguration(useCache: true),
    videoFormat: BetterPlayerVideoFormat.hls,
)
```

**Expected behavior**
Cache should work for HLS datasource for iOS

**Flutter doctor**
`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.2.0-10.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (1 available)

• No issues found!
`

**Better Player version**
- Version: 0.0.65

**Smartphone (please complete the following information):**
 - Device: iPhone SE2
 - OS: iOS14.5

**Comment by jhomlala** [comment]
Seems like problem with cache library used in iOS. I've created ticket in library repository, but I don't believe it will be solved quickly. https://github.com/ChangbaDevs/KTVHTTPCache/issues/151

**Comment by vanfresh** [comment]
Understood. Thank you.

**Comment by jhomlala** [comment]
This may solve issue: https://github.com/changsanjiang/SJMediaCacheServer but will require a lot of work.

**Comment by jhomlala** [comment]
Added support for HLS cache in 0.0.74.
