### ISSUE TITLE
[BUG] Cannot use better player with an Objetive C project

### ISSUE THREAD

**Issue by xlcod** [jhomlala/betterplayer#467]
**Describe the bug**
Cannot use better player with a Objetive C project ,
if i migrate the proyect to swift works fine but with a project created with java and Objetive C  app does not compile

**To Reproduce**
1. Just install better player on a flutter project created with java and Objetive C

**Example code*
No code added

**Expected behavior**
Should compile just fine.

**Flutter doctor**
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.3 20D91 darwin-arm, locale es-ES)
    • Flutter version 1.22.6 at /Users/administrador/Documents/flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/administrador/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 856AE459-0F69-4FC7-89A9-E6CB153A0530 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
**Better Player version**
- Version: anyone

**Smartphone (please complete the following information):**
 - Device: IPhone 12
 - OS: IOS 14.4

**Additional context**

**Comment by jhomlala** [comment]
@xlcod I've created Flutter project with ObjC and added Better Player. Everything works fine. Can you be more specific, what's the issue that your project doesn't compile? Seems like there's some problem on your side.

**Comment by xlcod** [comment]
Thanks for replying, right now it outputs a very long error script and if i delete the ios folder and then create the ios folder with swift , it  works totally fine  , right now i have the following dependencies: 

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.2+1
  http: ^0.12.2
  crypto: ^2.1.5
  video_player: ^1.0.1
  path_provider: ^1.6.24
  fluttertoast: ^7.1.5
  carousel_slider: ^2.3.1
  image_picker: ^0.6.7+22
  url_launcher: ^5.7.10
  cached_network_image: ^2.4.1
  page_indicator: ^0.3.0
  auto_orientation: ^1.0.1
  chewie: ^0.12.0
  bottom_navy_bar: ^5.6.0
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_messaging: ^8.0.0-dev.11
  flutter_local_notifications: ^3.0.2
  flutter_launcher_icons: ^0.8.1
 
 i really want to use better player but for some reason it doesn´t compile on ios , instead im using chewie for now..

**Comment by xlcod** [comment]
The error output gave no usefull information as usual with xcode, im also using Flutter 1.22.6 right know if that does matter

**Comment by xlcod** [comment]
better_player: ^0.0.61 

![Captura de pantalla 2021-05-06 a las 9 47 55](https://user-images.githubusercontent.com/44270692/117261620-a5f75a80-ae50-11eb-8343-8ec34afb0ade.png)
![Captura de pantalla 2021-05-06 a las 9 48 04](https://user-images.githubusercontent.com/44270692/117261769-d0e1ae80-ae50-11eb-9e57-988bcb593a13.png)
![Captura de pantalla 2021-05-06 a las 9 48 28](https://user-images.githubusercontent.com/44270692/117261812-dd660700-ae50-11eb-9f31-8c6a8b782ec0.png)

For some reason vs wont let me c&p the output

**Comment by jhomlala** [comment]
Could you try upgrade to latest Flutter stable and Better Player version?

**Comment by jhomlala** [comment]
No anwser from author. Closed.

**Comment by xlcod** [comment]
I just tried changing the project to Swift and still outputs the error , this is a fresh proyect just a copy .
Im now running flutter 2.2.0 on xcode 12.5



`Xcode build done.                                           29,4s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[49283]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f3491160) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1184802b8). One of the two will be used. Which one is undefined.
    objc[49283]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f34911b0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x118480308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    error: the following command failed with exit code 0 but produced no further output
    CompileC /Users/administrador/Library/Developer/Xcode/DerivedData/Runner-gazojkvtktwpuyehbyxdnejmixgg/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FMDB.build/Objects-normal/arm64/FMDatabase.o /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/FMDB/src/fmdb/FMDatabase.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    In file included from /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.m:26:
    /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.h:282:31: warning: 'NSTextAlignment' is only available on iOS 6.0 or newer [-Wunguarded-availability]
    @property (assign, nonatomic) NSTextAlignment titleAlignment;
                                  ^
    In module 'UIKit' imported from /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Target Support Files/Toast/Toast-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSText.h:20:28: note: 'NSTextAlignment' has been marked as being introduced in iOS 6.0 here, but the deployment target is iOS 4.3.0
    typedef NS_ENUM(NSInteger, NSTextAlignment) {
                               ^
    In file included from /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.m:26:
    /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.h:221:12: note: annotate 'CSToastStyle' with an availability attribute to silence this warning
    @interface CSToastStyle : NSObject
               ^
    /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.h:287:31: warning: 'NSTextAlignment' is only available on iOS 6.0 or newer [-Wunguarded-availability]
    @property (assign, nonatomic) NSTextAlignment messageAlignment;
                                  ^
    In module 'UIKit' imported from /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Target Support Files/Toast/Toast-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSText.h:20:28: note: 'NSTextAlignment' has been marked as being introduced in iOS 6.0 here, but the deployment target is iOS 4.3.0
    typedef NS_ENUM(NSInteger, NSTextAlignment) {
                               ^
    In file included from /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.m:26:
    /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.h:221:12: note: annotate 'CSToastStyle' with an availability attribute to silence this warning
    @interface CSToastStyle : NSObject
               ^
    /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.m:265:36: warning: 'NSLineBreakByTruncatingTail' is only available on iOS 6.0 or newer [-Wunguarded-availability]
            titleLabel.lineBreakMode = NSLineBreakByTruncatingTail;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Target Support Files/Toast/Toast-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSParagraphStyle.h:20:28: note: 'NSLineBreakMode' has been marked as being introduced in iOS 6.0 here, but the deployment target is iOS 4.3.0
    typedef NS_ENUM(NSInteger, NSLineBreakMode) {
                               ^
    /Users/administrador/Documents/alvaro_p_flutter/inspiria-pro/inspiria/ios/Pods/Toast/Toast/UIView+Toast.m:265:36: note: enclose 'NSLineBreakByTruncatingTail' in an @available check to s`

**Comment by jhomlala** [comment]
@xlcod Again this is not Better Player issue. Check stackoverflow: https://stackoverflow.com/questions/65089767/class-amsupporturlconnectiondelegate-is-implemented-in-both
