### ISSUE TITLE
HLS download & Offline playback 

### ISSUE THREAD

**Issue by Zartek-Technologies** [jhomlala/betterplayer#468]
A way to download and save HLS video , Select resolution to download and start downloading with notifier( running task)
A way to access downloaded files offline.

**Comment by jhomlala** [comment]
@Zartek-Technologies Please follow issue template. Is this feature request or bug?

Anyway, I assume that you're requesting some feature. This feature I believe should be handled by your app. Better Player general usage is to play videos, not to download and save them. I believe you can do that easily in your app and integrate Better Player with it. Also you may try use cache of Better Player which may help you reducing bandwidth load and increase speed of loading.
