### ISSUE TITLE
[BUG] HLS format problem

### ISSUE THREAD

**Issue by BitGhostX** [jhomlala/betterplayer#474]
##################### DESCRIPTION #####################
I am very grateful to better_player, for the mobile application it is very complete and configurable.
I use better_player in my application (set top box), using HLS as the source for the videos. When the video changes resolution to a lower one, the new small video overlaps the old one. The new video continues to play at its new size, and the previous large one loops the last frame before changing resolution.

![TOMA_1_BUG](https://user-images.githubusercontent.com/10550582/117556414-5e2e2a00-b02e-11eb-8b05-7b2ae023388b.jpeg)
![TOMA_2_BUG](https://user-images.githubusercontent.com/10550582/117556417-66866500-b02e-11eb-8956-23f067be1c8d.jpeg)

### file: player_provider.dart
import 'package:better_player/better_player.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/painting.dart';
import 'package:tv_streaming/models/channel.dart';

class PlayerProvider extends ChangeNotifier {
  BetterPlayerController _controller;
  BetterPlayerDataSource _dataSource;
  BetterPlayerConfiguration _configuration;
  void initializeController() async {
    // initial configuration
    _configuration = BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      fit: BoxFit.contain,
      autoPlay: true,
      autoDispose: true,
      controlsConfiguration: BetterPlayerControlsConfiguration(
        showControlsOnInitialize: false,
        enableSkips: false,
        showControls: false,
      ),
      eventListener: (event) {
        if (event.betterPlayerEventType == BetterPlayerEventType.changedTrack) {
          print(_controller.betterPlayerTracks.toString());
          print(_controller.betterPlayerTrack.toString());
        }
      },
    );
    // initial dataSource
    _dataSource = BetterPlayerDataSource.network(
      'https://ott1.nibotv.club/live_abr/LATINA/playlist.m3u8',
      videoFormat: BetterPlayerVideoFormat.hls,
      liveStream: true,
      useHlsAudioTracks: false,
      useHlsSubtitles: false,
    );
    // initial controller
    _controller = BetterPlayerController(_configuration);
    // initial setupDataSource
    await _controller.setupDataSource(_dataSource);
  }

  Future<void> changeChannel(Channel channel) async {
    BetterPlayerDataSource __dataSource = BetterPlayerDataSource.network(
      // BetterPlayerDataSourceType.network,
      channel.streamUrl,
      videoFormat: BetterPlayerVideoFormat.hls,
      liveStream: true,
      useHlsAudioTracks: false,
      useHlsSubtitles: false,
    );
    await _controller.setupDataSource(__dataSource);
  }

  BetterPlayerController get controller => _controller;
  BetterPlayerDataSource get dataSource => _dataSource;
}

### player.dart
...
AspectRatio(
  child: BetterPlayer(
    controller: playerProvider.controller,
  ),
  aspectRatio: 16 / 9,
),
...

##################### EXPECTED BEHAVIOR ###############
The expected behavior is that the video does not reduce its size when changing the resolution automatically or manually.

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [VersiÃ³n 10.0.19041.928], locale es-PE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1.0)
[✓] VS Code, 64-bit edition (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!

**Better Player version**
- Version: 0.0.66

**Device information:**
 - Device: TX3 mini
 - OS: Android 9

**Comment by jhomlala** [comment]
Could you check this issue with some newer Android version (i.e. 10,11)? This issue seems to connected with Flutter platform code, which couldn't be solved.

**Comment by jhomlala** [comment]
No answer from author - closing issue.
