### ISSUE TITLE
Problem While Changing Resolution Of Video

### ISSUE THREAD

**Issue by hamza-gaya** [jhomlala/betterplayer#476]
After Configuring the resolutions of the video of this player, like this:  
resolutions: {
          "360p": "<video url>",
          "540p": "<video url>",
          "720p": "<video url>",
          "1080p": "<video url>",
 });
Changing the quality while playing the video only audio is being heard and the video becomes blank

**Comment by jhomlala** [comment]
@hamza-gaya Please fill issue ticket properly.
