### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by olyshchuk** [jhomlala/betterplayer#479]
**Describe the bug**
 Video is reset after closing full-screen mode and the user should start it again from the beginning

**To Reproduce**
1. Start video
2. Pause 
3. Go to full screen and return to portrait
4. Video is reset

**Example code*
```
class VideoPlayerScreen extends StatefulWidget {
  final String url;

  VideoPlayerScreen(this.url);

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends State<VideoPlayerScreen> {
  final List<DeviceOrientation> orientation = const [
      DeviceOrientation.portraitUp,
  ];

  Widget _player() {
    return Center(
        child: BetterPlayer.network(widget.url,
            betterPlayerConfiguration: BetterPlayerConfiguration(
              deviceOrientationsAfterFullScreen: orientation,
                controlsConfiguration: BetterPlayerControlsConfiguration(enableSkips: false,
                    enableFullscreen: true, enableOverflowMenu: false),
                fit: BoxFit.scaleDown,
                aspectRatio: 9/16)
        )
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(iconTheme: Theme.of(context).iconTheme),
      backgroundColor: Colors.black,
      body: _player(),
    );
  }
}
```

**Flutter doctor**
C:\Users\lyshc\Flutter\1.22.6\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 1.22.6 at C:\Users\lyshc\Flutter\1.22.6\flutter
    • Framework revision 9b2d32b605 (4 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/lyshc/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/lyshc/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.55.2)
    • VS Code at C:\Users\lyshc\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 3 categories.
Process finished with exit code 0

**Better Player version**
- Version: ^0.0.61

**Smartphone (please complete the following information):**
 - Device: Pixel 4 API 30
 - OS: Android

**Comment by oleksandrlyshchuk** [comment]
my fail

**Comment by sha3rawi33** [comment]
@olyshchuk how did you solve this ?

**Comment by olyshchuk** [comment]
@sha3rawi33 Sorry, actually I I do not remember how, but it still reproduces...

**Comment by jhomlala** [comment]
I'm not sure why it's open. Closed.
