### ISSUE TITLE
How to add progress bar to customer control

### ISSUE THREAD

**Issue by pastordee** [jhomlala/betterplayer#480]
Hey loving  this plug-in I was wondering how can I add the progress bar to custom controls
Thanks

**Comment by jhomlala** [comment]
If you're not reporting any issue or feature request then use discussion tab. Anyway answer for your question is simple: just copy code from material/cupertino controls. https://github.com/jhomlala/betterplayer/blob/master/lib/src/controls/better_player_cupertino_controls.dart
https://github.com/jhomlala/betterplayer/blob/master/lib/src/controls/better_player_material_controls.dart
