### ISSUE TITLE
[BUG] When Navigating to other pages, better Player not auto handling lifeCylce, Audio is still playing in the background

### ISSUE THREAD

**Issue by Kaival-Patel** [jhomlala/betterplayer#484]
**History check**
I have checked the previous issues and couldn't find one that I am facing.

**Describe the bug**
Better Player is not auto disposing of the player and not auto handling the lifeCycle without Controller (I have also tried with the Controller too but the audio keeps playing in the background). When Navigating to other pages doesn't auto-stop (auto manage lifecycle) the video 

**Example code*
home_tab.dart (ui GetX)
[home_tab.dart](https://gist.github.com/Kaival-Patel/081afdb7f96b80611881ce2ef6bfb1d8)

homeViewController.dart (Controller GetX)
[homeViewController.dart](https://gist.github.com/Kaival-Patel/061cb76c2603ab11288924f9b2298094)

betterPlayerConfig.dart (configs for the better Player)
[betterPlayerConfig.dart](https://gist.github.com/Kaival-Patel/081afdb7f96b80611881ce2ef6bfb1d8)

**Expected behavior**
When I Navigate to another page Better Player should turn off the video or auto handle the lifeCycle so that audio stops playing in the background.
What I am trying to get is making an app like TikTok in which there are only videos but in my case, it can be video, image, or audio post too. Now just like TikTok users can swipe and see the videos. But the only problem is When I navigate to any page audio is still coming from the video (so lifecycle is not getting auto managed).
No doubt Better Player is the best I have come across all the players. Good Job jhomlala. 

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- better_player : 0.0.61

**Smartphone (please complete the following information):**
 - Device: Nokia 8.1, Oneplus Nord
 - OS: Both running android 11

**Additional context**
Let me know If you want the code with the controller in it, I will open the new issue. If I am making any mistake, Please guide me in that.

**Comment by jhomlala** [comment]
@Kaival-Patel  When you're using `playerVisibilityChangedBehavior` parameter from `BetterPlayerConfiguration` then you need to handle play/pause state of video. Basically, easiest fix is to remove: 
```dart
playerVisibilityChangedBehavior: (visibilityFraction){
},
``` from your code.

**Comment by Kaival-Patel** [comment]
@jhomlala Yes, I have tried removing the playerVisibilityBehaviour but when I navigate to other pages via Get.to(()=>somePage()), then in the background somewhere video player starts again
Is this the issue because of GetX? Kindly help, Thanks for the above help

**Comment by Urkman** [comment]
It's also not working for me :(
I'm using a BottomNavigationbar (on iOS a CupertinoTabScaffold) and when I switch tabs, the player is not pausing...

When I include this:
```
      playerVisibilityChangedBehavior: (visibilityFraction) {
        print(visibilityFraction);
      },
```
it only prints out `1.0' and nothing, when I leave the page... But when I come back t the page, it prints out `1.0` again...

**Comment by Kaival-Patel** [comment]
> It's also not working for me :(
> I'm using a BottomNavigationbar (on iOS a CupertinoTabScaffold) and when I switch tabs, the player is not pausing...
> 
> When I include this:
> 
> ```
>       playerVisibilityChangedBehavior: (visibilityFraction) {
>         print(visibilityFraction);
>       },
> ```
> 
> it only prints out `1.0' and nothing, when I leave the page... But when I come back t the page, it prints out `1.0` again...



> It's also not working for me :(
> I'm using a BottomNavigationbar (on iOS a CupertinoTabScaffold) and when I switch tabs, the player is not pausing...
> 
> When I include this:
> 
> ```
>       playerVisibilityChangedBehavior: (visibilityFraction) {
>         print(visibilityFraction);
>       },
> ```
> 
> it only prints out `1.0' and nothing, when I leave the page... But when I come back t the page, it prints out `1.0` again...

For me bottom tabs switching is happening, audio is getting stopped but I have found the real issue (issue is still with betterplayer) it was because of when you do navigate.push it will keep audio playing in the bg but if you do navigate.pushreplace then audio is getting stopped but hey you have to manage willpopscope and all the things on back press n all. Now coming to your problem can you please remove `playerVisibilityChangedBehaviour
and try bottom navigation with ValueListenable Builder

**Comment by Urkman** [comment]
`playerVisibilityChangedBehaviour` was only in there for testing... So removing this changes nothing :(

> try bottom navigation with ValueListenable Builder

What do mean by that?

**Comment by jhomlala** [comment]
Better Player uses https://pub.dev/packages/visibility_detector to check whether player is still visible in order to play or pause video. So if player widget is still counted as visible in widget tree then it won't be paused:
```dart
 ///Listener which handles state of player visibility. If player visibility is
  ///below 0.0 then video will be paused. When value is greater than 0, video
  ///will play again. If there's different handler of visibility then it will be
  ///used. If showNotification is set in data source or handleLifecycle is false
  /// then this logic will be ignored.
  void onPlayerVisibilityChanged(double visibilityFraction) async {
    _isPlayerVisible = visibilityFraction > 0;
    if (_disposed) {
      return;
    }
    _postEvent(
        BetterPlayerEvent(BetterPlayerEventType.changedPlayerVisibility));

    if (_isAutomaticPlayPauseHandled()) {
      if (betterPlayerConfiguration.playerVisibilityChangedBehavior != null) {
        betterPlayerConfiguration
            .playerVisibilityChangedBehavior!(visibilityFraction);
      } else {
        if (visibilityFraction == 0) {
          _wasPlayingBeforePause ??= isPlaying();
          pause();
        } else {
          if (_wasPlayingBeforePause == true && !isPlaying()!) {
            play();
          }
        }
      }
    }
  }
```
So in your cases there are 2 ways to solve issues:
1. Check visibility detector is not working in your widget tree.
2. Handle video play/pause manually - for example when you navigate from and back to your screen where Better Player is attached.

If case of 1. I can try debug issue but I need minimal reproducible code. The best way is to prepare some clean project with stuff that doesn't work without any redundant code.

**Comment by Urkman** [comment]
Managed it manually... Working now...

**Comment by Kaival-Patel** [comment]
> Managed it manually... Working now...

Can you please share the code? How you did it?

**Comment by raunakCm** [comment]
Kindly reopen this issue, it's still not fixed. The audio is still getting played in the background when I go into fullscreen mode on my android device, and then when I exit the fullscreen mode.

Steps to reproduce:

1. play the video in portrait.
2. click on the fullscreen icon on the player widget to enter fullscreen mode in landscape.
3. click on the fullscreen icon again (It won't exit the fullscreen mode which is also another bug).
4. However, we can exit the fullscreen mode from native back button on android. But after exiting the fullscreen mode using this method, the audio keeps playing in the background, and in the portrait mode, the video is paused at 00:00.
