### ISSUE TITLE
[FEATURE] Segmented WebVTT subtitle support

### ISSUE THREAD

**Issue by trms-alex** [jhomlala/betterplayer#486]
**Is your feature request related to a problem? Please describe.**
We're developing an app intended to play both VOD and live content through HLS. It's important to our users for it support closed captions in both types of media, but right now we have no way to display captions for live streams. We can control the generation of these HLS streams and we intend to implement segmented WebVTT captions on the backend.

Right now, it seems like better_player only supports a single .vtt file for a given HLS stream because we get no captions if we play a sample with multiple segmented .vtt files.

**Describe the solution you'd like**
We'd like better_player to be able to see more than one .vtt file and parse each one out to display as subtitles, periodically reading in new segments as the manifest is updated.

**Describe alternatives you've considered**
Our live streams currently use CEA-608 captions, which better_player doesn't detect at all. We've hacked the video_player plugin to select the appropriate text track in ExoPlayer2 on Android and pass the cues back into Flutter, but it doesn't seem like this is possible on iOS with AVPlayer.

**Additional context**
A sample HLS stream with segmented WebVTT captions can be found at this URL:
`https://eng-demo.cablecast.tv/segmented-captions/vod.m3u8`
Currently, it shows no captions in better_player, although we think that if the very first segment contained text data, it might be displayed as expected.

Note that while this stream is static, in a live stream scenario, the manifest would be rotating out VTT segments periodically.

**Comment by jhomlala** [comment]
@trms-alex Thanks for detailed ticket. This seems to be doable on dart side. Right now all segmented subtitles are loading on the beginning which may take some time since this source has 660 segments. I agree it should have some behaviour which will load part of them on demand and load rest later.

**Comment by trms-alex** [comment]
@jhomlala Thanks for the response. I figured out why we weren't seeing the subtitles in our example and submitted a PR (#491) to fix it.

You're right though. Right now it takes about 15 seconds for the captions to appear because of the hundreds of requests it needs to make. Maybe it should only load the next few seconds (value of `EXT-X-TARGETDURATION`?) at a time.

I don't know if it does this yet, but it will also need to reload the manifest periodically in a live stream scenario.

**Comment by jhomlala** [comment]
@trms-alex I've started working on implementation of this feature in branch may_changes_3. You can check this branch to see how it works right now.

Segmented subtitles are being loaded with JIT policy, so it won't have massive load time on video start. Anyway there's still some work to do with this but seems like it's doable. This feature may be released with next release.

**Comment by trms-alex** [comment]
@jhomlala That was quick! Thanks for putting the time into this, it really solves a big problem for us. We're going to dig in and try it out as soon as we have an example live stream.

**Comment by jhomlala** [comment]
Added in 0.0.68.
