### ISSUE TITLE
[FEATURE] Add YouTube support

### ISSUE THREAD

**Issue by itssidhere** [jhomlala/betterplayer#489]
Thanks for this awesome plugin. Can we add a fromYouTube constructor to it which can play the videos from youtube. Currently the YouTube player packages does really basic job unlike the plug-in so I would like to see this addition to the package. Thanks.

**Comment by itssidhere** [comment]
You can use this plugin for reference.
 https://pub.dev/packages/youtube_player_iframe

**Comment by Urkman** [comment]
This is working fine, with the help of this library:
https://pub.dev/packages/youtube_explode_dart

And here is the code... 
Works fine for me :)
```      
BetterPlayerDataSource dataSource;
      videoURL(channel.url).then(
        (value) {
          dataSource = BetterPlayerDataSource(
            BetterPlayerDataSourceType.network,
            value,
            liveStream: true,
          );

          betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
          betterPlayerController?.setupDataSource(dataSource);
          betterPlayerController?.enablePictureInPicture(Globals().betterPlayerKey);

          isPlayerInitialized(true);
        },
      );

  Future<String> videoURL(String url) async {
    var yt = YoutubeExplode();

    var streamInfo = await yt.videos.streamsClient.getManifest(url);
    var d = streamInfo.muxed.where((e) => e.container == StreamContainer.mp4);
    print(d.first.url.toString());
    return d.first.url.toString();
  }

```

**Comment by jhomlala** [comment]
Right now there's no plan for adding support for YouTube videos. There are many other plugins which can play YouTube videos.

**Comment by sahildev001** [comment]
@Urkman your example is **not working** if there any best solution that play video on better player please suggest me,
 it returns the link : "https://rr1---sn-qxaelnek.googlevideo.com/videoplayback?expire=1698854357&ei=dSFCZZGCN8PA4-EPgc6v-AU&ip=119.82.86.184&id=o-AJRgFikk1Y1-R0Un8GSzMO4fiXPZS7GKy--L47JSEN2s&itag=18&source=youtube&requiressl=yes&mh=ZD&mm=31%2C29&mn=sn-qxaelnek%2Csn-qxaeense&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=831250&spc=UWF9f1_wck97iycZ4LHmwjkUl8qQkMsk2wAWTVa1ZQ&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=8826284&ratebypass=yes&dur=382.664&lmt=1669271466515796&mt=1698832392&fvip=1&fexp=24007246&beids=24350017&c=ANDROID&txp=5319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIgCHNMyyOY2VyEWO0AhvdP2nEKvwNQoIH-0629RrJsoXkCIQDg0gupgF0rC3djgmk9DTOVqK2I30cgrLYoDlDHHftdpQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIhAPUj4O4A3fSlrosl-bCUkgSySJmbZYFhkfFgj2T5dEtoAiB-ck-jEKIHTf2rdlyI0RsFY7xGu1xpFJ1GmqY341oatQ%3D%3D" which is not working.
