### ISSUE TITLE
[BUG] Wrong aspect ration!!!!

### ISSUE THREAD

**Issue by A-Azizi79** [jhomlala/betterplayer#493]
Hi, thanks for your good plugin
there is one problem and the problem is the aspect ratio is wrong because different video sizes idk what is wrong look at this : 
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-05-20 at 18 21 19](https://user-images.githubusercontent.com/76846698/118990580-42187a00-b998-11eb-9b9b-b6a2ce5e9f74.png)

if you look you can see the height is a little bit long, and if I change it and make aspect ratio shorter it will be bad on another video if the size is bigger (sorry i know my English is very bad)
what we must do (something like auto ratio) like vlc player!

here is my code 

`AspectRatio(
      aspectRatio: 16 / 9,
      child: BetterPlayer.network(
        "http://up.asrup.ir//0d/xuyspsdjsjdsajdfss/Those.Who.Wish.Me.Dead.2021.480p.WEB-DL.HardSub.DigiMoviez.mp4",
        betterPlayerConfiguration: BetterPlayerConfiguration(
            deviceOrientationsAfterFullScreen: [DeviceOrientation.portraitUp],
            aspectRatio: 16 / 9,
            fullScreenAspectRatio: 16/9
        ),
      ),
    );
  }
`

**Comment by jhomlala** [comment]
@A-Azizi79 Please use issue template next time and don't put that amount of exclamation marks in title. You're probably doing something wrong on your side. I've put your code into one of the examples that you can find in this repo and everything is fine and video aspect ratio is correct. 

Before creating issue please double check examples to see how to setup Better Player properly.

```dart
import 'package:better_player/better_player.dart';
import 'package:better_player_example/constants.dart';
import 'package:better_player_example/utils.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class NormalPlayerPage extends StatefulWidget {
  @override
  _NormalPlayerPageState createState() => _NormalPlayerPageState();
}

class _NormalPlayerPageState extends State<NormalPlayerPage> {
  late BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
    BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      fit: BoxFit.contain,
      autoPlay: true,
    );
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      "http://up.asrup.ir//0d/xuyspsdjsjdsajdfss/Those.Who.Wish.Me.Dead.2021.480p.WEB-DL.HardSub.DigiMoviez.mp4",
    ));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Normal player"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Text(
              "Normal player with configuration managed by developer.",
              style: TextStyle(fontSize: 16),
            ),
          ),
          AspectRatio(aspectRatio: 16 / 9,
            child: BetterPlayer.network(
              "http://up.asrup.ir//0d/xuyspsdjsjdsajdfss/Those.Who.Wish.Me.Dead.2021.480p.WEB-DL.HardSub.DigiMoviez.mp4",
              betterPlayerConfiguration: BetterPlayerConfiguration(
                  deviceOrientationsAfterFullScreen: [
                    DeviceOrientation.portraitUp
                  ], aspectRatio: 16 / 9, fullScreenAspectRatio: 16 / 9),),),
          ElevatedButton(
            child: Text("Play file data source"),
            onPressed: () async {
              String url = await Utils.getFileUrl(Constants.fileTestVideoUrl);
              BetterPlayerDataSource dataSource =
              BetterPlayerDataSource(BetterPlayerDataSourceType.file, url);
              _betterPlayerController.setupDataSource(dataSource);
            },
          ),
        ],
      ),
    );
  }
}

````

**Comment by A-Azizi79** [comment]
> @A-Azizi79 Please use issue template next time and don't put that amount of exclamation marks in title. You're probably doing something wrong on your side. I've put your code into one of the examples that you can find in this repo and everything is fine and video aspect ratio is correct.
> 
> Before creating issue please double check examples to see how to setup Better Player properly.
> 
> ```dart
> import 'package:better_player/better_player.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> class NormalPlayerPage extends StatefulWidget {
>   @override
>   _NormalPlayerPageState createState() => _NormalPlayerPageState();
> }
> 
> class _NormalPlayerPageState extends State<NormalPlayerPage> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text("Normal player"),
>       ),
>       body: Column(
>         children: [
>           const SizedBox(height: 8),
>           Padding(
>             padding: const EdgeInsets.symmetric(horizontal: 16),
>             child: Text(
>               "Normal player with configuration managed by developer.",
>               style: TextStyle(fontSize: 16),
>             ),
>           ),
>           AspectRatio(
>             aspectRatio: 16 / 9,
>             child: BetterPlayer.network(
>               "http://up.asrup.ir//0d/xuyspsdjsjdsajdfss/Those.Who.Wish.Me.Dead.2021.480p.WEB-DL.HardSub.DigiMoviez.mp4",
>               betterPlayerConfiguration: BetterPlayerConfiguration(
>                   deviceOrientationsAfterFullScreen: [
>                     DeviceOrientation.portraitUp
>                   ],
>                   aspectRatio: 16 / 9,
>                   fullScreenAspectRatio: 16 / 9),
>             ),
>           ),
>         ],
>       ),
>     );
>   }
> }
> ```

Can i see your output on ios? Because my code is exactly like this

**Comment by A-Azizi79** [comment]
I think its better to explain with images look at this: 

### this is chewie player result : 
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-05-21 at 12 35 47](https://user-images.githubusercontent.com/76846698/119104205-3f1d9800-ba31-11eb-9e94-988ce912bbfe.png)

### and this is better player result:
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-05-21 at 12 32 24](https://user-images.githubusercontent.com/76846698/119104413-7a1fcb80-ba31-11eb-958c-130ed0e97ead.png)

### It's like chewie will set the ratio of video automatically.
What is your suggestion?

**Comment by A-Azizi79** [comment]
OH! my bad, i fixed the problem : 
`BetterPlayer.network(
            "http://up.asrup.ir//0d/xuyspsdjsjdsajdfss/Those.Who.Wish.Me.Dead.2021.480p.WEB-DL.HardSub.DigiMoviez.mp4",
            betterPlayerConfiguration: BetterPlayerConfiguration(
              deviceOrientationsAfterFullScreen: [
                DeviceOrientation.portraitUp
              ],
              fit: BoxFit.scaleDown,
              aspectRatio: 16/8
            ),
          ),`

By adding **fit: BoxFit.scaleDown**
