### ISSUE TITLE
AspectRatio of source video

### ISSUE THREAD

**Issue by vipinnegi90** [jhomlala/betterplayer#50]
Hey, great plugin! No doubt.
Is there a way to get the Aspect Ratio of video from URL so that I can assign it? Or, is it possible for Player to assign Ratio to itself from the video source automatically so that we don't have to assign manually. Of course, there should be override option in case someone needs it. Problem is, we would never know what ratio video the customer will upload. The player should be able to handle the ratio from the source and display video perfectly by default. This would be very convenient for us as a developer. 

The Chewie players lets you do that by:
```
_videoPlayerController = VideoPlayerController.network("widget.videoUrl");
await _videoPlayerController.initialize();
_chewieController = ChewieController( aspectRatio: _videoPlayerController.value.aspectRatio,);
```
With this, we don't have to define Aspect ratio for every video on the widget and all ratio videos render as they are without stretching.

**Comment by banool** [comment]
I'd love to see this too.

**Comment by jhomlala** [comment]
This is how you can setup aspectRatio:
```
 _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(
          aspectRatio: 1.0,
        ),
        betterPlayerDataSource: dataSource);
```

If you don't set aspectRatio is calculated like this:

```
width > height ? width / height : height / width;
```

**Comment by jhomlala** [comment]
Please check new release 0.0.15. There is a new `fit` option in configuration. This may solve your issue.

**Comment by engineerdeep** [comment]
Hey @jhomlala , thank you for better player first of all.

I have the exact same issue, I could set the aspect ratio of the video as mentioned in chewie but I just can't get it to work with BP. Fit does not help as the video size stays the same (16 / 9) regardless of the fit property. Would really appreciate your support on this please, thank you!

**Comment by Abacaxi-Nelson** [comment]
@engineerdeep same here.
I’m trying to show video fullscreen whatever device is.

i tried every combinaison of aspect ratio and fit.. no one set up the video full screen..

one thing that work is changing aspect ratio like for instance 9/19.. in iphone 12 looks good.. but not others

**Comment by postacik** [comment]
Hi,
I solved this problem like this:

Player widget in Scaffold:
```
        child: Center(
          child: AspectRatio(
            // aspectRatio: 16 / 9,
            aspectRatio: MediaQuery.of(context).size.width / MediaQuery.of(context).size.height,
            child: BetterPlayer(
              controller: _betterPlayerController!,
            ),
          ),
        ),
```
BetterPlayerController initialization:
```
    _betterPlayerController = BetterPlayerController(
        const BetterPlayerConfiguration(
          aspectRatio: 16 / 9,
          autoPlay: true,
          fit: BoxFit.cover, // If you want video to fill screen and crop if necessary use cover, if you want it just to fit the screen use contain
        ),
        betterPlayerDataSource: betterPlayerDataSource);

```

I hope it will be useful for someone else.
