### ISSUE TITLE
[BUG] does not play audio format (EAC3) 

### ISSUE THREAD

**Issue by lavara123** [jhomlala/betterplayer#508]
**Describe the bug**
eac3 not playing audio format, no sound

**To Reproduce**
Sample video link:
[https://samples.ffmpeg.org/A-codecs/AC3/eac3/channelcheck-ddplus_480.mp4](https://samples.ffmpeg.org/A-codecs/AC3/eac3/channelcheck-ddplus_480.mp4) 

sound in vlc

**Additional context**
Ffmpeg extension

[https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg)

**Comment by jhomlala** [comment]
Please use search: https://github.com/jhomlala/betterplayer/issues/121
