### ISSUE TITLE
[BUG] iOS only: some videos play sound only, screen is black

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#510]
I'll skip the details, because this is an official issue opened here: [flutter ticket](https://github.com/flutter/flutter/issues/28831).
There is also a fix [here](https://github.com/flutter/plugins/pull/1307). For some reason it doesn't get merged. I have experienced this bug and have tried the fix and it works.  
I'll submit a PR which applies this fix to BetterPlayer.

**Comment by jhomlala** [comment]
Thanks for PR, it will be added in next release.

**Comment by jhomlala** [comment]
Added in 0.0.69.

**Comment by maxakak1998** [comment]
I am still facing this problem with IOS platform
- IOS emulator: 11 - 13.2.2
- Flutter: 2.0.5 - Dart 2.12.3
![image](https://user-images.githubusercontent.com/50696626/122888873-7652d200-d36c-11eb-9ff6-2ee1e33def51.png)
![image](https://user-images.githubusercontent.com/50696626/122888916-81a5fd80-d36c-11eb-9f01-7ac071f01612.png)
Everything is fine but the black screen is showing
