### ISSUE TITLE
how to set Video Quality Options

### ISSUE THREAD

**Issue by ANDRUXUIS** [jhomlala/betterplayer#512]
Hi I was looking for how to set the quality options so I can select from like 360p or 480p, but when I click on the quality option it only shows " Auto "

how can I set the quality options

**Comment by jhomlala** [comment]
@ANDRUXUIS You should use discussion tabs to ask questions. Before asking for help, did you try to read manual in the main page of repository? Here is anwser: https://github.com/jhomlala/betterplayer#pass-multiple-resolutions-of-the-video

In the future, similar questions will be closed immediately.
