### ISSUE TITLE
A VideoPlayerController was used after being disposed.

### ISSUE THREAD

**Issue by mahboobahmed6577** [jhomlala/betterplayer#514]
I am using BetterPlayerListVideoPlayer in a list. There is floating action button which calls setState whenever clicked. So the issue is when I click on floating button then this crash occurs. 

The following assertion was thrown building BetterPlayerListVideoPlayer(state: _BetterPlayerListVideoPlayerState#b2631):
A VideoPlayerController was used after being disposed.

Once you have called dispose() on a VideoPlayerController, it can no longer be used.

Can you please help me with this..

**Comment by jhomlala** [comment]
This question was asked many times in the past. You're asking for help without:
* creating issue ticket properly
* checking history
* providing useful details.

Answer is simple: your video widget got rebuild which triggers dispose() of widget which triggers dispose of controller. Player widget shouldn't be rebuild by default. Anyway if you're doing something advanced with your widgets you can disable auto dispose.
