### ISSUE TITLE
[BUG] problems with fullscreen mode and portrait screens

### ISSUE THREAD

**Issue by Urkman** [jhomlala/betterplayer#515]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.
Yes, did it...

**Describe the bug**
The player does not return to portrait mode after Fullscreen.
The App should only use portrait and only landscape when playing videos...
Seems to work on android, but not on iOS...

**To Reproduce**
Use the code below.
1.) Start the video
2.) goto fullscreen
3.) end fullscreen

**Example code*
``` 
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp],
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MainPage(),
    );
  }
}

class MainPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Example player"),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Container(
            child: BetterPlayer.network(
              "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
              betterPlayerConfiguration: BetterPlayerConfiguration(
                aspectRatio: 16 / 9,
              ),
            ),
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Container(
                padding: EdgeInsets.all(10),
                child: Column(mainAxisAlignment: MainAxisAlignment.start, children: <Widget>[
                  Text(
                    "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
                    textAlign: TextAlign.center,
                  ),
                ]),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```
**Expected behavior**
The screen should return to portrait t mode after ending fullscreen.

**Screenshots**
Show the simulator after ending fullscreen...
![Simulator Screen Shot - iPhone 12 - 2021-06-01 at 22 25 03](https://user-images.githubusercontent.com/94297/120386631-2bbfd600-c329-11eb-812f-2fd69e454776.png)

**Flutter doctor**
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.5 20G5023d darwin-x64, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)

**Better Player version**
- Version: 0.0.66

**Smartphone (please complete the following information):**
 - Device: iPhone 12 (simulator)
 - OS: iOS 14.5

**Comment by Urkman** [comment]
And there are way problems with fullscreen :(
 - when playing a video in a bottomsheet
 - when using autodispose

I try to build a example project(and host it on github) tomorrow that shows all the problems...

**Comment by Urkman** [comment]
Here you can find a demo project, showing the problems with fullscreen mode:
https://github.com/Urkman/betterplayer_demo

Problems (iOS):
 - Not able to leave fullscreen (Clip Details Screen)
 - Not returning to portrait after fullscreen (Live Screen)
 - not stopping play when leaving a screen (Clip Details Screen)
 - strange behavior when using a bottom sheet (Clip Details Screen)
 
 Problems (Android)
 - Not able to start fullscreen (always switches back (Clip Details Screen)
 - not stopping play when leaving a screen (Clip Details Screen)
 - strange behavior when using a bottom sheet (Clip Details Screen)

On Android the switch back ti portrait works...  (Live Screen)

I hope you can help me out on this...

**Comment by SebastienBtr** [comment]
I have similar issues, I can't leave fullscreen on iOS, my app is also configured to be used in portrait. Currently the only workaround I found is to not allow landscape on fullscreen mode but it's definitely not great for users, ie:

`deviceOrientationsOnFullScreen: <DeviceOrientation>[
    DeviceOrientation.portraitUp
 ],`

**Comment by SebastienBtr** [comment]
Actually, it's still buggy even when I do what I mentioned above, I can't leave the fullscreen mode and go back to my view

**Comment by Urkman** [comment]
I hope that my demo project will help here :)

**Comment by SebastienBtr** [comment]
To implement a workaround I'd at least need a way to override the function when a user presses the fullscreen button. That way I could push a new page with the video taking all available space and use the back button in the app bar to go back to my regular view. But I don't see any param to do that unfortunately

**Comment by jhomlala** [comment]
I've did some basic checks and the issue is because full screen push is being closed immediately. This happens when Better Player is wrapped in Obx widget.

In BetterPlayer full screen route is opened with this code:
```dart
    await Navigator.of(context, rootNavigator: true).push(route);
```
Seems like GetX pops this route just after push. Better Player with Obx works fine.

**Comment by jhomlala** [comment]
@SebastienBtr Your issue may be solved already in this issue: https://github.com/jhomlala/betterplayer/issues/215

**Comment by jhomlala** [comment]
@Urkman 

Remove this line from your BetterPlayer widget:
```
 key: Globals().betterPlayerKey,
```
Seems like it's bugged with GetX.

Also add this to BetterPlayerConfiguration:

```dart
 deviceOrientationsAfterFullScreen: [DeviceOrientation.portraitUp,DeviceOrientation.portraitDown],
```

If you're want to have all orientations (portrait and horizontal) then use solution from issue linked above.

**Comment by Urkman** [comment]
@jhomlala Thanks for your help. With these changes, is works way better...

But the audio still keeps playing, when I leave a page...
Any suggestions for this?

`key: Globals().betterPlayerKey,`
I added these, to get PIP.

**Comment by Urkman** [comment]
I try to make use of `playerVisibilityChangedBehavior` this seems to work on push Routes.
But not on modal routes.
And it sometimes pauses the video on fullscreen change...

I updated to demo project with these changes...

**Comment by SebastienBtr** [comment]
@jhomlala Thanks I'll take a look at the issue you mentioned

**Comment by wizebaseLLC** [comment]
any update on this?  Receiving the same issue on iOS
