### ISSUE TITLE
[BUG] Playback speed set to 1.0 X after rewinding using seek bar

### ISSUE THREAD

**Issue by Andrii-Kichmarenko** [jhomlala/betterplayer#516]
**Describe the bug**
After setting the playback speed in the video, it returns to normal speed after rewinding back or forward using seek bar. The issue appears only on iOS.

**To Reproduce**
1. Open video
2. Play the video at 1.0 X playback speed.
3. Change the playback speed to 2.0 X.
4. Rewind back or forward using seekbar.

**Expected behavior**
Video is continuing to reproduce with 2.0 X playback speed.

**Actual behavior**
Video is reproducing with 1.0 X playback speed while 2.0 X is selected in the menu.

**Flutter doctor**
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.3.1 20E241 darwin-x64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)

**Better Player version**
- Version: 0.0.68

**Smartphone (please complete the following information):**
 - Device: iPhone8 emulator.
 - OS: iOS14.5

**Comment by jhomlala** [comment]
@Andrii-Kichmarenko I'm using same emulator on my side and everything works fine (I've checked it with example app within this repo). Maybe you could share your video?

**Comment by Andrii-Kichmarenko** [comment]
@jhomlala The issue reproduces also with the example app. 
Here is a recording - https://drive.google.com/file/d/1fJk6Rp0KICHhSU6CgFUyxsf8r4y0Xi_k/view?usp=sharing.

**Comment by jhomlala** [comment]
@Andrii-Kichmarenko Thanks for providing video. Seems like issue was with changing speed below 1.0 and seeking video.
This will be fixed with next release.

**Comment by Andrii-Kichmarenko** [comment]
Thank you very much @jhomlala!

I've just wanted to add. No matter what playback speed was set. It is always changed to 1.0 after the user rewinds back or forward using seek bar. It is difficult to recognize in the example project because the video is very dynamic.

**Comment by jhomlala** [comment]
Fixed in 0.0.70.
