### ISSUE TITLE
[BUG] [IOS ONLY] exception: cannot open file

### ISSUE THREAD

**Issue by SinoMiles** [jhomlala/betterplayer#517]
IOS can't play local video. but Android can play this.
```
      var file = File(savePath);
      var ex = file.existsSync();
      print(ex);//this will be true.
   var source =
          BetterPlayerDataSource(BetterPlayerDataSourceType.file, savePath);
      betterPlayerController.setupDataSource(source);
```

here is my video link 
https://drive.google.com/file/d/1e6hlZ2fJSubqHBWMcJCuOmlqG3urIs-2/view?usp=sharing

**Comment by jhomlala** [comment]
@SinoMiles Please start use issue templates. This is last warning.

Did you try at least use search? AVPlayer doesn't support playing .ts files: https://stackoverflow.com/questions/21237312/avplayer-play-ts-file

Android is backed with ExoPlayer which supports .ts.
