### ISSUE TITLE
[BUG][iOS ONLY] Blurred control configuration buttons.

### ISSUE THREAD

**Issue by antoniocranga** [jhomlala/betterplayer#518]
I've got these blurred icons only on iOS. The code seems to be fine, I tested it with a new fresh app and It  worked. Any solutions ?

Mention : I don't get any errors just blurred icons after the video is fully loaded and playing.

![Simulator Screen Shot - iPhone 11 Pro - 2021-06-02 at 14 11 55](https://user-images.githubusercontent.com/72743999/120477998-0e384e00-c3b5-11eb-9c73-f8158a6164a6.png)

**Comment by antoniocranga** [comment]
The code : 
```dart
void changeController(String link) {
    print("changeController");
    if (this.mounted) {
      setState(() {
        final data = link;
        betterplayerController = new BetterPlayerController(
            BetterPlayerConfiguration(
              autoPlay: true,
              aspectRatio: 4 / 3,
              //autoDispose: true,
            ),
            betterPlayerDataSource:
                BetterPlayerDataSource.network(data, liveStream: true));
      });
    }
  }
```

**Comment by jhomlala** [comment]
Do you have any plugin which does blur in your app? Without full reproducible example (whole project) I won't help you since you didn't provide any useful details. Code above looks generic and works fine. Please fill issue ticket properly (i.e. provide your device and reproducible code).

**Comment by antoniocranga** [comment]
This is the full code : https://pastebin.com/JKt0X2Cs
No I am not using any plugin which does blur.

**Comment by antoniocranga** [comment]
Recently I got this errors : 
The relevant error-causing widget was:
  CustomPaint
  file:///Users/crangaantonio/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.68/lib/sr
  c/controls/better_player_cupertino_progress_bar.dart:129:18

When the exception was thrown, this was the stack:
#2      _rrectIsValid (dart:ui/painting.dart:46:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:4207:12)
#4      _ProgressBarPainter.paint
(package:better_player/src/controls/better_player_cupertino_progress_bar.dart:189:12)
#5      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#6      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#9      _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7937:15)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#15     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#24     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#27     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2795:15)
#28     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#31     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7937:15)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#37     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#38     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:394:12)
#39     RenderBackdropFilter.paint (package:flutter/src/rendering/proxy_box.dart:1176:15)
#40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#42     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#43     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:394:12)
#44     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:486:7)
#45     RenderClipRRect.paint (package:flutter/src/rendering/proxy_box.dart:1538:23)
#46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#48     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#51     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7937:15)
#52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#54     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#57     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1016:17)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#60     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2795:15)
#61     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#64     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#67     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#73     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2795:15)
#74     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#75     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#78     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#79     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#81     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7937:15)
#82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#83     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#84     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#85     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#86     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#87     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#90     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#91     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:394:12)
#92     RenderVisibilityDetector.paint (package:visibility_detector/src/render_visibility_detector.dart:64:13)
#93     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)

**Comment by jhomlala** [comment]
Can you try remove everything from VIdeo Player except Better Player?

**Comment by antoniocranga** [comment]
I've tested the code on a dummy app and worked well. In my current app I've also implemented a dark/light mode changer, this is the MyApp widget. This might be the problem ? 
return ChangeNotifierProvider(
      create: (_) {
        return themeChangeProvider;
      },
      child: Consumer<DarkThemeProvider>(
          builder: (BuildContext context, value, Widget? child) {
        return MaterialApp(
          title: //,
          debugShowCheckedModeBanner: false,
          theme: Styles.themeData(themeChangeProvider.darkTheme, context),
          home: //,
        );
      }),
    );

**Comment by jhomlala** [comment]
@antoniocranga I don't know. I don't have access to your code. How can I help you if you didn't fill the issue ticket properly, didn't provide code which is reproducible. Don't provide code which isn't reproducible. Please provide code which or project which I can download and run on my side. Without this, debugging is a little bit useless. 

I provided you clue what you can do - strip your Video Screen from other widgets. As you said clear project works, so Better Player works fine. This not a Better Player issue rather problem with your project and code. Probably something interferes with Better Player controls causing this issue. Try to debug this issue by going step by step.

**Comment by antoniocranga** [comment]
I solved the issue by removing your BackdropFilter from Widgets.

**Comment by shimaatech** [comment]
Hi @antoniocranga 

I have the same issue. Could you please provide more details on how you solved this issue?

Thanks

**Comment by shimaatech** [comment]
The issue happened to me when showing banner ad on same screen of the video.
Removing BackDropFilter from the cupertino theme solved the issue.
@jhomlala Isn't this a bug in the better player cupertino theme?

**Comment by jhomlala** [comment]
@shimaatech Please try this:
```
better_player:
    git:
      url: https://github.com/jhomlala/betterplayer
      ref: feature/august_changes_2
```
