### ISSUE TITLE
video not disposing

### ISSUE THREAD

**Issue by ShyamKrishna122** [jhomlala/betterplayer#520]
I have a screen that has a vertical listview and its children are horizontal listview. I am using BetterPlayerListVideoPlayer in horizontal listview so when I scroll down my vertical listview I get the error "A VideoPlayerController was used after being disposed." also this error occurs when I move from this screen to any screen in the app.

How to solve this issue??

**Comment by jhomlala** [comment]
@ShyamKrishna122 Use issues properly. If you're asking for help then use discussions tab.

Use reusable video player to play videos in list: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list
