### ISSUE TITLE
Cant play Video from BetterPlayer.file [BUG]

### ISSUE THREAD

**Issue by laxkarparas1** [jhomlala/betterplayer#522]
this is throw this error 

E/ExoPlayerImplInternal(26481): Playback error
E/ExoPlayerImplInternal(26481):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(26481):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal(26481):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(26481):       at android.os.Looper.loop(Looper.java:225)
E/ExoPlayerImplInternal(26481):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(26481):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FragmentedMp4Extractor, Mp4Extractor, FlvExtractor, FlacExtractor, WavExtractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal(26481):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(26481):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1026)
E/ExoPlayerImplInternal(26481):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(26481):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(26481):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(26481):       at java.lang.Thread.run(Thread.java:919)
E/flutter (26481): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

**Comment by laxkarparas1** [comment]
I'm using simple method to play video

and my result.path is    ==   /sdcard/download/videodec.mp4

AspectRatio(
            aspectRatio: 16/9,
            child: BetterPlayer.file(
              result.path,
              betterPlayerConfiguration: BetterPlayerConfiguration(
                aspectRatio: 16 / 9,
              ),
            ),
          ),

**Comment by jhomlala** [comment]
@laxkarparas1 Please use issue template. If you're requesting for help then at least fill this ticket.

Can you confirm that you have access to that file `/sdcard/download/videodec.mp4`? You can do simple check with File class in dart.

**Comment by laxkarparas1** [comment]
i was using wrong encrypted url to play video.... 

now its working fine...

thanks for nice package
