### ISSUE TITLE
[BUG] BetterPlayerDataSourceType.memory.   (IOS)

### ISSUE THREAD

**Issue by KOSSHOH** [jhomlala/betterplayer#527]
An error occurs when I try to open data in memory or file BetterPlayerDataSourceType. It is only on iOS platform

`Unhandled Exception: PlatformException(VideoError, Failed to load video: Cannot Open, null, null)`

When I converted the video to byte without saving it and opened it in memory, it still gave an error in memory. It is only on iOS platform

**Comment by jhomlala** [comment]
Please use template for issue report. You need to provide additional details about your issue. Issues without any explanation will be ignored and closed. Please format your issue with the template provided in this repo.

**Comment by jhomlala** [comment]
Duplicate: https://github.com/jhomlala/betterplayer/issues/534
