### ISSUE TITLE
[BUG]HLS(m3u8) video is not working on iOS(Android is working)

### ISSUE THREAD

**Issue by upaychat** [jhomlala/betterplayer#531]
Blackscreen is shown.

 - Device: iPhone 12 Pro Max
 - OS: iOS 14.5

**Comment by jhomlala** [comment]
@gabrielginter Please use template for issue template. You need to provide additional details for bug report. Issues without any explanation will be ignored and closed. Please format your issue with the template provided in this repo.

**Comment by jhomlala** [comment]
Just tested latest BP release with both simulator and real device (iOS 14.x) and HLS videos are working fine. Please respect my time and fill the issue properly.

**Comment by kxmatejka** [comment]
@upaychat make sure cache is disabled for iOS
https://github.com/jhomlala/betterplayer/issues/461

**Comment by jhomlala** [comment]
No answer from author. Closing.
