### ISSUE TITLE
[FEATURE]Expose classes in ASMS folder

### ISSUE THREAD

**Issue by gabrielginter** [jhomlala/betterplayer#532]
**Is your feature request related to a problem? Please describe.**
I want to create my own UI to select tracks, instead of using the overflow menu. 

**Describe the solution you'd like**
Exposing the classes (or some of them) in the asms folder would allow developers to create their own UI for selecting tracks and audio tracks.
We have access to the following methods:

```dart
BetterPlayerController.setTrack(BetterPlayerAsmsTrack track)
BetterPlayerController.setAudioTrack(BetterPlayerAsmsAudioTrack audioTrack)
```

But no access to the classes 'BetterPlayerAsmsTrack ' or 'BetterPlayerAsmsAudioTrack '.

**Describe alternatives you've considered**
I use dynamic types a the moment but this can bring problems in the future and I have no good way to create an 'AUTO' video track without access to the class.

**Additional context**

**Comment by jhomlala** [comment]
@gabrielginter Please use template for feature request. You need to provide additional details why do you need that. Issues without any explanation will be ignored.

**Comment by gabrielginter** [comment]
@jhomlala formating done and more information provided

**Comment by jhomlala** [comment]
Added in 0.0.70.
