### ISSUE TITLE
[FEATURE] Method in BetterPlayerController to open the 'overflowMenu'

### ISSUE THREAD

**Issue by gabrielginter** [jhomlala/betterplayer#533]
**Is your feature request related to a problem? Please describe.**
I want to create my own button to open the overflow menu, allowing me more customization. But at the moment I can't trigger the menu from the controller, forcing me to rely on the button on the player.

**Describe the solution you'd like**
Would be great to have a method to trigger this menu programmatically allowing us to hide the overflowMenu button.

**Describe alternatives you've considered**
An alternative would be to let customize the overflowMenu button with our own Widget instead of just being able to change the icon, although it doesn't really solve the problem, it helps.

**Additional context**

**Comment by jhomlala** [comment]
@gabrielginter Please use template for feature request. You need to provide additional details why do you need that. Issues without any explanation will be ignored and closed. Please format your isssue with the template provided in this repo.

**Comment by gabrielginter** [comment]
@jhomlala formating done and more information provided

**Comment by jhomlala** [comment]
Added support for open overflow menu in 0.0.70.

**Comment by APWHY** [comment]
For anyone else coming here after trying to do the same, you can open the overflow menu by extending `BetterPlayersControlState` [(here)](https://pub.dev/documentation/better_player/latest/better_player/BetterPlayerControlsState-class.html) in the relevant `State` class and then calling `onShowMoreClicked()` in your callback.

**Comment by iMro0t** [comment]
I managed to get it working by using `GlobalKey`

```dart
import 'package:better_player/src/controls/better_player_material_controls.dart';
```

```dart
GlobalKey<BetterPlayerControlsState> _globalKey = GlobalKey();
_controlsConfiguration = BetterPlayerControlsConfiguration(
        enableOverflowMenu: true,
        playerTheme: BetterPlayerTheme.custom,
        customControlsBuilder: (controller, onPlayerVisibilityChanged) =>
              BetterPlayerMaterialControls(
                  key: _globalKey,
                  onControlsVisibilityChanged: onPlayerVisibilityChanged,
                  controlsConfiguration: _controlsConfiguration,
              ),
);
```

Now you can directly call `onShowMoreClicked` function

```dart
_globalKey.currentState?.onShowMoreClicked();
```
