### ISSUE TITLE
BUG] BetterPlayerDataSourceType.memory. (IOS)

### ISSUE THREAD

**Issue by KOSSHOH** [jhomlala/betterplayer#534]
**Describe the bug**
An error occurs when I try to open data in memory or file BetterPlayerDataSourceType. It is only on iOS platform

**To Reproduce**
1. Send request https for video.
2. Convert response bytes.
3. Open better_player from memory 
4. Error

**Example code*
```
BetterPlayerDataSource betterPlayerDataSource =
                  BetterPlayerDataSource(
                BetterPlayerDataSourceType.memory,
                "",
                bytes: list,
                liveStream: true,
              );
              _betterPlayerController = BetterPlayerController(
                BetterPlayerConfiguration(),
                betterPlayerDataSource: betterPlayerDataSource,
              );
```

**Expected behavior**
Open memory type in better_player.

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.2 20D80 darwin-arm, locale en-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)
```

**Better Player version**
- Version: ^0.0.69

**Smartphone (please complete the following information):**
 - OS: [IOS all version]

**Additional context**
When I converted the video to byte without saving it and opened it in memory, it still gave an error in memory. It is only on iOS platform
`Unhandled Exception: PlatformException(VideoError, Failed to load video: Cannot Open, null, null)`

**Comment by jhomlala** [comment]
What's the format of video? If it's HLS (m3u8) video then it can't be opened from file. https://developer.apple.com/forums/thread/69357

**Comment by jhomlala** [comment]
No answer from author. Closing.
