### ISSUE TITLE
[ISSUE] does not display video when the app is downloaded from the internet

### ISSUE THREAD

**Issue by i9suaradio** [jhomlala/betterplayer#536]
I'm having a problem with better_player when submitting the app to the playstore or when I download via download and install. 
The application does not display the video in release mode, in debug mode it works perfectly.

![WhatsApp Image 2021-06-05 at 19 52 13](https://user-images.githubusercontent.com/5317297/120907617-59fb2980-c639-11eb-8a48-1f69f87dd190.jpeg)

Downloading via PlayStore or Downloading and installing it on the device, it doesn't display the video (only a gray screen), but I can hear the streaming audio. See below

![WhatsApp Image 2021-06-05 at 19 52 35](https://user-images.githubusercontent.com/5317297/120907616-59629300-c639-11eb-9ced-fd148f896e3f.jpeg)

In cable debug mode, it works perfectly displaying both audio and video. See below
![WhatsApp Image 2021-06-05 at 19 59 59](https://user-images.githubusercontent.com/5317297/120907613-5798cf80-c639-11eb-95d1-1d2c5925f23a.jpeg)

Am I missing something to enable video when the app is being downloaded from the internet or store?

Can someone help me?

**Comment by jhomlala** [comment]
Did you see: https://github.com/jhomlala/betterplayer/issues/535?
Please format your issue ticket properly.

This issue may be connected with missing permissions:
```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
```
Check if you have these permissions in AndroidManifest.xml in your release APK.

**Comment by i9suaradio** [comment]
worked perfectly!!!!
Thank you @jhomlala!!!!

**Comment by Letalus** [comment]
@i9suaradio don't forget to close the issue if it has been resolved ;)
