### ISSUE TITLE
How to get full video duration

### ISSUE THREAD

**Issue by CalmAndCoDe** [jhomlala/betterplayer#54]
Hi, i'm using this package in a project that i need to redesign the controls based on UI so i have decided to do it manually and the problem is that i don't know how can i show the full video duration at the start, is there anyway to do this ?
Thanks

**Comment by AhmedNourJamalElDin** [comment]
.

**Comment by amontin** [comment]
Deduced from looking at the source code:

`_betterPlayerController.videoPlayerController.value.duration`

**Comment by joseespana** [comment]
This return to 0.0.00 why?
