### ISSUE TITLE
How to show control bar long time like 3 seconds or 4 seconds when user tap on video player?

### ISSUE THREAD

**Issue by simp13** [jhomlala/betterplayer#541]
How to show control bar long time like 3 seconds or 4 seconds when user tap on video player?

I try controlhidetimes but it only disappear slowly but I want to show control bar 3 or 4 seconds when user click on player after that control bar disappear immediately.How can I do that?

Could you please tell me how to do that?

**Comment by jhomlala** [comment]
Please follow issues policy: https://github.com/jhomlala/betterplayer/issues/535

Answer from @lavara123 is the correct one.
