### ISSUE TITLE
[BUG] 5 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by xlcod** [jhomlala/betterplayer#542]
**History check**
Nothing to see

**Describe the bug**
I just created a new proyect with swift , if i install and run the application doesn´t compile

**To Reproduce**
1 j-ust create a new proyect , install the pod, and in my case deactivate bitcode because of another error

**Screenshots**
![Captura de pantalla 2021-06-08 a las 10 26 20](https://user-images.githubusercontent.com/44270692/121204651-50f79b80-c877-11eb-96df-484c5d0744e0.png)

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.3.1 20E241 darwin-arm, locale
    es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
    ! Error: iPhone 12 de Álvaro is busy: Copying cache files from device. Xcode
      will continue when iPhone 12 de Álvaro is finished. (code -10)

! Doctor found issues in 1 category.

**Better Player version**
- Version: 0.0.61

**Smartphone (please complete the following information):**
 - Device: Iphone 12
 - OS: IOS 14.5

**Comment by jhomlala** [comment]
@xlcod 
You're using old Flutter version (1.2.6) with old Better Player version (0.0.61) with latest XCode (12.5). Please try upgrade to latest Flutter stable version and latest Better Player version. This should solve your issue.
