### ISSUE TITLE
i did to tested reusable_list_video, i have a prolen when show full screen. one more thing, i want to pause last video when i play new video. thank for read!

### ISSUE THREAD

**Issue by gamestap99** [jhomlala/betterplayer#543]
**Flutter doctor**
![image](https://user-images.githubusercontent.com/43195138/121312057-33860880-c92f-11eb-944f-61cf166282ea.png)

**Better Player version**
- Version: 0.0.69

**Smartphone (please complete the following information):**
 - Device: RMX1911

**Additional context**

**Comment by jhomlala** [comment]
@gamestap99 Please fill issue ticket properly. Issue title isn't the place where you should describe your issue. Add more detailed info in issue body.
