### ISSUE TITLE
VideoController is disposed on list scroll

### ISSUE THREAD

**Issue by RalphMarvin** [jhomlala/betterplayer#55]
I get '`A VideoPlayerController was used after being disposed. Once you have called dispose() on a VideoPlayerController, it can no longer be used`'.

I have a bunch of videos inside a list, my list is actually not only made up of videos but other text data. Its a list of posts, some posts are videos some are not.  I have a code that checks if the current item in the viewport is a video while scrolling, then i auto play the video. the above error is thrown when i scroll past a video and then scroll back to that video to play it again.

I don't have anything in my dispose method.

**Comment by jhomlala** [comment]
Should be fixed with version 0.0.14.
