### ISSUE TITLE
对于有中文的视频地址 无法播放[BUG]

### ISSUE THREAD

**Issue by 979881765** [jhomlala/betterplayer#550]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SinoMiles** [comment]
我就服直接发中文的。。。

**Comment by 979881765** [comment]
编码过后传的

**Comment by jhomlala** [comment]
@979881765 Please use english when you're trying to report an issue. Not everyone understand chinese. Also follow issue policy: https://github.com/jhomlala/betterplayer/issues/535
