### ISSUE TITLE
[FEATURE] A way to listen to the position

### ISSUE THREAD

**Issue by MiroLiebschner** [jhomlala/betterplayer#552]
Run custom code when a specific audio / video position was reached is really hard right now. 

A solution I would like is a listener that gives the position once every millisecond.

Right now I check twice a second if second X is reached. This is not optimal, especially since I would like to check for milliseconds. 

If there is already a solution in place that I missed please point me in a direction. I got no answer on this in the discussion forum (yet).

**Comment by shilangyu** [comment]
It is possible to listen the the position, though it is fired pretty rarely (about once every 600ms)

```dart
BetterPlayerConfiguration(
  eventListener: (e) {
    switch (e.betterPlayerEventType) {
      case BetterPlayerEventType.progress:
        final progress = e.parameters!['progress']! as Duration;
        print(progress);
        break;
      default:
        break;
    }
  },
// ...
)
```

I am also interested in a way to get notified more often as I want to render a custom progress bar.

**Comment by MiroLiebschner** [comment]
Thank you very much I missed those options. 300ms might work for our usecase. A solution that would listen every 25ms would be even better so we could have frame perfect stop points.
