### ISSUE TITLE
I am requesting for Chromecast 

### ISSUE THREAD

**Issue by pranjaljain011** [jhomlala/betterplayer#553]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kxmatejka** [comment]
There is already an open issue #64

**Comment by jhomlala** [comment]
@pranjaljain011 First read issues policy in the top of issues section. Second use search function to find if same issue exists.

Closed.
