### ISSUE TITLE
combine video with audio Tracks

### ISSUE THREAD

**Issue by Joseph-Nathan** [jhomlala/betterplayer#554]
is that possible to play video  from url , and play audio  from an other url in same time .
i have videos that audios for that video  spited (many audio  Language in mp3 , acc  );

```
BetterPlayer.network(
          _videoURL ,
          audioSource : _ audioURL  ,
          betterPlayerConfiguration: BetterPlayerConfiguration(
            aspectRatio: 16 / 9,
          ),
        ),
```

**Comment by jhomlala** [comment]
Please follow issue template next time: https://github.com/jhomlala/betterplayer/issues/535

There's no way to use different audio url. Video and audio source should be in one resource.
