### ISSUE TITLE
[BUG] time position is not being updated

### ISSUE THREAD

**Issue by FelipeFernandesLeandro** [jhomlala/betterplayer#562]
**Describe the bug**
The 'time position' is not being updated after the video is finished then reposition it's seek bar.

**To Reproduce**
1. Start a video
2. Drag the seek bar close to it's end then let it finish
3. While the video is stoped after it's finished drag the seek bar again in another position
4. The video will continue to run in this new position but the 'time position' text won't be updated anymore

**Expected behavior**
'time position' text should be constantly updated.

**Flutter doctor**
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1052], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition
[√] Connected device (3 available)

**Better Player version**
- Version: 0.0.59

**Smartphone (please complete the following information):**
 - Device: [moto g60]
 - OS: [android 11]

**Comment by jhomlala** [comment]
Fixed in 0.0.70.
