### ISSUE TITLE
[DOCUMENTATION] Manual controller disposal

### ISSUE THREAD

**Issue by LastxTemplar** [jhomlala/betterplayer#564]
The question about disposing of the controller is asked a lot of times, especially when the error says:
`A VideoPlaverController was used after being disposed`. 

Better Player is great that it disposes automatically but there are use cases when you need to use manual disposal. It took me a while to find this solution but it would be awesome to actually have it in the readme or the documentation somewhere:

```
void changeSource(String url) {
  if (betterPlayerController != null) {
    betterPlayerController!.pause();

    final oldController = betterPlayerController!.videoPlayerController;

    WidgetsBinding.instance!.addPostFrameCallback((_) async {
      await oldController!.dispose();

      // Initing new controller
      var config = BetterPlayerConfiguration(
        aspectRatio: 16 / 9,
        autoPlay: true,
        autoDispose: false
      );

      var source = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        url
      );

      betterPlayerController = BetterPlayerController(config);
      betterPlayerController!.setupDataSource(source);
    });
    betterPlayerController = null;
  }  
}
```

**Comment by Williano** [comment]
Please were you using this in a list view?

**Comment by LastxTemplar** [comment]
Yes, in case you want to change the source then this needs to be called when you tap on a card in the list or similar component.

**Comment by Williano** [comment]
Okay, thank you.

I am trying to implement a list view of videos that will auto play immediately the card is 100% visible when the user scrolls.


Please is it possible to share the full code of your implementation with me?
Thank you

**Comment by LastxTemplar** [comment]
Unfortunately I can't share my code, but it's really not that complicated. attach this method to your onTap in the list view and send the new url to the method. The `betterPlayerController` here is your actual player controller.

**Comment by Williano** [comment]
Great 👍.

Thank you very much for the tip

**Comment by jhomlala** [comment]
Added documentation in https://jhomlala.github.io/betterplayer/#/manualdispose
