### ISSUE TITLE
[DOCUMENTATION] Error handling for setupDataSource()

### ISSUE THREAD

**Issue by LastxTemplar** [jhomlala/betterplayer#565]
Experienced developers would know that `setupDataSource` returns a future and that it can be used to handle errors like a source url being invalid, but this is not mentioned in the docs and I could not find an example for this. This would be a nice a addition to the docs showing how to handle an invalid source without listening to `events` or similar:

```
betterPlayerController!.setupDataSource(source)
.then((response) {
  // Source loaded successfully
  videoLoading = false;
})
.catchError((error) async {
  // Source did not load, url might be invalid
  inspect(error);
});
```

**Comment by jhomlala** [comment]
Added documentation in https://jhomlala.github.io/betterplayer/#/sourceload
