### ISSUE TITLE
[FEATURE] Lazy init setupDataSource

### ISSUE THREAD

**Issue by vanfresh** [jhomlala/betterplayer#567]
**Is your feature request related to a problem? Please describe.**
I have a chat screen with many HLS video messages.  
I don't want the datasource to initialize before the user clicks play since there can be hundreds of video messages in one chat screen. 
However, if I don't setup datasource, the controls are not laid out. 

**Describe the solution you'd like**
I want datasource to be lazy init until the user clicks play on a message.  

**Describe alternatives you've considered**
I tried `setControlsAlwaysVisible` but doesn't work without datasource.

**Comment by jhomlala** [comment]
It's useless to show controls without initializing data source. Anyway if you really want to show controls without data source,  you should just wrap Better Player in Stack widget and simply add some fake controls over Better Player widget. Once user clicks on these controls, then setup data source in `BetterPlayerController`.
