### ISSUE TITLE
[BUG] Error enabling use cache with network video data source

### ISSUE THREAD

**Issue by JosueMCapita** [jhomlala/betterplayer#568]
**History check**
I didn't find anything which may solve this issue.

**Describe the bug**
After updating to the latest version of the package, I found out that it is now possible to enable cache to network source videos. Without enabling it is working fine, but when I enabled it for the first time the video just doesn't reproduce.

**To Reproduce**
1. After just adding this `cacheConfiguration: BetterPlayerCacheConfiguration(useCache: true),`
2.
```
I/System.out(17652): (HTTPLog)-Static: isSBSettingEnabled false
E/ExoPlayerImplInternal(17652): Playback error
E/ExoPlayerImplInternal(17652):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal(17652):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(17652):       at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal(17652):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(17652):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 502
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:54)
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:764)
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1015)
E/ExoPlayerImplInternal(17652):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(17652):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/ExoPlayerImplInternal(17652):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/ExoPlayerImplInternal(17652):       at java.lang.Thread.run(Thread.java:762)
```

**Example code**
```
BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
  BetterPlayerDataSourceType.network,
  widget.videoUrl,
  cacheConfiguration: BetterPlayerCacheConfiguration(useCache: true),
  notificationConfiguration: BetterPlayerNotificationConfiguration(
    showNotification: false,
    title: "Some title",
    author: "Some author",
  ),
);
```

**Expected behavior**
That the video would be cached.

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.1052], locale pt-PT)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

**Better Player version**
- Version: 0.0.70

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Grand Prime Pro
 - OS: Android 7.1.1

**Additional context**
Nothing else.

**Comment by jhomlala** [comment]
@JosueMCapita Thanks for reporting this issue, but I can't reproduce it on my side. Can you provide video which fails on your side?

**Comment by jhomlala** [comment]
No answer from author. Closed.
