### ISSUE TITLE
[BUG] IOS can't set speed.

### ISSUE THREAD

**Issue by SinoMiles** [jhomlala/betterplayer#574]
**History check**
I have checked issues history and didn't find anything which may solve my issue.

**Describe the bug**
Only ios can't set speed

**To Reproduce**
//1.set network dataSource
 'https://cache1.parwix.com:4433/cache/iqiyi/d1684cfa3aa8423098b804ef6a7a434c.m3u8'
//2.add a double-tap gesture to invoke setSpeed method
//3.return this video cannot be played fast forward

**Example code*
```
betterPlayerController.setSpeed(2);
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9588025/123413720-ace75180-d5e5-11eb-9bb9-9101c215c3db.png)

**Flutter doctor**  
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.1 20D75 darwin-x64, locale
    en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

**Better Player version**
- Version:
-     better_player: ^0.0.70

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12 mini]
 - OS: [e.g. iOS14.5]

**Additional context**

**Comment by mohankr123** [comment]
Same issue. Not able to set playback speed on IOS.

**Comment by sunejask** [comment]
I have the same problem on iOS.

**Comment by jhomlala** [comment]
This is not a bug. For some videos AVPlayer can't apply speed and you will see this error in console.

**Comment by mohankr123** [comment]
Playback speed not working on IOS with EZDRM.
Getting error when trying to set speed

`_videoPlayerController!.setSpeed(2.0);`

Error :- 

`[VERBOSE-2:ui_dart_state.cc(199) Unhandled Exception: PlatformException(unsupported_fast_forward, This video cannot be played fast forward, null, null)
#0      StandardMethodCodec.decodeEnvelope
#1      MethodChannel._invokeMethod
<asynchronous suspension>
#2      VideoPlayerController._applySpeed
<asynchronous suspension>
#3      VideoPlayerController.setSpeed
<asynchronous suspension>`


Please help.

**Comment by mohankr123** [comment]
After removing conditions "_player.currentItem.canPlayFastForward" from BetterPlayer.m file, Playback speed working for me.

Change from
` } else if ((speed > 1.0 && _player.currentItem.canPlayFastForward) ||
               (speed < 1.0 && _player.currentItem.canPlaySlowForward)) {
        _playerRate = speed;
        result(nil);
    } else {`

to
` } else if ((speed > 1.0) ||
               (speed < 1.0)) {
        _playerRate = speed;
        result(nil);
    } else {`

**Comment by juzejunior** [comment]
@mohankr123 solution, works perfect here, playing HLS video. Thanks!

**Comment by blueeyestw** [comment]
> After removing conditions "_player.currentItem.canPlayFastForward" from BetterPlayer.m file, Playback speed working for me.
> 
> Change from ` } else if ((speed > 1.0 && _player.currentItem.canPlayFastForward) || (speed < 1.0 && _player.currentItem.canPlaySlowForward)) { _playerRate = speed; result(nil); } else {`
> 
> to ` } else if ((speed > 1.0) || (speed < 1.0)) { _playerRate = speed; result(nil); } else {`

how do I edit the native source code?

**Comment by Invincible1996** [comment]
@blueeyestw Fork this repository and you can edit in your project

**Comment by neeluagrawal04** [comment]
@jhomlala after making these change in ios/Classes/BetterPlayer.m file still the player speed is not working when setting the speed greater than 1.0x. Kindly re-check the functionlity once
