### ISSUE TITLE
FairPlay EZDRM Licence URL

### ISSUE THREAD

**Issue by mohankr123** [jhomlala/betterplayer#575]
How can I send parameter licenseUrl in case of fairplay EZDRM.

Please help.

**Comment by jhomlala** [comment]
@mohankr123 You didn't fill issue ticket properly. Please correct your issue.

Right now Better Player doesn't support custom license url for EZDRM. Can you explain why do you need custom license url and why you can't use hardcoded one which is `https://fps.ezdrm.com/api/licenses`?

**Comment by mohankr123** [comment]
Thank you for your reply.

I am using EZDRM with Wowza Streaming Engine.
When I am trying to play video, better player can not extract
correct license URL.
That's why video is not playing. I also need custom data parameter for user
identification  like
https://fps.ezdrm.com/api/licenses/09cc0377-6dd4-40cb-b09d-XXXXXXXX?customdata1=123?customdata2=345&ClientIP=12.34.567.89

When I hardcode license URL in BetterPlayerEzDrmAssetsLoaderDelegate.m then
video  playing fine.

**Comment by jhomlala** [comment]
@mohankr123 Now it's clear for me. I'll add support for license url in next release(s).

**Comment by jhomlala** [comment]
Support for license URL will be added in next BP version.

**Comment by jhomlala** [comment]
Added in latest release.
