### ISSUE TITLE
[FEATURE] Advice long feed of videos

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [jhomlala/betterplayer#578]
Hi,
Thanks a lot for your work, and sorry to not folowing one of your template, but im looking for advices and feedback.

Use case: feed of video like tiktok.

From your hard work, will you advice to:
- init, create and dispose each betterplayer
- or use strategy you already implement in one of your example. Having a list of betterplayer, and use them

Video are in hls format.

Best regards,
Nelson

**Comment by jhomlala** [comment]
For long video list use reusable video list. Here's an example how to do that: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list
