### ISSUE TITLE
Is it possible to restrict simultanious playing of 2 or more players inside listView?

### ISSUE THREAD

**Issue by RomanShtyk** [jhomlala/betterplayer#58]
Is it possible to restrict simultaneous playing of 2 or more players inside listView? e.g. it should be like in Coub app, where there is only one player can be playing at a time.

**Comment by jhomlala** [comment]
Hi @RomanShtyk,
please check playFraction parameter of BetterPlayerListVideoPlayer.

```
  ///Fraction of the screen height that will trigger play/pause. For example
  ///if playFraction is 0.6 video will be played if 60% of player height is
  ///visible.
  final double playFraction;
```
If properly configured, BetterPlayer will auto play/pause videos in your list.
You should consider making videos enough big, that it will trigger playFraction properly. Please check example app here: https://github.com/jhomlala/betterplayer/tree/master/example
