### ISSUE TITLE
[BUG] A BetterPlayerController was used after being disposed.

### ISSUE THREAD

**Issue by mimi-tech** [jhomlala/betterplayer#580]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LastxTemplar** [comment]
@mimi-tech , please respect the author's time, this issue is garbage, you didn't even take the time to put minimal effort in describing your issue.

**Comment by jhomlala** [comment]
Author didn't fill issue ticket properly. Closed.
