### ISSUE TITLE
IOS black screen

### ISSUE THREAD

**Issue by getpu** [jhomlala/betterplayer#581]
I used latest 0.70 version, ios emulator 14.5, and between times system breakdown,  audio normal， fultter official video player it works normally.

**Comment by LastxTemplar** [comment]
Please use the template for bugs as described when creating an issue. You need to provide some workable code.

**Comment by getpu** [comment]
class _GalleryVideoViewPageState extends State<GalleryVideoViewPage> {
  late BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      fit: BoxFit.cover,
      // aspectRatio: 1,
      autoPlay: true,
      looping: true,
      controlsConfiguration: BetterPlayerControlsConfiguration(
        enablePlaybackSpeed: false,
        enableSkips: false,
        enableMute: false,
        showControls: false,
        enableSubtitles: false,
        enableQualities: false,
        enableOverflowMenu: false,
        enableFullscreen: false,
        enablePip: false,
        backgroundColor: Colors.transparent,
      ),
    );
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      widget.url,
      cacheConfiguration: BetterPlayerCacheConfiguration(useCache: true),
    );
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(dataSource);
    _betterPlayerController.addEventsListener((BetterPlayerEvent event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.initialized) {
        _betterPlayerController.setOverriddenAspectRatio(
            _betterPlayerController.videoPlayerController!.value.aspectRatio);
      }
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        child: Container(
          color: Colors.black,
          width: double.infinity,
          height: double.infinity,
          child: Stack(
            children: [
              Hero(
                tag: widget.tag ?? widget.url,
                child: BetterPlayer(controller: _betterPlayerController),
              ),
            ],
          ),
        ),
        onTap: () {
          Navigator.pop(context);
        },
      ),
    );
  }

  @override
  void dispose() {
    _betterPlayerController.dispose();
    super.dispose();
  }
}

This code before version it's normally work.  update after not work, return back version not work meet too.

**Comment by getpu** [comment]
I used it temporarily video player repair this issue, I hope better better better...

```
class _GalleryVideoViewPageState extends State<GalleryVideoViewPage> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
  }

  Future<void> _future() async {
    File file = await DownloadManager.getVideoFile(widget.url);
    _controller = VideoPlayerController.file(file)
      ..setLooping(true)
      ..play();
    return _controller.initialize();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        child: Container(
          color: Colors.black,
          width: double.infinity,
          height: double.infinity,
          child: Stack(
            children: [
              Hero(
                tag: widget.tag ?? widget.url,
                child: FutureBuilder(
                  future: _future(),
                  builder: (ctx, snp) {
                    if (snp.connectionState == ConnectionState.done) {
                      return Center(
                        child: AspectRatio(
                          aspectRatio: _controller.value.aspectRatio,
                          child: VideoPlayer(_controller),
                        ),
                      );
                    }
                    return _buildLoading();
                  },
                ),
              ),
            ],
          ),
        ),
        onTap: () {
          Navigator.pop(context);
        },
      ),
    );
  }

  Widget _buildLoading() {
    return Container(
      child: Center(
        child: SizedBox(
          height: 50,
          width: 50,
          child: CircularProgressIndicator(
            strokeWidth: 3,
            color: Color(0xFFFFFFFF),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}
```

**Comment by pratikbaid3** [comment]
I am experiencing the same issue. The audio works fine but for some reason, there is no video

**Comment by jhomlala** [comment]
@getpu I've run your first code and video was displayed correctly:

![flutter_02](https://user-images.githubusercontent.com/1329033/124892000-c327e100-dfd9-11eb-9d80-3376934105d5.png)

You didn't fill issue ticket properly, so I don't know which Flutter version did you use. 

@pratikbaid3 Create issue ticket with issue template rather than complain that something is not working on your side. Without any details there's no chance to help you.

**Comment by jhomlala** [comment]
No answer from author. Closed.
