### ISSUE TITLE
When it vertical mode, it doesn't work full screen

### ISSUE THREAD

**Issue by KadriyeMacit** [jhomlala/betterplayer#582]
While it is horizontal screen, it works full screen. But the video on the vertical screen; first turns sideways, then becomes a black screen and broken.

I tried on iphone 11.

<img width="1267" alt="Ekran Resmi 2021-06-29 14 12 44" src="https://user-images.githubusercontent.com/13748518/123788035-351a6f00-d8e4-11eb-9dd4-f4f5d963e366.png">

Flutter doctor:
<img width="696" alt="Ekran Resmi 2021-06-29 14 19 45" src="https://user-images.githubusercontent.com/13748518/123788795-19fc2f00-d8e5-11eb-8f8d-8929aee86ea1.png">

**Comment by KadriyeMacit** [comment]
Also, again when i did fullScreenByDefault: true, i got this error. How can i fixed it?
 

<img width="1009" alt="Ekran Resmi 2021-06-29 14 39 28" src="https://user-images.githubusercontent.com/13748518/123791584-4d8c8880-d8e8-11eb-8477-ee43199a5dd9.png">

**Comment by LastxTemplar** [comment]
@KadriyeMacit please provide some workable code as described in the Bugs template:
`Paste here your minimal reproducible code. This code should be ready to copy-paste-run.`

there's nothing we can help you with just by looking at those errors.

Also please describe what exactly are you trying to do, you want the player to be fullscreen no matter what the orientation of the device is?

**Comment by KadriyeMacit** [comment]
@LastxTemplar 

This is the code i use:

BetterPlayerPlaylist(
            betterPlayerConfiguration: BetterPlayerConfiguration(
                autoPlay: true,)
            betterPlayerPlaylistConfiguration:
                BetterPlayerPlaylistConfiguration(),
            betterPlayerDataSourceList: createDataSet())

It doesn't notify device orientation changes. Let try to full screen when you use portrait mode then quit to full screen when you use landscape mode. This is error reason.

**Comment by jhomlala** [comment]
@KadriyeMacit This is definitely not a minimal reproducible example. https://en.wikipedia.org/wiki/Minimal_working_example

You should provide example which can be copy and run without any changes. This code is only some part of your problem which won't let me debug your issue. If you really need help then at least create some working example. 

If you won't provide example which I can run, I'll close issue. Debugging issue with screenshots and some part of code is not possible.

**Comment by jhomlala** [comment]
No answer from author. Closed.
