### ISSUE TITLE
I want change the button background

### ISSUE THREAD

**Issue by YeFei572** [jhomlala/betterplayer#588]
How can I change the background of the control panel to transparent 
![image](https://user-images.githubusercontent.com/26360338/124359501-ed834280-dc57-11eb-958d-5adf9cec9466.png)
 
Here is my code : 
```dart
betterPlayerController = BetterPlayerController(
          BetterPlayerConfiguration(
            fit: BoxFit.fitHeight,
            autoPlay: true,
            subtitlesConfiguration: BetterPlayerSubtitlesConfiguration(),
            controlsConfiguration: BetterPlayerControlsConfiguration(
              enableMute: true,
              controlBarColor: Colors.transparent,
              controlBarHeight: 50.w,
              forwardSkipTimeInMilliseconds: 30000,
              backwardSkipTimeInMilliseconds: 15000,
              enablePlayPause: false,
              controlsHideTime: Duration(seconds: 1),
              playerTheme: BetterPlayerTheme.cupertino,
            ),
          ),
          betterPlayerDataSource: betterPlayerDataSource,
        );
```

**Comment by jhomlala** [comment]
Please fill issue ticket properly and follow this policy: https://github.com/jhomlala/betterplayer/issues/535

Just change `controlBarColor` in `BetterPlayerControlsConfiguration` to your desired color.

**Comment by YeFei572** [comment]
Sorry about I haven't written the issue use the template first.
Maybe I didn't express my question.
I want to remove the Gaussian Blur.

I have set the `controlBarColor` to  `Colors.transparent`, but it doesn't work
