### ISSUE TITLE
[BUG] Video starts playing when onSeek is used even if video was paused before

### ISSUE THREAD

**Issue by Letalus** [jhomlala/betterplayer#589]
**Describe the bug**
When I click on the basic video within the example app and click on the pause button the video pauses. Now when I use the seekTo Widget and seek to second X the video starts playing automatically. The expected behavior would be that the video is still paused until I unpause it.

This bug can be reproduced with the basic player within the example.

Important: This is an iOS bug only. On Android this bug does not appear. Only on iOS the video player starts playing when seeking to a specific position

**Comment by jhomlala** [comment]
Will be fixed with next release.

**Comment by jhomlala** [comment]
Fixed in 0.0.71.
