### ISSUE TITLE
Seek a BetterPlayerListVideoPlayer

### ISSUE THREAD

**Issue by nicholascioli** [jhomlala/betterplayer#59]
As it stands, the BetterPlayerListVideoPlayerController is missing feature parity with the underlying BetterPlayerController. 

Maybe add a way to expose the underlying controller? Something like:

```dart
// Somewhere in better_player_list_video_player_controller.dart
BetterPlayerController get controller => _betterPlayerController;
BetterPlayerController set controller(BetterPlayerController c) => _betterPlayerController = c;
```

I can make a pull request, if that would be easier.

**Comment by jhomlala** [comment]
Added seekTo to BetterPlayerListVideoPlayerController in version 0.0.14.
