### ISSUE TITLE
How can I put the video controls at the bottom of the screen without changing the actual video aspect ratio or alignment?

### ISSUE THREAD

**Issue by pintalubaf** [jhomlala/betterplayer#590]
For example I want to have a landspace video play just like that, and the controls shows inside the video at the bottom, I want to have the video controls at the bottom of the whole screen, not inside the video container.

Is there a current way to do this? If not, this is a much needed feature!

Thank you.

**Comment by jhomlala** [comment]
You need to use aspect ratio to set controls on the bottom. 
Please follow this policy https://github.com/jhomlala/betterplayer/issues/535 when you're requesting for help. If you fill that this is bug, then use issue template.
