### ISSUE TITLE
It's should be have zoom in or zoom out.

### ISSUE THREAD

**Issue by Pisey-Nguon** [jhomlala/betterplayer#591]
I saw the youtube is can zoomed to fill and scale down to the original of the screen during play

![make-youtube-videos-fill-whole-screen-any-phone 1280x600](https://user-images.githubusercontent.com/47247206/124540643-0e12ee80-de4a-11eb-9d94-2684e6c28ccf.jpg)

**Comment by LastxTemplar** [comment]
What is the actual issue? You want the video to take the whole screen or something? You can set the controller's aspect ratio with the `aspectRatio` parameter in the `BetterPlayerConfiguration` method to set the size of the video. You can also leave that blank and actually wrap the video player with a container or something to suit your needs.

**Comment by jhomlala** [comment]
Please fill issue properly. Use issue templates and follow this policy: https://github.com/jhomlala/betterplayer/issues/535
