### ISSUE TITLE
[BUG] out of memory exception with 0.0.70 only

### ISSUE THREAD

**Issue by thegrxp** [jhomlala/betterplayer#592]
**Describe the bug**

With 0.0.69 everything works great, after upgrading to 0.0.70 I get Memory errors leading to a crash (Android only on all devices).
I display up to 3 videos in a list or just one video alone, error is the same if I just  leave and go back 2 or 3 times to the screen containing videos.

`
I/(27384): Clamp target GC heap from 279MB to 256MB E/ExoPlayerImplInternal(27384): Source error E/ExoPlayerImplInternal(27384): com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 15904 free bytes and 15KB until OOM, target footprint 268435456, growth limit 268435456 E/ExoPlayerImplInternal(27384): at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:450) E/ExoPlayerImplInternal(27384): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) E/ExoPlayerImplInternal(27384): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) E/ExoPlayerImplInternal(27384): at java.lang.Thread.run(Thread.java:919) E/ExoPlayerImplInternal(27384): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 15904 free bytes and 15KB until OOM, target footprint 268435456, growth limit 268435456 E/ExoPlayerImplInternal(27384): at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102) E/ExoPlayerImplInternal(27384): at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:392) E/ExoPlayerImplInternal(27384): at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:181) E/ExoPlayerImplInternal(27384): at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:474)
`

This line is displayed multiple time per second
`I/(27384): Clamp target GC heap from 279MB to 256MB`

**Better Player version**
- Version: 0.0.70

**Smartphone (please complete the following information):**
 - Only on Android

**Comment by LastxTemplar** [comment]
I was getting this when I was not disposing the player controller correctly. Did you set the `autoDispose` parameter to false by any chance?

**Comment by thegrxp** [comment]
> I was getting this when I was not disposing the player controller correctly. Did you set the `autoDispose` parameter to false by any chance?

Thanks for your help, I already use `autoDispose`. It's been working perfectly for a few versions but when I update to 0.70 it's broken

**Comment by jhomlala** [comment]
@thegrxp Please provide minimal reproducible code which. I need to reproduce it on my devices in order to provide any solution for this problem. Also you should provide device details on which you've enountered issue and video(s) that you have used.

**Comment by thegrxp** [comment]
I have rework totally the implementation and it's working as expected now. Sorry for the inconvenience and thank you for your work!
