### ISSUE TITLE
[FEATURE] Upgrade ExoPlayer to 2.14.1

### ISSUE THREAD

**Issue by naamapps** [jhomlala/betterplayer#599]
**Is your feature request related to a problem? Please describe.**
Yes, currently if the package depends both on video_player and betterplayer, we can't build our app because of version mismatch.

**Describe the solution you'd like**
Upgrade exoplayer to the same version video_player uses (2.14.1).

**Describe alternatives you've considered**
Can't think of an alternative.

**Additional context**
This is the error
` java.lang.RuntimeException: Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.14.1-runtime.jar (com.google.android.exoplayer:exoplayer-common:2.14.1) and jetified-exoplayer-ui-2.13.3-runtime.jar (com.google.android.exoplayer:exoplayer-ui:2.13.3)
`

**Comment by jhomlala** [comment]
Fixed in 0.0.72.
