### ISSUE TITLE
normal player ios is not support

### ISSUE THREAD

**Issue by GobinathAngler** [jhomlala/betterplayer#601]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jhomlala** [comment]
@GobinathAngler Please try to fill issue template next time.
