### ISSUE TITLE
[BUG] Video is not working on iOS but audio works fine

### ISSUE THREAD

**Issue by rakib205** [jhomlala/betterplayer#605]
Android is fine but the problem is happening on iOS. The video is not working, always shows a blank screen but the audio works fine. Tested on iOS simulator 14.4.

**Code Sample**

```
class LocalVideoPlayer extends StatefulWidget {
  const LocalVideoPlayer({Key? key, required this.videoUrl}) : super(key: key);

  final String videoUrl;

  @override
  _LocalVideoPlayerState createState() => _LocalVideoPlayerState();
}

class _LocalVideoPlayerState extends State<LocalVideoPlayer> {
  late BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    super.initState();
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(BetterPlayerDataSourceType.network, widget.videoUrl);
    _betterPlayerController = BetterPlayerController(
      
      BetterPlayerConfiguration(
        deviceOrientationsAfterFullScreen: const [DeviceOrientation.portraitUp],
        aspectRatio: 16/9,
        controlsConfiguration: BetterPlayerControlsConfiguration(
          enableSkips: false, 
          enableOverflowMenu: false,
        )
      ),
      betterPlayerDataSource: betterPlayerDataSource,
      
    );
  }

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
        aspectRatio: 16 / 9,
        child: BetterPlayer(
          controller: _betterPlayerController,
        )
    );
  }
}
```

**Snapshot**
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-15 at 11 44 20](https://user-images.githubusercontent.com/34546369/125735135-9b7a553b-ea87-4cfd-88a0-37a22565477e.png)

**Flutter Version**
```
Last login: Wed Jul 14 18:32:00 on ttys002
rakibbhuiyan@Rakibs-iMac ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.0)
[✓] Connected device (2 available)

• No issues found!
rakibbhuiyan@Rakibs-iMac ~ % 

```

**Comment by deva666** [comment]
Same here
Flutter version
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.4.0-5.0.pre.85, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] VS Code (version 1.58.0)
[✓] Connected device (3 available)
```
Works on Android, but on iOS simulator black screen.
Same Network video with Chewie plays no problem.

**Comment by AhabweEmmanuel** [comment]
Same issue with me. I figured that this bug was cleared in better player version 0.0.69. The bug is now appearing again in version 0.0.71 and 0.0.72.

**Comment by Rohithgilla12** [comment]
Same here!

**Comment by ndcollins** [comment]
I'm observing the same

**Comment by DevMalik08** [comment]
same issue here.
i have observed when i use package http: ^0.13.0 black screen is appearing and only audio is coming
but when i upgrade my package to http: ^0.13.3. this problem is resolved.
in case its helpful to anyone :)

**Comment by ndcollins** [comment]
@DevMalik08 I am using http: ^0.13.3 and I still have just a black video screen

**Comment by jhomlala** [comment]
To all interested in this issue: please provide video which causes this issue. Without this, debugging is impossible. Upgrading `http` library is nonsense since Better Player doesn't use `http` internally.

**Comment by jhomlala** [comment]
@rakib205  @AhabweEmmanuel  @Rohithgilla12 @ndcollins @DevMalik08

**Comment by AhabweEmmanuel** [comment]
> To all interested in this issue: please provide video which causes this issue. Without this, debugging is impossible. Upgrading `http` library is nonsense since Better Player doesn't use `http` internally.

I have noticed that video fails on this version of IOS simulator => IPhone SE 2nd Generation. When I used a different simulator, it worked well.

**Comment by Rohithgilla12** [comment]
@jhomlala anything hosted on firebase storage is also failing.
Thanks

**Comment by jhomlala** [comment]
@AhabweEmmanuel Seems like your sources are generating these errors:

```
2021-08-09 19:55:58.290513+0200 Runner[12232:174691] Task <67B80674-948E-4365-B9B9-B717E846FB2A>.<28> finished with error - code: -999
2021-08-09 19:55:58.290679+0200 Runner[12232:174883] Task <67B80674-948E-4365-B9B9-B717E846FB2A>.<28> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://archive.org/download/rdm_podcast_episode_2_invisible_realities/rdm_podcast_episode_2_invisible_realities.mp4, NSErrorFailingURLKey=https://archive.org/download/rdm_podcast_episode_2_invisible_realities/rdm_podcast_episode_2_invisible_realities.mp4, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <67B80674-948E-4365-B9B9-B717E846FB2A>.<28>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <67B80674-948E-4365-B9B9-B717E846FB2A>.<28>, NSLocalizedDescription=cancelled} [-999]
```
AVPlayer which is used underhood try to load some part of the video which didn't complete before next request.
https://stackoverflow.com/questions/16073519/nsurlerrordomain-error-code-999-in-ios
```
As you can see; -999 is caused by ErrorCancelled. This means: another request is made before the previous request is completed.
```

Try to setup video in some properly configured faster hosting.

**Comment by rakib205** [comment]
@jhomlala https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4

**Comment by tareq55** [comment]
same problem

**Comment by jhomlala** [comment]
Probably something connected with simulator. Can you check if it works fine in real device?

**Comment by Rohithgilla12** [comment]
@jhomlala working in real device and not in simulator.
Thanks,

**Comment by Rohithgilla12** [comment]
@jhomlala any hacks to make it work in simulator?
Thanks :D

**Comment by jhomlala** [comment]
I don't see any solution to fix this issue. If anyone know how to enable playback in simulator, then please let me know in this issue and I'll reopen it.

**Comment by rakib205** [comment]
Still facing this issue on iOS 14.4 simulators. Tried your example app but the result is the same. Blank iOS screen.

**Comment by baesparza** [comment]
Same issue in production environment, some videos dont play, even though it is the same video

**Comment by jhomlala** [comment]
I agree there's issue, but saying "me too" definitely won't help solving this issue. I know the issue is there, but I don't see any solution for it right now.

**Comment by darmie** [comment]
@jhomlala I experience this issue only when I am playing from File, HLS video stream seems to work fine.

**Comment by baesparza** [comment]
I've found that this problem occurs whenever the video file is too big or the file storage provider is too slow. I'm using firebase Storage in my particular case, and the video file was 1GB MP4 Size (I know it is not ideal). Therefore I'm looking to implement a better solution or more optimized files. 

The reason might be loading the metadata. Because when the audio starts, neither do it shows the video duration. 

This problem only happens in IOS and might be related to the low-level execution process.

**Comment by im-v** [comment]
Please check https://github.com/jhomlala/betterplayer/issues/661#issuecomment-958722131

**Comment by ciriousjoker** [comment]
It worked when we used `video_player`. Does anyone have an idea why is it broken in `better_player`?

With `video_player` I think we used local files, perhaps that's why it worked..

**Comment by rikai-trongpq** [comment]
This problem has existed for many years...

**Comment by dunghacknicktao** [comment]
Is there any solution to the problem? now i have upgraded the library version to the latest (0.0.81) but still no improvement.. :(
