### ISSUE TITLE
[FEATURE] Fullscreen TextDirection causing jumpled control widgets.

### ISSUE THREAD

**Issue by FlatCodeIq** [jhomlala/betterplayer#606]
**Is your feature request related to a problem? Please describe.**
I am making an app where the Locale is not English. the problem is the TextDirection of that Locale is RTL not LTR. the video player icons  in Fullscreen are flipped due to the textDirection being RTL. but it's extremely ugly and makes no sense. i want to force LTR on the video player. so i have  wrapped the BetterPlayer() widget with Directionality() widget and provided LTR. but the issue is in Fullscreen, the Widgets flips again to RTL and i can't flip them. i am unable to release my app because of this **critical issue.** 

```
AspectRatio(
      aspectRatio: 16 / 9,
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: BetterPlayer(
          controller: gcVideoPlayerController.getController,
        ),
      ),
    );
```

**Describe the solution you'd like**
I want a flag of textDirection in the BetterPlayerConfiguration.  to enforce specific TextDirection.

```
    betterPlayerConfiguration = BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      autoPlay: true,
      allowedScreenSleep: false,
     textDirection: TextDirection.ltr,
.
.
.
);

```

**Describe alternatives you've considered**
i tried to use EventListener and onFullscreen event, i tried to change the locale. but it's crashing the app as expected.

**Additional context**
I just want to flip the icons as if it was English Locale and LTR. even though the app text is RTL.

![217207136_1440224456341857_5861908952082611001_n](https://user-images.githubusercontent.com/67160218/125930695-fb76cad3-16a9-4d7a-8418-f28d889588d4.jpg)

Look below, the Icons are flipped in an ugly way. **i want to make it have the same look as the picture above.**

![218185333_355906349278882_6788070383360990197_n](https://user-images.githubusercontent.com/67160218/125930986-05cc3a7e-beed-42d7-8911-f59d3feffb45.jpg)

**Comment by jhomlala** [comment]
@FlatCodeIq This will be fixed in next release.

**Comment by jhomlala** [comment]
Fixed in latest release.
