### ISSUE TITLE
When using Better player inside StreamBuilder will be crash after click on Flull screen android[BUG]

### ISSUE THREAD

**Issue by Chomroeun** [jhomlala/betterplayer#611]
@override
  Widget build(BuildContext context) {
    final Stream<DocumentSnapshot> _filmStream =
        Constant.db.collection('films').doc(widget.id).snapshots();
    return StreamBuilder(
        stream: _filmStream,
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot.hasError) {
            return Text('Something went wrong');
          }

          if (snapshot.connectionState == ConnectionState.waiting) {
            return CircularProgressIndicator();
          }

          return Scaffold(
              appBar: AppBar(
                title: Text('Watch Movie'),
              ),
              body: Column(children: [
                const SizedBox(height: 8),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  child: Text(
                    "Player with subtitles loaded from file. Subtitles are enabled by default."
                    " You can choose subtitles by using overflow menu (3 dots in right corner).",
                    style: TextStyle(fontSize: 16),
                  ),
                ),
                AspectRatio(
                  aspectRatio: 16 / 9,
                  child: BetterPlayer(controller: _betterPlayerController),
                ),
              ]));
        });
  }

Message error is:

The VideoPlayerController sending notification was:
  VideoPlayerController#0d2b1(VideoPlayerValue(duration: 0:00:15.021000, size: Size(1280.0, 720.0),
  position: 0:00:01.775000, absolutePosition: null, buffered: [DurationRange(start: 0:00:00.000000,
  end: 0:00:15.021000)], isPlaying: false, isLooping: false, isBuffering: false, volume: 1.0,
  errorDescription: null))

**Comment by jhomlala** [comment]
@Chomroeun Please fill issue ticket properly. Your example is not reproducible code and the "error" doesn't present any value to me.
