### ISSUE TITLE
Build failed due classes duplicate

### ISSUE THREAD

**Issue by augusto3691** [jhomlala/betterplayer#613]
Hi, im trying to build a app with this but always got same error:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.14.1-runtime.jar (com.google.android.exoplayer:exoplayer-common:2.14.1) and jetified-exoplayer-ui-2.13.1-runtime.jar (com.google.android.exoplayer:exoplayer-ui:2.13.1)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Exception: Gradle task assembleDebug failed with exit code 1

```

Already tryied clear flutter cash, delete files of pub cache and delete cache of gradle, if i remove the package from my project works like a charm.

any thoughts?

**Comment by CodingDavid8** [comment]
Getting the same error here... 

I have the assumption that it might have to do with having several video player dependencies.

**Comment by jhomlala** [comment]
Well it's not my problem that you're using multiple video players in your app. Answer is simple - use just one. I assume that Better Player provides biggest addition to your project, then remove other players from your `pubspec.yaml`.

You can also exclude duplicated dependencies in android's `build.gradle` :https://stackoverflow.com/questions/56029393/why-im-getting-duplicate-class-when-running-my-android-project/56029604
