### ISSUE TITLE
[FEATURE] Enable Default Subtitle

### ISSUE THREAD

**Issue by kkdlau** [jhomlala/betterplayer#615]
**Is your feature request related to a problem? Please describe.**
I'm making a subtitle-related application and people who using that app are expected to watch the videos with subtitles. But it will quite annoying if the user needs to manually select the default subtitle every time when they play the video.

**Describe the solution you'd like**
In `controlsConfiguration`, provides a parameter named `enableDefaultSubtitle`, and if this parameter is `true`, default subtitle will be enabled at the beginning of the video.

Hmm maybe make this parameter only functional if only a subtitle is passed to the player.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jhomlala** [comment]
Please use `selectedByDefault` parameter in `BetterPlayerSubtitlesSource`. See subtitles example in sample app.
