### ISSUE TITLE
Doesn't work for ios   onTap: () 

### ISSUE THREAD

**Issue by lukdim** [jhomlala/betterplayer#616]
Doesn't work for ios: 
onTap: () {
        _betterPlayerController.isPlaying()!
            ? _betterPlayerController.pause()
            : _betterPlayerController.play();
      },

onLongPress  works!

Everything is fine on android! Need help

**Comment by LastxTemplar** [comment]
@lukdim this might help you solve the issue:
https://jhomlala.github.io/betterplayer/#/multiplegesturedetector

**Comment by jhomlala** [comment]
@lukdim I think @LastxTemplar gives right answer for your problem.
