### ISSUE TITLE
[FEATURE] Update to Exoplayer 2.14.2

### ISSUE THREAD

**Issue by waltojac** [jhomlala/betterplayer#621]
**Is your feature request related to a problem? Please describe.**
We have custom FMP4 videos that have only a video and a text track, and do not play on Exoplayer. This update of Exoplayer (2.14.2) has a fix for it:
>RELEASENOTES.md
...
Extractors:
Fix issue where a trun atom could be associated with the wrong track in an FMP4 stream (#9056). The fix removes a previous workaround to handle content in which the track_ID is set incorrectly (#4083). Such content is malformed and should be re-encoded.

**Describe the solution you'd like**
Update the Exoplayer version BetterPlayer uses to 2.14.2

**Describe alternatives you've considered**
Having a fork of betterplayer and exoplayer that depends on this version.

**Comment by jhomlala** [comment]
ExoPlayer version will be update in next release.

**Comment by jhomlala** [comment]
Updated in latest release.
