### ISSUE TITLE
[BUG] Large cache causing OOM issues

### ISSUE THREAD

**Issue by petoknm** [jhomlala/betterplayer#625]
I have noticed that using cache increases my heap size to a point where I get `OutOfMemory` errors. Is it using purely in-memory based cache, or does it store the data on the filesystem?

Target OS: Android

**Comment by petoknm** [comment]
After some digging I found that [exoplayer uses an in-memory cache](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/SimpleCache.html) that is also backed by FS.

**Comment by petoknm** [comment]
Exoplayer2 demo app uses `android:largeHeap="true"` to increase the max heap size and avoid OOMs.
Here is the issue related to `SimpleCache`'s RAM consumption: https://github.com/google/ExoPlayer/issues/7567

Maybe we should mention in the docs, that if you want to use large cache you should also enable `largeHeap` because `SimpleCache` is not very RAM efficient at this point.

**Comment by petoknm** [comment]
Turns out, in my case, the main problem wasn't the cache, it was the buffering configuration. I just decreased the min/max buffer sizes and now I don't have any issues.

```dart
bufferingConfiguration: BetterPlayerBufferingConfiguration(
  minBufferMs: Duration(seconds: 10).inMilliseconds,
  maxBufferMs: Duration(seconds: 60).inMilliseconds,
),
```

**Comment by tibfox** [comment]
thx @petoknm you saved my day with the bufferconfig
