### ISSUE TITLE
[FEATURE] Track video duration while playing (real time)

### ISSUE THREAD

**Issue by Tom3652** [jhomlala/betterplayer#626]
Thanks a lot for your work on this package !

**Is your feature request related to a problem? Please describe.**

This is more a question than a feature request but it can become one

in my app i need to hide controls : ```controlsConfiguration: BetterPlayerControlsConfiguration(showControls: false)```
I could not find myself how to be able to do the "duration countdown" while the video is playing. 

**Describe the solution you'd like**
A simple "playing listener" that returns the video duration in real time as long as the player is playing the video.

**Describe alternatives you've considered**
I am currently using the method specified in the (very nice) documentation : 
```
_betterPlayerController.addEventsListener((event){
    print("Better player event: ${event.betterPlayerEventType}");
    if (event.betterPlayerEventType == BetterPlayerEventType.progress) {
        widget.listener();
      }
});
```
And it gives a feedback, but is there a simple way to retrieve to video duration second by second as it is played ?

**Comment by jhomlala** [comment]
Try this:

```dart
    _betterPlayerController?.videoPlayerController?.addListener(() { 
      Duration? position = _betterPlayerController.videoPlayerController?.value.position;
      Duration? duration = _betterPlayerController.videoPlayerController?.value.duration;
    });
```
