### ISSUE TITLE
[BUG] Controller position does not change immediately after calling await seekTo();

### ISSUE THREAD

**Issue by yaroslav-kahaniak** [jhomlala/betterplayer#628]
@jhomlala 
Greetings. Thanks for the work you put into package development. Could you check the following player's behavior?

**Description:**
I am calling `await seekTo();`. After that I am calling `await controller.videoPlayerController!.position`. 
What I expect to get: position after seekTo. 
What I get: position before seekTo.
I have to wait approximately 50-100ms after calling `seekTo` before calling `controller.videoPlayerController!.position` to make sure, that seekTo return 'right' value.

**Example code**
```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

class SeekToTest extends StatefulWidget {
  final String link;

  SeekToTest({Key? key, required this.link}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<SeekToTest> {
  static const Duration _delta = const Duration(seconds: 5);
  late BetterPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = BetterPlayerController(
      BetterPlayerConfiguration(
        aspectRatio: 1,
        autoPlay: true,
      ),
      betterPlayerDataSource: BetterPlayerDataSource.network(widget.link),
    );
    _controller.addEventsListener((event) async {
      if (event.betterPlayerEventType == BetterPlayerEventType.initialized) {
        await seekTo(_controller, _delta);
        await seekTo(_controller, _delta);
        await seekTo(_controller, _delta);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BetterPlayer(controller: _controller),
    );
  }

  Future<void> seekTo(BetterPlayerController controller, Duration delta) async {
    Duration currentPosition = (await controller.videoPlayerController!.position) ?? Duration(minutes: 0);
    print('---> currentPosition: ${currentPosition.inSeconds}');
    Duration videoDuration = controller.videoPlayerController!.value.duration ?? Duration(hours: 1);
    Duration nextPosition = currentPosition + delta;

    if (nextPosition < Duration(seconds: 0)) {
      nextPosition = Duration(seconds: 0);
    } else if (nextPosition >= videoDuration) {
      nextPosition = videoDuration - Duration(seconds: 1);
    }

    print('---> seekTo: ${nextPosition.inSeconds}');
    await controller.seekTo(nextPosition);
    print('---> seekedTo');
  }
}
```
**Prints**
```
---> currentPosition: 0
---> seekTo: 5
---> seekedTo
---> currentPosition: 0
---> seekTo: 5
---> seekedTo
---> currentPosition: 0
---> seekTo: 5
---> seekedTo
```

**Flutter doctor**
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (1 available)

**Better Player version:**
better_player: ^0.0.72

**Device:**
iPhone8 (real device)

**Comment by jhomlala** [comment]
This is normal behavior. There's 300 ms interval in internal timer which gets current position of video. This is because ExoPlayer won't return current position that quickly. From my research, this value (300ms) works best. Lowering this value won't change anything - ExoPlayer won't reply any faster. So your idea to wait after seek is correct.
