### ISSUE TITLE
[BUG]  On iOS lockscreen:VideoPlayer crashes [notification_player_page.dart]

### ISSUE THREAD

**Issue by MiroLiebschner** [jhomlala/betterplayer#629]
The bug
When using the lock-screen controls the player / app crashes. This only happens  on iOS, you can control the video in lock-screen on Android just fine. 

To Reproduce:
1. Use the player with notification  from the example: notification_player_page.dart 
2. Play the video file, lock your phone.
3. Try to control the video from the iOS lock-screen overlay by changing the position multiple times in a short period of time. .
4. App crashes.

Error Log: 
![Bildschirmfoto 2021-08-02 um 15 19 51](https://user-images.githubusercontent.com/56092186/127868303-6f212b73-b63c-4dba-9c5f-6dbf41bb6fbd.png)

`
Abgestürzt: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010
__45-[FLTBetterPlayerPlugin setupRemoteCommands:]_block_invoke_2
keyboard_arrow_down
`

From the Run console: 
`commandHandler=SeekToPlaybackPosition<E7FE00EF-271E-4B08-9563-1320B7ADEFAF> was called and still waiting for completion
[        ] [MediaRemote] It has been more than <7.000000> seconds since commandHandler=SeekToPlaybackPosition<E7FE00EF-271E-4B08-9563-1320B7ADEFAF> was called and still waiting for completion
[        ] [MediaRemote] It has been more than <7.000000> seconds since 
[        ] [connection] nw_endpoint_handler_set_adaptive_write_handler [C21.1 142.250.185.202:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
`

After doing some research we realized that in better_player_controller.dart the method _handleVideoEvent gets called **multiple times after each action taken on the Lock Screen**. This might be a problem but we suspect the connection between the betterPlayer and the iOS notifications center ( might be called different) is flawed.

Better Player version
- Version: 0.0.72

 - Device: iPhone SE 2020
 - OS: iOS 14.6

**Comment by jhomlala** [comment]
This will be fixed in next release.

**Comment by jhomlala** [comment]
Fixed in latest release.
