### ISSUE TITLE
[BUG] After calling of seekTo multiple times, video and sound become out of sync

### ISSUE THREAD

**Issue by yaroslav-kahaniak** [jhomlala/betterplayer#630]
**Description**
After rapid tapping of 'Fast Forward' button 2 times, the video and sound becomes out of sync.
FYI: 'Fast Forward' button fast forwards video by 5 seconds.

**To Reproduce**
1 Open screen with video
2 Rapidly tap 'Fast Forward' button 2 times
3 Video and sound becomes out of sync

**Example code**
```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

class SeekToTest extends StatefulWidget {
  final String link;

  SeekToTest({Key? key, required this.link}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<SeekToTest> {
  late BetterPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = BetterPlayerController(
      BetterPlayerConfiguration(
        aspectRatio: 0.5,
        autoPlay: true,
      ),
      betterPlayerDataSource: BetterPlayerDataSource.network(widget.link),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            BetterPlayer(controller: _controller),
            _buildSeekToButton(),
          ],
        ),
      ),
    );
  }

  Widget _buildSeekToButton() {
    return Container(
      color: Colors.blue,
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: _onSeekToTap,
          child: Padding(
            padding: const EdgeInsets.fromLTRB(25, 15, 25, 15),
            child: Text('Fast Forward'),
          ),
        ),
      ),
    );
  }

  void _onSeekToTap() {
    seekTo(_controller, const Duration(seconds: 5));
  }

  Future<void> seekTo(BetterPlayerController controller, Duration delta) async {
    Duration currentPosition = (await controller.videoPlayerController!.position) ?? Duration(minutes: 0);
    Duration videoDuration = controller.videoPlayerController!.value.duration ?? Duration(hours: 1);
    Duration nextPosition = currentPosition + delta;

    if (nextPosition < Duration(seconds: 0)) {
      nextPosition = Duration(seconds: 0);
    } else if (nextPosition >= videoDuration) {
      nextPosition = videoDuration - Duration(seconds: 1);
    }

    print('---> isInitialized: ${controller.isVideoInitialized() ?? false}');
    await controller.seekTo(nextPosition);
    print('---> seekTo completed');
  }
}
```

**Prints**
```
---> isInitialized: true
---> seekTo completed
---> isInitialized: true
---> seekTo completed
```

**Video**
https://user-images.githubusercontent.com/79097999/127871542-8bdb339b-f22e-4a87-8a90-0cceec7b1bea.mp4

**Flutter doctor**
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (1 available)

**Better Player version**
better_player: ^0.0.72

**Device**
iPhone 8 (real device)

**Comment by SinoMiles** [comment]
same issue only ios.

**Comment by jhomlala** [comment]
@yaroslav-kahaniak Can you provide sample video? Also please provide your iOS version.

I've did some research and seems like there's nothing useful can be find about this issue. It can be some AVPlayer internal issue.

**Comment by jhomlala** [comment]
No reply from author. Closed.

**Comment by appsw** [comment]
I have the same problem on iOS
