### ISSUE TITLE
[BUG] Video paused when dragging on progress bar

### ISSUE THREAD

**Issue by nhingo-312** [jhomlala/betterplayer#635]
When I dragging on progress bar to seek to another position, video get paused even when it was playing before. 
It's happened on both iOS and Android with real devices.
I debugged in the better_player_material_progress_bar.dart, it's truely invoked line 113, method 
```
if (_controllerWasPlaying) {
          controller!.play();
        }
```
but in video_player.dart, when it went to method `_applyPlayPause` line 461, it jump to line 466 `value.isPlaying` with true value for the first time and then kept jumping to this line with false value later on.
Can anybody help me with this?  

**To Reproduce**
1. Play a video
2. Drag on the progress bar
3. Error: Video paused

**Better Player version**
- Version: 0.0.72

**Comment by jhomlala** [comment]
It's not an issue, it's intended behavior. Video is paused during seek to prevent jumps of the video until seek has been completed. Feel free to fork if you want to change this behavior for your purposes.

**Comment by nhingo-312** [comment]
> It's not an issue, it's intended behavior. Video is paused during seek to prevent jumps of the video until seek has been completed. Feel free to fork if you want to change this behavior for your purposes.

I know it will be paused during seeking, but after finishing seeking, it's pause, is this intended too?

**Comment by jhomlala** [comment]
No it's not. Can you provide reproducible code and steps which help me debug this issue?

**Comment by jhomlala** [comment]
No Reply from author. Closed.
