### ISSUE TITLE
[FEATURE] Pass headers with each fragment request for secured HLS content

### ISSUE THREAD

**Issue by djsjr** [jhomlala/betterplayer#639]
**Is your feature request related to a problem? Please describe.**
HLS content secured with CloudFront signed cookies isn't playable

**Describe the solution you'd like**
Header param should set header for each ts request. it looks right now like it is only doing the first file (.m3u8) and not the fragments that follow. The header stays the same, but it most go out with each HTTP request the player makes.

**Describe alternatives you've considered**
None with regards to this player

**Additional context**
AWS Amplify framework allows devs to serve video content with this method. It is the [recommended method for serving HLS content using CloudFront.  ](https://aws.amazon.com/about-aws/whats-new/2015/03/amazon-cloudfront-signed-cookies/).

**Comment by jhomlala** [comment]
@djsjr Can you provide some sample video from CloudFront with cookies, so I'll able to test this on my side? Seems like there's way in ExoPlayer to setup cookies: https://github.com/google/ExoPlayer/issues/8386  and in AVPlayer: https://github.com/ykying/Swift_Player_AWS_Cookie.

**Comment by jhomlala** [comment]
For anyone interested in this issue: simply use `headers` parameter from `BetterPlayerDataSource`. Please format headers same as presented in this issue in ExoPlayer issue: https://github.com/google/ExoPlayer/issues/8386. It should work both on Android and iOS.

**Comment by djsjr** [comment]
Yes. Passing a map like this should work - it does with the standard video player. 
```
      String cookieValue = '';
      cookieValue += "CloudFront-Policy=" + policy + ";";
      cookieValue += "CloudFront-Signature=" + signature + ";";
      cookieValue += "CloudFront-Key-Pair-Id=" + keyPaidId + ";";

      Map<String, String> cookie = {'Cookie': cookieValue};

```

**Comment by SalahAdDin** [comment]
@djsjr can you give us an example of a custom policy for this issue?

**Comment by jhomlala** [comment]
Just use headers parameter.
