### ISSUE TITLE
[Help] Avoid brief black flash when video is looping

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [jhomlala/betterplayer#640]
Hi,
Thanks a lot for your plugin. It helps a lot!
Using last version.

I have a feed of videos 

```dart
final betterPlayerDataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      widget.url,
      cacheConfiguration: const BetterPlayerCacheConfiguration(
        useCache: true,
        preCacheSize: 10 * 1024 * 1024,
        maxCacheSize: 10 * 1024 * 1024,
        maxCacheFileSize: 10 * 1024 * 1024,
        key: "testCacheKey",
      ),
    );
    _controller = BetterPlayerController(
        BetterPlayerConfiguration(
          looping: true,
          aspectRatio: hiveBox.get('width') / hiveBox.get('height'),
          fit: BoxFit.cover,
          controlsConfiguration: BetterPlayerControlsConfiguration(
            showControls: false,
          ),
        ),
        betterPlayerDataSource: betterPlayerDataSource);
```

Working pretty well, my only concern is about looping.
There's a brief black flash when the video ends, before it begins looping again.

Any of you guys have avoided this brief flash ?

Thank you,

**Comment by jhomlala** [comment]
What do you mean "black flash"? Maybe first frames of your video are the black one that's why you're seeing black screen? Maybe you didn't enable cache and video starts loading again? Without video I can't say what's the issue. Maybe you can provide some recording of this "problem"?

**Comment by jhomlala** [comment]
No reply from author. Closing.
