### ISSUE TITLE
[BUG] having BackDropFilter below video player breaks the page on IOS

### ISSUE THREAD

**Issue by jeremiahlukus** [jhomlala/betterplayer#642]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

https://user-images.githubusercontent.com/17206638/128587364-c93bd44e-f5b5-47da-b983-ba47a3cd9583.MP4

**Describe the bug**
https://user-images.githubusercontent.com/17206638/128587364-c93bd44e-f5b5-47da-b983-ba47a3cd9583.MP4

**To Reproduce**
I have a Stack where i am applying blur effects first then showing things on top of the blur effects, when i place the video is blurs everything above it 

**Screenshots**
https://user-images.githubusercontent.com/17206638/128587364-c93bd44e-f5b5-47da-b983-ba47a3cd9583.MP4

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version: lastest 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 max]

**Additional context**

**Comment by jeremiahlukus** [comment]
![File](https://user-images.githubusercontent.com/17206638/128587567-55414aa1-bdd6-4c62-a1bb-799656e198b2.jpg)


when i comment out the blur effects it shows

**Comment by jeremiahlukus** [comment]
Im also able to click on the X when its blurred so the layering seems correct

**Comment by jeremiahlukus** [comment]
https://user-images.githubusercontent.com/17206638/128587689-dc04e767-2666-45b2-be99-56b588dd6064.MP4

**Comment by jeremiahlukus** [comment]
Originally i was using chewie to display the video bu there were some performance issue which you have fixed. So this was working with chewie which is why i think its a bug

**Comment by jeremiahlukus** [comment]
https://github.com/jeremiahlukus/blur_video 

Here is a example

**Comment by jeremiahlukus** [comment]
https://user-images.githubusercontent.com/17206638/128605515-5ee0444e-5090-4e08-8aed-aaeea4b14b54.mov



hmm so weird, just using 

```
   BetterPlayer.network(
                              "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
                            ),
   ```
   
   now

**Comment by jeremiahlukus** [comment]
narrowed it down to using a BackdropFilter

**Comment by jeremiahlukus** [comment]
<img width="500" alt="Screen Shot 2021-08-07 at 11 50 28 AM" src="https://user-images.githubusercontent.com/17206638/128605972-f2558164-6953-4944-8a5b-62fed21f848b.png">


yea %100 an issue with using a BackdropFilter , for some reason it blurs everything above the video like in #518

**Comment by jeremiahlukus** [comment]
tried adding 
```
   controlsConfiguration: BetterPlayerControlsConfiguration(
        playerTheme: BetterPlayerTheme.material,
      ),
      
    ```
    
    didn't change the outcome.

**Comment by jeremiahlukus** [comment]
When its buffering the screen looks fine

**Comment by jhomlala** [comment]
@jeremiahlukus I don't understand what's your problem and what do you want to achieve. Instead of adding multiple comments, can you specify exactly what do you need?

**Comment by jeremiahlukus** [comment]
@jhomlala it looks like adding a blur filter behind the better player blurs everything above the video. This only is on IOS on android every looks and functions correctly. 

https://github.com/jeremiahlukus/blur_video

Here is a link to an example of this. 

sorry for the multi comments I was trying to update when I found new info, as I wasn’t entirely sure what was breaking it on IOS.

**Comment by b3nni97** [comment]
same problem here

**Comment by jhomlala** [comment]
Can you recheck this issue with latest release? There're new parameters: `sigmaX` and `sigmaY` in BetterPlayerControlsConfiguration. They control blur of the iOS controls.

**Comment by jeremiahlukus** [comment]
@jhomlala It did not resolve the issue. I have updated the example application 
https://github.com/jeremiahlukus/blur_video  

I set sigmaX and sigmaY to `0` as well as other values to see if anything changes but it did not.  Here is the screen shot of the sample application with sigmaX and sigmaY to `0` 
<img width="503" alt="Screen Shot 2021-08-15 at 6 47 35 PM" src="https://user-images.githubusercontent.com/17206638/129494940-e7ce25bc-8c9a-4391-9674-fe43b940ef2e.png">  

and here is the video player with a broken url to see there is text above the video

<img width="501" alt="Screen Shot 2021-08-15 at 6 49 19 PM" src="https://user-images.githubusercontent.com/17206638/129494984-e1f46953-1489-404e-9354-7fc758e6e003.png">

**Comment by jhomlala** [comment]
@jeremiahlukus Thanks for preparing example app. I have reworked cupertino theme. Right now this theme doesn't use BackdropFilter in inner widgets. Also I've removed rounded corners from the player. Please do not use rounded corners for the player in your app, because the texture on which BP renders video is rectangle.

Please try using this temp. dependency in your app:
```
better_player:
    git:
      url: https://github.com/jhomlala/betterplayer
      ref: feature/august_changes_2
```

You may need to remove `sigmaX` and `sigmaY` from BetterPlayerControlsConfiguration. Also please remove `ClipRRect` from `VideoPlayerItem` widget.

**Comment by jeremiahlukus** [comment]
Ill look at this tomorrow got a bit busy with stuff.

**Comment by jeremiahlukus** [comment]
@jhomlala Im unable to get it to run on the example i have removed sigmaX and sigmaY and ClipRRect

Ii pushed the changes to https://github.com/jeremiahlukus/blur_video
```
    /bin/sh -c /Users/jparrack/Library/Developer/Xcode/DerivedData/Runner-encapuimlqqlunegmwyesruzwhyu/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh

../../phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/lib/src/core/better_player.dart:117:20: Error: Method not found: 'SystemChrome.setEnabledSystemUIMode'.
      SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
                   ^^^^^^^^^^^^^^^^^^^^^^
../../phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/lib/src/core/better_player.dart:230:24: Error: Method not found: 'SystemChrome.setEnabledSystemUIMode'.
    await SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);
                       ^^^^^^^^^^^^^^^^^^^^^^
../../phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/lib/src/core/better_player.dart:268:24: Error: Method not found: 'SystemChrome.setEnabledSystemUIMode'.
    await SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
                       ^^^^^^^^^^^^^^^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by jeremiahlukus** [comment]
Ive done a full clean and still cannot get past the errors


```

    /Users/jparrack/phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/ios/Classes/CacheManager.swift:213:13: warning:
    initialization of immutable value 'str' was never used; consider replacing with assignment to '_' or removing it
            let str = String(format: "%.1f%%", percentage)
            ~~~~^~~
            
    /Users/jparrack/phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/ios/Classes/CachingPlayerItem.swift:74:46:
    warning: cast from 'Dictionary<NSObject, AnyObject>.Element' (aka '(key: NSObject, value: AnyObject)') to unrelated type 'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                          ~~~~~~ ^   ~~~~~~
    /Users/jparrack/phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/ios/Classes/CachingPlayerItem.swift:74:85:
    warning: cast from 'Int' to unrelated type 'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                                                                   ~~~~ ^   ~~~~~~
    /Users/jparrack/phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/ios/Classes/CacheManager.swift:213:13: warning:
    initialization of immutable value 'str' was never used; consider replacing with assignment to '_' or removing it
            let str = String(format: "%.1f%%", percentage)
            ~~~~^~~
            _
    /Users/jparrack/phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/ios/Classes/CachingPlayerItem.swift:74:46:
    warning: cast from 'Dictionary<NSObject, AnyObject>.Element' (aka '(key: NSObject, value: AnyObject)') to unrelated type 'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                          ~~~~~~ ^   ~~~~~~
    /Users/jparrack/phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/ios/Classes/CachingPlayerItem.swift:74:85:
    warning: cast from 'Int' to unrelated type 'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                                                                   ~~~~ ^   ~~~~~~
    ../../phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/lib/src/core/better_player.dart:117:20: Error: Method not
    found: 'SystemChrome.setEnabledSystemUIMode'.
          SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
                       ^^^^^^^^^^^^^^^^^^^^^^
    ../../phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/lib/src/core/better_player.dart:230:24: Error: Method not
    found: 'SystemChrome.setEnabledSystemUIMode'.
        await SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);
                           ^^^^^^^^^^^^^^^^^^^^^^
    ../../phil/flutter/.pub-cache/git/betterplayer-d3e21ef7daaf8edcc36c9d6298b8d37bcbce855a/lib/src/core/better_player.dart:268:24: Error: Method not
    found: 'SystemChrome.setEnabledSystemUIMode'.
        await SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
                           ^^^^^^^^^^^^^^^^^^^^^^
                           ```

**Comment by jhomlala** [comment]
Please upgrade to latest Flutter stable version: `flutter upgrade`.

**Comment by jhomlala** [comment]
You can try this with latest BP version - 0.7.4.

**Comment by jeremiahlukus** [comment]
still fails:


```
    /Users/jparrack/phil/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.74/ios/Classes/BetterPlayer.h:53:47: warning: 'height' used as the name of the previous parameter rather than as part of the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                                  ^
    /Users/jparrack/phil/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.74/ios/Classes/BetterPlayer.h:53:47: note: introduce a parameter name to make 'height' part of the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                                  ^
    /Users/jparrack/phil/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.74/ios/Classes/BetterPlayer.h:53:53: note: or insert whitespace before ':' to use 'height' as parameter name and have an empty entry in the selector
    - (void)setTrackParameters:(int) width: (int) height: (int)bitrate;
                                                        ^
    /Users/jparrack/phil/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.74/ios/Classes/CachingPlayerItem.swift:74:46: warning: cast from 'Dictionary<NSObject, AnyObject>.Element' (aka '(key: NSObject, value: AnyObject)') to unrelated type 'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                          ~~~~~~ ^   ~~~~~~
    /Users/jparrack/phil/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.74/ios/Classes/CachingPlayerItem.swift:74:85: warning: cast from 'Int' to unrelated type 'String' always fails
                        request.setValue((_value as! String), forHTTPHeaderField: (_key as! String))
                                                                                   ~~~~ ^   ~~~~~~
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'GCDWebServer' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 8 Plus.
```

using  Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en)

**Comment by jeremiahlukus** [comment]
i updated my example with the newest version

**Comment by jeremiahlukus** [comment]
<img width="424" alt="Screen Shot 2021-09-20 at 4 59 04 PM" src="https://user-images.githubusercontent.com/17206638/134074880-0405c3b5-975a-43ce-9146-2e7d799f59be.png">

**Comment by jhomlala** [comment]
So what's wrong here? Is there any issue?

**Comment by jeremiahlukus** [comment]
Yes, the video audio plays but nothing is displayed. Also when clicking play the video height gets shrunken as you see in the photo

**Comment by jhomlala** [comment]
Are you testing on iOS simulator? Please use real device for testing. For some videos iOS simulator will fail to play.

**Comment by jhomlala** [comment]
Closing for now. Feel free to answer in this issue and I'll reopen it.

**Comment by arbile26** [comment]
The same issue with the latest version!
