### ISSUE TITLE
[BUG] Official documentation does not work

### ISSUE THREAD

**Issue by MohiuddinM** [jhomlala/betterplayer#644]
**Describe the bug**
The get started button on https://jhomlala.github.io/betterplayer/#/ does not work

**To Reproduce**
1. Go to https://jhomlala.github.io/betterplayer/#/
2. Click on "Get Started"
3. Nothing happens

**Comment by jhomlala** [comment]
Thanks for reporting, it will be fixed in next release.

**Comment by jhomlala** [comment]
Fixed in latest release.
