### ISSUE TITLE
Enhance the player with the persistent licenses feature[FEATURE]

### ISSUE THREAD

**Issue by avonwagle** [jhomlala/betterplayer#645]
BetterPlayer should  have feature of downloading drm DASH media video files, and play it back fully offline like the exoplayer that works on native andriod.  Currently it supports drm playback for online only. I want the player to play the drm protected video when there is no internet connection too.

**Comment by jhomlala** [comment]
@avonwagle Please use issue template. Also try to use search function. There's already similar issue: https://github.com/jhomlala/betterplayer/issues/600. Closed due to duplication.
