### ISSUE TITLE
[BUG] Can I get subtitles in 2 languages at the same time?

### ISSUE THREAD

**Issue by kpk-i710** [jhomlala/betterplayer#646]
**History check**
At first I was glad I thought that 2 or more languages were supported, but I could only switch between them.
If you call _betterPlayerController.subtitlesLines [currentindex] .texts, you can only get the current language, somehow you can also get the second language at the same time like _betterPlayerController.subtitlesLines [currentindex] .text.ru,
_betterPlayerController.subtitlesLines [currentindex] .text.en
for example, Russian and English at once?

**Comment by jhomlala** [comment]
No it's not possible and there's no plans to add this feature. Maybe you can try to combine your subtitles in one file and apply it in BP.
