### ISSUE TITLE
[FEATURE] More sensitive error forwarding in iOS

### ISSUE THREAD

**Issue by jeiea** [jhomlala/betterplayer#651]
**Is your feature request related to a problem? Please describe.**
I tried playing signed URL playlist with this library, and worked well on android. But in iOS, better_player couldn't report avplayer's error notification well when signed URL expires.
It takes about a minute to dispatch the error event, or even it was missed.

**Describe the solution you'd like**
I could get the exception early from [AVPlayerItemFailedToPlayToEndTimeNotification and AVPlayerItemNewErrorLogEntryNotification](https://developer.apple.com/library/archive/technotes/tn2436/_index.html), it could be forwarded to flutter code.

**Describe alternatives you've considered**
It would be more convenient if this library classifies and rewraps exceptions, but it would be more complex.

**Comment by jhomlala** [comment]
@jeiea Can you provide some video which can help me reproduce this scenario? I would like to check AVPlayerItemFailedToPlayToEndTimeNotification and AVPlayerItemNewErrorLogEntryNotification notifications but I need some way to trigger it. You don't need to provide your production data source. You can also provide reproduction steps (if there any).

**Comment by jhomlala** [comment]
No answer from author. Closing. Feel free to anwser and I'll reopen it.
