### ISSUE TITLE
[BUG]Aspect ratio broken after switching between different resolution/aspect ratio videos

### ISSUE THREAD

**Issue by emanuel801** [jhomlala/betterplayer#654]
**History check**
I confirm that I did not find anything in the problem history

**Describe the bug**
Based on the code example of the repository of the examples folder playlist_page.dart, three streams of different resolution were placed and this problem of image overlap is presented in the tvbox tx3mini.
`![imagen](https://user-images.githubusercontent.com/7025149/129958579-1a7310a3-f462-4435-beef-c0f596529428.png)`
https://user-images.githubusercontent.com/7025149/129958579-1a7310a3-f462-4435-beef-c0f596529428.png

**To Reproduce**
1 . Implement the example playlist_page.dart place with three hls streams in different qualities.
2. switch streams

**Example code*
The example repository playlist_page.dart
**Expected behavior**
the channel change is expected to continue without the overlap

**Screenshots**
[https://user-images.githubusercontent.com/7025149/129958579-1a7310a3-f462-4435-beef-c0f596529428.png](url)

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-2.0.pre.79, on Linux, locale es_PE.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
**Better Player version**
- Version:0.73

**Smartphone (please complete the following information):**
 - Device: [e.g. tv box tx3mini]
 - OS: [e.g. android]

**Additional context**
this overlap scenario also occurs when you are on the same stream and the abr is applied.
Thank you for your attention and answer

**Comment by jhomlala** [comment]
Seems like similar issue to https://github.com/jhomlala/betterplayer/issues/308. Previously I couldn't find solution for this issue. This may be connected with `TextureView` which is being used by ExoPlayer and Flutter framework.

**Comment by cosmane** [comment]
This issue ( relating to #308 ) still occurs for me: 
flutter version 2.5.0
android: version 11
on emulator

but (for me) it only occurs going from 720p to 360p.  Have three resolutions, 720p, 360p, 144p.  All other transition combinations are ok.  Only 720p -> 360p transition causes this picture in a picture issue.  So for e.g. 720p -> 144p -> 360p is ok.
