### ISSUE TITLE
S3 Videos from aws url

### ISSUE THREAD

**Issue by Ankit0080** [jhomlala/betterplayer#655]
I have seen too many issues regarding same problem but none of them are fixed yet so i am adding it with code.
Not Able to play video from Aws server url

import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  BetterPlayerController _betterPlayerController;

  @override
  void initState() {

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: AspectRatio(
          aspectRatio: 16 / 9,
          child: BetterPlayer.network(
            "https://testhop.s3.ap-south-1.amazonaws.com/Risk+for+Hospitalization+Prior+Function+Post+Hospitalization+Syndrome.mp4",
            betterPlayerConfiguration: BetterPlayerConfiguration(
              aspectRatio: 16 / 9,
            ),
          ),

        ));
  }
}

and the error i have :  

 Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal(15681):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
E/ExoPlayerImplInternal(15681):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)

Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error

**Comment by SalahAdDin** [comment]
I am using **S3** with **Cloud Front** and it works like a charm.

**Comment by Ankit0080** [comment]
@SalahAdDin  Yes i found the work around also but the video quality option is not working with MP4 file it is working with m3u8 only can you help me regarding this.?

**Comment by SalahAdDin** [comment]
> @SalahAdDin Yes i found the work around also but the video quality option is not working with MP4 file it is working with m3u8 only can you help me regarding this.?

I didn't review any related things about it.
