### ISSUE TITLE
[FEATURE] Application theme based player theme.

### ISSUE THREAD

**Issue by SalahAdDin** [jhomlala/betterplayer#656]
**Is your feature request related to a problem? Please describe.**
Many of **Flutter** users love to customize their themes, and fitting the **BetterPlayer**'s theme to their themes requires to change many options on a _BetterPlayerControlsConfiguration_ because this package does not have a way to take main colors and others directly from the `Theme.of(context)`.

**Describe the solution you'd like**
This package could have a constructor for _BetterPlayerControlsConfiguration_ based on the current context's theme. 

**Describe alternatives you've considered**

**Additional context**
Packages like **Chewie** base their default theme on the current application's theme, for instance.

**Comment by jhomlala** [comment]
@SalahAdDin Which part of UI should be changed based on `Theme` instance? Right now BP controls are black/white which is pretty neutral. Let's assume that some app uses bright colors. Based on your request, player should have same bright colors which is not so good.

Anyway I'm open for any discussion. Please provide information which options of `Theme` should be used in `BetterPlayerControlsConfiguration.

**Comment by SalahAdDin** [comment]
> @SalahAdDin Which part of UI should be changed based on `Theme` instance? Right now BP controls are black/white which is pretty neutral. Let's assume that some app uses bright colors. Based on your request, player should have same bright colors which is not so good.
> 
> Anyway I'm open for any discussion. Please provide information which options of `Theme` should be used in `BetterPlayerControlsConfiguration`.

By default, _Chewie_ gets the primary color and its decolored version for the progress bar, controls, menu and other icons, based on the theme, i could be good to add a constructor for it, not a default one cause as you said, black/white is pretty neutral.

**Comment by jhomlala** [comment]
Okay, I'll add this in next release.

**Comment by jhomlala** [comment]
Added in 0.0.74.
