### ISSUE TITLE
[BUG] try to fullscreen but error

### ISSUE THREAD

**Issue by callmejm** [jhomlala/betterplayer#657]
I new to here, just following example of [List player usage](https://jhomlala.github.io/betterplayer/#/listplayerusage), but already facing issue when try to fullscreen.

better_player: ^0.0.73

    return Scaffold(
      extendBodyBehindAppBar: false,
      backgroundColor: Colors.white,
      appBar: AppBar(
        leading: CustomBack(),
        backgroundColor: Colors.white,
      ),
      body: SmartRefresher(
        controller: refreshController,
        primary: false,
        enablePullDown: true,
        enablePullUp: false,
        onLoading: () async {
        },
        onRefresh: () async {
        
        },
        header: MaterialClassicHeader(),
        footer: ClassicFooter(
          loadStyle: LoadStyle.ShowWhenLoading,
        ),
        physics: BouncingScrollPhysics(),
        child: CustomScrollView(
          slivers: [
            SliverToBoxAdapter(
              child: AspectRatio(
                aspectRatio: 16 / 9,
                child: BetterPlayerListVideoPlayer(
                  BetterPlayerDataSource(BetterPlayerDataSourceType.network, 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4'),
                  key: Key('video-1'),
                  playFraction: 0.8,
                ),
              )
            )
          ],
        ),
      ),
    );

https://user-images.githubusercontent.com/6957533/130239364-8577d424-9f5b-4123-9ee7-25da1cdb6516.mp4

**Comment by jhomlala** [comment]
@callmejm You didn't provide minimal reproducible example. Anyway I've setup it based on your example and I can't reproduce your issue.

```dart
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

class NormalPlayerPage extends StatefulWidget {
  @override
  _NormalPlayerPageState createState() => _NormalPlayerPageState();
}

class _NormalPlayerPageState extends State<NormalPlayerPage> {
  final refreshController = RefreshController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: false,
      backgroundColor: Colors.white,
      appBar: AppBar(
        leading: Text("Back"),
        backgroundColor: Colors.white,
      ),
      body: SmartRefresher(
        controller: refreshController,
        primary: false,
        enablePullDown: true,
        enablePullUp: false,
        onLoading: () async {},
        onRefresh: () async {},
        header: MaterialClassicHeader(),
        footer: ClassicFooter(
          loadStyle: LoadStyle.ShowWhenLoading,
        ),
        physics: BouncingScrollPhysics(),
        child: CustomScrollView(
          slivers: [
            SliverToBoxAdapter(
                child: AspectRatio(
              aspectRatio: 16 / 9,
              child: BetterPlayerListVideoPlayer(
                BetterPlayerDataSource(BetterPlayerDataSourceType.network,
                    'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4'),
                key: Key('video-1'),
                playFraction: 0.8,
              ),
            ))
          ],
        ),
      ),
    );
  }
}
```
Please provide reproducible steps with reproducible code.

**Comment by jhomlala** [comment]
Closed due to no response from author. Please let me know in this issue if you still have this issue. If you will provide reproducible steps then I'll reopen it.
