### ISSUE TITLE
[BUG] Duplicate globalkey detected for BetterPlayerPlaylist

### ISSUE THREAD

**Issue by threadprogrammer** [jhomlala/betterplayer#660]
**History check**
Nothing found in previous issues

**Describe the bug**
I have video playlists in my app; And now I get an error message that say Duplicate GlobalKey detected in Widget tree when I want to use the MiniPlayer Action like Youtube. Because it creates multiple instances of BetterPlayerPlaylist with the same Globalkey; and finally throws exception.

**To Reproduce**
1. Go to examples folder
2. Click on PLaylistItems
3. Use BetterPlayerPlaylist instance in 2 screens (with the key that is assigned for setting betterplayerplaylistcontroller)
4. Now it throws exception because of having multiple widgets with the same globalkey

**Expected behavior**
I want a single instance of BetterplayerPlaylist for all the pages to behave like youtube's miniplayer

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.59.1)
[√] Connected device (3 available)
**Better Player version**
- Version:

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL API 30 (emulator)
 - OS: Android 11

**Comment by jhomlala** [comment]
Please provide reproducible example. If you're using other plugin then you need to provide sample project.

**Comment by jhomlala** [comment]
@threadprogrammer You have failed to provide example code. If you will provide all necessary data in this issue then I'll open it again.
