### ISSUE TITLE
[BUG] Cannot play HLS video

### ISSUE THREAD

**Issue by hungharry123** [jhomlala/betterplayer#661]
I have an issue when play m3u8 file. It alway show loading but not show any log unil out of time.
I try to view in VLC or Safari. It still work but i don't why.
Can you help me what i miss
Here is my HLS 

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:55

#EXTINF:3.960,
/live/box_1_cam_15168/1629795925.ts
#EXTINF:3.960,
/live/box_1_cam_15168/1629795929.ts
#EXTINF:3.960,
/live/box_1_cam_15168/1629795933.ts

**Comment by jhomlala** [comment]
@hungharry123 Please format your issue according to issue template.Please setup your example on some hosting storage and provide link to the HLS video.

**Comment by hungharry123** [comment]
I've tried to play in here it's work https://players.akamai.com/players/hlsjs
<img width="1871" alt="Screen Shot 2021-08-26 at 21 24 18" src="https://user-images.githubusercontent.com/32124906/131223593-b388ea3f-ee09-4a51-9655-ede430ac0b14.png">

**Comment by hungharry123** [comment]
I've tried to play in here https://players.akamai.com/players/hlsjs, it's worked.
![Screen Shot 2021-08-28 at 22 53 21](https://user-images.githubusercontent.com/32124906/131223611-3c055489-a950-4a71-be50-bf35f4a705d2.png)

**Comment by hungharry123** [comment]
In here( https://demo.theoplayer.com/test-your-stream-with-statistics) I turned off the **`Preload video`** it's work too.
![Screen Shot 2021-08-28 at 22 56 31](https://user-images.githubusercontent.com/32124906/131223664-79fb447e-a2e9-464e-8bf8-b90d46c5e5d6.png)

**Comment by jhomlala** [comment]
@hungharry123 On my side your HLS stream doesn't work. Are you sure that your stream is accessible?

**Comment by hungharry123** [comment]
Sometime in the first time play the stream not ready. You'll retry after 5 seconds.

**Comment by hungharry123** [comment]
I tried to debug at` FLTBetterPlayerPlugin.m ` in the observeValue case `timeRangeContext`, the `AVPlayerItem` get ranges is empty in `loadedTimeRanges` so your player not working. I thinks the issue is right here.
I tried to present AVPlayerController using the same link it worked fine.

**Comment by jhomlala** [comment]
@hungharry123 I think it's something connected with your playlist or server, not sure what's exactly. I'm getting random errors like this:

```
Error Domain=NSURLErrorDomain Code=-1008 "resource unavailable" UserInfo={NSLocalizedDescription=resource unavailable, NSUnderlyingError=0x280591950 {Error Domain=NSOSStatusErrorDomain Code=-12884 "(null)"}}
```
```
Error Domain=NSURLErrorDomain Code=-1008 "See -[AVPlayerItem errorLog] for 2 events" UserInfo={NSDebugDescription=See -[AVPlayerItem errorLog] for 2 events, NSLocalizedDescription=resource unavailable, NSUnderlyingError=0x281401050 {Error Domain=CoreMediaErrorDomain Code=-16845 "Nie można ukończyć tej operacji. (Błąd CoreMediaErrorDomain -16845 - HTTP 400: (unhandled))" UserInfo={NSDescription=Nie można ukończyć tej operacji. (Błąd CoreMediaErrorDomain -16845 - HTTP 400: (unhandled))}}}
```

I've tried this url: https://demo.edge247.xyz/live/box_1_cam_15259/playlist.m3u8
This url also doesn't work in THEO and Akamai player.

**Comment by hungharry123** [comment]
@jhomlala i'm using right now. Can you try again ?
<img width="2032" alt="Screen Shot 2021-09-03 at 00 42 21" src="https://user-images.githubusercontent.com/32124906/131891597-b7933e9b-3bac-461b-8d8f-7af0fc6bb743.png">

**Comment by jhomlala** [comment]
No I can't. Probably this is because of some firewall and I can't access it from my location.

**Comment by jhomlala** [comment]
<img width="1174" alt="Zrzut ekranu 2021-09-2 o 19 45 59" src="https://user-images.githubusercontent.com/1329033/131892115-76a6f002-0537-4546-8490-31e63ea28fff.png">

**Comment by hungharry123** [comment]
@jhomlala Can you VPN to Viet Nam ? My Server can't push stream to your country.

**Comment by hungharry123** [comment]
Here is the` timeRangeContext` I debug
![image](https://user-images.githubusercontent.com/32124906/131897354-2508acf7-42ec-4799-b621-c187819c40f1.png)

**Comment by jhomlala** [comment]
Sorry can't help you if I can't reproduce it on my side. Feel free to create PR and I'll check it.

**Comment by im-v** [comment]
You guys run mediastreamvalidator provided by apple. 
Maybe you need to validate your stream first.

**Comment by im-v** [comment]
`Must Fix Issues

1. Illegal MIME type

All Variants, MIME type: audio/x-mpegurl
Master Playlist, MIME type: audio/x-mpegurl
2. I-frame playlists ( EXT-X-I-FRAME-STREAM-INF ) MUST be provided to support scrubbing and scanning UI

Master Playlist
3. Each EXT-X-STREAM-INF tag MUST have a FRAME-RATE attribute

Master Playlist Stream Definition for Variant #2
Master Playlist Stream Definition for Variant #3
Master Playlist Stream Definition for Variant #4
Master Playlist Stream Definition for Variant #5
Master Playlist Stream Definition for Variant #6
Master Playlist Stream Definition for Variant #7
Master Playlist Stream Definition for Variant #8
Master Playlist Stream Definition for Variant #9
4. The server MUST deliver playlists using gzip content-encoding

All Variants
Master Playlist
5. (Segment) Playlist vs segment duration mismatch

Variant #1
6. (Segment) The request timed out.

Variant #4
Variant #5
Variant #7
Variant #9
7. If EXT-X-INDEPENDENT-SEGMENTS is not in master playlist, then you MUST use the EXT-X-INDEPENDENT-SEGMENTS tag in all video media playlists

Variant #2
Variant #3
Variant #4
Variant #5
Variant #6
Variant #7
Variant #8
`

If you get something like this then please fix your HLS configuration first.
