### ISSUE TITLE
[BUG] Notification on android is not killed and progress bar is moving after app killed

### ISSUE THREAD

**Issue by kkoken** [jhomlala/betterplayer#662]
**History check**
Didn't find any issue raised on this.

**Describe the bug**
A player with notification configured and lifeCycle set to false (Background play).
I paused the video. Then I killed the app, notification is still alive, and progress bar on notification starts moving.

**To Reproduce**
1. Play a video
2. Then pause it.
3. Completely kill the app
4. Progress bar on notification is on pause state however progress bar is moving on.

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**
Notification should be killed or at least progress bar should not continue

**Screenshots**
(Please do not mind time on top corner)
![image](https://user-images.githubusercontent.com/87978754/130629402-fba9e53e-3a57-4b79-8377-6886c81b2855.png)
![image](https://user-images.githubusercontent.com/87978754/130630005-7ffff1df-bead-42ef-9167-3980903630de.png)

**Flutter doctor**
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-TR)
    • Flutter version 2.2.3 at /Users/kaantahakoken/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kaantahakoken/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/kaantahakoken/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Mi 9T (mobile)             • c22e6ace                             • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • 26BC8058-BE89-4B45-91CE-8C8292E876DD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

**Better Player version**
- Version: 0.0.73

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS: Android 10 (Mi UI Global 12.0.9)

**Additional context**

**Comment by jhomlala** [comment]
Did you add special service within your app to remove notification on app stop? 

https://jhomlala.github.io/betterplayer/#/notificationconfiguration
_Important note for android: You need to add special service in android native code. Service will simply destroy all remaining notifications. This service need to be used to handle situation when app is killed without proper player destroying. Check BetterPlayerService in example project to see how to add this service to your app. https://github.com/jhomlala/betterplayer/blob/feature/player_notifications/example/android/app/src/main/kotlin/com/jhomlala/better_player_example/BetterPlayerService.kt_

**Comment by kkoken** [comment]
> Did you add special service within your app to remove notification on app stop?
> 
> https://jhomlala.github.io/betterplayer/#/notificationconfiguration
> _Important note for android: You need to add special service in android native code. Service will simply destroy all remaining notifications. This service need to be used to handle situation when app is killed without proper player destroying. Check BetterPlayerService in example project to see how to add this service to your app. https://github.com/jhomlala/betterplayer/blob/feature/player_notifications/example/android/app/src/main/kotlin/com/jhomlala/better_player_example/BetterPlayerService.kt_

Yes, I followed your instruction before I submit the issue

**Comment by kkoken** [comment]
@jhomlala Actually I fixed the issue; however, I am not sure that it is the right solution.  I moved this part
`
  val notificationManager =
            getSystemService(
                Context.NOTIFICATION_SERVICE) as NotificationManager
        notificationManager.cancelAll()
`

to MainActivity and called it in `onDestroy`

**Comment by jhomlala** [comment]
@kkoken with this code, you will kill all notifications in your app. Better try to kill notification with id: `20772077` which is used by BP.

**Comment by jhomlala** [comment]
Probably issue is already solved. Feel free to answer in this topic if you still encounter this issue.

**Comment by cuongx** [comment]
@kkoken @jhomlala  is there any way to turn off notifications on ios i am having this problem please reply

**Comment by cuongx** [comment]
@jhomlala reply my with
