### ISSUE TITLE
[FEATURE] Supporting instant playback of playlist items

### ISSUE THREAD

**Issue by iosephmagno** [jhomlala/betterplayer#664]
Hello,
At Presence we need to preload/prebuffer mutiple mp4 video streams before playing them (so that they will start instantly). Is it possible to have it as a ready-to-use feature of Better Player? Feature is sort of supporting instant playback of playlist items. Common use case is instagram/snapchat/tiktok-like applications.

Thanks for this great plugin!
Ioseph Magno
Presence’s CEO

**Comment by jhomlala** [comment]
Please check latest BP version (0.0.74) which should have pre-cache feature enabled for iOS.

**Comment by iosephmagno** [comment]
Thanks.
