### ISSUE TITLE
[BUG] Video HLS is unsync while playing

### ISSUE THREAD

**Issue by siloebb** [jhomlala/betterplayer#669]
**History check**
I search in the issues and can't find anything that can help me.

**Describe the bug**
When I play HLS (m3u8) i saw that there is an unsync with the real time.
I'm developing a video platform, like Netflix, but the scene played in browser is different of the mobile, I played in many others players in browser (or desktop) with many videos in many different devices, and another thing that happens is that the subtitle in mobile unsync whats is the worst item.
How much long the video more unsync is.

**To Reproduce**
1. Play the example (or another project) with m3u8 link
2. Seek to a far played time (eg. more than 10 minutes)
3. Do the same thing with a player in web
4. Compare the scene in same time.
5. (Please if the scene is correct, try again, in rare occasions may be right)

**Example code*
I modified the example of the project in this branch, just run and click in "Unsync Player"
https://github.com/siloebb/betterplayer/tree/unsync_eg

**Expected behavior**
When I play the video I expect that the subtitle is sync with the video and the same scene is showed in every player.

**Screenshots**
![Captura de Tela 2021-08-26 às 08 54 01](https://user-images.githubusercontent.com/5496305/130961352-6cc34a34-f5e1-445b-9ae8-482b6cdb86a0.png)
In this screenshot you can see that the scene in mobile is different of the browser player

![Captura de Tela 2021-08-26 às 08 56 12](https://user-images.githubusercontent.com/5496305/130961747-74c30257-965d-44a0-902e-4373a8dba587.png)
In this screenshot you can see when the same scene is showed

![WhatsApp Image 2021-08-11 at 17 04 23](https://user-images.githubusercontent.com/5496305/130963598-3fc05066-12d9-4134-80e2-8cf8a8003e35.jpeg)
In this screenshot you can see that the subtitle is unsync, in the browser the subtitles is right. The betterplayer here is modified because is my project.

**Flutter doctor**
`[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.59.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.`

**Better Player version**
- Versions: 0.0.73 or 0.0.72

**Smartphones used:**
 - Device: Galaxy Note 9
 - OS: Android 10
 
 - Device: Iphone X
 - OS: iOS14.5

 - Device: iPhone 6
 - OS: iOS13.5

Edit: 

**Other infos**
You can use this link, was it that I use in the screenshots example:
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

**Comment by siloebb** [comment]
After so many debugging, I think that can be a problem in ExoPlayer (Using natively has same error), the error happens when the `EXTINF` not is floating-point (e.g `#EXTINF:11,`). Maybe I wrong, but it's my results.

**Comment by jhomlala** [comment]
I'll close this issue. If anyone has solution for this issue then please let me know and I'll reopen it.
