### ISSUE TITLE
Better player controllers(play, pause, duration) are blurred in ios

### ISSUE THREAD

**Issue by SalishKumar** [jhomlala/betterplayer#674]
**History check**
i searched about bug on internet, but couldn't find anything on internet

**Describe the bug**
I am using  better_player: ^0.0.69. it is working fine on android but on ios, its controllers are getting blur(play,pause,duration etc)

**To Reproduce**
Implement better player and in ios you will not notice controllers getting blue(it is happening some times)

**Screenshots**
<img width="312" alt="Screenshot 2021-08-29 at 2 12 36 PM" src="https://user-images.githubusercontent.com/54025715/131245236-57830465-d01b-48cc-b9ae-32d290cef726.png">

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version: better_player: ^0.0.69.

**Smartphone:**
 - Device: Iphone se
 - OS:  iOS 14.5

**Comment by jhomlala** [comment]
@SalishKumar Please format your issue with issue template or your issue will be closed within few days.

**Comment by SalishKumar** [comment]
**History check**
i searched about bug on internet, but couldn't find anything on internet

**Describe the bug**
I am using  better_player: ^0.0.69. it is working fine on android but on ios, its controllers are getting blur(play,pause,duration etc)

**To Reproduce**
Implement better player and in ios you will not notice controllers getting blue(it is happening some times)



**Screenshots**
<img width="312" alt="Screenshot 2021-08-29 at 2 12 36 PM" src="https://user-images.githubusercontent.com/54025715/131245236-57830465-d01b-48cc-b9ae-32d290cef726.png">


**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version: better_player: ^0.0.69.

**Smartphone:**
 - Device: Iphone se
 - OS:  iOS 14.5

**Comment by jhomlala** [comment]
I've reworked cupertino theme in my temporary branch. Update your `pubspec.yaml`:
```
better_player:
    git:
      url: https://github.com/jhomlala/betterplayer
      ref: feature/august_changes_2
```
This should solve your problems.

**Comment by SalishKumar** [comment]
@jhomlala till now haven't faced issue(as i told it is happening sometimes)

**Comment by jhomlala** [comment]
@SalishKumar So as I understand this fix has solved your issue. If you encounter this issue again, please let me know in this issue and I'll reopen it.

**Comment by SalishKumar** [comment]
@jhomlala Extra controls like playback speed are not working now(on ios only ), it is poping  the screen.

**Comment by SalishKumar** [comment]
In android controllers are hiding behind bottom navigation 
there should be a property like bottom padding
<img width="319" alt="Screenshot 2021-09-05 at 1 19 01 PM" src="https://user-images.githubusercontent.com/54025715/132120348-bd846da8-4f44-4ec6-abf2-835fadb80651.png">
