### ISSUE TITLE
mkv file canot be played

### ISSUE THREAD

**Issue by hussenIbrahim** [jhomlala/betterplayer#676]
**Describe the bug**
i testd tow mkv files one of them are not working 
[video file](https://we.tl/t-3fYYjbAmTV)
**To Reproduce**
1.  use the demo example
2.  replace the file in assets with my new file
 
**Expected behavior**
 must work
 
**Flutter doctor**
 `Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\Hussen\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\Hussen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • SM T515 (mobile)  • R52NC0AA5XT • android-arm    • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19043.1165]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 92.0.902.84`
**Better Player version**
- Version: 0.0.73

**Smartphone (please complete the following information):**
 - SM T515 (mobile)  • R52NC0AA5XT • android-arm    
 - Android 11 (API 30)

**Comment by jhomlala** [comment]
@hussenIbrahim Please format your issue ticket and use issue template. Please provide reproducible code or steps. Without this I'll close this ticket in a few days.

**Comment by jhomlala** [comment]
No answer from author. Closing issue.

**Comment by abdoutech93** [comment]
Same problem with MKV files
