### ISSUE TITLE
Preload controller of following video on a list

### ISSUE THREAD

**Issue by kiloki-official** [jhomlala/betterplayer#681]
Hello,

Your example of a (reusable) VP in list views is great, but I noticed one missing feature and one problem:

- Can you please show me how I could preload the controller of the following list item so that the following video is displayed more quickly.

- When I scroll through the videos, sometimes, the video controller is not disposed and the same video plays a second time in the background. And it crashes the app (memory leak).

This is the example I'm talking about: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list

Thanks

**Comment by jhomlala** [comment]
If you're asking for help then use discussion tab. See this policy: https://github.com/jhomlala/betterplayer/issues/535

1. Use cache: https://jhomlala.github.io/betterplayer/#/cacheconfiguration
2. Lower values in `BetterPlayerBufferingConfiguration` in `BetterPlayerDataSource`.

These techniques may solve your issues. If you encounter any issue please report issue ticket with proper issue template.
