### ISSUE TITLE
[BUG]Rtmp url error

### ISSUE THREAD

**Issue by sendershawn** [jhomlala/betterplayer#683]
when i use bp on rtmp://.  It can't use and show retry.
Only on ios.

**Comment by jhomlala** [comment]
@sendershawn  Please format your issue ticket and use issue template. Please provide reproducible code or steps. Without this I'll close this ticket in a few days.

**Comment by jhomlala** [comment]
@sendershawn Please don't create issues like this in the future. If you want to report issue then do it correctly.
