### ISSUE TITLE
[FEATURE] HLS don't start with or give access to know which subtitle is the default

### ISSUE THREAD

**Issue by siloebb** [jhomlala/betterplayer#687]
**Is your feature request related to a problem? Please describe.**
When I use HLS (eg. m3u8) I receive an attribute when a subtitle is the default the `DEFAULT=YES`, but I can't access this field from the lib and the player don't start with the subtitle with this field marked.

**Describe the solution you'd like**
I wait that the video start with the subtitle that have the attribute `DEFAULT=YES`, a used pattern in the players, or at least give the information of which subtitle is the default.

**Additional context**
I saw another feature requested [[FEATURE] Enable Default Subtitle](https://github.com/jhomlala/betterplayer/issues/615) , but my request differs because the HLS came ready to play and not is needed set the subtitles.

The example project have a video that can be used, the `HLS subtitles`, if you play in the most of players the default sub will be selected by default.
In the file of [example](https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8) you can see this line below with the field `DEFAULT=YES`
`#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE="en",URI="subtitles_en.m3u8"`

**Comment by siloebb** [comment]
I made a PR to resolve this issue, I will thanks if can review.

**Comment by jhomlala** [comment]
Added in 0.0.74. Thank you for your PR.
