### ISSUE TITLE
[BUG] iOS Full screen is not working in reusable player list demo, don't know how to fix.

### ISSUE THREAD

**Issue by majingAragon** [jhomlala/betterplayer#689]
Hi, I use code as the demo on iOS.  the demo link: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list, but entering full screen is not working, only device rotate , not enter full screen, I run the demo, entering full screen is working. How to set configuration to fix it ? 

When clicking full screen button, the terminal show the following error:

> ════════ Exception caught by foundation library ════════════════════════════════
setState() or markNeedsBuild() called during build.
════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:3944
#1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:3958
#2      Element.findRootAncestorStateOfType
package:flutter/…/widgets/framework.dart:4018
#3      Navigator.of
package:flutter/…/widgets/navigator.dart:2725
#4      _BetterPlayerState._pushFullScreenWidget
package:better_player/…/core/better_player.dart:258 <asynchronous suspension>
#5    _BetterPlayerState.onFullScreenChanged (package:better_player/src/core/better_player.d<…>

flutter version: 2.2.3

Better Player version: 0.0.73

flutter doctor

> [✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    zh-Hans-CN)
  [✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)
    ! Error: “songsong”的 iPhone is not connected. Xcode will continue when
      “songsong”的 iPhone is connected. (code -13)

**Comment by majingAragon** [comment]
In my project, i create widget as following code:
`return Scaffold(
      appBar: buildTitleBar(),
      backgroundColor: Color(0xff191919),
      body: Container(
        color: Color(0xff191919),
        child: TabBarView(
          controller: tabController,
          children: [
            HomeListView(
              0,
              model: _model,
              isFollowingNotifier: isFollowingNotifier,
            ),
            HomeListView(
              1,
              model: _model,
              isFollowingNotifier: isFollowingNotifier,
            ),
            HomeListView(
              2,
              model: _model,
              isFollowingNotifier: isFollowingNotifier,
            ),
            HomeListView(
              3,
              model: _model,
              isFollowingNotifier: isFollowingNotifier,
            ),
            HomeListView(
              4,
              model: _model,
              isFollowingNotifier: isFollowingNotifier,
            ),
          ],
        ),
      ),
    );`

 HomeListView class is reusable player list, navigate to full screen, the method "navigator.of(context)" except error.

**Comment by jhomlala** [comment]
@majingAragon Please provide reproducible example. Without this I'm unable to debug issue. The code provided by you is not enough to debug this issue.

**Comment by jhomlala** [comment]
Author failed to provide reproducible example. Closing issue.
