### ISSUE TITLE
Duplicate plugin key

### ISSUE THREAD

**Issue by PedroCM-git** [jhomlala/betterplayer#69]
Hey there, im developing a flutter app using your plugin. In android it works just fine but on IOS I get the following:

![image](https://user-images.githubusercontent.com/35906679/94431023-12acc700-0195-11eb-8ca1-c15459619463.png)

I´ve been digging for a while and I believe its some kind of conflict with the class naming of the [https://pub.dev/packages/video_player](url) since they have both the same name.

**Comment by jhomlala** [comment]
Hi, this should be fixed with latest release (0.0.23).

**Comment by PedroCM-git** [comment]
> Hi, this should be fixed with latest release (0.0.23).

Hey, thanks its fixed now. [https://github.com/jhomlala/betterplayer](url) is the **better player**.
