### ISSUE TITLE
How to get current position (To do autocomplete)[FEATURE]

### ISSUE THREAD

**Issue by MomenAbdezaher** [jhomlala/betterplayer#690]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jhomlala** [comment]
@MomenAbdezaher If you want to ask question then do it correctly. At least fill all the data from the issue. To ask questions use discussion tab or use search option.

**Comment by MomenAbdezaher** [comment]
Sorry, I am new to using these sites and methods and I hope you will answer a question directly, thanks for the help
