### ISSUE TITLE
[BUG] iOS Seek bar position revert to original after move for a second

### ISSUE THREAD

**Issue by mlph-vbarcinal** [jhomlala/betterplayer#694]
**Describe the bug**
I used your example code to test. In the [hls_tacks_page.dart](https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/hls_tracks_page.dart), I changed the `URL` of `BetterPlayerDataSource` to [Constants.phantomVideoUrl](https://github.com/jhomlala/betterplayer/blob/d8fb72275c68feb69d8f2907865eeac5a98b68d7/example/lib/constants.dart#L25) and when I move the seek bar position, the seek bar position will stay from the original position for about a second I think then moved to the desired position. I attached a screen recording played on my iPhone 12 device. Start at 0:09 of the video.

**Expected behavior**
After I moved the seek bar position, it must stay there.

**Screenshots**

https://user-images.githubusercontent.com/60649880/132155984-6f574021-822d-48ef-9797-03dea21cb8ce.mp4

**Flutter doctor**

> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-PH)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [!] Android Studio (version 2020.3)
>     ✗ Unable to find bundled Java version.
> [✓] Connected device (2 available)

**Better Player version**
- Version: 0.0.73

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.7.1

**Comment by jhomlala** [comment]
@mlph-vbarcinal Thanks for reporting. Seems like this issue is connected with your internet connection. Please try to add this in `pubspec.yaml` and check if it will fix your issue.

```
better_player:
    git:
      url: https://github.com/jhomlala/betterplayer
      ref: feature/august_changes_2
```

**Comment by mlph-vbarcinal** [comment]
@jhomlala Thank you for noticing this issue. I tested it and it works! Thank you very much!
