### ISSUE TITLE
Many bugs in better player

### ISSUE THREAD

**Issue by SalishKumar** [jhomlala/betterplayer#695]
**History check**
I have searched alot but could n't find anything
**Describe the bug**
There are many bugs

1. Sometimes i get error ("Video can't be played)
<img width="306" alt="Screenshot 2021-09-06 at 10 15 12 PM" src="https://user-images.githubusercontent.com/54025715/132248296-6d16e20c-28aa-4c29-8201-97907f998171.png">

2. Extra controls like playback speed are not working now(on ios only ), it is poping the screen.
https://user-images.githubusercontent.com/54025715/132248447-c554a8b1-86ee-449f-9599-6ec18d1d8da3.mp4

3. In android controllers are hiding behind bottom navigation
there should be a property like bottom padding
<img width="339" alt="Screenshot 2021-09-06 at 10 20 00 PM" src="https://user-images.githubusercontent.com/54025715/132248499-5e779c2f-c408-4dc0-a798-449518217518.png">

4. Ios app is crashing alot in release mode after using mentioned version

**To Reproduce**
Bug1
1. It is happening very offen
Bug2
1, Happening after using reworked version in https://github.com/jhomlala/betterplayer/issues/674#issuecomment-909550195
Bug3
1. Check with bottom navigation bar in android only

**Better Player version**
better_player:
    git:
      url: https://github.com/jhomlala/betterplayer
      ref: feature/august_changes_2

Smartphone:

Device: Iphone se
OS: iOS 14.5

**Comment by jhomlala** [comment]
@SalishKumar Please provide minimal reproducible code. From my perspective all of this bugs are connected with your app structure and used libraries. I've tested basic flow in example app and everything is fine, so there's no regression right now.

**Comment by SalishKumar** [comment]
Bug1  = couldn;t find the reason it happens sometimes
bug2 = use this version  (happening only in ios if it was due to my code then it should malfunction on android too)
better_player:
git:
url: https://github.com/jhomlala/betterplayer
ref: feature/august_changes_2

bug3 = it is actually a suggestion for android
bug 4 = ios  app is crashing  in release after  integrated this version 
better_player:
git:
url: https://github.com/jhomlala/betterplayer
ref: feature/august_changes_2

**Comment by jhomlala** [comment]
@SalishKumar Again, please provide useful details about issues. I don't have a time to debug your issues without any reproducible code. If you won't provide it, I will simply close this issue.

- Bug number 1. If it happens randomly then it may be connected with your connection issue. Please test on other device.
- Bug number 2. It's your app issue, not BP. Please check BP example and you will see that everything works fine.
- Suggestion 3. If it's suggestion then add reproducible code and I'll try to find solution.
- Bug number 4. How I suppose to debug your "problem" if you didn't provide any error log?

@SalishKumar This is last call. I won't repeat myself. Please provide details (reproducible code) for each issue/suggestion.

**Comment by SalishKumar** [comment]
for bug 2 did you try the mentioned library as it was provided by you after bug fixing in ticket #674

**Comment by SalishKumar** [comment]
_controller = VideoPlayerController.network(widget.url);
    timer = Timer.periodic(Duration(seconds: 2), (timer) async {
      if (!checkingForReady) {
        checkingForReady = true;
        final bool isReady = await checkIfVideoReadyToStream();
        checkingForReady = false;
        if (isReady) {
          timer.cancel();
          setState(() {
            final betterPlayerDataSource = BetterPlayerDataSource(
              BetterPlayerDataSourceType.network,
              widget.url,
            );
            // _betterPlayerController
            //     .addEventsListener((BetterPlayerEvent event) {
            //   if (event.betterPlayerEventType ==
            //       BetterPlayerEventType.initialized) {
            //     _betterPlayerController.setOverriddenAspectRatio(
            //         _betterPlayerController
            //             .videoPlayerController.value.aspectRatio);
            //   }
            // });

            _betterPlayerController = BetterPlayerController(
                BetterPlayerConfiguration(
                  aspectRatio: _controller.value.aspectRatio,
                  autoPlay: false,
                  fit: BoxFit.scaleDown,
                  controlsConfiguration: BetterPlayerControlsConfiguration(
                    enableSkips: false,
                    enableFullscreen: true,
                    enablePip: false,
                  ),
                ),
                betterPlayerDataSource: betterPlayerDataSource);

            readyToStream = true;
          });
        }
      }
    });

**Comment by jhomlala** [comment]
@SalishKumar Sorry, this issue is totally chaotic and not well structured. People don't have time to debug your issues if you can't explain exactly what's your problem. There's issue template which you should follow. Also you have been requested for minimal reproducible example. Please respect other people time and structure your question. Feel free to create new issue if you will be able to setup reproducible example.
