### ISSUE TITLE
[BUG] Video doesn't fully clipped in circle path

### ISSUE THREAD

**Issue by Nico3652** [jhomlala/betterplayer#696]
**Describe the bug**
The video inside ClipPath with CustomClipper<Path> is not fully clipped in circle

**To Reproduce**
1. Simply run the app
2. See the video not fully clipped inside circle

**Example code*

```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: VideoTest(),
    );
  }
}

class VideoTest extends StatefulWidget {
  @override
  _VideoTestState createState() => _VideoTestState();
}

class _VideoTestState extends State<VideoTest> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: CustomPaint(
        painter: PaintCircleBorder(
          minRadius: 150,
          maxRadius: 150,
          cx: MediaQuery.of(context).size.width / 2,
          cy: MediaQuery.of(context).size.height / 2,
        ),
        child: ClipPath(
          clipper: CircularPath(
              minRadius: 150,
              maxRadius: 150,
              cx: MediaQuery.of(context).size.width / 2,
              cy: MediaQuery.of(context).size.height / 2,
              fraction: 1),
          child: VideoPlayerWidget(),
        ),
      ),
    );
  }

}


class VideoPlayerWidget extends StatefulWidget {

  @override
  _VideoPlayerWidgetState createState() => _VideoPlayerWidgetState();
}

class _VideoPlayerWidgetState extends State<VideoPlayerWidget> {

  BetterPlayerController? controller;

  @override
  void initState() {
    controller = BetterPlayerController(
        BetterPlayerConfiguration(
          aspectRatio: 1,
          looping: true,
          autoPlay: true,
          autoDispose: false,
          handleLifecycle: false,
          controlsConfiguration:
          BetterPlayerControlsConfiguration(showControls: false),
        ),
        betterPlayerDataSource: BetterPlayerDataSource(
            BetterPlayerDataSourceType.network,
            'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
        )

    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return BetterPlayer(controller: controller!);
  }
}




class CircularPath extends CustomClipper<Path> {
  double fraction = 1;
  final double minRadius;
  final double maxRadius;
  final double cx, cy;

  CircularPath({
    required this.fraction,
    required this.cx,
    required this.cy,
    required this.minRadius,
    required this.maxRadius,
  });

  @override
  Path getClip(Size size) {
    return Path()
      ..addOval(
        Rect.fromCircle(
          center: Offset(cx, cy),
          radius: lerpDouble(minRadius, maxRadius, fraction),
        ),
      );
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => true;

  static double lerpDouble(double a, double b, double t) {
    return a * (1.0 - t) + b * t;
  }
}

class PaintCircleBorder extends CustomPainter {
  double fraction = 1;
  final double minRadius;
  final double maxRadius;
  final double cx, cy;
  double strokeWidth;
  Color shadowColor;
  Color strokeColor;

  PaintCircleBorder(
      {required this.cx,
      required this.cy,
      required this.minRadius,
      required this.maxRadius,
      this.shadowColor = Colors.black,
      this.strokeColor = Colors.white,
      this.strokeWidth = 15});

  @override
  void paint(Canvas canvas, Size size) {
    Path path = Path()
      ..addOval(
        Rect.fromCircle(
          center: Offset(cx, cy),
          radius: lerpDouble(minRadius, maxRadius, fraction),
        ),
      );

    Paint paint = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..color = strokeColor;

    canvas.drawShadow(path, shadowColor, 8, false);
    canvas.drawPath(path, paint);
  }

  static double convertRadiusToSigma(double radius) {
    return radius * 0.57735 + 0.5;
  }

  double lerpDouble(double a, double b, double t) {
    return a * (1.0 - t) + b * t;
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}

```

**Expected behavior**
Video clipped in circle and not above the paint

**Screenshots**

**Video clipped :**

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-09 at 01 29 36](https://user-images.githubusercontent.com/50270977/132599676-22a9ea85-f5e9-4d85-94b3-899a82428ad2.png)

**Clipper with out video :**

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-09 at 01 29 54](https://user-images.githubusercontent.com/50270977/132599744-1b97ca56-c231-47b4-87f9-71a18a9d9656.png)

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Better Player version**
- Version: ```better_player: ^0.0.73```

**Smartphone (please complete the following information):**
 - Device: [Iphone 12 pro max simulator ]
 - OS: [iOS 14.5]

**Additional context**
SAME ISSUE ON REAL DEVICE
The issue appear while playing and NOT playing.

Have you ever seen this problem ?
Could it be a clipper problem ?

Thanks in advance

**Comment by eugeen3** [comment]
Try this
`child: Center(
                    child: ClipRRect(
                      borderRadius: BorderRadius.all(Radius.circular(300)),
                      child: BetterPlayer(
                        controller: _betterPlayerController.value,
                      ),
                    ),
                  ),`

**Comment by Nico3652** [comment]
@eugeen3  According my tests this is happening only on IOS and I'm not able to run on IOS since the new flutter release 2.5 . I'll try as soon as I can . Thanks for help

**Comment by eugeen3** [comment]
@Nico3652 Flutter 2.5 doesn't work on iOS?

**Comment by Nico3652** [comment]
@eugeen3  My team and I are not able to run anymore. We tried to downgrade flutter version but issues on Xcode are remaining.
Can't say for everyone. But in our apps run fails. I heard that 2.6 release will be available soon to fix reported issues and I hope this one will be fix too.

As I said the video issue is not visible on Android and I don't know why. Therefore I'll try your code and if it still not working  I'll dig on IOS side.

**Comment by eugeen3** [comment]
@Nico3652 Yeah, I have several problems with running apps with Flutter 2.5 on iOS. I downgraded Flutter to 2.2.3 (latest version i used when apps running well on iOS) and `https://stackoverflow.com/a/64075795/13111967` do this, so now it's fine.

**Comment by jhomlala** [comment]
@Nico3652 I think it's issue with ClipPath and platform view. Your code seems fine, but Flutter is creating wrong clipping of iOS platform view. Can you check if same problem occurs when clipping player from VideoPlayer package? 

BP and VideoPlayer creates platform view in a different way, so checking VideoPlayer will give us clue what can be wrong.

**Comment by Nico3652** [comment]
@eugeen3  Thanks for help. I can run on IOS now . But your solution is not working .. seems that radius value could not be the solution for this. 

@jhomlala  Unfortunately I'm not able to load video with the VideoPlayer because I'm facing this [issue](https://github.com/flutter/flutter/issues/62785) as many people on IOS (real devices). The video sound is playing but frames are not displayed and I couldn't fix it yet. I just retried as you recommended but no result again. 
By the way this is why I'm using your plugin and much more. Big thank you for your job !

We are very embarrassed with this issue because this video display is our main core in app.

**Comment by jhomlala** [comment]
I'm closing this issue, because I don't see any solution for that. Feel free te answer in this issue and I'll reopen it.
