### ISSUE TITLE
how can i show the time of the video?

### ISSUE THREAD

**Issue by ziboilihua** [jhomlala/betterplayer#7]
can't  find how i can show the time of the video in BetterPlayerConfiguration , is there a way to config this?

**Comment by jhomlala** [comment]
` _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(
          controlsConfiguration:
              BetterPlayerControlsConfiguration(enableProgressText: true),
        ),
        betterPlayerDataSource: dataSource);`

`enableProgressText` will enable/disable progress text in controls

**Comment by jhomlala** [comment]
If this doesn't solve your problem please open new issue with more details.
