### ISSUE TITLE
[FEATURE] Is this library support callback onPlay, onPause from Notification?

### ISSUE THREAD

**Issue by yusriltakeuchi** [jhomlala/betterplayer#700]
Can this library handle callback onPlay and onPause when the user doing something play or pause in notification items?

**Comment by jhomlala** [comment]
First, you should read this: https://github.com/jhomlala/betterplayer/issues/535. Second you should read manual here: https://jhomlala.github.io/betterplayer/#/events

**Comment by m1n093** [comment]
@jhomlala 
When i tap pause on notification, there are any events video stop, but still with progress event.

![image](https://user-images.githubusercontent.com/41908373/171516322-9d08fd32-ed10-420d-bec3-91fe0fbbb197.png)
