### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by jhomlala** [jhomlala/betterplayer#702]
In the past one and half year Better Player has been activiely maintained by me and ocassionally by many other people. There was over 480 closed issues and 125 PRs. Better Player is one of the main video solutions in Flutter enviornment and is being used by many apps.
 
Unfortunately due to my limited spare time, I'm unable to activiely maintain this project. This situation won't change for a next few months, so I'm looking for person(s) who will be able to help me maintain this awesome project. Feel free to contact me here in this issue.

There's a chance that I will look into some important issues/feature requests in next months, but BP is not in my priority list, so please don't contact me with questions "when it will be done". Anyone is free to contribute to this project or to fork it. 

I would like to continue this project in the future, but for now Better Player won't be maintained. Issues or features requests may be not responded for long time until I or someone will pick that.

Thank you for your support and for using Better Player.

**Comment by purplecandy** [comment]
Hi, 
Thank you for efforts it has helped us a lot.

I'm interested to help in maintaining this library where can I start? I have already looking into issues.

**Comment by jhomlala** [comment]
Please start looking into issues and create patch PR which contains fixes for one or more issues.

**Comment by ptsekov** [comment]
Hello, I'd like to help maintaining Better Player. I am not exactly fluent with Flutter though I am trying to improve that, but I can help with the platform part.

**Comment by Holofox** [comment]
@jhomlala, hello! Please give me the rights of the maintainer, I will try to check the existing PRs and merge them into the main branch.

**Comment by developameya** [comment]
Hi, I would to be included as a maintainer for this repo. I'm fluent in Dart and good with Flutter.

**Comment by Eimji** [comment]
Hello,

I also want to be a maintainer for the code. I have fixed a lot of issues to make PiP worked both in Android & iOS.

Thanks

**Comment by FlawLessx** [comment]
Hello, are you done selecting who will maintain this plugin?  Many PRs or issues have not been processed

**Comment by zLuoManhwas** [comment]
Podemos ayudar a mantener este proyecto!

**Comment by gaborcselle** [comment]
Hi there, I was wondering if you've found anyone to maintain this? Or is there a fork of better player that has some of the PRs that people have offered up? Thank you for making betterplayer!

**Comment by nateshmbhat** [comment]
i've been using better_player_plus package and its been great so far. It also uses the new media3 exo player for playback

**Comment by nateshmbhat** [comment]
Unfortunately the developer of better_player hasn't been getting enough time to work and maintain this project.

So have forked, maintaining and updating this project as `awesome_video_player` here (https://pub.dev/packages/awesome_video_player) 

Feel free to raise feature requests and PRs 🎊 🥳

**Comment by cka29** [comment]
> Unfortunately the developer of better_player hasn't been getting enough time to work and maintain this project.
> 
> So have forked, maintaining and updating this project as `awesome_video_player` here ([pub.dev/packages/awesome_video_player](https://pub.dev/packages/awesome_video_player))
> 
> Feel free to raise feature requests and PRs 🎊 🥳

Hi @nateshmbhat ! Awesome! Where can I find the actual GH repo? 🙏 The one linked on pub.dev is not available: https://github.com/nateshmbhat/awesome_video_player

**Comment by nateshmbhat** [comment]
@cka29 its the same link as listed 
 https://github.com/nateshmbhat/awesome_video_player

It's visibility was private by mistake. It's fixed now 🙏🏻
