### ISSUE TITLE
[FEATURE] HSL Stream Resolution Setting?

### ISSUE THREAD

**Issue by yusriltakeuchi** [jhomlala/betterplayer#703]
**Is your feature request related to a problem? Please describe.**
I think we need to set resolution when playing HSL Streaming Url with format .m3u8, because we want to optimize for users with slow internet networks

**Describe the solution you'd like**
Maybe it's can be better if we can set resolution in HSL Streaming. I just know betterplayer has "resolution" field in data source but we must set with different url, i just have 1 stream url now.

If the feature already exists, please tell me how to use it.
https://jhomlala.github.io/betterplayer/#/resolutionsofvideo
in this documentation just explain how to use resolution in non Streaming video

**Comment by jhomlala** [comment]
Resolutions feature is used when you want to setup different resolutions of the same video which is non-HLS. If you're using HLS and it's properly configured then resolutions will be auto-detected by BP. Please see this example: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/hls_tracks_page.dart
