### ISSUE TITLE
Saving state of controller

### ISSUE THREAD

**Issue by eugeen3** [jhomlala/betterplayer#704]
In my app I have some kind of tab bar and in one of the tab i use BetterPlayer. When i switching between tabs and go back to page with player it's state is already disposed and I'm getting error instead of player widget.

**Comment by jhomlala** [comment]
Please create your issue by using issue template (https://github.com/jhomlala/betterplayer/issues/535). Regarding your problem, you should manually dispose your controller: https://jhomlala.github.io/betterplayer/#/manualdispose.
