### ISSUE TITLE
[FEATURE] Can i get the duration and position of a video player?

### ISSUE THREAD

**Issue by eugeen3** [jhomlala/betterplayer#708]
I'm using a `BetterPlayer` in a separate widget, where it just plays the video and video controls for this videoplayer is disabled. And also, i have my own widget with play/pause button and two text widgets, which are intended to display position and duration of a video. I've simply managed the play/pause button, but have no idea how to update position and duration. I'm also used and `audioplayers` library and it has `onAudioPositionChanged/onAudioDurationChanged Streams`, and with subscription to this i can get the latest values of position and duration. I tried to do something like this (position and duration in my case is ValueNotifiers) : 
```@override
  void initState() {
    super.initState();

    betterPlayerController.value.addEventsListener((BetterPlayerEvent e) {
      if (e.betterPlayerEventType == BetterPlayerEventType.play) {
        Timer.periodic(_requestFrequency, (Timer t) {
          _updateDuration();
          _updatePosition();
        });
      }
    });
  }

  void _updatePosition() {
    position.value =
        betterPlayerController.value.videoPlayerController?.value.position ??
            Duration(seconds: 0);
  }

  void _updateDuration() {
    duration.value =
        betterPlayerController.value.videoPlayerController?.value.duration ??
            Duration(seconds: 0);
  }
```
But it's doesn't work as i supposed.

**Comment by jhomlala** [comment]
@eugeen3 Please use issue template and provide reproducible code. This snippet code can't be used to reproduce issue. Probably something is wrong with your code rather than Better Player.

**Comment by eugeen3** [comment]
Thanks for the answer man, I'm already done what i wanted, just wrapped `_updatePosition()` and `_updateDuration()` calls in `Timer` with `setState()` and that's all.
