### ISSUE TITLE
[BUG] On speed and quality menu tap the app automatically go to previous page (only on iOS)

### ISSUE THREAD

**Issue by sidelux** [jhomlala/betterplayer#715]
Hi,
i have a problem with betterplayer with standard implementation, only on iOS, when i tap on "Speed" or "Quality" button it opens the next menu (with speed selection or quality selection) but the app go back to previous page.
I have a list and when i tap on a list element it open the detail page with the video on the top of the screen.

**Expected behavior**
The app should open the quality and speed selection without go back in navigation.

**Screenshots**
[Imgur](https://imgur.com/a/JNPh4KG)

**Flutter doctor**
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Versione 10.0.19043.1237], locale it-IT)
    • Flutter version 2.2.3 at C:\Users\Edoco\Documents\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Edoco\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\Edoco\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Mi A3 (mobile) • 1285731c08d6 • android-arm64  • Android 11 (API 30)
    • Chrome (web)   • chrome       • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)     • edge         • web-javascript • Microsoft Edge 93.0.961.52

! Doctor found issues in 1 category.
```
(Android Studio is installed btw...)

**Better Player version**
- Version: 0.0.73

**Smartphone:**
 - Device: iPhone 12 Pro
 - OS: iOS 15.0

**Comment by Chomroeun** [comment]
Yes I met this issue with iOS as well.

**Comment by jhomlala** [comment]
Please provide minimal reproducible example @sidelux.

**Comment by daveshirman** [comment]
I can confirm this.

I suspect this is happening with people also using a custom solution to keep a persistent bottom navigation tab bar in their apps.  

To reproduce:

Just put the player on a page and try it, but with the `rootNavigator` set to `true`, e.g in my case:

```
      Navigator.of(context, rootNavigator: false).push(
        CupertinoPageRoute(
          builder: (context) => PageVideo(
            video: _selectedVideo!,
          ),
        ),
      );
```

When in that resulting page I try to use the quality or speed options, the app navigates back, popping the page.

If I change `rootNavigator` to `true` - then the bug doesn't happen with the modal sheets switch.

**Comment by jhomlala** [comment]
Can you try run BP version from this PR: https://github.com/jhomlala/betterplayer/pull/679 and see if it helps?

**Comment by sidelux** [comment]
I can confirm that @daveshirman's solution works.
For now i can't test the PR.

**Comment by jhomlala** [comment]
In version 0.0.76 `useRootNavigator` parameter has been added to the `BetterPlayerConfiguration` class.
