### ISSUE TITLE
[FEATURE] support ass subtitles

### ISSUE THREAD

**Issue by zdabing** [jhomlala/betterplayer#716]
Can support ass subtitles?

**Comment by jhomlala** [comment]
What is .ass? Why it should be supported? Please elaborate.

**Comment by zdabing** [comment]
> 什么是. ass？为什么要支持它？这在移动播放器中支持这真的是重要的字幕标准吗？请详细说明。

ASS subtitles

**Comment by jhomlala** [comment]
@zdabing Sorry I don't understand what do you wanted to say. Please answer my questions or I will close this issue.
