### ISSUE TITLE
[FEATURE] Set resolution using api or set default resolution 

### ISSUE THREAD

**Issue by sidelux** [jhomlala/betterplayer#717]
Hi,
i would like to know if there is a way to set a custom resolution before building the player (not the first one only), or an api to set the resolution in a later moment (something like `setResolution("resolution name")`).
Thanks

**Comment by jhomlala** [comment]
For asking question there's special "discussion" tab. Please read this policy: https://github.com/jhomlala/betterplayer/issues/535

Also before asking question, did you check documentation? This may help you: https://jhomlala.github.io/betterplayer/#/resolutionsofvideo

**Comment by sidelux** [comment]
Thanks but the docs now it no helps.
Anyway i move to discussion tab, sorry.
