### ISSUE TITLE
Platform Interface Refactor

### ISSUE THREAD

**Issue by JohnGalt1717** [jhomlala/betterplayer#719]
**Is your feature request related to a problem? Please describe.**
Right now, better_player doesn't support web or any other devices other than ios or android.  I'd like to add Web support as an example using jsplayer (and/or the existing video_player and adding additional functionality like DRM to it, but can't as the project currently sits.

**Describe the solution you'd like**
Please consider refactoring the project into a platform interface structure as recommended by the documentation.  This will allow me to easily contribute the web implementation and later other implementations like Windows and others can be added easily.

**Describe alternatives you've considered**
There are no supported alternatives.

**Comment by jhomlala** [comment]
@JohnGalt1717 Duplicate of https://github.com/jhomlala/betterplayer/issues/369
Sorry, don't have time for that. Feel free to create PR which introduces platform interface refactor. I'll be really happy to add this into BP.

**Comment by JohnGalt1717** [comment]
@jhomlala Done from my work account.
