### ISSUE TITLE
[BUG] Video not playing on iOS emulator

### ISSUE THREAD

**Issue by iosephmagno** [jhomlala/betterplayer#722]
**History check**
I checked this and didn't find anything which may solve your issue.

**Describe the bug**
Video plays properly on device but it doesn't on iOS emulator.

**To Reproduce**
1. Run official betterplayer's example on iOS emulator.

**Example code*
Official betterplayer's example.

**Expected behavior**
Video should play on both real device and emulator. That's important for debugging purpose.

**Screenshots**
Screenshots attached below (example running on both emulator and real device).

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-arm, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneXS]
 - OS: [e.g. iOS17.7.1]
 - Emulator iPhone 11 Pro

**Additional context**
<img width="358" alt="emulator" src="https://user-images.githubusercontent.com/83366073/134385383-356daa4b-9d6e-488e-a047-395b6abc77fe.png">
![real device](https://user-images.githubusercontent.com/83366073/134385399-5a84d4ee-4796-4b92-8e97-e711afa49c43.PNG)

**Comment by jhomlala** [comment]
@iosephmagno I can't reproduce your issues on latest Flutter version (2.5.1) and XCode 13 and simulator with iOS 15. For some videos there's no video playback (only audio), but this is known issue: https://github.com/jhomlala/betterplayer/issues/605

What's your flutter doctor output and what's your XCode version?

**Comment by iosephmagno** [comment]
@jhomlala XCode 12.5, simulator with iOS 14.5. 

I don't have this problem running chewie example.

Flutter doctor attached below:

[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-arm, locale en-IT)
    • Flutter version 2.5.1 at /Users/iosemagno/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (5 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/iosemagno/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPhone 11 Pro 14.14 (mobile) • 5BF7535B-7565-42B8-9A46-B94121D42C08 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 93.0.4577.82

**Comment by iosephmagno** [comment]
@jhomlala In #605 audio works fine, here both video and audio don’t.

**Comment by jhomlala** [comment]
Can you check it on latest iOS - iOS 15?

**Comment by iosephmagno** [comment]
Not soon but will keep you posted on that.

**Comment by jhomlala** [comment]
Closed right now. Feel free to answer with new information and I'll reopen it.

**Comment by iosephmagno** [comment]
Checked on latest iOS 15 and the bug is still visible there.
