### ISSUE TITLE
[BUG] IOS build issue 0.0.76 / Flutter 2.5.1 / Xcode 13

### ISSUE THREAD

**Issue by jamieownsu** [jhomlala/betterplayer#736]
Just trying to run on my device, build fails during xcode build.

Build error: 
`    /Users/jamieotoole/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.76/ios/Classes/BetterPlayer.m:6:9: fatal error: 'better_player/better_player-Swift.h' file not found
    #import <better_player/better_player-Swift.h>`

flutter doc:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)
• No issues found!

**Comment by jhomlala** [comment]
There's already issue connected with iOS build: https://github.com/jhomlala/betterplayer/issues/714 Can you check if anything from this issue may help you?

Also can you check if problem occurs on clean fresh project on your side? If it works on clean project then problem is with your project's iOS configuration.

**Comment by jamieownsu** [comment]
I will double check all that and get back to you. Thanks.

**Comment by jhomlala** [comment]
Also please provide full output of app build.

**Comment by ArrowNeck** [comment]
Issue found in pod install. Build fail

[!] CocoaPods could not find compatible versions for pod "better_player":
  In Podfile:
    better_player (from `.symlinks/plugins/better_player/ios`)

Specs satisfying the `better_player (from `.symlinks/plugins/better_player/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by jhomlala** [comment]
Better Player requires min iOS version 11. Please update your project settings in XCode.

**Comment by jamieownsu** [comment]
Going to close issue, appears to be issue with my project, not the plugin!
