### ISSUE TITLE
[BUG] 0.0.76 still got IOS building issue.

### ISSUE THREAD

**Issue by what2003** [jhomlala/betterplayer#737]
### **1. better_player: ^0.0.76 still got IOS building issue. Yesterday with 0.0.75, all fine, today this issue jumped out, flutter clean, upgrade to 0.0.76, nothing changed. Start a new project with 0.0.76, same issue.**
   In Podfile:
        better_player (from `.symlinks/plugins/better_player/ios`)
    Specs satisfying the `better_player (from `.symlinks/plugins/better_player/ios`)` dependency were found, but they required a higher minimum deployment target.

### **2. Is cache only for one video? Tested in my chat room, two videos only one could been played when wifi was disconnected.**
     cacheConfiguration: BetterPlayerCacheConfiguration(
        useCache: true,
        preCacheSize: 10 * 1024 * 1024,
        maxCacheSize: 10 * 1024 * 1024,
        maxCacheFileSize: 10 * 1024 * 1024,

        ///Android only option to use cached video between app sessions
        key: widget.url ?? widget.video!.path,
      ),

$ flutter doctor -v
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on Mac OS X 10.15.4 19E287 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-5.2.pre at /Users/jack/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (2 weeks ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • SM G975U (mobile) • 192.168.0.101:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 83.0.4103.61
    ! Device 192.168.0.87:5555 is offline.
    ! Error: 吴杰的 iPhone7 is not connected. Xcode will continue when 吴杰的 iPhone7 is connected. (code -13)

• No issues found!

**Comment by jhomlala** [comment]
@what2003 Please read your console output and installation guide: https://jhomlala.github.io/betterplayer/#/install

Everything is perfect clear here and you need to change your iOS version to 11.

**Comment by what2003** [comment]
Thank you for quick response, sorry for my careless, I should go through the installation again, the pic blow is for someone makes the same mistak
<img width="1407" alt="截屏2021-10-01 下午3 20 31" src="https://user-images.githubusercontent.com/10448102/135615378-bd06ee92-a521-4eab-9c73-6b4fc3effd0d.png">
e.

**Comment by what2003** [comment]
Here is my video play widget, basicly copy from the example, what should I do, thanks

------------------------------------------------------------------
import 'dart:io';
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

class Vplayer extends StatefulWidget {
  final String? url;
  final File? video;

  const Vplayer({Key? key, this.url, this.video}) : super(key: key);
  @override
  _VplayerState createState() => _VplayerState();
}

class _VplayerState extends State<Vplayer> {
  @override
  Widget build(BuildContext context) {
    if (widget.url == null && widget.video == null) {
      return Scaffold(
          extendBodyBehindAppBar: true,
          appBar: AppBar(
//        backgroundColor: Colors.transparent,
            backgroundColor: Color(0x44000000),
            elevation: 0,
          ),
          backgroundColor: Colors.black,
          // ignore: prefer_const_constructors
          body: Center(
              child: const Icon(
            Icons.broken_image_rounded,
            color: Colors.white,
          )));
    }
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
            autoPlay: true,
            allowedScreenSleep: false,
            autoDetectFullscreenDeviceOrientation: true,
            controlsConfiguration: const BetterPlayerControlsConfiguration(
              enableFullscreen: false,
              enableOverflowMenu: false,
            ),
            aspectRatio: 1 / MediaQuery.of(context).devicePixelRatio,
            fit: BoxFit.contain);
    _betterPlayerDataSource = BetterPlayerDataSource(
      widget.video != null
          ? BetterPlayerDataSourceType.file
          : BetterPlayerDataSourceType.network,
      widget.video != null ? widget.video!.path : widget.url!,
      cacheConfiguration: BetterPlayerCacheConfiguration(
        useCache: true,
        preCacheSize: 10 * 1024 * 1024,
        maxCacheSize: 10 * 1024 * 1024,
        maxCacheFileSize: 10 * 1024 * 1024,

        ///Android only option to use cached video between app sessions
        key: widget.url ?? widget.video!.path,
      ),
    );
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.preCache(_betterPlayerDataSource);
    _betterPlayerController.setupDataSource(_betterPlayerDataSource);

    return Scaffold(
      extendBodyBehindAppBar: true,
//       appBar: AppBar(
// //        backgroundColor: Colors.transparent,
//         backgroundColor: Color(0x44000000),
//         elevation: 0,
//       ),
      body: SafeArea(
        child: Stack(
          children: [
            SizedBox(
              height: MediaQuery.of(context).size.height,
              width: MediaQuery.of(context).size.width,
              child: BetterPlayer(
                // Constants.forBiggerBlazesUrl,
                controller: _betterPlayerController,
              ),
            ),
            Positioned(
                left: 10,
                top: 20,
                child: IconButton(
                  icon: const Icon(
                    Icons.arrow_back_ios_new_sharp,
                    color: Colors.white,
                  ),
                  onPressed: () {
                    Navigator.pop(context);
                  },
                ))
          ],
        ),
      ),
    );
  }

  late BetterPlayerController _betterPlayerController;
  late BetterPlayerDataSource _betterPlayerDataSource;

  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    if (!(widget.url == null && widget.video == null)) {
      _betterPlayerController.dispose(forceDispose: true);
    }
    super.dispose();
  }
}

**Comment by what2003** [comment]
Cache issue - also my bad, my code was wrong, now it is works great, thank you again!
