### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by Zchandev** [jhomlala/betterplayer#74]
Thanks for your project, I like it. 

Is there a way to add support for video cache? I use https://pub.dev/packages/cached_video_player for that now, with my custom modification of chewie

**Comment by jhomlala** [comment]
@Zchandev I will proceed with cache based on this PR: https://github.com/flutter/plugins/pull/2429, but I can't give you exact timeframes when it will be done.

**Comment by jhomlala** [comment]
I've just pushed new version (0.0.32) with cache support. If you encounter any problem, please open new issue based on issue template.
