### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ITApexGroup** [jhomlala/betterplayer#748]
PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640020, -1, null, [720, 1280, 29.970999], [-1, -1]), format_supported=YES, null, null)

**Comment by jhomlala** [comment]
@ITApexGroup Please provide additional details or I'll close it within a few days.

**Comment by jhomlala** [comment]
You have failed to provide additional details. Closing issue.
