### ISSUE TITLE
Video image does not appear on Ios

### ISSUE THREAD

**Issue by maiquitome** [jhomlala/betterplayer#749]
The audio and progression work... but the picture is all black. On android everything works perfect.

![image](https://user-images.githubusercontent.com/16550103/136616100-d7275176-7903-41d9-8a38-3bbb9e4edebb.png)

![image](https://user-images.githubusercontent.com/16550103/136616279-ac085be0-0c5a-43d1-97a0-c0f54cd6ac91.png)

I am using a virtual machine just for Ios...

![image](https://user-images.githubusercontent.com/16550103/136616489-2c7429e0-e255-4c33-b3f1-a83529bec5cf.png)

better_player: ^0.0.61
![image](https://user-images.githubusercontent.com/16550103/136616789-7afceeae-a18b-4686-b805-6e0743b673fe.png)

**Comment by maiquitome** [comment]
Thank you very much :)

**Comment by abdullah432** [comment]
Videos image was showing for me but it suddenly stop showing from yesterday. I'm storing all videos at aws. I run the example code and it is also not working on iOS Simulator
