### ISSUE TITLE
[BUG] The entire page is blured when the video is being played

### ISSUE THREAD

**Issue by arbile26** [jhomlala/betterplayer#750]
**Describe the bug**
The entire page is blured when the video is being played. In the contrary, when the video is being played the controllers of videos loses its blur effect. Everything is ok in version `0.0.66` but when I update to the latest version the problem occurs.

**Expected behavior**
NO blur when the videos is being played & the controllers can have blured background.

**Better Player version**
- Version: 0.0.76

**Smartphone**
 - Device: iPhone 12
 - OS: iOS 15

**Comment by jhomlala** [comment]
Please provide minimal reproducible example.

**Comment by jhomlala** [comment]
@arbile26 You have failed to provide reproducible example.
