### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by falconictech** [jhomlala/betterplayer#751]
**Describe the bug**
Find this Bug while testing the latest version v0.0.76

Because every version of flutter_test from sdk depends on meta 1.3.0 and bestvideoplayer depends on meta ^1.7.0, flutter_test from sdk is forbidden.
So, because bestvideoplayer depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because bestvideoplayer depends on flutter_test any from sdk, version solving failed.

**Better Player version**
- Version: 0.0.76

**Comment by mtAlves** [comment]
Try upgrade your Flutter:
```flutter upgrade```

**Comment by falconictech** [comment]
Thanks
