### ISSUE TITLE
[BUG] iOS Seek bar position revert to original after moving it backwards

### ISSUE THREAD

**Issue by mlph-vbarcinal** [jhomlala/betterplayer#755]
**Describe the bug**
Thank you for fixing this [issue](https://github.com/jhomlala/betterplayer/issues/694) before but I noticed something.

I used your example code to test. In the [hls_tacks_page.dart](https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/hls_tracks_page.dart), I changed the `URL` of `BetterPlayerDataSource` to [Constants.phantomVideoUrl](https://github.com/jhomlala/betterplayer/blob/d8fb72275c68feb69d8f2907865eeac5a98b68d7/example/lib/constants.dart#L25) and when I move the seek bar position backward, the seek bar position will stay from the original position for about a second I think then moved to the desired position. I attached a screen recording played on my iPhone 12 device. Start at 0:05 of the video.

**Expected behavior**
After I moved the seek bar position backwards, it must stay there.

**Screenshots**

https://user-images.githubusercontent.com/60649880/137269227-fa4b5c42-77b4-4186-9a9e-167f24c7d1a6.mov

**Flutter doctor**

> [✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale en-PH)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2020.3)
> [✓] Connected device (2 available)

**Better Player version**
- Version: 0.0.76

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.0.2

**Comment by jhomlala** [comment]
Fixed in 0.0.77.
