### ISSUE TITLE
[BUG] auto play not working on onHorizontalDragEnd

### ISSUE THREAD

**Issue by mlph-vbarcinal** [jhomlala/betterplayer#756]
**Describe the bug**
I used your example code to test. In the [hls_tacks_page.dart](https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/hls_tracks_page.dart), I changed the `URL` of `BetterPlayerDataSource` to [Constants.phantomVideoUrl](https://github.com/jhomlala/betterplayer/blob/d8fb72275c68feb69d8f2907865eeac5a98b68d7/example/lib/constants.dart#L25) and when I move the seek bar while playing, autoplay not working and it just paused. I attached a screen recording played on my iPhone 12 device.

**Expected behavior**
After I moved the seek bar position while the video is playing, it must play.

**Screenshots**

https://user-images.githubusercontent.com/60649880/137273357-95e1f828-af83-4ca2-9ca0-b53ef20414a2.mp4

**Flutter doctor**

> [✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale en-PH)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2020.3)
> [✓] Connected device (2 available)

**Better Player version**
- Version: 0.0.76

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.0.2

**Comment by jhomlala** [comment]
Fixed in 0.0.77.
