### ISSUE TITLE
[FEATURE] Change the position of the button on the entire screen

### ISSUE THREAD

**Issue by donghakIpixel** [jhomlala/betterplayer#757]
This module is really useful and well used for me.
The module version I use is as follows.

flutter : 2.5.2
video_player: ^2.2.5
chewie: ^1.2.2
better_player : 0.0.76

Currently, IOS is testing the video player, and what I want is to change the position of the toggle button on the entire screen.

I would like to change the full screen button located at the top left to the bottom right of the player. If it doesn't work at the bottom right, it's okay to go to the top right.

The current ui is different from the video players I've experienced so far, so I think it will come out heterogeneous to other users. Is there a way to change it?

![ios](https://user-images.githubusercontent.com/86765016/137296952-beae1f7b-12c8-4e9f-a8fd-a105ea0bc311.png)

**Comment by arbile26** [comment]
I guess there is no such option to change it to like you want but you still have the ability to build your custom controller just as I did.

**Comment by jhomlala** [comment]
@donghakIpixel Just create custom controls: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/custom_controls
