### ISSUE TITLE
[BUG] Strange behavior in PIP mode

### ISSUE THREAD

**Issue by kkoken** [jhomlala/betterplayer#758]
**History check**
I checked the issues but I haven't caught it.

**Describe the bug**
In the app, we have changed player logic for better usage. The Player (provider & view) starts to run & stays in the background, and the home page is the first displayed screen in the app (both start to run in parallel).

After the app route is changed to the player route necessary stuff is initialized (controller etc..). Then picture in picture mode enabled externally. As can be seen in the screenshot,  `This video is playing in the picture in picture mode` become visible on top of the other screen. How can this behavior solve?

```
  void setPictureInPicture() async {
    if (await controller!.isPictureInPictureSupported()) {
      await controller!.enablePictureInPicture(betterPlayerKey);
      await controller!.play();
      RouteManager.instance.pop();
    } else {
      //TODO: picture & picture is not supported
    }
  }
```

**To Reproduce**

**Expected behavior**
`This video is playing in the picture in picture mode` picture should not be visible.

**Screenshots**
![IMG_39C927C2695E-1](https://user-images.githubusercontent.com/87978754/137328357-26156dd0-9b18-449e-bd69-69223801241e.jpeg)

**Flutter doctor**
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5 20G71 darwin-x64, locale en-TR)
    • Flutter version 2.5.1 at /Users/kaantahakoken/fvm/versions/2.5.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kaantahakoken/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/kaantahakoken/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • iPhone’u (mobile)       • 00008030-001439DE0A87802E • ios            • iOS 14.5 18E199
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 94.0.4606.81

**Better Player version**
- Version: 0.076

**Smartphone (please complete the following information):**
 - Device: Iphone 11
 - OS: 14.5

**Comment by jhomlala** [comment]
You have failed to provide reproducible example. Closing issue.
