### ISSUE TITLE
[BUG] [iOS] Video blink during Hero page transition

### ISSUE THREAD

**Issue by jonasroussel** [jhomlala/betterplayer#764]
**Describe the bug**
Hello, I recently replaced `video_player` by `better_player` inside a  social app after having a lot of trouble with it. Everything works perfectly fine, but with one exception: on iOS when the player is transitioning between two pages with a Hero widget, the video blink during one frame. You have a video that show the bug bellow.

**To Reproduce**
1. Create a controller with network source
2. Use the controller with a BetterPlayer inside a CustomScrollView
3. Tap on the video will open a new page `Navigator.push...` with the same BetterPlayer with an Hero widget
4. Bug: Video blink during transition

**Example code**
This is how I create the controller
```dart
controller = BetterPlayerController(
  BetterPlayerConfiguration(
    autoDispose: false,
    autoPlay: false,
    controlsConfiguration: BetterPlayerControlsConfiguration(showControls: false),
    fit: BoxFit.cover,
    looping: true,
    aspectRatio: attachment.width / attachment.height,
    placeholder: _placeholder(),
    playerVisibilityChangedBehavior: _onVisibilityChanged,
  ),
  betterPlayerDataSource: BetterPlayerDataSource.network(attachment.url!),
);

...

Widget _placeholder() {
    return Stack(
    children: [
      Positioned.fill(
        child: PImage(
          path: attachment.thumbnail.url,
          attachment: attachment.thumbnail,
        ),
      ),
      Positioned.fill(
        child: Center(
          child: PLoader(size: 50),
        ),
      ),
    ],
  );
}
```

This is how I implement the player
```dart
Hero(
  tag: widget.tag,
  child: AspectRatio(
    aspectRatio: widget.aspectRatio,
    child: BetterPlayer(controller: controller.controller),
  ),
)
```

**Video**
This video show what happen:
https://pikomit-dev.fra1.digitaloceanspaces.com/test/IMG_1297.MP4

**Flutter doctor**
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.0.1 20B50 darwin-x64, locale fr-FR)
    • Flutter version 2.5.2 at /Users/jroussel/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jroussel/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

**Better Player version**
- Version: 0.0.76

**Smartphone (please complete the following information):**
 - Device: iPhone 11, iPhone 6
 - OS: iOS 14.4, iOS 12.5.4

**Comment by jhomlala** [comment]
@jonasroussel During my tests I have disabled placeholder and the blink still occurs.

**Comment by jonasroussel** [comment]
Ok, thanks for your search. Can it be fixed ?

**Comment by jhomlala** [comment]
I don't see any solution for that issue right now.
