### ISSUE TITLE
[FEATURE] Support for buffering (partial response) video streams for iOS

### ISSUE THREAD

**Issue by ErrorCode-404** [jhomlala/betterplayer#765]
Currently we are using this plugin to stream MP4 videos (about 5 minutes) from our server. There we have a service which provides the videos via urls (with video-extension). In the response we set the 206 (Partial Content) code and set the Accept-Ranges, Content-Length and Content-Type header.

So our goal is to stream the videos and to use buffering because the videos can be larger in future.
So therefore we know that support for buffering on android works very well. But on iOS its seems that there is no buffering at all or is there something we didn't see?
If the server responses with a partial response iOS results in an error while its working fine on android.

the following error appears on ios:

Error Domain=CoreMediaErrorDomain Code=-12939 "content range mismatch - should be start 0 length 10546620 is start 0 length 999999"

the total content length of the video (10546620) is requested but server responses with a partial response which seems to be not handled by ios.

Plugin version: 0.0.77
Flutter version: 2.5.2

So if there is no support for buffering and partial requests/responses could that be implemented?

**Comment by jhomlala** [comment]
Seems like AVPlayer which is used underhood can't play your data source. This is not something that can be fixed on Better Player. I think the only way to solve this issue is to change your data source or server hosting.

Here's some more info: https://stackoverflow.com/questions/47454359/ios-not-playing-some-videos-coremediaerrordomain-code-12939?noredirect=1#comment81864268_47454359

**Comment by jhomlala** [comment]
Seems like issue has been solved. Closing this issue for now. Feel free to answer and I'll reopen it.

**Comment by anup-geeky** [comment]
> Okay we could solve the problem. We implemented our service so that it returned always a fixed chunk size which works on android and even a web browser. But on iOS it didnt' work. We think that the native player on iOS sends it own range header which could have led to the content range mismatch between the chunk size of the player and the service.
> 
> We removed the chunk size on the server side and now it works.

Can you please share your code.
