### ISSUE TITLE
[BUG] Fullscreen on ios and android

### ISSUE THREAD

**Issue by VanTy207** [jhomlala/betterplayer#766]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.
<img width="1081" alt="Screen Shot 2021-10-19 at 10 44 52" src="https://user-images.githubusercontent.com/35839235/137840788-53904e39-c3f6-43bd-8889-66d2d6937548.png">
<img width="1102" alt="Screen Shot 2021-10-19 at 10 48 12" src="https://user-images.githubusercontent.com/35839235/137840803-f9390895-25b1-47f8-a8ca-41f66fe90bec.png">
<img width="1099" alt="Screen Shot 2021-10-19 at 10 48 32" src="https://user-images.githubusercontent.com/35839235/137840806-84c03ad4-c00b-48e4-b13f-5480f3903e4a.png">
<img width="1099" alt="Screen Shot 2021-10-19 at 10 48 48" src="https://user-images.githubusercontent.com/35839235/137840809-fffbf273-3163-4efc-b13b-350239e820c7.png">

**Describe the bug**
When click fullscreen for item of BetterPlayerListVideoPlayerController.

**Flutter doctor**
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (3 available)

**Better Player version**
- Version: 0.7.7

**Smartphone (please complete the following information):**
 - Device: Iphone 11, Samsung S10
 - OS: IOS 15, Android 11

**Comment by jhomlala** [comment]
@VanTy207 This example doesn't work. It shows white screen with "Video" text and that's all. Please provide working example.

![image](https://user-images.githubusercontent.com/1329033/140624238-821384d5-3e3c-471b-8a71-e796bc4844ec.png)

**Comment by VanTy207** [comment]
Oh, sorry
Please, check again sample code.

Thank you.
