### ISSUE TITLE
[BUG] Not working with flutter version 2.2.3

### ISSUE THREAD

**Issue by lucasdidur** [jhomlala/betterplayer#767]
Because every version of flutter_test from sdk depends on meta 1.3.0 and better_player >=0.0.74 depends on meta ^1.7.0, flutter_test from sdk is incompatible with better_player >=0.0.74.

So, because vre depends on both better_player 0.0.77 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because vre depends on both better_player 0.0.77 and flutter_test any from sdk, version solving failed.)
exit code 1

**Comment by jhomlala** [comment]
Please read what you have pasted and just update your `meta` library.
