### ISSUE TITLE
fullScreenByDefault not working

### ISSUE THREAD

**Issue by KalaiMalarD** [jhomlala/betterplayer#77]
Hii

I need to open the video in fullscreen mode by default. I have given "fullScreenByDefault : true" in BetterPlayerConfiguration but I get only the portrait mode first  and then the landscape mode. Can you please help solving this.

**Comment by MhtSuthar** [comment]
You can do it by `@override
  void initState() {
    super.initState();

    ///default landscape
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeRight,
      DeviceOrientation.landscapeLeft,
    ]);
  }`

and after screen dispose you can portrait screen ` @override
  void dispose() {
    _betterPlayerController.dispose();
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeRight,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    super.dispose();
  }`

**Comment by KalaiMalarD** [comment]
There was a lag in making the video fullscreen. How to get rid of this.

**Comment by jhomlala** [comment]
The reason why it's no showing full screen by default is false value in `autoPlay`. What you need to do is simply put these 2 values together as true:
```
fullScreenByDefault: true,
autoPlay: true,
```

**Comment by MhtSuthar** [comment]
Yes but I want to show only in landscape mode no need to show the first portrait and than landscape
