### ISSUE TITLE
[FEATURE] Trigger the controlsVisible and controlsHidden events before the animation

### ISSUE THREAD

**Issue by nmradako** [jhomlala/betterplayer#774]
**Is your feature request related to a problem? Please describe.**
I'm having a problem with the `controlsVisible` and `controlsHidden` events triggering at the wrong time. In BetterPlayerMaterialControls and BetterPlayerCupertinoControls an AnimatedOpacity widget is used to transition from visible and hidden, but this only triggers the `_onPlayerHide` method using the `onEnd` parameter. We have widgets that need to be hidden/shown at the same time as these default controls.

**Describe the solution you'd like**
Possibly moving the `_onPlayerHide` method to be called when `_hideStuff` is changed.
This would send the `controlsVisible` and `controlsHidden` events at the same time of the animation.

**Describe alternatives you've considered**
An alternative is just passing a zero duration to `controlsHideTime` in the `BetterPlayerControlsConfiguration`. This is not optimal since there would be no animation.

**Comment by jhomlala** [comment]
This feature will be included in next PR which comes with this branch: https://github.com/jhomlala/betterplayer/tree/feature/november_2021_changes

**Comment by jhomlala** [comment]
Fixed in 0.0.78.
