### ISSUE TITLE
[BUG] CustomControlsBuilder is missing onControlsVisibilityChanged

### ISSUE THREAD

**Issue by 515445681** [jhomlala/betterplayer#775]
**Describe the bug**

I found that onControlsVisibilityChanged cannot be received when creating a custom control layer, but it exists in BetterPlayerMaterialControls and BetterPlayerCupertinoControls. I see that BetterPlayerSubtitlesDrawer uses playerVisibilityStreamController.stream. If the custom control layer does not callback, is there a problem with it.

**To Reproduce**
1. better_player_with_controls.dart  
2.  _buildMaterialControl()  or  _buildMaterialControl().  onControlsVisibilityChanged exists
3. controlsConfiguration.customControlsBuilder!(betterPlayerController)  Not delivered  playerVisibilityStreamController

**Better Player version**
- Version: 0.0.77

**Comment by jhomlala** [comment]
This will be included in next PR which comes with this branch: https://github.com/jhomlala/betterplayer/tree/feature/november_2021_changes

**Comment by jhomlala** [comment]
Fixed in 0.0.78.
