### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nemanja02** [jhomlala/betterplayer#777]
Subtitles that are encoded in hls video are not appearing in the captions menu.
VLC player can normally play and read subtitles from the same video.

Flutter code:
`
betterPlayerController.setupDataSource(BetterPlayerDataSource(
  BetterPlayerDataSourceType.network,
  params[1], // video url
  useAsmsSubtitles: true,
  useAsmsTracks: true,
  useAsmsAudioTracks: true,
));
`

Flutter doctor -v: https://pastebin.com/BJeyd24T

**Comment by jhomlala** [comment]
@Nemanja02 Please provide video that's having issues.

**Comment by jhomlala** [comment]
No answer from author. Closing issue.
