### ISSUE TITLE
Keep playing video on screen lock

### ISSUE THREAD

**Issue by prasmalla** [jhomlala/betterplayer#78]
Hi, I need to keep the media playing when user locks the screen.
not getting expected behavior on changing this config
```BetterPlayerConfiguration(
          allowedScreenSleep: false
```

**Comment by jhomlala** [comment]
@prasmalla Currently better player doesn't support playing once user locks the screen. `allowedScreenSleep` parameter is used to prevent from screen sleep, so in your case you shouldn't expect described behavior. I can't define timeframes when this feature will be implemented.

**Comment by nateshmbhat** [comment]
There's an issue with allowedScreenSleep param in better player. have fixed it here in this release : 
https://github.com/nateshmbhat/awesome_video_player/issues/16
