### ISSUE TITLE
[BUG] Large video (more than 2 hours) has loading time too long, very slow to start that video

### ISSUE THREAD

**Issue by NhaPCS** [jhomlala/betterplayer#780]
**History check**
I loaded this link [Better Mood](https://r11---sn-8qj-i5ozd.googlevideo.com/videoplayback?expire=1635497596&ei=HGJ7YY2dA-6Z1d8P35aT6As&ip=14.162.205.169&id=o-AC2zMHhqaiiQbk6tOUw1WXxPSh0GULQ9XdmZlVtRa1Lh&itag=22&source=youtube&requiressl=yes&mh=tC&mm=31%2C29&mn=sn-8qj-i5ozd%2Csn-8qj-i5o6d&ms=au%2Crdu&mv=m&mvi=11&pl=23&initcwndbps=1720000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=18855.973&lmt=1635077579462751&mt=1635475727&fvip=1&fexp=24001373%2C24007246&c=ANDROID_EMBEDDED_PLAYER&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgfZOLkHt2d3XpdKYbk623j1gopTau1SPtbIaa6IWcG9ACIQDx6WsdntvW-vxxpbVydWaIrLgeW4wpDmcVnm4dXppAcA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgStWu_8QjN95SNqd8q5-ltdgpWyaozBHYOg0P02yZDxECIQDHf5v3s6QSX1JLnncP5pcn28vmp9qKIFfd99wR2ss-DQ%3D%3D) on Youtube [(Youtube link)](https://www.youtube.com/watch?v=4KVIFNJ7mDQ&t=9s)

but it takes very long time to start the video

**Describe the bug**
Can you please check that link? or every video that has duration more than 2 hours. Because I checked other player, it still can load it fast, also on chrome.

**Flutter doctor**
`[✓] Flutter (Channel stable, 2.5.2, on macOS 11.3.1 20E241 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
`

**Better Player version**
- Version: 0.0.77

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: 14.7.1

**Comment by jhomlala** [comment]
@NhaPCS Your url doesn't work. Probably you're trying to play one large file instead using HLS streaming. Please fix your link or I'll close this issue.

**Comment by NhaPCS** [comment]
@jhomlala https://r11---sn-8qj-i5ozd.googlevideo.com/videoplayback?expire=1635867650&ei=ogeBYdSPN5Tj4AKWsb-wBg&ip=14.162.205.169&id=o-AC2vQ27_N3gSh7AancAXjwbDZSq1hyc9Ut0Oye9eA2QG&itag=22&source=youtube&requiressl=yes&mh=tC&mm=31%2C29&mn=sn-8qj-i5ozd%2Csn-8qj-i5o6d&ms=au%2Crdu&mv=m&mvi=11&pl=23&initcwndbps=1641250&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=18855.973&lmt=1635077579462751&mt=1635845576&fvip=1&fexp=24001373%2C24007246&c=ANDROID_EMBEDDED_PLAYER&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMzm_5d_I0ObR-AIrunQU2uW95e50p-sc0B98cq4r_ksAiEArQaeUv6OBnGBnd38gIWz6a0IZfByTi1n73n8jojE88Y%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAI5J8DQCnetTiANtw_EtsCSdWc6absB2XItjxD22LnaDAiEAw5-IR9qTWp2lLK1hQt5bt4yVVjDTT6mmZe5gNLByRqE%3D

here you are!

**Comment by jhomlala** [comment]
@NhaPCS Again, resource behind this link is not available for me. I'm receiving 403 error. Please provide video which won't expire in a few days.

**Comment by itssidhere** [comment]
I suggest the author of this issue to give a code to get the link of the YouTube video using YouTube explode dart plugin as I am facing same issue very slow loading time and keeps buffering

**Comment by itssidhere** [comment]
This is a YouTube throttling issue, please refer to this https://github.com/Tyrrrz/YoutubeExplode/issues/599#issue-1035765454

**Comment by jhomlala** [comment]
This is something that can't be fixed on BP side.
