### ISSUE TITLE
[BUG] [IOS] when video is playing, if I move the app to background, video always is frozen for 2 seconds then continue play

### ISSUE THREAD

**Issue by NhaPCS** [jhomlala/betterplayer#781]
**History check**
I am playing a video, it plays normally, but if I move the app to background, it always get frozen for 2 seconds

**Describe the bug**
It only happens on IOS, Android works fine

**To Reproduce**
1. Play a video on IOS
2. Move app to background
3. See error

**Expected behavior**
It should be playing normally without any stucking

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.3.1 20E241 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (3 available)

```

**Better Player version**
- Version: 0.0.77

**Smartphone (please complete the following information):**
 - Device: IPhoneX
 - OS: 14.7.1

**Comment by jhomlala** [comment]
@NhaPCS Can you record video where you"ll present this issue?

**Comment by jhomlala** [comment]
No answer from author. Closing issue.

**Comment by vocsygautam** [comment]
[ADD]   betterplayer addListener into didChangeAppLifecycleState when app is paused
