### ISSUE TITLE
While Live Streaming Error appears too early I want to change the time it wait for source to connect 

### ISSUE THREAD

**Issue by sheribaloch** [jhomlala/betterplayer#782]
Hi, First of all thank you very much for such a great and easy to use package. Issue i am facing is that when a source is disconnected Error or Retry appears to early and I want it to wait for a bit more time to reconnect. Please help in this.

**Comment by jhomlala** [comment]
@sheribaloch Please create issue with issue template. This description is totally unreadable and I don't understand it at all. Please create new ticket with properly documented problem.
