### ISSUE TITLE
[FEATURE] Send play event on video restart

### ISSUE THREAD

**Issue by ngallazzi** [jhomlala/betterplayer#789]
**Is your feature request related to a problem? Please describe.**
The BetterPlayerEventType.play is not triggered when a video restarts (autoplay: true)

**Describe the solution you'd like**
Provide a new "OnVideoRestart" event

**Comment by jhomlala** [comment]
This is not possible. Repeat mode (looping) is being handled by native players which doesn't provide end state when looping finishes. I believe the only way to solve this issue is to listen to progress events from BP and detect when video has been restarted.
