### ISSUE TITLE
Best strategy to implement a video feed screen

### ISSUE THREAD

**Issue by aytunch** [jhomlala/betterplayer#79]
Just like TikTok, I want to implement a video feed screen with infinite scrolling. The List Item widgets will be `BetterPlayer`s and the data sources will be taken from Firebase. A user can see 100's of videos but I want to limit the number of `BetterPlayerController`s to just 4 or 5 controllers. This way is better for memory management right?
If a user does not see the player/controller anymore, I want to change(set a new) `BetterPlayerDataSource` to that specific controller but I did not see any API to reset a Data Source. (except of the private `setupDataSource`?)
Do we have to create a new Controller for every new Data source? 
And how do we dispose the unwanted controller and release the unused video memory along with it?

One last question: How to know if a video is ready or prepared? I don't see any `await`s in the documentation. How will we know if video is initialized or ready? Is there a way to listen for when the video is prepared and ready to be played?

Thanks.

**Comment by jhomlala** [comment]
@aytunch 

```Just like TikTok, I want to implement a video feed screen with infinite scrolling. The List Item widgets will be BetterPlayers and the data sources will be taken from Firebase. A user can see 100's of videos but I want to limit the number of BetterPlayerControllers to just 4 or 5 controllers. This way is better for memory management right?```

You can try using BetterPlayerListVideoPlayer which should work within lists. But there may be issues if you want to play too much videos - see this issue:  https://github.com/jhomlala/betterplayer/issues/27. Your idea to use 4/5 controllers and re-use them if video is not anymore visible seems to be valid. You can try it and share your results here.

```If a user does not see the player/controller anymore, I want to change(set a new) BetterPlayerDataSource to that specific controller but I did not see any API to reset a Data Source. (except of the private setupDataSource?)```

There's controllerInstance.setupDataSource(newDataSource) to setup new data source in given controller.

```Do we have to create a new Controller for every new Data source?```
No, you can use setupDataSource for new data source.

```And how do we dispose the unwanted controller and release the unused video memory along with it?```
controllerInstance.dispose()

```One last question: How to know if a video is ready or prepared? I don't see any awaits in the documentation. How will we know if video is initialized or ready? Is there a way to listen for when the video is prepared and ready to be played?```

  controllerInstance.videoPlayerController.addListener(() {
      if (_betterPlayerController.videoPlayerController.value.initialized){
        print("Video is ready to play!");
      }
    });

**Comment by jhomlala** [comment]
Better Player is fork of both video_player and chewie combined into one plugin. Anyway cache support may be introduced into Better Player, but i can't assure timeframes when it will be done. Just keep looking at next versions of Better Player.

**Comment by jhomlala** [comment]
Cache topic will be continued here: https://github.com/jhomlala/betterplayer/issues/74. If you encounter any issue, please open another issue.

**Comment by marc-walton** [comment]
> @jhomlala Hi:)
> Thanks for the clear answers, I will try to implement that strategy and hopefully get a stable solution.
> 
> A little off-topic question:
> The official VideoPlayer plugin will receive [Video Cache support](https://github.com/flutter/plugins/pull/2429) any day now.
> It is basically caching the video file which is being watched/streamed so that we don't need to download it over and over again.
> 
> This package is an upgrade to Chewie which is a wrapper for VideoPlayer right?
> So will BetterPlayer have this functionality too?

Hi can you please help me with an example code im creating a page just like yours but i have no idea to begin with

**Comment by Abacaxi-Nelson** [comment]
@aytunch 
Would be great to share your final version. Reusing controller is a bit tricky specially when preloading mutiple video...
