### ISSUE TITLE
[BUG] Cannot compile with versions after 0.0.77

### ISSUE THREAD

**Issue by itssidhere** [jhomlala/betterplayer#797]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**
Whenever  I try to compile  a simple app with better_player version greater than 0.0.77 I get two errors

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\better_player-0.0.79\android\build.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':better_player'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':better_player'.
> compileSdkVersion is not specified. Please add it to build.gradle
```

**To Reproduce**
Simply compiling with better player 0.0.78 or 0.0.79 as a dependency

**Expected behavior**
It should compile like 0.0.77

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.7.0-3.1.pre, on Microsoft Windows [Version 10.0.22000.282], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (3 available)

```
• No issues found!

**Better Player version**
- Version: ^0.0.78

**Comment by jhomlala** [comment]
@itssidhere 
Please do following steps:
1. Update your kotlin version to `1.5.31`.
2. Enable multidex in your app.

**Comment by itssidhere** [comment]
Ok thanks @jhomlala I will do the changes although two of it 2nd and 3rd point you mentioned are already there but i use java instead of kotlin so maybe that's causing the issue?

**Comment by jhomlala** [comment]
https://github.com/react-native-webview/react-native-webview/issues/1407 You need to add kotlin to your project.

**Comment by itssidhere** [comment]
> [react-native-webview/react-native-webview#1407 (comment)](https://github.com/react-native-webview/react-native-webview/issues/1407#issuecomment-634436481) You need to add kotlin to your project.

Thanks Sir, It alone fixed those issues
