### ISSUE TITLE
Play encrypted hls in BetterPlayer

### ISSUE THREAD

**Issue by jpolstre** [jhomlala/betterplayer#799]
I wonder if it is possible to implement this functionality, as in this post: `https://github.com/google/ExoPlayer/issues/5362`

**Comment by jhomlala** [comment]
Yes, it's possible, but seems like you're the only one that need that feature. I think you should check available DRM methods here: https://jhomlala.github.io/betterplayer/#/drmconfiguration and try to use one of them. 

If you really need new DRM method, feel free to fork BP, and modify native android code which contains DRM configuration for ExoPlayer.
