### ISSUE TITLE
How to add dynamic rightPadding to subtitles? (To show them on the left side of the screen)

### ISSUE THREAD

**Issue by alurei97** [jhomlala/betterplayer#80]
Hi, first of all, thanks for this great plugin.

I'm trying to show subtitles only on the left side of the screen, so I thought "add padding of the screen width / 2 and that's all" so I tried to add it to the example code from this repo (everything was working perfectly before adding this):
```
_betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(
          fit: BoxFit.contain,
          controlsConfiguration: BetterPlayerControlsConfiguration(
            enableProgressText: true,
            enablePlaybackSpeed: true,
            enableSubtitles: true,
          ),
          subtitlesConfiguration: BetterPlayerSubtitlesConfiguration(
            rightPadding: MediaQuery.of(context).size.width/2, 
          ),
        ),
        betterPlayerDataSource: dataSource);
```

At first, when my phone is vertical it works perfectly, but when I
· rotate the phone or
· go to fullscreen and exit fullscreen
I get a weird behavior: sound keeps playing but the player resets to 0:00 and the video gets reloaded (if I play the new one, I hear both of them). I think it's because the context and screen size changes so the player reloads with the new screen size.

I also tried putting a fixed size like:
`rightPadding: 500,`
which works well in fullscreen and doesn't reset the player but when my phone is vertical, subtitles are like:
```
 ________________
|     PLAYER     |
|                |
| S______________|
  U
  B
  S
```
overflowing player's size and showing one character per line because there's no space.

Any idea in how to fix this?

**Comment by jhomlala** [comment]
@alurei97 
Please upgrade to flutter 0.0.28.
You can use now `alignment` property in BetterPlayerSubtitlesConfiguration to align your subitiles within row.
You shouldn't use MediaQuery.of(context) when building better player controller because it will lead to recreating better player and issue presented above.

**Comment by alurei97** [comment]
```
subtitlesConfiguration: BetterPlayerSubtitlesConfiguration(
    fontSize: 20,
    alignment: Alignment(-1.0, 1.0),
    leftPadding: 40,
    bottomPadding: 40,
),
```

Works as I wanted, thanks!
