### ISSUE TITLE
compile time error on flutter 2.5.3

### ISSUE THREAD

**Issue by uc-dve** [jhomlala/betterplayer#801]
**Describe the bug**
I have upgraded flutter 2.2.3 to 2.2.5 and better_player is not supporting and is unable to build the app now on android and ios both.

**Screenshots**
Ios screenshot

![image](https://user-images.githubusercontent.com/28289763/141119441-e9e6ec7e-919d-4771-bace-12aad73a3cd4.png)

android screenshot

![image](https://user-images.githubusercontent.com/28289763/141116720-2e081034-ee69-4edd-bf45-65dc98c5446c.png)

**Flutter doctor**
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.62.0)
[✓] Connected device (4 available)

• No issues found!

**Better Player version**
- Version: 0.0.79

**Smartphone (please complete the following information):**
 - Device: redmi 6 pro
 - OS: android 9

**Additional context**

**Comment by itssidhere** [comment]
Update your kotlin version to **1.5.31**

in android/build.grade

buildscript {
    ext {
        ...
        kotlinVersion = "1.5.31"
    }
    dependencies {
        ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

**Comment by uc-dve** [comment]
> Update your kotlin version to **1.5.31**
> 
> in android/build.grade
> 
> ```
> buildscript {
>     ext {
>         ...
>         kotlinVersion = "1.5.31"
>     }
>     dependencies {
>         ...
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
>     }
> }
> ```

Thank you so much it is working fine now
for iOS there was caching issue I just run the following command and build successfully
`flutter clean && \
rm ios/Podfile ios/Podfile.lock pubspec.lock && \
rm -rf ios/Pods ios/Runner.xcworkspace && \
flutter run`
