### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by trulykasodiya-hub** [jhomlala/betterplayer#804]
Better Player will come in a web supported version ?

**Comment by rpksharma** [comment]
Is it have brightness adjust option?

**Comment by rpksharma** [comment]
plz provide this option

**Comment by kevin4dhd** [comment]
+1

**Comment by jhomlala** [comment]
This question has been answered at least few times. The answer is no at this moment. Please use search option and you will find these issues in this repo.
