### ISSUE TITLE
[BUG] Video is stopped for 2 seconds when move app to background

### ISSUE THREAD

**Issue by NhaPCS** [jhomlala/betterplayer#813]
**History check**
I am playing a video, it plays normally, but if I move the app to background, it always get frozen for 2 seconds

**Describe the bug**
It only happens on IOS, Android works fine

**To Reproduce**
1. Play a video on IOS
2. Move app to background
3. See error
Please refer to the video recording [Video of issue](https://drive.google.com/file/d/1By4buWn7lsadPWPhpmZ222Olby3F9vfi/view?usp=sharing)

**Expected behavior**
It should be playing normally without any stucking

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.3.1 20E241 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (3 available)

```

**Better Player version**
- Version: 0.0.77

**Smartphone (please complete the following information):**
 - Device: IPhoneX
 - OS: 14.7.1

**Comment by jhomlala** [comment]
Probably you need to check `handleLifecycle` parameter which is used to play/pause on application pause/resume. Playing video after pause can take some time if app is going back from background.

**Comment by vocsygautam** [comment]
[ADD] betterplayer addListener into didChangeAppLifecycleState when app is paused
