### ISSUE TITLE
[BUG] - SplashColor of Fullscreen Button not symmetrical

### ISSUE THREAD

**Issue by MatheusHenriq** [jhomlala/betterplayer#815]
**History check**
I try to found the resolution for this, but i didn't find anything

**Describe the bug**
When i tap in fullscreen button, the splashcolor goes to far to the rightside, and it is not symmetrical

**To Reproduce**
1. click on fullscreen button and see the splashcolor

**Expected behavior**
I want a way to make it symmetrical

**Screenshots**
![symmetrical](https://user-images.githubusercontent.com/51083627/142410820-c54e7714-d700-4564-b761-3db0755139fa.png)

**Flutter doctor**
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [versÃ£o 10.0.19043.1348], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code (version 1.62.2)
[√] Connected device (3 available)

• No issues found!

**Better Player version**
- Version: 0.0.73

**Smartphone (please complete the following information):**
 - Device: sdk gphone x86 arm

**Comment by jhomlala** [comment]
This will be fixed in next version.

**Comment by jhomlala** [comment]
Fixed in 0.0.81.
