### ISSUE TITLE
[BUG] Cannot play after setting setupDataSource

### ISSUE THREAD

**Issue by thedoubler** [jhomlala/betterplayer#818]
**Describe the bug**
Have better player with playlist configured.
loopVideos: false
autoPlay: false

Let's say there are 3 videos and the handler which take care of playing the next video.
After all videos played  I set: 
```
  _betterPlayerPlaylistStateKey
                    .currentState.betterPlayerPlaylistController
                    .setupDataSource(0);

```
After this, I'm calling play() method.
The video is not longer playing.

Am I missing something?

**Better Player version**
- Version:  0.0.72

**Smartphone:**
Android Emulator

**Comment by jhomlala** [comment]
Please provide working reproducible code and steps. I've tried to do same scenario as you but there's no error. Can you provide logs?
