### ISSUE TITLE
Feature Request: Support for custom parameters in options menu

### ISSUE THREAD

**Issue by Sirabein** [jhomlala/betterplayer#82]
Hi, your plugin is very convenient, but there's one thing that would make it even better

It'd be great if you could override title of the parameters to make localization, or add new ones so that they where part of the player.
 I know there's _customControls_ parameter in _BetterPlayerControlsConfiguration_, but in this situation you have to remake all the controls, while you just need to, for example, change a few text fields.

Please tell me if this might be a feature in future updates or/and is it even possible.

**Comment by jhomlala** [comment]
@Sirabein 
Please upgrade to BetterPlayer 0.0.27 and use:
```overflowMenuCustomItems``` in BetterPlayerControlsConfiguration to setup new menu items for options menu
```translations``` in BetterPlayerConfiguration to setup translations for existing elements
