### ISSUE TITLE
[BUG]The plugin fails to play videos after playing successfully 10-15 times. Playback error

### ISSUE THREAD

**Issue by MabroukAmal** [jhomlala/betterplayer#820]
![image_2021_11_23T15_30_48_550Z](https://user-images.githubusercontent.com/88428957/143056953-245129ab-a5c1-465c-b641-6174df449c72.png)

**Comment by ALLY-MAFTAH** [comment]
I'm facing the same issue

**Comment by jhomlala** [comment]
This is typical ExoPlayer behavior. You should reuse same BetterPlayerController as long as possible. This will prevent issue like that. I guess the best option will be some kind of players pool (for example 3) which can be reused in different parts of your app.

**Comment by sabriboughanmi** [comment]
This bug is reproduced in BetterPlayer examples such as 'Video in list'.
Steps to reproduce it:
* set videos count to 30 for dataList in Video in list.
* make a fast scroll.
all players will show the Video can't be played screen.
tested on Samsung S10.
