### ISSUE TITLE
[FEATURE] Dynamically Update the fit of the video

### ISSUE THREAD

**Issue by rsbthebest** [jhomlala/betterplayer#821]
**Is your feature request related to a problem? Please describe.**
Right now we have the ability to set the fit of the video in the configuration. Is there any way to set it up dynamically? Ability to change it on the go so the user can decide if he wants the video to be streached, fit height or fit width

**Describe the solution you'd like**
Ability to set the Box Fit

**Comment by kevin4dhd** [comment]
Any solution?

**Comment by jhomlala** [comment]
0.0.81 introduces `setOverridenFit` method which solves this issue.
