### ISSUE TITLE
[BUG] PlayBack Error

### ISSUE THREAD

**Issue by rafay-tariq** [jhomlala/betterplayer#822]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32284465/143404308-2cafb6c8-058c-461d-9a0b-09832d82e6d6.png)

**To Reproduce**
1. First stop the video 
2. then click on "three dot" button on top right side. 
3. click on playback screen or just stay there for 3-5 seconds
4. you will see this error. 

**------------- LOGS ----------- **

E/ExoPlayerImplInternal(20523): Playback error
E/ExoPlayerImplInternal(20523):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.640028, 446911, null, [1920, 1080, -1.0], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
E/ExoPlayerImplInternal(20523):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(20523):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(20523):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(20523):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
E/ExoPlayerImplInternal(20523):       ... 3 more
E/ExoPlayerImplInternal(20523):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(20523):       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
E/ExoPlayerImplInternal(20523):       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:98)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1199)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)
E/ExoPlayerImplInternal(20523):       ... 5 more
E/ExoPlayerImplInternal(20523): Disable failed.
E/ExoPlayerImplInternal(20523):   java.lang.IllegalStateException
E/ExoPlayerImplInternal(20523):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(20523):       at android.media.MediaCodec.flush(MediaCodec.java:2298)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:165)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:895)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:888)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:741)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:483)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:178)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1635)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1377)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1340)
E/ExoPlayerImplInternal(20523):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:574)
E/ExoPlayerImplInternal(20523):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(20523):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(20523):       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by MabroukAmal** [comment]
I have the same issue here

**Comment by SalahAdDin** [comment]
I have the same issue when i have multiple videos or widget who use `exo_player` to reproduce media, like `just_player`.

**Comment by ahammamlho** [comment]
I have the same issue

**Comment by jhomlala** [comment]
Please provide minimal reproducible example.
