### ISSUE TITLE
Upgrade flutter_widget_from_html dependency

### ISSUE THREAD

**Issue by murilots** [jhomlala/betterplayer#824]
**Is your feature request related to a problem? Please describe.**
Yes,  can't build my app because of version mismatch.

**Describe the solution you'd like**
Upgrade flutter_widget_from_html to 0.8...

**Comment by gabrielginter** [comment]
Although not critical, would be great to upgrade the dependencies.

@murilots in the meantime just downgrade to 0.7.0

thanks for all the great work guys!

**Comment by jhomlala** [comment]
This will be fixed with next release.
