### ISSUE TITLE
Change Video Quality in the Middle of the Video [FEATURE]

### ISSUE THREAD

**Issue by MalshanPerera** [jhomlala/betterplayer#826]
**Is your feature request related to a problem? Please describe.**
A issue I've faced with this plugin is that it only supports play at one resolution at a time and can only change resolutions manually

**Describe the solution you'd like**
A preferred solution would be to be able to automatically change the video according to the network connectivity or maybe even make it possible to change the resolution in the code itself

**Comment by jhomlala** [comment]
@MalshanPerera This is something that you should maintain within your app. I think it shouldn't be hard. You can use for example this plugin: https://pub.dev/packages/internet_speed_test do detect speed of the internet and then change resolution based on that.
