### ISSUE TITLE
Can we have better player for web? [FEATURE]

### ISSUE THREAD

**Issue by bhanu-under25** [jhomlala/betterplayer#828]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arslee07** [comment]
Yeah, we can use [Shaka ayer](https://github.com/google/shaka-player), which covers all our cases

**Comment by jhomlala** [comment]
This question has been answered at least few times. The answer is no at this moment. Please use search option and you will find these issues in this repo.
