### ISSUE TITLE
Rotate full screen custom direction on full screen button pressed

### ISSUE THREAD

**Issue by budo385** [jhomlala/betterplayer#829]
Upon pressing the full screen button and entering the full screen mode, the player rotation is counter clockwise.

Could it be possible to add a parameter to customise the initial rotation upon going to full screen. 
So that we can choose what initial orientation of the full screen mode.

Could not find any parameter for it and saw that _postControllerEvent(BetterPlayerControllerEvent event) is called...

**Comment by Ankit0080** [comment]
@jhomlala I am having the same issue. In Ios devices when we click on the full screen button then the video player direction is just opposite to the normal direction we have in usual. The player moves to counter clock wise

**Comment by Ankit0080** [comment]
@budo385 You can try with this, this should be helpful

if (event.betterPlayerEventType == BetterPlayerEventType.openFullscreen) {
        Helper.showToast("msg");
        BetterPlayerConfiguration(
          deviceOrientationsOnFullScreen: [DeviceOrientation.landscapeLeft],
        );
      }

**Comment by budo385** [comment]
@Ankit0080 
can you please give me a full example, not quite sure how this should work. 
Should I change the controller configuration on rotate?

**Comment by Ankit0080** [comment]
@budo385 It is not working in my case too.

**Comment by Ankit0080** [comment]
@budo385  this worked

deviceOrientationsAfterFullScreen: [DeviceOrientation.portraitUp],
          deviceOrientationsOnFullScreen: [DeviceOrientation.landscapeRight],

**Comment by jhomlala** [comment]
Seems like issue has been solved. I'm closing this issue.
