### ISSUE TITLE
Disposing controller in a confusing way

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [jhomlala/betterplayer#83]
Hi,

I have only one video (not a playlist) and I want to play it only. and when it's done, the code throws exception stating that the controller is used after being disposed.

I've checked the code, and I found in [this line](https://github.com/jhomlala/betterplayer/blob/31a284e231ca60e3d40c1f9e99ad0b4ed7de77ea/lib/src/core/better_player.dart#L79) that:

```

  @override
  void dispose() {
    widget.controller.removeListener(onFullScreenChanged);

    ///Controller from list widget must be dismissed manually
    if (widget.controller.betterPlayerPlaylistConfiguration == null) {
      widget.controller.dispose();
    }

    super.dispose();
  }
```

so you dispose the controller if betterPlayerPlaylistConfiguration is null, and I don't need to configure it. 

Am I doing it wrong?

**Comment by jhomlala** [comment]
Can you show your code? Maybe you're using controller once it's disposed?

**Comment by AhmedNourJamalElDin** [comment]
Hello,
When I add a value for `betterPlayerPlaylistConfiguration`, it works fine.
this is my initalization of the controller.
```
    controller = BetterPlayerController(
      BetterPlayerConfiguration(),
      betterPlayerDataSource: BetterPlayerDataSource(
        BetterPlayerDataSourceType.FILE,
        filePath,
      ),
    );
```
and the new initialization which works fine:
```
 controller = BetterPlayerController(
      BetterPlayerConfiguration(),
      betterPlayerPlaylistConfiguration: BetterPlayerPlaylistConfiguration(),
      betterPlayerDataSource: BetterPlayerDataSource(
        BetterPlayerDataSourceType.FILE,
        filePath,
      ),
    );
```

**Comment by jhomlala** [comment]
I'm trying to reproduce your issue, but on my side it working fine.

Here is an example:
```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

class OtherPage extends StatefulWidget {
  @override
  _OtherPageState createState() => _OtherPageState();
}

class _OtherPageState extends State<OtherPage> {
  BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    super.initState();
  }

  Future _initData() async {
    final directory = await getApplicationDocumentsDirectory();
    _betterPlayerController = BetterPlayerController(
      BetterPlayerConfiguration(),
      betterPlayerDataSource: BetterPlayerDataSource(
        BetterPlayerDataSourceType.FILE,
        "${directory.path}/testvideo.mp4",
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Other page"),
      ),
      body: FutureBuilder(
        future: _initData(),
        builder: (context, data) {
          if (_betterPlayerController == null) {
            return Text("Loading...");
          }
          return AspectRatio(
            aspectRatio: 16 / 9,
            child: BetterPlayer(controller: _betterPlayerController),
          );
        },
      ),
    );
  }

  @override
  void dispose() {
    _betterPlayerController.dispose();
    super.dispose();
  }
}
```

Can you provide your example which throws error?
Also do you dispose controller manually? If yes, please remove it, controller will be disposed automatically (if you're not using playlist).

**Comment by AhmedNourJamalElDin** [comment]
Well, my code is a bit different. I use the same controller in two widgets i.e. two BetterPlayer widgets with only and only one controller instance.
Why so?
I want to display thumbnail and when it's clicked, I would like to play the video.

I've just added playlist default config and it works but in my PoV it's a bug becasue the controller is disposed if playlist config is null whereas I don't want to use playlists.

I think I can close this one.
