### ISSUE TITLE
[BUG] error flutter 2.5.3

### ISSUE THREAD

**Issue by kadan-dev** [jhomlala/betterplayer#830]
Launching lib\main.dart on SM N975F in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-runtime-ktx:2.4.0-beta01.
        AAR metadata file: C:\Users\kadan\.gradle\caches\transforms-2\files-2.1\737dca0a286f2a86590637184e008a5d\jetified-lifecycle-runtime-ktx-2.4.0-beta01\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.work:work-runtime:2.7.0.
        AAR metadata file: C:\Users\kadan\.gradle\caches\transforms-2\files-2.1\6ca6bfbb6ed79157a08fdd6548cc9e4d\work-runtime-2.7.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-runtime:2.4.0-beta01.
        AAR metadata file: C:\Users\kadan\.gradle\caches\transforms-2\files-2.1\d076dcb8b618192c464d1aa108e37b0e\lifecycle-runtime-2.4.0-beta01\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by muccurly** [comment]
@kadan-dev  did u find a solution?

**Comment by Letalus** [comment]
@muccurly was the workaround working for you?

**Comment by muccurly** [comment]
> @muccurly was the workaround working for you?

yeah I just changed `compileSdkVersion 30 to 31,` and `ext.kotlin_version = '1.3.50'` to `ext.kotlin_version = '1.5.31'`

**Comment by jhomlala** [comment]
As mentioned above please update compile SDK version to 31 and kotlin version to 1.5.31.
