### ISSUE TITLE
Can we have better_player for Desktop(Windows, Linux, macOS)?[FEATURE]

### ISSUE THREAD

**Issue by bhushanudupa** [jhomlala/betterplayer#835]
**Hello developers,**
Can we work on developing the desktop version of the [better_player](https://pub.dev/packages/better_player) so that one can rely on only one player for all the platforms.
Thanks and regards,
Bhushan Udupa

**Comment by vikram25897** [comment]
There is no PlatformView support for flutter desktop yet so it can't be done AFAIK.

**Comment by arslee07** [comment]
> There is no PlatformView support for flutter desktop yet so it can't be done AFAIK.

Yes.

However, PlatformView is supported on Flutter Web, but BetterPlayer depends on its own plugins, which were made for Android, iOS, but not the Web.

Of course, we can use the video_player package supported by the Flutter team, but we will lose such an important part of the functionality as, for example, DRM support. 🙁

**Comment by bhushanudupa** [comment]
@arslee07 @vikram25897  Just thought of asking. Can we create our own PlatformView and implement the same for Desktop(Probably Windows OS to start with)?
Please share your thoughts on the same.
Thank you, 
[`Happy Coding`](https://flutter.dev/multi-platform/desktop)

**Comment by arslee07** [comment]
Desktop platforms don't support PlatformView AFAIK

**Comment by jhomlala** [comment]
This question has been answered at least few times. The answer is no at this moment.
