### ISSUE TITLE
How can we add our subtitles to example? Because it doesn't read my .srt file

### ISSUE THREAD

**Issue by Fazyl03** [jhomlala/betterplayer#836]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Fazyl03** [comment]
I have added my .srt file inside assets/ file and set the link of this file inside constants.dart. But it shows this /data/user/0/com.jhomlala.better_player_example/app_flutter/example.srt doesn't exist!. How can I set its link right?

**Comment by jhomlala** [comment]
Assets data source is not supported. You need to store your file from assets directory to files directory. Here's how to do that: https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/welcome_page.dart
