### ISSUE TITLE
Option to remove menu button

### ISSUE THREAD

**Issue by litzbalane2017** [jhomlala/betterplayer#84]
Good Day.

Great plugin. However, it seems I cannot remove the vertical menu button, since  I am not using any of subtitle, playspeed or quality in my app. 

I hope we can add this in the future. 

Thank you.

**Comment by jhomlala** [comment]
@litzbalane2017 
Please upgrade to BetterPlayer 0.0.27 and use enableOverflowMenu parameter in BetterPlayerControlsConfiguration.
