### ISSUE TITLE
[FEATURE] Add Cookies protected

### ISSUE THREAD

**Issue by travisfimmel743** [jhomlala/betterplayer#842]
hello team, i have a question if there option add cookies to header request for license drm widevin , because there are many video protect by cookies header request

**Comment by Letalus** [comment]
sorry, I'm not 100% if I understand your question correctly. Could you please elaborate on your question?

**Comment by jhomlala** [comment]
This should solve your issue: https://github.com/jhomlala/betterplayer/issues/639
