### ISSUE TITLE
[BUG] flutter_local_notifications: ^9.1.5  incompatible

### ISSUE THREAD

**Issue by zhangKunUserGit** [jhomlala/betterplayer#843]
error img
<img width="485" alt="截屏2021-12-15 下午6 00 39" src="https://user-images.githubusercontent.com/13297317/146165495-a41b5ebe-033e-4d35-8382-75b2771e71ce.png">

better_player.framework/better_player normal (in target 'better_player' from project 'Pods'

**Comment by Letalus** [comment]
could you please elaborate a little bit, what exactly your error is?

**Comment by jhomlala** [comment]
I don't understand what's your issue. Please format your issue with issue template and provide reproducible example.
