### ISSUE TITLE
[BUG] cant change overflowModalColor color by switch theme

### ISSUE THREAD

**Issue by vrman** [jhomlala/betterplayer#846]
i want to change color of modal by theme changes dark/light mode , i cant set it in initial state because when theme change it cant update it at runtime,

im also tried to set configuration in widget tree , to get access theme changes , but its not working again and after switching theme mode, video player rebuilt again and i get this error message and color not change too. :

> setState() or markNeedsBuild() called when widget tree was locked.

> A VideoPlayerController was used after being disposed.

**Comment by jhomlala** [comment]
Fixed in 0.0.81. You can change controls configuration in runtime.
