### ISSUE TITLE
Ability to change aspect ratio

### ISSUE THREAD

**Issue by bharatmk256** [jhomlala/betterplayer#847]
Being able to change aspect ratio while watching video
- we can change aspect ratio of the video before watching but if we can change aspect ratio of video by pinch or by tapping on button so it takes whole width and height of screen

**Comment by forgedIron** [comment]
Bump

**Comment by ibhanu** [comment]
Please Bump

**Comment by jhomlala** [comment]
Please use `setOverridenAspectRatio` from `BetterPlayerController` to change aspect ratio during runtime.

**Comment by ibhanu** [comment]
@jhomlala how can we detect gesture when the video player is full screen?

I can work when the video player is not full screen, but while it full screen it does not detect scale gesture.
