### ISSUE TITLE
version 0.0.73 cant play DASH youtube links on iOS

### ISSUE THREAD

**Issue by tdujmic** [jhomlala/betterplayer#849]
BetterPlayerConfiguration betterPlayerConfiguration =
    BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      fit: BoxFit.contain,
    );

    BetterPlayerDataSource dataSource =  BetterPlayerDataSource(
        BetterPlayerDataSourceType.network, posts[0].streamingUrl,
        videoFormat:  posts[0].streamingUrl.contains('manifest.googlevideo') == true ? BetterPlayerVideoFormat.dash : BetterPlayerVideoFormat.hls
    );
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    await _betterPlayerController.setupDataSource(dataSource);

posts[0].sttreamingUrl represents youtube mpd file url in DASH format

this code works on Android, but on iOS returns error in debug window:

flutter: Exception on parseSubtitles: SignalException: Input does not start with the #EXTM3U header.
flutter: Exception on parseSubtitles: SignalException: Input does not start with the #EXTM3U header.
flutter: Exception on hls parse: SignalException: Input does not start with the #EXTM3U header.
Failed to load video:
Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped, NSUnderlyingError=0x2805e97d0 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}}
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)

It looks like in iOS it doesnt recon mpd and it tries to opent as hls, even if i set format to dash it doesnt work,

This one is really urgent for me so please can you look into. Im using this in my live app.

Thank you !

**Comment by tdujmic** [comment]
one example url, it expires but I can provide more or url whn you can read new url at any time:

https://manifest.googlevideo.com/api/manifest/dash/expire/1639792225/ei/Aeq8Yf7HEJ2J6dsPtdyRsAM/ip/3.123.183.87/id/a69061b363362f15/source/youtube/requiressl/yes/playback_host/rr1---sn-4g5e6nsk.googlevideo.com/mh/dQ/mm/31%2C26/mn/sn-4g5e6nsk%2Csn-5hnedn7z/ms/au%2Conr/mv/u/mvi/1/pl/20/tx/24044258/txs/24044258%2C24044259%2C24044260%2C24044261/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/mt/1639769739/fvip/6/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhANS7BD1yTJ5Buxgh3xftOQ-dv1Oi53ZyT_N4ToBhMWOXAiAiqnxP7PISWHFyiSPBm62HH2SlnYSPXGmMFECW0op7kg%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl/lsig/AG3C_xAwRAIgLeE4vNXYHmcf7KcfYdtoIDck00dk3uYmwweaFUuxUtYCIBHV8TqJDfmaGVk2KzcSOThFrH4-9-5vtsSKji-8_Rjs

**Comment by jhomlala** [comment]
Can you please check latest BP version (0.0.79)? Also based on provided logs I guess it's because invalid format of your stream. Can you double check if you can play this video with other players (for example web players)?
