### ISSUE TITLE
[BUG] Video playback Issue on IOS devices

### ISSUE THREAD

**Issue by Demoxing** [jhomlala/betterplayer#852]
I am facing an issue with the video playback on IOS devices. It is not working correctly, sometimes no video (only sound), sometimes not able to play at all, but everything is smooth in the same android version! No issues at all. Any idea how to fix it?

https://user-images.githubusercontent.com/53024273/147451248-4ec8e23d-d9a1-48aa-863e-c90bbc3b99c6.mp4

**Flutter doctor**

> ❯ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel unknown, 2.5.3, on macOS 11.6.2 20G314 darwin-arm, locale
>     en-IN)
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2020.3)
> [✓] VS Code (version 1.63.2)
> [✓] Connected device (1 available)
> 
> • No issues found!

**Better Player version**
- Version: 0.0.79

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS15.2

**Comment by jhomlala** [comment]
Sometimes video can't be played on iOS simulator. Please use real device to test Better Player.
