### ISSUE TITLE
[BUG] Manual dispose not working when you set autoDispose to false

### ISSUE THREAD

**Issue by vrman** [jhomlala/betterplayer#863]
i have a video controller which has autodispose false inside configuration , i used that because i have a long page and player is on top of the page , and after i scroll down video stop playing . 

so i tried to do dispose manualy , but when i leaving the page , videocontroller dispose not calling in page dispose, and video still playing when i go to other app pages.

im sure there is a bug in there

**Comment by GabrielDamasceno** [comment]
When `autoDispose: false` try using `_betterPlayerController.dispose(forceDispose: true);`
