### ISSUE TITLE
[BUG]I want all apps to be vertical, and only video pages can be switched horizontally and vertically

### ISSUE THREAD

**Issue by devyueyue** [jhomlala/betterplayer#865]
The app is set with a fixed vertical screen. After startup, the page will not follow the gravity sensing of the mobile phone to rotate the horizontal and vertical screen, but on the video playback page, the user manually clicks the button to rotate it into a horizontal screen and then rotate it into a vertical screen. After that, all pages will automatically rotate the horizontal and vertical screen following the gravity sensing of the mobile phone. How can I disable the gravity sensing of the mobile phone to automatically rotate the horizontal and vertical screen?

flutter sdk: 2.8.1
better_player: ^0.0.81

**Comment by jhomlala** [comment]
Just set correct `deviceOrientationsAfterFullScreen` value in `BetterPlayerConfiguration`. https://jhomlala.github.io/betterplayer/#/generalconfiguration
