### ISSUE TITLE
[BUG]Horizontal and vertical screen switching

### ISSUE THREAD

**Issue by devyueyue** [jhomlala/betterplayer#869]
await OrientationHelper.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);
  await OrientationHelper.forceOrientation(DeviceOrientation.portraitUp);

Set the app fixed vertical screen. After clicking the rotate horizontal and vertical screen on the video page and exiting the full screen, all pages will follow the gravity sensing of the mobile phone to rotate the horizontal and vertical screen continuously. How do you set this?

flutter sdk: 2.8.1
better_player: ^0.0.81

**Comment by jhomlala** [comment]
Do not change preferred orientation when video is playing in the full screen.
