### ISSUE TITLE
Get Video Quality List

### ISSUE THREAD

**Issue by MhtSuthar** [jhomlala/betterplayer#87]
Hi, thanks for providing this kind of work really appreciated.
But I want to know that programmatically how can I get the quality list like 360p, 480p, and 720p for streaming video URL(.m3u8) files. 
I have a controller object in global.

**Comment by jhomlala** [comment]
@MhtSuthar 
You can use:
```betterPlayerControllerInstance.betterPlayerTracks;``` to access available hls tracks (qualities)
```betterPlayerControllerInstance.betterPlayerTrack``` to access currently used hls track (quality). Please remember it will be null until you choose any track (quality).

I believe it will solve your issue, so I'll close it.

**Comment by MhtSuthar** [comment]
Yes, thanks, I ll check it, Can you please tell me how can I change more icon options?

**Comment by Jazzykhan** [comment]
hi, can we change the quality of playing manually?

**Comment by MhtSuthar** [comment]
Yes you can change but in using this dependency not possible you need to add that module in your project
