### ISSUE TITLE
how to make the BetterPlayer widget appear on the whole screen, adapting the controls in portrait mode

### ISSUE THREAD

**Issue by kevin4dhd** [jhomlala/betterplayer#876]
**Is your feature request related to a problem? Please describe.**
I am making an app to play videos, and the BetterPlayer library is the best in customization, but now I find this problem, I want the video screen to remain the same but the widget to be fullscreen, so that the title and buttons are position at the top and bottom taking advantage of the entire screen in portrait mode

**Describe the solution you'd like**
I don't know how the solution would be, but I show you in text how it looks in another application, this is what I want to achieve
![69d7cca2-738c-41af-b09c-da2657961611](https://user-images.githubusercontent.com/22886367/148847170-a79247f6-9f1a-4f87-8ffe-c1a62faf44c0.jpg)
If it is fixed, the video although it is for horizontal screen, the title and the buttons remain on the top and bottom of the device, while with betterplayer they are seen inside the video

**Describe alternatives you've considered**
The other alternative is from flutter to put all this manually, but I think it would really be difficult and complete the communication between widgets

**Additional context**
This is how it looks with better player
![image](https://user-images.githubusercontent.com/22886367/148846416-98ba5a0f-0239-4811-b4f3-20e50509bd44.png)

**Comment by shiyiya** [comment]
see example `Overridden aspect ratio`.

**Comment by kevin4dhd** [comment]
I have achieved it by activating this option in better player configuration "expandToFill: false" and putting the player in an expanded

The result:
![image](https://user-images.githubusercontent.com/22886367/149271279-1ac19014-06b1-4304-9870-e2698a7b032d.png)
I personally like

**Comment by rafgl** [comment]
Good morning, I was trying to put the title and the return there in the icons in the player, how do you put it?
