### ISSUE TITLE
[BUG] Video in list fails to load even in BetterPlayer example

### ISSUE THREAD

**Issue by sabriboughanmi** [jhomlala/betterplayer#879]
im getting a bug "Black screen with Video can't be played" while trying the BetterPlayr Video in List,  is reproduced in BetterPlayer examples such as 'Video in list'.

Steps to reproduce it:

set videos count to 30 for dataList in Video in list.
make a fast scroll.
all players will show the Video can't be played screen.
tested on Samsung S10

https://user-images.githubusercontent.com/32723106/148972893-bbeb1eb5-48b1-4d88-8ede-042d42d4c92e.mp4

**Comment by itsdani121** [comment]
where did you get this code i try to found this code but did not.

**Comment by sabriboughanmi** [comment]
> where did you get this code i try to found this code but did not.
Clone the example and check Video in List part.

**Comment by inc16sec** [comment]
Have you tried with reusable video list?.. They might look the same, but with reusable list you don't create a controller for each video, instead, you create a bunch of controllers that are reused for all videos, this helps with performance and a faster initialization of the video.

**Comment by itsdani121** [comment]
Basically i wants to play video like tiktok where 5-8 videos initialize in
it when i go to next video then video is already buffer and just play video
Ao that's the main reason

**Comment by inc16sec** [comment]
> 

Then try reusable video list.

https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list

**Comment by itsdani121** [comment]
Is it possible to buffer video in advance which not shows in screen

**Comment by inc16sec** [comment]
> 

That's the whole point of reusable (list) controllers. You'll find the controllers ready the moment the (video) widget shows up on your screen, it won't be loading, it was already loaded.

**Comment by itsdani121** [comment]
I want to show full screen portrait mode video like riktok but the issue is
length of video ia just half of screen and not go more than about it ao
what can i do thatvvideo will go full screen

**Comment by inc16sec** [comment]
> 

First of all make sure that the video widget takes the whole screen and then set the aspect ratio of the video widget to be the same as the video. 
```dart
controller!.setOverriddenAspectRatio(
  videoWidth / videoLength,
);
```
I recommen that you go to youtube and watch how to create a tiktok replica.. as for the list use a pageView

**Comment by itsdani121** [comment]
Thanks, I'll check it out.

**Comment by nhat108** [comment]
> > 
> 
> That's the whole point of reusable (list) controllers. You'll find the controllers ready the moment the (video) widget shows up on your screen, it won't be loading, it was already loaded.

Hi @inc16sec, i facing the problem when use "reusable list video", it's not preload next video, how I solve it?

**Comment by nhat108** [comment]
Hi @itsdani121 , can you share your code, I also building an app like TikTok, now facing the problem performance when playing video, it's too slow and does not reload next video!

**Comment by inc16sec** [comment]
> > > 
> > 
> > 
> > That's the whole point of reusable (list) controllers. You'll find the controllers ready the moment the (video) widget shows up on your screen, it won't be loading, it was already loaded.
> 
> Hi @inc16sec, i facing the problem when use "reusable list video", it's not preload next video, how I solve it?

Use a reusable controller like the one in this example and pass it to your items in the list.

https://github.com/jhomlala/betterplayer/blob/master/example/lib/pages/reusable_video_list/reusable_video_list_controller.dart

**Comment by sabriboughanmi** [comment]
By setting handleLifecycle to false, the controller's visibility callback is no longer executed, which is something we require to manage the behavior of the list.

**Comment by rikai-trongpq** [comment]
@inc16sec I tried example of better_player but it's not working (Black screen)
![image](https://user-images.githubusercontent.com/83201151/154921046-fc54674a-8962-4ed3-a3d8-418a937ccf20.png)

**Comment by inc16sec** [comment]
> @inc16sec I tried example of better_player but it's not working (Black screen) ![image](https://user-images.githubusercontent.com/83201151/154921046-fc54674a-8962-4ed3-a3d8-418a937ccf20.png)

Could you provide a piece of your code, especially the videoplayer widget code. Also what version of better player are you using?

**Comment by rikai-trongpq** [comment]
@inc16sec  I was using version `0.0.8.1`. I'm running on the `better_player` instance and without any modifications.

**Comment by inc16sec** [comment]
> @inc16sec I was using version `0.0.8.1`. I'm running on the `better_player` instance and without any modifications.

Give me an excerpt of the VideoPlayer widget that you are using and the video Player controller code.

**Comment by jhomlala** [comment]
Please use reusable video list which was mentioned above.
