### ISSUE TITLE
[FEATURE]upgrade depandences ExoPlayer to 2.16.0

### ISSUE THREAD

**Issue by LeiQiao** [jhomlala/betterplayer#882]
current version using ExoPlayer 2.15.1, its unable to play mp4 file which is recorded by Weixin, cause of ExoPlayer throw an "ArrayIndexOutOfBoundsException" error.

the new version of ExoPlayer 2.16.0 has fixed it:

ExoPlayer 2.16.0 :
MP4: Avoid throwing ArrayIndexOutOfBoundsException when parsing invalid colr boxes produced by some device cameras (#9332).

**Comment by shiyiya** [comment]
- https://github.com/jhomlala/betterplayer/issues/702
- 1. upgrade exoPlayerVersion 2.16.1
- 2. replace SimpleExoPlayer to ExoPlayer `android/src/main/.../BetterPlayer.kt`

**Comment by devyueyue** [comment]
Hi, did you have this problem?
--------------------------------------------------------------------------------
await OrientationHelper.setPreferredOrientations([
DeviceOrientation.portraitUp,
]);
await OrientationHelper.forceOrientation(DeviceOrientation.portraitUp);

Set the app fixed vertical screen. After clicking the rotate horizontal and vertical screen on the video page and exiting the full screen, all pages will follow the gravity sensing of the mobile phone to rotate the horizontal and vertical screen continuously. How do you set this?

flutter sdk: 2.8.1
better_player: ^0.0.81

**Comment by shiyiya** [comment]
set option afterflullscreen

**Comment by bdlukaa** [comment]
A bunch of issues were fixed on the newest versions: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md

This would be highly appreacited!

**Comment by shiyiya** [comment]
u can try .
- https://github.com/shiyiya/betterplayer/tree/upgrade-exo-2.16.1

**Comment by LeiQiao** [comment]
> u can try . **only android**
> 
> * https://github.com/shiyiya/betterplayer/tree/upgrade-exo-2.16.1

u guys are awesome!!! totally works!! thx~

ps:
I have to add the following code to build.gradle of your project, otherwise AS will reports error

kotlinOptions {
    jvmTarget = '1.8'
}

**Comment by shiyiya** [comment]
@bdlukaa Note that the ios related code has not been updated and it will not work on ios.
