### ISSUE TITLE
[FEATURE] Play audio only and hide video control

### ISSUE THREAD

**Issue by elmawardy** [jhomlala/betterplayer#890]
**Is your feature request related to a problem? Please describe.**
We want to play DRM audio only. the problem is we don't find an option to hide the video from the component.

**Describe the solution you'd like**
It would be good to have an option to hide the video control and allow the audio only to be played.

**Comment by jhomlala** [comment]
https://jhomlala.github.io/betterplayer/#/enabledisablecontrols
