### ISSUE TITLE
Web support 

### ISSUE THREAD

**Issue by Yoda-Man** [jhomlala/betterplayer#891]
Chewie works on web but I see that your package does not have web support.

**Comment by jhomlala** [comment]
This question has been answered so many times, so I don't even bother to add duplicate link here. Please use search.

**Comment by Yoda-Man** [comment]
Thanks for taking the time to answer my question 4 months later. By pointing me to where I can find the answer. I absolutely love your work.

**Comment by jhomlala** [comment]
Thanks 👍  I searched it for you, so you don't need to wait next 4 months: https://github.com/jhomlala/betterplayer/issues/142

**Comment by Yoda-Man** [comment]
I was going to wait for a year even 2 doing nothing just waiting for an answer.
