### ISSUE TITLE
[BUG] m3u8 video can't be played on iOS

### ISSUE THREAD

**Issue by weebsproject** [jhomlala/betterplayer#909]
Hello.

Im using better player latest version,
and try to play a live stream video from m3u8 format,
on android work charmingly but not on ios

on ios I got message :

`Failed to load video:
Error Domain=NSURLErrorDomain Code=-1102 "You do not have permission to access the requested resource." UserInfo={NSLocalizedDescription=You do not have permission to access the requested resource., NSUnderlyingError=0x2839347e0 {Error Domain=CoreMediaErrorDomain Code=-12660 "The operation couldn’t be completed. (CoreMediaErrorDomain error -12660 - HTTP 403: Forbidden)" UserInfo={NSDescription=The operation couldn’t be completed. (CoreMediaErrorDomain error -12660 - HTTP 403: Forbidden)}}}`

is there anything to do?

**Comment by 04pd** [comment]
it's seems like your video link is broken,mine is working well in both platform

**Comment by jhomlala** [comment]
@weebsproject Please read your logs. Everything is there.

**Comment by Tiagocf2** [comment]
Hi, i'm getting the same error only in iOS
I have an URL in a UTF-8 encoding like so: `https://samplewebsite.com/url-with-symbõls-here.m3u8` 
And it doesn't work, even encoded as URI, it works fine on Android though. 

I noted that only URLs with symbols like `Ç Ã Â À Á` or so doesn't work, while URLs with only standard letters works fine
