### ISSUE TITLE
Update Wakelock Dependency to 0.6.1+1 [FEATURE]

### ISSUE THREAD

**Issue by julienandco** [jhomlala/betterplayer#923]
The current version of betterplayer is not compatible with chewie >= 1.3.0 unfortunately. 

But: the issue can easily be solved by upgrading betterplayer's wakelock dependency. Wakelock did not introduce breaking changes, so everything should work out fine!

cheers!

**Comment by gabrielginter** [comment]
2 packages I'm using can't be updated because of this as well.

thanks

**Comment by jhomlala** [comment]
Fixed in latest release (0.0.82).
