### ISSUE TITLE
Unable to view custom icons over player

### ISSUE THREAD

**Issue by MhtSuthar** [jhomlala/betterplayer#93]
I want to add two buttons over video when player control visible or hide so I have created a stack widget and implement it but it's working smoothly in portrait mode but when the screen rotate and full screen then my custom button is not visible.
Can you please help me how can I achieve this plz check the below code ->

```
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
        child: Scaffold(
          body: Stack(
            children: [
              Center(
                child: BetterPlayer(
                  controller: _betterPlayerController,
                ),
              ),
              _getCenterNextButton() // My Custom button which hide show
            ],
          ),
        ),
        onWillPop: onWillPopS);
  }
```

**Comment by jhomlala** [comment]
@MhtSuthar Just released new version (0.0.29) which allows you to do this:

```
_betterPlayerController = BetterPlayerController(
      BetterPlayerConfiguration(
        routePageBuilder: (BuildContext context, Animation<double> animation,
            Animation<double> secondAnimation, provider) {
          return AnimatedBuilder(
            animation: animation,
            builder: (BuildContext context, Widget child) {
              return Scaffold(
                backgroundColor: Colors.black,
                resizeToAvoidBottomPadding: false,
                body: Stack(children: [
                  Container(
                    alignment: Alignment.center,
                    child: provider,
                  ),
                  _getCenterNextButton(),
                ]),
              );
            },
          );
        },
      ),
    );```

This should solve your issue.

**Comment by MhtSuthar** [comment]
Yes, it works thanks a lot @jhomlala , but I want to hide show that center button like player controls hide show so how can I achieve this?

**Comment by jhomlala** [comment]
Use event listener: https://github.com/jhomlala/betterplayer/blob/master/README.md#listen-to-video-events

You should check these events:
```
CONTROLS_VISIBLE,
CONTROLS_HIDDEN,
```

**Comment by MhtSuthar** [comment]
Thanks, @jhomlala for the reply but let me explain my issue

Suppose _betterPlayerController is initialised in initState() method so I define routePageBuilder for showing that buttons, I also have event listener for video controller but the issue is when I am going to change the state of the page than initState() never call so how can I show hide that button.
Sorry for my English but my view(show hide) is on routePageBuilder in initState() and if i change state than how can i notifify that button state?
