### ISSUE TITLE
[BUG] I want to skip forward and backward event but I can't get current position of player ,how to solve it ,Please!

### ISSUE THREAD

**Issue by ayezarniaung** [jhomlala/betterplayer#932]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xuala69** [comment]
_playerController.videoPlayerController!.position returns a Future<Duration>  which is the current Playing position but since it is a future, there is a small delay     _playerController.videoPlayerController!.seekTo(position) can be used to skip or rewind the playback

**Comment by ayezarniaung** [comment]
> _playerController.videoPlayerController!.position returns a Future which is the current Playing position but since it is a future, there is a small delay _playerController.videoPlayerController!.seekTo(position) can be used to skip or rewind the playback
videoPLayerController.position() or seekTo() is working on video player package and Chewie  but betterPlayerController can't get current position. So I want to get current position in betterVideoPlayerController not with videoPlayer and Chewie .

**Comment by ayezarniaung** [comment]
> _playerController.videoPlayerController!.position returns a Future which is the current Playing position but since it is a future, there is a small delay _playerController.videoPlayerController!.seekTo(position) can be used to skip or rewind the playback

**Thank You [Solved]**
