### ISSUE TITLE
How I Play vimeo Video like  url :- https://vimeo.com/682850647 in better player[BUG]

### ISSUE THREAD

**Issue by rajkamal06** [jhomlala/betterplayer#934]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sha3rawi33** [comment]
You have to provide the full URL to the video file to better player and not an absolute URL like (https://vimeo.com/682850647). 

on your Vimeo video dashboard; go to sharing -> video file links -> MP4/HLS -> copy
and use that URL as betterplayer's video source.
Tip: use HLS playback to add multiple quality functionality or use the vimeo_player flutter package to use MP4 playback with multiple quality.
