### ISSUE TITLE
[FEATURE] Support for WEBVTT Cue Settings

### ISSUE THREAD

**Issue by blueeyestw** [jhomlala/betterplayer#935]
**Is your feature request related to a problem? Please describe.**
My subtitle contents have position settings embedded inside them. But it seems the player ignores those settings and only displays the subtitles in the bottom of the screen.

**Describe the solution you'd like**
Support for full WEBVTT Cue settings as described here:
[https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#cue_settings](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#cue_settings)

**Describe alternatives you've considered**
I have tried different property values in the BetterPlayerSubtitlesConfiguration class, but the subtitles are always shown in the bottom. (There might be a bug actually, please see issue https://github.com/jhomlala/betterplayer/issues/936)

**Additional context**
Sample WEBVTT content:
```
WEBVTT

1
00:00:01.000 --> 00:00:30.000   line:0%
<c.title>Welcome</c>
<c.title>test123456 版權所有，不得轉載</c>

2
00:00:11.000 --> 00:00:21.000 line:81% position:61%  size:20%\nstudent

3
00:00:51.000 --> 00:01:01.000 line:58% position:15% size:20% line:58% position:15%  size:20%
student

4
00:01:31.000 --> 00:01:41.000 line:21% size:20%
student

5
00:02:11.000 --> 00:02:21.000 line:17% position:22%  size:20%
student

6
00:02:51.000 --> 00:03:01.000 line:92% position:35% size:20% line:92% position:35%  size:20%
student

7
00:03:31.000 --> 00:03:41.000 line:28% size:20%
student

8
00:04:11.000 --> 00:04:21.000 line:56% position:54%  size:20%
student

9
00:04:51.000 --> 00:05:01.000 line:68% position:31% size:20% line:68% position:31%  size:20%
student

10
00:05:31.000 --> 00:05:41.000 line:55% size:20%
student

11
00:06:11.000 --> 00:06:21.000 line:3% position:41%  size:20%
student

12
00:06:51.000 --> 00:07:01.000 line:56% position:35% size:20% line:56% position:35%  size:20%
student

13
00:07:31.000 --> 00:07:41.000 line:17% size:20%
student

14
00:08:11.000 --> 00:08:21.000 line:75% position:27%  size:20%
student


```

**Comment by jhomlala** [comment]
Please try using latest version (1.10.0) which improves VTT subtitles support.
