### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "better_player":

### ISSUE THREAD

**Issue by mingyouzhu** [jhomlala/betterplayer#937]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "better_player":
  In Podfile:
    better_player (from `.symlinks/plugins/better_player/ios`)

<img width="1311" alt="Screen Shot 2022-03-03 at 5 47 28 PM" src="https://user-images.githubusercontent.com/37821420/156539473-9bb71889-4c46-4589-bdc5-9bf799ad3085.png">

**Comment by Jai05-techie** [comment]
Hi,  Any solution found? 

Me too facing the same issue CocoaPods could not find compatible versions for pod "better_player".

Flutter: 2.8.1 channel stable - MacBook Air M1

**Comment by appsdeveloperhub** [comment]
I am also facing same issue for ios

**Comment by hasnainelahi** [comment]
I solved it: change it in  project/ios/Podfile.         platform :ios, '11.0'

**Comment by jhomlala** [comment]
I think this issue is already solved.
