### ISSUE TITLE
IOS无法播放

### ISSUE THREAD

**Issue by aluo44** [jhomlala/betterplayer#94]
问题描述:
`此链接: http://oss.alizyw.com:88/api/download?repository=registry.cn-hangzhou.aliyuncs.com/alizyw/www&digest=sha256:6f6e7af3fafa4a77019f7627e318a13d5248641d3781489b674e6b5652f43a83`
在安卓上可以正常播放, 但是在IOS上无法播放
返回信息: `flutter: PlatformException(VideoError, Failed to load video: Operation Stopped, null)`

其它信息:
flutter版本: 
`Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.5 19F96, locale
    zh-Hans-CN)
    • Flutter version 1.22.0 at /Users/cp/flutter/stable
    • Framework revision d408d302e2 (3 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn`

手机信息: 6s, 12.0.1

**Comment by jhomlala** [comment]
Please create issue in english.
