### ISSUE TITLE
[FEATURE] Is it possible to take video screenshot(frameshot) programmaticaly on ios?

### ISSUE THREAD

**Issue by fLySpin** [jhomlala/betterplayer#942]
Hello, guys!
Please add a method to take screenshot on ios or please give me some advice how to do this.
I'm working on solution and so far have a code that produce screenshot! :
`- (FlutterStandardTypedData*) getFrameShot {
    
    NSDictionary* settings = @{ (id)kCVPixelBufferPixelFormatTypeKey : @(kCVPixelFormatType_32BGRA) };
    self.playerOutput = [[AVPlayerItemVideoOutput alloc] initWithPixelBufferAttributes:settings];
    [self.playerItem addOutput:self.playerOutput];
    
    CVPixelBufferRef buffer = [self.playerOutput copyPixelBufferForItemTime:[self.playerItem currentTime] itemTimeForDisplay:nil];
    
    UIImage * image = [CVPixelBufferTools getUIImageFromCVPixelBuffer : buffer];
    
    NSData *data = UIImagePNGRepresentation(image);
    return [FlutterStandardTypedData typedDataWithBytes:data];
}`

and it's possible to display it 

`late Uint8List? _imageFile = null;
Image.memory(_imageFile!)
`

but  after this line 
`[self.playerItem addOutput:self.playerOutput];`
better player widget turned black and show nothing:)

My environment is the same https://github.com/jhomlala/betterplayer/issues/941
Thanks!

**Comment by jhomlala** [comment]
Screenshot creation is out of the scope of this plugin.
