### ISSUE TITLE
How to change Subtitles Configuration without having to re-initialize BetterPlayerController

### ISSUE THREAD

**Issue by donghuuquan** [jhomlala/betterplayer#950]
I am using better_player to play video and display subtitle.
On the video player screen on my application allows the user to adjust the subtitle's configuration such as font size, font color... After adjusting, I want the user to be able to see immediately how the subtitle will look.
But I cannot change BetterPlayerSubtitlesConfiguration after I have initialized BetterPlayerController.

Is there any other way I can change it without having to re-initialize BetterPlayerController?

**Comment by ameya730** [comment]
@donghuuquan Did you find a solution for this as I am facing the same issue ?
