### ISSUE TITLE
[FEATURE] A button to switch the view type

### ISSUE THREAD

**Issue by prateekmedia** [jhomlala/betterplayer#952]
**Is your feature request related to a problem? Please describe.**
Many video player has a button to switch view type to stretch crop fill etc

**Describe the solution you'd like**
Add a button in the player itself

**Describe alternatives you've considered**
An alternative is also to add pinch to fit the video to width 

**Additional context**
VLC for android does that

**Comment by jhomlala** [comment]
This is something that is out of the scope of this player.
