### ISSUE TITLE
How to run file with filepath

### ISSUE THREAD

**Issue by worldwidee** [jhomlala/betterplayer#956]
Its not working when i give filepath to url part. 
AspectRatio(
              aspectRatio: 16 / 9,
              child: BetterPlayer.file(filePath),
            )
or
AspectRatio(
              aspectRatio: 16 / 9,
              child: BetterPlayer.file(File(path).path),
            )

**Comment by jhomlala** [comment]
Just read the manual. https://jhomlala.github.io/betterplayer/#/generalplayerusage
