### ISSUE TITLE
android build: Execution failed for task ':app:checkDebugDuplicateClasses'.

### ISSUE THREAD

**Issue by mhadad** [jhomlala/betterplayer#963]
**History check**
I have checked and I could not find a solution for the issue

**Describe the bug**
When running Flutter build apk with version 0.0.81 the following error is thrown 
 > 1 exception was raised by workers:   java.lang.RuntimeException: Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime.jar (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.15.1-runtime.jar (com.google.android.exoplayer:exoplayer-ui:2.15.1)[BUG]

I tried to exclude the module and group in android's build.gradle and still it does not work.
My pubspec.yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

So how can I use better_player: 0.0.81

**Comment by VanTy207** [comment]
Me too the same issue.

**Comment by sadaqatdev** [comment]
same here any update?

**Comment by GauravCalidig** [comment]
Same here any updates

**Comment by sadaqatdev** [comment]
use lower version of video_player plugin

**Comment by mhadad** [comment]
https://stackoverflow.com/a/71664475/1561547
