### ISSUE TITLE
[BUG] Player flips when exiting pip mode

### ISSUE THREAD

**Issue by yurasakun** [jhomlala/betterplayer#966]
**History check**
didn't find anything that could solve my problem

**Describe the bug**
when exiting pip mod, the player is flipped, but this does not happen only on android version 11

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/30806775/161395671-95dad960-6837-4fd0-bb28-ab36d483823b.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: andoroid 10, 12

**Comment by Alii-isk** [comment]
i can confirm this issue i am on **android 12**
