### ISSUE TITLE
Old version of exo-player creating problem while building app.

### ISSUE THREAD

**Issue by DK070202** [jhomlala/betterplayer#968]
Hi. We are using better_player and flick_video_player in our app, while we are trying to run our project it throws error and from that we are able to understand why it is going like this. So, the better_player depends on version 2.15.1 of _exo-playe_r and depends on the 2.17.0 due to this we can not run our app.

1.  Add this two dependencies in your pubspec file.
     - _better_player_: _^0.0.81_
     - _flick_video_player_: _0.4.0-dev.4_
2. Flutter pub get.
3. Run app. 

Flutter doctor
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1526], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
[√] Android Studio (version 2020.3)
[√] VS Code, 64-bit edition (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
**Better Player version**
- Version: ^0.0.81

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android Version 11

**Comment by postacik** [comment]
I have a fork of betterplayer which uses exoplayer 2.17.1.

You can replace better_player reference in your pubspec.yaml to point to that fork and try.

```
  # better_player: ^0.0.81
  better_player: 
    git: https://github.com/postacik/betterplayer.git

```

If your specific need is 2.17.0, just fork my fork and change the following line in `android\build.gradle` and make your project point to your own fork.

```
buildscript {

    ext.exoPlayerVersion = "2.17.1" //Upgraded exoplayer to latest version 

```

**Comment by DK070202** [comment]
> I have a fork of betterplayer which uses exoplayer 2.17.1.
> 
> You can replace better_player reference in your pubspec.yaml to point to that fork and try.
> 
> ```
>   # better_player: ^0.0.81
>   better_player: 
>     git: https://github.com/postacik/betterplayer.git
> ```
> 
> If your specific need is 2.17.0, just fork my fork and change the following line in `android\build.gradle` and make your project point to your own fork.
> 
> ```
> buildscript {
> 
>     ext.exoPlayerVersion = "2.17.1" //Upgraded exoplayer to latest version 
> ```

Thank for @postacik  quick response  solution is working properly 🚀🚀.
