### ISSUE TITLE
The video is played only in the sample application.

### ISSUE THREAD

**Issue by sergeyAx7007** [jhomlala/betterplayer#970]
Hi. I want use your cool widget. The video is played only in the sample application.
I get the url of the video from the server 'http://10.0.4.79:5001/api/Videos/GetVideoStream?id=71 ', if I pass it to the sample application, it plays successfully. If I create a new application and try to reproduce it, I get an error:
 W/xample.untitle( 9202): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl( 9202): Init e9f666 [ExoPlayerLib/2.15.1] [generic_x86, Android SDK built for x86, unknown, 30]
E/ExoPlayerImplInternal( 9202): Playback error
E/ExoPlayerImplInternal( 9202):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:596)
E/ExoPlayerImplInternal( 9202):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 9202):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 9202):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 9202):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$CleartextNotPermittedException: Cleartext HTTP traffic not permitted. See https://exoplayer.dev/issues/cleartext-not-permitted
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:358)
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1014)
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
E/ExoPlayerImplInternal( 9202):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 9202):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 9202):       at java.lang.Thread.run(Thread.java:923)
E/ExoPlayerImplInternal( 9202):   Caused by: java.io.IOException: Cleartext HTTP traffic to 10.0.4.79 not permitted
E/ExoPlayerImplInternal( 9202):       at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:127)
E/ExoPlayerImplInternal( 9202):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
E/ExoPlayerImplInternal( 9202):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:629)
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:526)
E/ExoPlayerImplInternal( 9202):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:352)
E/ExoPlayerImplInternal( 9202):       ... 6 more
E/flutter ( 9202): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, , null)
E/flutter ( 9202): 

I think that the reason is in the modules android\app\src\main\kotlin\com\jhomlala\better_player_example\ from this folder, they are not created in a new project. Please help me. A very cool widget, I would like to use it

**Comment by rounce** [comment]
Cleartext HTTP traffic not permitted
If your app targets Android 9 (API level 28) or later, cleartext HTTP traffic is disabled by the default configuration.
Either add android:usesCleartextTraffic="true" to the application element of your app’s AndroidManifest.xml, or change target API.

**Comment by sergeyAx7007** [comment]
thank you, it helped
