### ISSUE TITLE
custom controls builder

### ISSUE THREAD

**Issue by AhmadFalahian** [jhomlala/betterplayer#974]
When I use customControlsBuilder  backward is no longer displayed and customControls remains on the screen as a static display
` customControlsBuilder: (BetterPlayerController controller,
          Function(bool) onPlayerVisibilityChanged) {
        return Row(
          children: const [
            Text('next'),
            Icon(Icons.arrow_forward_sharp),
          ],
        );
      })`
![WhatsApp Image 2022-04-17 at 3 21 44 PM](https://user-images.githubusercontent.com/87113603/163711320-e90ff4c8-bd61-41c5-8ed2-852bf813cb37.jpeg)

**Comment by jhomlala** [comment]
Purpose of custom controls builder is to build whole player UI just like material / cupertino theme. Everything is fine here from my perspective, you just didn't understand that it will replace whole player UI.

**Comment by SeshaiHari** [comment]
The controls displayed on screen wont hide automatically. I'm also not able to hide the controls manually. It would be better if better player provides some control to hide them.
