### ISSUE TITLE
rename modal bottom sheet item text

### ISSUE THREAD

**Issue by AhmadFalahian** [jhomlala/betterplayer#977]
I want to change the text of the items in bottom modal sheet How can I do this
![WhatsApp Image 2022-04-19 at 11 09 27 AM](https://user-images.githubusercontent.com/87113603/163941709-86b48b63-1160-4a87-8f74-14b16c6cf2f3.jpeg)

**Comment by aravind-b-dev** [comment]
my configuration

    BetterPlayerConfiguration betterPlayerConfiguration =
    BetterPlayerConfiguration(
        aspectRatio: 9/18,
        fit: BoxFit.contain,
        autoPlay: false,
        controlsConfiguration :BetterPlayerControlsConfiguration(
          showControls: true,
          enableSkips: false,
          enableFullscreen: true,
          // enableMute : false,
          // enableProgressText: false,
          // enableProgressBar :false,
          enablePip:false,
          enablePlayPause:false,
          enableOverflowMenu: false,
        )
    );

**Comment by jhomlala** [comment]
Use translations to change text in overflow menu: https://jhomlala.github.io/betterplayer/#/translationsconfiguration.
