### ISSUE TITLE
[BUG] Better Player Crashing in iOS

### ISSUE THREAD

**Issue by harmeet-rgyan** [jhomlala/betterplayer#979]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.
Yes, I have checked the issues history and did not find anything which solves my issue.

**Describe the bug**
App is crashing on iOS simulator and real device with NSInvalidArgumentException

**To Reproduce**
1. Add the Better player library to your Flutter project
2. Run the app on iOS simulator/real device
3. Play any video and you will see the black screen or only audio is going to player and after few seconds app is going to crash with NSInvalidArgumentException.

**Flutter doctor**

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
    • Flutter version 2.10.3 at /Users/harmeetsidhu/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/harmeetsidhu/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 11 (mobile)          • E1BBDD94-A3E5-46A4-82B5-D32FB8CB8D53 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Better Player version**
- Version: 0.0.81

**Smartphone (please complete the following information):**
 - Device: iPhone 11 simulator
 - OS: iOS 15.4 (19E240)

**Additional context**
Error Logs:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x10fdd0fb0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010faded44 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010de60a65 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010faedcfa +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x000000010fae32ff ___forwarding___ + 1471
	4   CoreFoundation                      0x000000010fae5488 _CF_forwarding_prep_0 + 120
	5   libswiftCore.dylib                  0x000000011032e02e $ss18_bridgeCocoaStringys01_C4GutsVyXlF + 158
	6   libswiftCore.dylib                  0x000000011032e0e2 $sSS12_cocoaStringSSyXl_tcfC + 18
	7   libswiftFoundation.dylib            0x0000000112446c7c $sSS10FoundationE36_unconditionallyBridgeFromObjectiveCySSSo8NSStringCSgFZ + 28
	8   better_player                       0x000000010ddab775 $s13better_player12CacheManagerC07stopPreC0_8cacheKey17completionHandlery10Foundation3URLV_SSSgySbcSgtFTo + 165
	9   better_player                       0x000000010dda7df6 -[BetterPlayerPlugin handleMethodCall:result:] + 9110
	10  Flutter                             0x000000011b329571 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	11  Flutter                             0x000000011adb86df _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE + 193
	12  Flutter                             0x000000011adbddf9 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE + 35
	13  Flutter                             0x000000011b1fe09b _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell29OnEngineHandlePlatformMessageENS_10unique_ptrINS5_15PlatformMessageENS_14default_deleteIS8_EEEEE4$_15EENS_9allocatorISD_EEFvvEEclEv + 81
	14  Flutter                             0x000000011b0fdef0 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 164
	15  Flutter                             0x000000011b104324 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	16  CoreFoundation                      0x000000010fa4c0fa __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	17  CoreFoundation                      0x000000010fa4bbc8 __CFRunLoopDoTimer + 915
	18  CoreFoundation                      0x000000010fa4b189 __CFRunLoopDoTimers + 265
	19  CoreFoundation                      0x000000010fa4576d __CFRunLoopRun + 2016
	20  CoreFoundation                      0x000000010fa44a90 CFRunLoopRunSpecific + 562
	21  GraphicsServices                    0x0000000113968c8e GSEventRunModal + 139
	22  UIKitCore                           0x0000000123d5990e -[UIApplication _run] + 928
	23  UIKitCore                           0x0000000123d5e569 UIApplicationMain + 101
	24  Runner                              0x0000000100c4f78f main + 63
	25  dyld                                0x000000010958cf21 start_sim + 10
	26  ???                                 0x00000002010f751e 0x0 + 8607724830
	27  ???                                 0x00000002010f2000 0x0 + 8607703040
)
libc++abi: terminating with uncaught exception of type NSException
`

**Comment by LabiadhMo** [comment]
same here

**Comment by rgyantech** [comment]
@LabiadhMo were you able to find any solution??

**Comment by harmeet-rgyan** [comment]
@LabiadhMo were you able to find any solution?

**Comment by harmeet-rgyan** [comment]
I have found the fix from a previous issue #913, so I am closing this issue.
