### ISSUE TITLE
Fullscreen is ingoring Stack

### ISSUE THREAD

**Issue by MiroLiebschner** [jhomlala/betterplayer#99]
Usecase: A Quiz-Container that pops up at certain positions in the video. Both are in a stack.  

Problem: This is working fine when the video is not full screen. When the video is fullscreen the popup will not be placed over the video. When I minimize the video the popup is shown. 

Is there anything I miss? Maybe another solution to this problem or a reason why the popup is not placed over the video when the video is in fullscreen mode?

Thanks! Miro

**Comment by mahmood-heja** [comment]
same here 

throw Exception when go full screen and return on android 10 
`A VideoPlayerController was used after being disposed.
`

**Comment by MiroLiebschner** [comment]
So my theory is that fullscreen is pushed as a page. That could be the reason the Stack isn't working. Is there a possibility to customize the Fullscreen button in a way that custom code is play?

**Comment by jhomlala** [comment]
@MiroLiebschner use custom route builder which allows you to draw over full screen player: https://github.com/jhomlala/betterplayer/issues/93#issuecomment-713106462

**Comment by jhomlala** [comment]
@mahmood-heja Please open issue with example code which can be used to reproduce this issue.

**Comment by MiroLiebschner** [comment]
@jhomlala I will try that and report back if it worked. Thank you so much!

**Comment by MiroLiebschner** [comment]
@jhomlala I will try that and report back if it worked. Thank you so much!

Edit: It is working perfectly fine. This issue can be closed. Thank you for helping :)

**Comment by MhtSuthar** [comment]
Hay @MiroLiebschner Could you please share your code coz I need to implement like this

**Comment by MiroLiebschner** [comment]
@MhtSuthar  `routePageBuilder: (BuildContext context, Animation<double> animation,
          Animation<double> secondAnimation, provider) {
        return AnimatedBuilder(
          animation: animation,
          builder: (BuildContext context, Widget child) {
            return WillPopScope(
              onWillPop: () async {
                VideoPlayerProviderNewUI videoPlayerProviderNewUI =
                    Provider.of(context, listen: false);
                if (videoPlayerProviderNewUI.getIsPopUpActive() == true) {
                  videoPlayerProviderNewUI.deactivate();
                  return false;
                }
                return true;
              },
              child: Scaffold(
                body: GestureDetector(
                  behavior: HitTestBehavior.translucent,
                  onTap: () {
                    print("Background was tapped");
                  },
                  child: Container(
                    color: Colors.black,
                    child: Stack(children: [
                      Positioned(
                        top: 10,
                        right: 10,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.pop(context);
                            Navigator.pop(context);
                          },
                          child: CustomCloseButtonUi(
                              Device.getTrueHeight(context),
                              Device.getWidth(context)),
                        ),
                      ),
                      Container(
                        alignment: Alignment.center,
                        child: provider, //provider,
                      ),
                      TestPushUpOnExercisePage(),
                    ]),
                  ),
                ),
              ),
            );
          },
        );
      },`
